### ISSUE TITLE
Update Package.json to reflect server details

### ISSUE THREAD

**Issue by heyjordn** [PalisadoesFoundation/talawa-api#101]
Currently the `package.json` shows some details regarding `tenten`, not sure what that is but it should at least reflect the repository details

```json
  "name": "talawa-api-rework",
  "version": "1.0.0",
  "description": "\"# tenten-api-rework\"",
```

**Comment by pranavich18** [comment]
@heyjordn I would like to work o this issue.
Can you please tell me what all details are needed to be added?

**Comment by Sagar2366** [comment]
@heyjordn, there is definitely scope to update entries in package.json file. Such as name of project(name), current stable version(version property), description(brief about project), git repo urls(in repository.url), etc.

Read this article, what important information can be added in package.json - https://nodesource.com/blog/the-basics-of-package-json-in-node-js-and-npm/.

**Comment by Sagar2366** [comment]
@heyjordn , please mark this as #good-first-issue for beginners to work on.

**Comment by SriramPatibanda** [comment]
@Sagar2366 Can I work on this issue?
