### ISSUE TITLE
Typescript type errors are not being checked in PR workflow.

### ISSUE THREAD

**Issue by xoldyckk** [PalisadoesFoundation/talawa-api#1017]
**Describe the bug**
Currently there's nothing preventing PRs with `typescript` type errors getting merged to the repo.

**To Reproduce**

1. Run `npm run typecheck`
2. Check the type errors

**Expected behavior**
If the PR has type errors it should not be merged.

**Actual behavior**
Some test files have type errors and they were merged because there was no job in PR workflow to prevent this.

**Screenshots**
![type_errors](https://user-images.githubusercontent.com/82873939/216990400-2ea521e0-213b-4b9e-ad71-1be514ecb2c6.png)

**Additional details**

**Comment by xoldyckk** [comment]
Suggested solution:- Add a job for type-checking the codebase in PR workflow configuration.

**Comment by Frey0-0** [comment]
I would like to take up this issue

**Comment by palisadoes** [comment]
@Frey0-0 We will need a similar solution for the Talawa-Admin repository when you have completed this one.

**Comment by Frey0-0** [comment]
yeah sure @palisadoes I would get on it after raising a PR here.

**Comment by Frey0-0** [comment]
@xoldyckk @palisadoes I have raised a PR for this issue, check it and please suggest any changes if required
