### ISSUE TITLE
Fix all type errors in the codebase. 

### ISSUE THREAD

**Issue by xoldyckk** [PalisadoesFoundation/talawa-api#1018]
**Describe the bug**
There are type errors in some of the test files.

**To Reproduce**

1. run `npm run typecheck`
2. check the type errors

**Expected behavior**
There should not be any type errors in the codebase.

**Actual behavior**
There are type errors in some of the test files.

**Screenshots**
![type_errors](https://user-images.githubusercontent.com/82873939/216994622-0d0d4a7a-ce3f-4145-bc86-03d7c0b15a06.png)

**Additional details**
This issue has surfaced due to lack of a type checking solution in PR workflows. It's mentioned in issue #1017.

**Comment by anshgoyalevil** [comment]
I would like to work on this
