### ISSUE TITLE
Feature Request: Change the GitHub action to only check for Formatting and Linting Errors

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1019]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
As discussed in [talalwa-admin](https://github.com/PalisadoesFoundation/talawa-admin/pull/437), the GitHub action file should only check for linting and formatting errors, instead of manually linting and formating the code. The same should be implemented here, to maintain consistency across the repositories.
 
**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
1. Create scripts in `package.json` like `lint:check`, `lint:fix`, `format:check` and `format:fix`.
2. Use these scripts in the GitHub workflows (while ensuring the jobs are configured properly to need other jobs)

**Additional context**
Helps to maintain consistency in the codebase.

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
@EshaanAgg 
1. Please refer to https://github.com/PalisadoesFoundation/talawa-api/issues/1018
1.Type checks must also be included as a job in the GitHub actions file [pull-request.yml](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml). We need to make sure that these errors do persist.
1. Similar treatment must also be added to the Talawa-Admin pull request GitHub action file too.

**Comment by EshaanAgg** [comment]
Sure @palisadoes. I will get cracking on these changes.

**Comment by palisadoes** [comment]
An issue was created for updating the GitHub Action to detect type errore before I commented. It's been assigned https://github.com/PalisadoesFoundation/talawa-api/issues/1017

**Comment by EshaanAgg** [comment]
Okay. I will wait for #1017 to be completed, before I will raise a PR for this issue.
