### ISSUE TITLE
Fix deprecated `get-changed-files` Pull Request GitHub Action

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1023]
**Describe the bug**
We are getting these errors when PRs are submitted:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: jitterbit/get-changed-files@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

The `get-changed-files` GitHub **_pull request_** action has not been updated since 2020 and will soon be unsupported by GitHub. We need to fix this deficiency.

**To Reproduce**

1. [See this action run](https://github.com/PalisadoesFoundation/talawa/actions/runs/4107719370)
2. It is happening in all repositories

**Expected behavior**
No errors

**Actual behavior**
See above

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/217083702-8fb6eb7b-dbf4-4d73-b37c-1cd9b3e02a6f.png)

**Additional details**
N/A

**Comment by faraz16iqbal** [comment]
@palisadoes Can I work on this?

**Comment by palisadoes** [comment]
> @palisadoes Can I work on this?

@faraz16iqbal Stop immediately. I have warned you multiple times to follow the guidelines in the CONTRIBUTING.md file. Everyone needs to get a chance. Your actions are not in keeping with the collaborative culture of our community.

You have repeatedly asked to be assigned issues that are already assigned an in many cases, issues that were assigned in the past 24 hours.

Please run the apps and try to discover serious bugs or serious flaws in the features. That will be a good start. 

We also have lots of testing issues that will provide a good start. This is stated in the pinned issues in the #general slack channel.

**Comment by jessy521** [comment]
hello @palisadoes ,
Jessy this side having experience on  backend of 1.5+ years with stacks like express,mongo,SQL,jenkins,docker,k8s,aws, git,github,javascript,typescript and so on. I think I'm much able to fix this issues  and after 3 internships now I'm willing to contribute on some opensource projects, have also gathered some interested on devops also ,So here I've reached to you, It would be so greatful to me if you allow me to have some contribution on your project , you can check my github also.
Thanking you,
Jessy

**Comment by jadeharr** [comment]
@jessy521 This issue has already been assigned. Please follow the guidelines in the CONTRIBUTING.md file.

**Comment by palisadoes** [comment]
Closing.
