### ISSUE TITLE
Sporadic Errors in `tests/middleware/isAuth.spec.ts`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1025]
**Describe the bug**
We are seeing sporadic errors when the `tests/middleware/isAuth.spec.ts` tests are run in our GitHub actions

**To Reproduce**

1. See - https://github.com/PalisadoesFoundation/talawa-api/actions/runs/4108458059/attempts/2

**Expected behavior**
1. No error
1. Fix the location of the expected missing file
1. Find a way to locate the missing file such that it is temporarily generated for the test (If applicable)
1. Find a way for the test file to be located in the `test/` directory tree
1. Adjust .gitignore to prevent this test file from being saved 

**Actual behavior**
See Screenshot and text below

```
 ✓ tests/middleware/isAuth.spec.ts  (7 tests) 52ms
stdout | tests/middleware/isAuth.spec.ts > middleware -> isAuth > returns authData if decoded token is not set
info 2023-02-06 22:27:35 - decoded token is not present {} 

stdout | unknown test
[Error: ENOENT: no such file or directory, open '/home/runner/work/talawa-api/talawa-api/images/image.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/talawa-api/talawa-api/images/image.png'
}


Test Files  38 passed (39)
     Tests  327 passed (329)
  Start at  22:26:59
  Duration  35.73s (transform 1.63s, setup 5ms, collect 9.22s, tests 22.86s)

⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: ENOENT: no such file or directory, open '/home/runner/work/talawa-api/talawa-api/images/image.png'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
 % Coverage report from c8
Error: Process completed with exit code 1.

```

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/217103888-d74467f5-52e7-4613-a69b-be86f7bf8e27.png)

**Additional details**
N/A

**Potential internship candidates**

**Comment by anshgoyalevil** [comment]
I would like to work upon this issue. Please assign this to me.

I just have a query. There is already an issue #1010 similar to this.

**Comment by palisadoes** [comment]
You are right. I lost track. Closing
