### ISSUE TITLE
Feature Request: Use Husky

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1027]
**Is your feature request related to a problem? Please describe.**
With the introduction of typechecking, formatting and linting checks in the GitHub workflows, there are a couple of commands that the developer now needs to ensure to run after making changes, which might be tiresome. 

**Describe the solution you'd like**
We can add [Husky](https://www.npmjs.com/package/husky) to our code-base, which helps to make working with Git Hooks easy. 
Using Husky we can easily configure the code to run scripts like `format:check`, `lint:check` and `typecheck` for the developer locally each time he makes a commit, thus ensuring that their PRs do not fail when they create a PR.

**Describe alternatives you've considered**
Using a shell script to run all the checking and fixing commands.

**Approach to be followed (optional)**
1. Install Husky.
2. Add scripts to run `format:check`, `lint:check` and `typecheck` at each commit using `Husky`.
3. (Optional) Add script to run tests.
4. Update documentation about the same and about the `--no-verify` flag that can be used with `git commit` to bypass the `Husky` hooks (if the developer desires)

**Additional context**
I personally am a huge advocate for Husky, as it helps to minimise the number of commands that I as a developer have to run, and automates all of the burden, leaving only the responsibility of fixing my errors to me (and automates code quality and maintainance)

**Comment by anshgoyalevil** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
1. @EshaanAgg Do you want to work on this as you created it?
1. We'll need the same approach for all typescript repositories for consistency.
1. @xoldyckk and @noman2002 What are your thoughts?

**Comment by EshaanAgg** [comment]
Thanks @palisadoes! I want to work this issue. I was just waiting for peer review before working on it, as wanted the thoughts of other developers on it as well. 
If approved, we can work on integrating Husky in all of the repositories for Palisadoes Foundation.

**Comment by palisadoes** [comment]
1. Please don't begin until we get feedback from the others.
1. You'll need to think of a way to show a suitable error message if the incorrect flags are used.

**Comment by EshaanAgg** [comment]
1. Sure @palisadoes 
2. Husky does automate that for us too if I recall correctly. I can dwell deeper into the same once we have an approval for this idea.

**Comment by xoldyckk** [comment]
@EshaanAgg Sure, it's a good idea. But make sure to include in the documentation on how to opt out of pre commit/push hooks. Because not everyone wants to run these checks everytime they make a change in their local codebase.

Besides main repo's CI will always be the source of truth so even if they opt out of it, the errors will be caught in CI.

**Comment by EshaanAgg** [comment]
Okay @xoldyckk!
I'll make sure to update the documentation about the same explicitly.
