### ISSUE TITLE
Code coverage not generating locally on Ubuntu and macOS 

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-api#1037]
**Describe the bug**
The vite.config.ts file has the reporter started as "lcov" only, to generate lcov.info file for github CI/CF however for development purposes I need to change that to - 'text' , 'html' , 'json' when running tests to generate a code cov report , and other contributors have mentioned the same issue too.
**To Reproduce**

1. run `npm run test` on linux or macOS
2. Codecov does not generate anything.

**Expected behavior**
A code coverage report rendered on the terminal after execution of all tests 
**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![Screenshot from 2023-02-09 22-35-44](https://user-images.githubusercontent.com/96020697/217886119-bf4d4d11-1107-4358-a620-afcce47a497d.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Possible fix**
Changing the reporter to [ 'lcov' , 'text' , 'json' , 'html ']  solves  this problem for other contributors so that we handle lcov file generation in ci/cd as well as the development environment of contributors.

It is not a breaking change as lcov.info file is generated as well for the github CI/CD

**Comment by kb-0311** [comment]
pls assign it to me

**Comment by palisadoes** [comment]
@xoldyckk I saw the slack conversation. If this is OK, please assign or else close.

**Comment by aashimawadhwa** [comment]
I also checked for the same as it was not generating code coverage for me , I guess this change will solve the problems for all of us.  @palisadoes

**Comment by kb-0311** [comment]
@palisadoes update : He did approve in the thread 
https://thepalisadoes-dyb6419.slack.com/archives/CSWH4PN0M/p1675969563253969?thread_ts=1675951586.959659&cid=CSWH4PN0M
