### ISSUE TITLE
Export multiple arguments of an error as an object to reduce import statements.

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#1038]
**Is your feature request related to a problem? Please describe.**
This issue is related to the refactoring of code, where the multiple arguments of an error are being exported as separate constants. For example:

```
export const COMMENT_NOT_FOUND = "Comment not found";
export const COMMENT_NOT_FOUND_CODE = "comment.notFound";
export const COMMENT_NOT_FOUND_MESSAGE = "comment.notFound";
export const COMMENT_NOT_FOUND_PARAM = "comment";
```
this can be converted to an object like
```
export const COMMENT_NOT_FOUND_ERROR = {
  DESC: "Comment not found",
  CODE: "comment.notFound",
  MESSAGE: "comment.notFound",
  PARAM: "comment",
};
```
which can further be imported in the codebase as an object, and can replace the error constants such as
```
if (!comment) {
    throw new errors.NotFoundError(
      IN_PRODUCTION !== true
        ? COMMENT_NOT_FOUND
        : requestContext.translate(COMMENT_NOT_FOUND_MESSAGE),
      COMMENT_NOT_FOUND_CODE,
      COMMENT_NOT_FOUND_PARAM
    );
  }
```
with 
```
if (!comment) {
    throw new errors.NotFoundError(
      IN_PRODUCTION !== true
        ? COMMENT_NOT_FOUND
        : requestContext.translate(COMMENT_NOT_FOUND_ERROR.MESSAGE),
      COMMENT_NOT_FOUND_ERROR.CODE,
      COMMENT_NOT_FOUND_ERROR.PARAM
    );
  }
```

**Approach to be followed (optional)**
The following approach can be followed:
- Create the error objects.
- Search the codebase for the usage of those constants, and replace them with those objects.

**Additional context**
This will reduce the complexity of codebase import statements, since there are a lot of import statements inside a code file, for the constant, which can be grouped together.

**Comment by anshgoyalevil** [comment]
@noman2002 @palisadoes Please take a look at this issue. If its valid, the issue #1035 can be solved while keeping this issue in sync.

**Comment by KrutikaBhatt** [comment]
In case it's fine, can I work on this issue?

**Comment by anshgoyalevil** [comment]
> In case it's fine, can I work on this issue?

Let's wait for others view on this. After that, we can create child issues for it, and work upon them.

**Comment by anshgoyalevil** [comment]
@xoldyckk What's your view on this?

**Comment by xoldyckk** [comment]
@anshgoyalevil It's a good idea.

**Comment by anshgoyalevil** [comment]
@palisadoes 
I have unassigned myself from this issue.
This is a good first issue, so want new contributors to get into it. It would give them a thorough understanding of the project.

**Comment by KrutikaBhatt** [comment]
Can I work on this?

**Comment by xoldyckk** [comment]
@KrutikaBhatt assigned you
