### ISSUE TITLE
Adding constants for the error messages`src/resolver/mutation`

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-api#1039]
**Is your feature request related to a problem? Please describe.**

This is a child issue to the issue listed here: #1035 
 - The code needs to be changed in `src/resolver/mutation`.
 - constant are values that are already defined for the different values of error message/code/param that are then further used by importing the src/constants folder.

**Describe the solution you'd like**
- we have to define constants for all the hard-coded message/code/param exist in this file. 
-  Refer to the parent issue on getting an insight on how this issue need to be resolved

**Important**
 - Please refer to the parent issues on how to refactor the code correctly.

**Comment by anshgoyalevil** [comment]
I would like to work upon this child issue.

**Comment by noman2002** [comment]
@Manoramsharma is already working on this. Please refer to the parent issue.

**Comment by Manoramsharma** [comment]
@noman2002 I think I could be assigned here for the issue, as #1035 is parent issue.
