### ISSUE TITLE
Add a CONTRIBUTING.md File for the repository 

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa-api#104]
Adding a contributing guide will help contributors follow best practices.
I would like to work with maintainers help them adding adding a CONTRIBUTING.md file for the repository.

**Comment by yasharth291** [comment]
can i contribute to it too. My idea for this was to make a different webpage for maintaining the contributors and when we click on their picture their personal website will open.

**Comment by iamsaumya** [comment]
@yasharth291 I think that will be too much unnecessary work. Not everybody has a personal website and GitHub already has a page for the contributors of a project [here](https://github.com/PalisadoesFoundation/talawa-api/graphs/contributors)

**Comment by yasharth291** [comment]
but it looks nice and the work is not much we can make a template regarding that so further people can also use that.

**Comment by iamsaumya** [comment]
The author of this issue has a valid concern as a contribution.md is a recommended file to have on a repo.

I will leave the decision for your request to the maintainer of the projects. However, I don't see how it adds any value to the project.  

Thanks :beers:
