### ISSUE TITLE
Adding constants for the error messages `tests/libraries/errors`.

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-api#1041]
**Is your feature request related to a problem? Please describe.**

This is a child issue to the issue listed here: #1035 
 - The code needs to be changed in `tests/libraries/errors`.
 - constant are values that are already defined for the different values of error message/code/param that are then further used by importing the src/constants folder.

**Describe the solution you'd like**
- we have to define constants for all the hard-coded message/code/param exist in this file. 
-  Refer to the parent issue on getting an insight on how this issue need to be resolved

**Important**
 - Please refer to the parent issues on how to refactor the code correctly.

**Comment by noman2002** [comment]
@anshgoyalevil You can take this if you want to?

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil You can take this if you want to?

Yes Sure. Please assign this issue to me.
