### ISSUE TITLE
Refactor Installation.md : Database Section

### ISSUE THREAD

**Issue by aviraldevv** [PalisadoesFoundation/talawa-api#1047]
**Describe the bug**
Currently instructions for setting up database are not clear and beginner friendly.

**To Reproduce**
We need very clear and comprehensive instructions on how to setup local instance of MongoDB database via:
   1.MongoDB Compass
   2.Mongo Shell

**Expected behavior**
Document will be more readable and beginner friendly.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aviraldevv** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
Please work on updating the `Talawa-Admin` documentation to refer to this API document. All API setup steps must be removed from the `Talawa-Admin` `INSTALLATION.md` file.

This took a long time, but we should see much better rates of installation. Thanks.
