### ISSUE TITLE
Bug Report: Outdated GraphQL-Upload package

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1055]
**Describe the bug**
We have used the `Upload` Scalar in our schema, and the current `graphql-upload` package we are using to handle the same is outdated, and vulnerable to CSRF attacks.

**To Reproduce**
1. Start the development server with `npm run dev`
2. The warning is logged in the starting of the console.

**Expected behavior**
We should not use such deprecated packages.

**Screenshots**
![image](https://user-images.githubusercontent.com/96648934/218257537-e32ce656-abc9-428f-8171-903916fdf896.png)

**Additional details**
We should upgrade to Apollo Server 3.7, as recommended. Migrating from Apollo 2 to 3 requires no changes in the codebase, as listed [here](https://www.apollographql.com/docs/apollo-server/v3/migration/#:~:text=Many%20Apollo%20Server%202%20users,and%20how%20to%20make%20them.).

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by EshaanAgg** [comment]
Upgrading to Apollo-Server-Express 3 is not as simple as I thought as it, and it requires us to have some breaking changes, like restructuring some of the code as certain parts of the API have been deprecated in the version `3.7`. Here is a [guide](https://medium.com/lego-engineering/migrating-from-apollo-server-v2-to-v3-part-2-server-upgrade-e9a9b7cafad5) that covers some of the steps and differences.
 
Should I continue working on the same, or halt on it for a while, as the migration is a quite a project in itself.

**Comment by EshaanAgg** [comment]
FYI, Apollo Server 3 has also been [officially deprecated](https://www.apollographql.com/docs/apollo-server/v3/), and we should consider moving to Apollo Server 4 in incremental ways.

**Comment by palisadoes** [comment]
What would you propose as the best approach to do this without impacting the PR process?

**Comment by EshaanAgg** [comment]
According to me the best way to proceed with the same is to create a new branch in the repository, where different contributors would be solely dedicated to migrating the same to first Apollo 3, and then to Apollo 4. This branch would be under heavy development, and wouldn't even compile due to the step-by-step migration.

When the migration would be complete, we can then merge it with the `develop` branch. This would allow other developers to continue working on the `develop` branch meanwhile.

**Comment by palisadoes** [comment]
I'm going to close this. Updating the dependencies to current versions is now part of a GSoC idea.
