### ISSUE TITLE
Document GraphQL-Playground

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1058]
**Describe the bug**
Our repository includes the `graphql-playground` package which allows users to use a `Talawa-API` API endpoint other than `/graphql` that allows developers to do Talawa graphql queries directly from their browser.

1. YouTube example - https://www.youtube.com/watch?v=CHNAnGSmQeA
1. Talawa discussion - https://github.com/PalisadoesFoundation/talawa-api/pull/1051

**Requirements**
1. We need to add a short section in the [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/CONTRIBUTING.md) document that tells developers how to use this feature. 
2. Provide a sample query that developers can use as a starting point with output. A screenshot would be sufficient, with the image being a part of the repository.

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, can I take up this issue?

**Comment by SiddheshKukade** [comment]
@palisadoes Sir please assign me. I can do this.
