### ISSUE TITLE
Super Admin Access Control Security Bug and API Mutation bugs

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-api#1066]
**Describe the bug**
Now that I have implemented the `superAdminCheck` function and authorization directive https://github.com/PalisadoesFoundation/talawa-api/pull/1065 . I will be next implementing them in each resolver when necessary.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
pls assign it to me

**Comment by noman2002** [comment]
@kb-0311 You have 3 issues assigned but as per the rule "maximum assigned issue to a single person should not be more that 2". I request you to please unassign any one of those and give everyone a chance or I'll unassign randomly.

**Comment by kb-0311** [comment]
@noman2002 yep completely understandable. As I had mentioned in `talawa-api` slack channel  yesterday, Some of the issues are a little big so that's why taking time.

Gonna unassign myself from  
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/396
2. https://github.com/PalisadoesFoundation/talawa-api/issues/913

**Comment by aviraldevv** [comment]
@kb-0311 I can see you have refactoring of code which were assigned to me. I will submit a PR for same latest by tomorrow. Please wait for me to submit a PR.
