### ISSUE TITLE
Server getting hung when trying to upload image in createOrganisation

### ISSUE THREAD

**Issue by rishav-jha-mech** [PalisadoesFoundation/talawa-api#1079]
**Describe the bug**
Server is getting hung while uploading files on createOrganisation mutation. I am working on adding the upload functionalities to the talawa-admin repository  (https://github.com/PalisadoesFoundation/talawa-admin/issues/477#issue-1590246917), and while submitting files on the server, the server is getting hung and not completing the request.

**To Reproduce**

1. Add `apollo-upload-client` to talawa-admin so that you can upload images.
2. Convert the form data in OrgList in screen, so that image is being sent to the backend
3. Convert the mutation of `CREATE_ORGANIZATION_MUTATION` to 

```

export const CREATE_ORGANIZATION_MUTATION = gql`
  mutation CreateOrganization(
    $description: String!
    $location: String!
    $name: String!
    $visibleInSearch: Boolean!
    $isPublic: Boolean!
    $tags: [String!]!
    $image: Upload
  ) {
    createOrganization(
      data: {
        description: $description
        location: $location
        name: $name
        visibleInSearch: $visibleInSearch
        isPublic: $isPublic
        tags: $tags
      }
      file: $image
    ) {
      _id
    }
  }
`;
```

4. Now that the file is being sent to the server, remember to create `images` folder in the root directory of `talawa-api` or you will get an error.
5. Try uploading the file from the `talawa-admin`, you will keep seeing a loading screen

**Expected behavior**
The uploaded image of the organisation should be uploaded to the server and the server should respond from next time with the image url of the organisation.

**Actual behavior**
The screen kept on showing loading.

**Screenshots**
![Loading screen](https://user-images.githubusercontent.com/76212518/220645833-910826e4-2b3e-4af4-aa4a-6154188b0cbf.png)

Meanwhile an empty file with file size zero is getting stored in the images directory.
![Sizeless file](https://user-images.githubusercontent.com/76212518/220650123-ec38a6d6-6bc7-4128-9c43-24dda814e6d7.png)

**Additional details**
I am getting this error log in my console 

```
(node:1500) [DEP0135] DeprecationWarning: ReadStream.prototype.open() is deprecated
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
```
I think the issue is in the `uploadImage` utility.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@rishav-jha-mech the GraphQL file management dependency has recently been deprecated and doesn't work. It will need to be rectified as a project. We are working on a quick fix for this with this issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1080

I suggest that you wait for that fix, but in the mean time use this issue to fix the hanging and present a suitable error message.

**Comment by palisadoes** [comment]
@rishav-jha-mech Please verify whether this still applies now that the image storage issue has been resolved. If so resolve this issue in a PR or else close this issue.

**Comment by faraz16iqbal** [comment]
@palisadoes I would like to work on this if this issue is still open

**Comment by palisadoes** [comment]
> @palisadoes I would like to work on this if this issue is still open

@faraz16iqbal Stop immediately. I have warned you multiple times to follow the guidelines in the CONTRIBUTING.md file. Everyone needs to get a chance. Your actions are not in keeping with the collaborative culture of our community.

**Comment by rishav-jha-mech** [comment]
Sorry @palisadoes this issue is fixed now. I am closing this issue 🚀
