### ISSUE TITLE
Implement a Scalable workflow for validation in Mutations

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1082]
**Is your feature request related to a problem? Please describe.**
As evident from the discussion [here](https://github.com/PalisadoesFoundation/talawa-api/pull/1081), there is a need for:
1. Add GraphQL scalars to talawa-api repository so that most of the data types can be validated for us.
2. Add validation methods to check for business requirements in all of the mutation methods, and provide a way to easily send error messages for the same. 

**Describe the solution you'd like**
Integrating GraphQL scalars into the repository seems like a job that can been accomplished within a short time frame, and thus should be done ASAP. After the integration of the same, we must come to consensus about a uniform strategy for validation (a third party library maybe?), and then try to incorporate the same in the mutation resolvers (as well as add tests for them).
 
**Approach to be followed (optional)**
Described above

**Additional context**
I can get started on the GraphQL scalars integration, and in the meanwhile we can try to ideate the best way to deal with validation requirements.

**Comment by palisadoes** [comment]
Are you still working on this? It's been over 10 days. Others need to get a chance.

**Comment by EshaanAgg** [comment]
This issue has already been implemented by other contributors in other PRs with the help of regexes.
As per discussions with @xoldyckk, we should move away from regexes and do so with the help of some validation library, but it would make sense to implement it only after the migration to `GraphQL Yoga`.

So as of now, this issue can be closed.
