### ISSUE TITLE
Update CONTRIBUTING.md as instructed.

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-api#1092]
**Describe the bug**

**To Reproduce**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
pls assign this to me.

**Comment by xoldyckk** [comment]
@kb-0311 provide a description of what you're going to do.

**Comment by kb-0311** [comment]
@xoldyckk There was a little miscommunication today between me and another contributor and because of that miscommunication @palisadoes asked me to write a few points about how interrelated issues need to be communicated in the contributing.md file.

**Comment by xoldyckk** [comment]
@kb-0311 ok
