### ISSUE TITLE
Feature Request: Add documentation for configuring logger

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1104]
**Is your feature request related to a problem? Please describe.**
Currently, our logger has support for both, different log levels and colourised logging. But there is no central documentation on as to what are the different options that can be used for `log level`, what differences they have, and how to set them up.
 
**Describe the solution you'd like**
Add documentation for the same in the respective markdown files.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
Update documetation

**Additional context**
NA

**Comment by palisadoes** [comment]
This needs to be added to Talawa docs. Please read DOCUMENTATION.md

**Comment by KrutikaBhatt** [comment]
We just need to make small changes in documentation and .env.sample to include customization options for COLORIZE_LOGS and LOG_LEVEL. Can I work on this?

**Comment by palisadoes** [comment]
We need to consider removing colorized logs. When the github actions fail I think the colorizations and clear screens that happen are making it difficult to track.
