### ISSUE TITLE
Adding post-merge functionality for the husky to improve developer experience.

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-api#1108]
**Describe the bug**
Currently, we dont have any post-merge functionality in husky... Sometimes, when some new dependencies are added to package.json and user git pulls the files to his local system, he gets errors and some of the required node modules will be missing....To prevent this , we can add post-merge functionality so that everytime a user uses 'git pull', if the remote repo had some changes into package.json, 'npm install' should automatically run

**To Reproduce**

1.Update your remote repo and then use git pull
2.You will see this error if the remote had some changes in pakage.json

**Expected behavior**
no errors should be there and the developing experience should be good

**Actual behavior**
might get errors sometime and developers may get stuck

**Screenshots**
not required

**Comment by anurag0006** [comment]
I have also made a similar issue for talawa-admin so i would also like to work on this issue to solve it...Please assign it to me

**Comment by xoldyckk** [comment]
@anurag0006 Make sure you document what it does, and how to opt out of it.
