### ISSUE TITLE
Completing the Upload Encoded Image Utility

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-api#1111]
**Describe the bug**
Now that there has been no breaking change for create organization image , this solution can be applied everywhere.
This PR will introduce the following change:
1. Optimise the reupload logic for multiple reuploads , 
2. Delete Image Function
3. Apply upload Image function wherever necessary.
4. Add the tests for 2. and 3.

**To Reproduce**

1. Try to delete an image or upload an image in any other pop up beside create org 
2. The server hangs
3. Because the uploadEncodedImage is not implemented yet.
4.  

**Expected behavior**
There should be a clear logic to delete images in the FS.
There should be the ability to upload images from the talawa-admin portal and mobile app.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
@palisadoes pls assign this to me

**Comment by palisadoes** [comment]
1. Please fill in the issue template properly. We need it done to help with our searches tracking.
1. Ensure that the reference issue in Admin is included
