### ISSUE TITLE
Code Enhancement - Creating enums for constants in DB

### ISSUE THREAD

**Issue by BhuvaneshPatil** [PalisadoesFoundation/talawa-api#1114]
**Describe the bug**
There are many constant values used in db schema. Ex - "USER", "SUPERADMIN", "ADMIN", "ACTIVE" etc.
It would be great enhancement to create enums and use them through out the project. This will help in faster development, avoiding typing mistakes.

**Expected behavior**
Enums should be created for constants.

**Additional details**
This should be created in incremental way, changing few files at a time, this will help reduce conflicts because many contributors may be working on same file.

**Comment by palisadoes** [comment]
There is no need for this. They are already constants. Closing

**Comment by BhuvaneshPatil** [comment]
Thank you @palisadoes . I think I couldn't explain it better.
Example - 
There are three types of user - 

1. User - USER
2. Admin - ADMIN
3. Super admin - SUPERADMIN

My suggestion was to create the enums for same - 
```
enum USER_TYPE_ENUM {
  USER = 'USER',
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
}
```

These enums can be used across the projects.

**Comment by palisadoes** [comment]
Thanks, but we will not do this. Focus on fixing bugs that are seriously affecting the expected operation of the apps.

**Comment by BhuvaneshPatil** [comment]
sure
