### ISSUE TITLE
No appropriate message on startup when DB is offline 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1122]
**Describe the bug**
If you start Talawa API and the DB isn't started you get the message in the screen shot.

If you look carefully you will see a:
1. TCP Connection refused (ECONNREFUSED) message
2. Session timeout message

Then there is a stack trace.

This  is not a good UX. A typical non-IT administrator will not know how to proceed. 

**To Reproduce**

- See above

**Expected behavior**

- A very clear message that the DB is unreachable and that it may be offline without the stack trace.

**Actual behavior**

- See above

**Screenshots**

![image](https://user-images.githubusercontent.com/16875803/222993989-641ad8ff-bd9a-4949-a8a3-1050300cebe5.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aviraldevv** [comment]
@palisadoes I am up for fixing this.

**Comment by aviraldevv** [comment]
But I feel the stack trace is useful because lots of fixes are available for it on stackoverflow. What do you think @palisadoes ??

**Comment by palisadoes** [comment]
There is a third possibility, the DB connection string URL could be wrong.

**Comment by aviraldevv** [comment]
Yes I tried doing that it throws the same error.

**Comment by aviraldevv** [comment]
Still I feel removing stack trace is not a viable option as there can be multiple reasons for refusing connections it might help to diagnose and fix errors for unknown cases.

**Comment by aviraldevv** [comment]
We can give some possible fixes along with that.

**Comment by aviraldevv** [comment]
We can surely add some possible fixes along witht the error meesage.

**Comment by palisadoes** [comment]
OK. But the application's message must be clearly defined in the output. Preferably separated from the rest of the text blank line feed space.

**Comment by aviraldevv** [comment]
@palisadoes please assign me I will do the needful on priority.

**Comment by aviraldevv** [comment]
![Screenshot_330](https://user-images.githubusercontent.com/121368112/223025813-f99c97b9-2b5a-424f-9586-61be99a8446a.png)
@palisadoes Give me some suggestions on how the error message should look like I will add it up.

**Comment by palisadoes** [comment]
Please use your initiative.  We want the Talawa message to stand out. White space around it would be OK.

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed ex vitae elit mollis imperdiet. Praesent eget tincidunt leo, eget pretium odio. Donec faucibus ullamcorper dolor sit amet auctor. Donec non orci porta, egestas nisl id, posuere tortor. Mauris tristique, dui in lacinia laoreet, ante diam vehicula ante, sit amet rutrum risus ipsum id lectus. Phasellus vitae elit non risus porta hendrerit. Aliquam auctor rutrum erat, luctus tempus ipsum accumsan quis. Suspendisse a justo egestas, ultricies tortor a, fringilla felis. Pellentesque imperdiet sed dui non faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In iaculis consequat lectus, in sagittis metus efficitur sed. Ut augue lorem, ornare eget leo at, lobortis consequat turpis. 

Put Talawa message here. I leave the wording up to you.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nulla tortor, tempus dictum cursus ut, venenatis at mauris. Fusce imperdiet risus a porta lobortis. Vestibulum at laoreet orci, vel iaculis ante. Proin nulla mauris, interdum vitae commodo at, auctor ac nibh. Praesent sollicitudin ut nisi eu dapibus. Suspendisse potenti. Morbi quis mi sed magna gravida tristique. Mauris elementum suscipit orci sed tempor. Pellentesque blandit elementum interdum. Mauris nunc arcu, fringilla vel arcu at, luctus ultrices ligula. Integer fermentum tristique elit in eleifend. Quisque porta varius posuere. Curabitur nec risus at purus facilisis placerat. 
```

**Comment by aviraldevv** [comment]
![Screenshot_333](https://user-images.githubusercontent.com/121368112/223036712-de9150a2-8e85-4d0a-8dbd-2c29df355d06.png)
@palisadoes Does this look good to you?? I have added only important keyword of stack trace.

**Comment by palisadoes** [comment]
You can leave the entire stack trace above, have the space and but leave the Talawa message at the bottom.

Make the possible causes bullets, it will stand out more like this:

1. Possible Cause 1
2. Possible Cause 2
3. Your database may not be running

**Comment by aviraldevv** [comment]
Okay I am trying out that.

**Comment by aviraldevv** [comment]
![Screenshot_334](https://user-images.githubusercontent.com/121368112/223040555-dadcecb8-d954-48fc-a22e-de868c2ce3b1.png)
I have made the message bold instead of line breaks its looking good.

**Comment by aviraldevv** [comment]
@palisadoes Shall I submit a PR now??

**Comment by palisadoes** [comment]
Please add:

1. A space between the stack trace and the Talawa-Admin message. This was requested before.
1. You have not mentioned that a possible cause could be that MongoDB isn't started. This was requested before.
1.  Some text to show that this isn't an unexpected crash. Something like.

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed ex 
vitae elit mollis imperdiet. Praesent eget tincidunt leo, eget pretium odio. 
Donec faucibus ullamcorper dolor sit amet auctor. Donec non orci porta, 
egestas nisl id, posuere tortor. Mauris tristique, dui in lacinia laoreet, ante 
diam vehicula ante, sit amet rutrum risus ipsum id lectus. Phasellus vitae 
elit non risus porta hendrerit. Aliquam auctor rutrum erat, luctus tempus
 ipsum accumsan quis. Suspendisse a justo egestas, ultricies tortor a, fringilla 
felis. Pellentesque imperdiet sed dui non faucibus. Pellentesque habitant 
morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
In iaculis consequat lectus, in sagittis metus efficitur sed. Ut augue lorem, 
ornare eget leo at, lobortis consequat turpis.

Talawa Admin encountered an error. This could be caused by:

1. Reason 1
2. Reason 2
3. Reason 3
4. Reason 4
```
Don't use `and` or `or` in the reasons. There must be one reason per line because people often don't read the second part of the sentence when they are in a hurry.

**Comment by palisadoes** [comment]
Then submit the PR. Please pay closer attention to the advice given.

**Comment by aviraldevv** [comment]
> Then submit the PR. Please pay closer attention to the advice given.

I will make sure to follow the instructions.

**Comment by anshgoyalevil** [comment]
@aviraldevv 

A quick tip:

You may use the ASCII Arts to beautifully differentiate errors, like the box below

```
************************************
* 1                                *
* 2                                *
* 3                                *
* 4                                *
************************************
```

**Comment by aviraldevv** [comment]
> @aviraldevv
> 
> A quick tip:
> 
> You may use the ASCII Arts to beautifully differentiate errors, like the box below
> 
> ```
> ************************************
> * 1                                *
> * 2                                *
> * 3                                *
> * 4                                *
> ************************************
> ```

@anshgoyalevil Nice idea. Seems good to me , will give it a try buddy!!

**Comment by anshgoyalevil** [comment]
@aviraldevv 

Some most popular packages use such errors.

For example:
- Azure cloud console
- MSF Console
- AWS
- etc

**Comment by aviraldevv** [comment]
@palisadoes what do you think about this??

**Comment by palisadoes** [comment]
1. Please use your initiative to get the optimal result, then
1. Submit the PR.

This does not need more of my input.
