### ISSUE TITLE
Update Organization Input Can't Accept Location

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#1125]
**Describe the bug**
Update Organization Input doesn't have location field. This makes the location mutation to fail.

**To Reproduce**

1. It can't be reproduced as of now, since it is related to update org (https://github.com/PalisadoesFoundation/talawa-admin/issues/531)

This issue is linked to the admin issue https://github.com/PalisadoesFoundation/talawa-admin/issues/531 for api changes

**Comment by anshgoyalevil** [comment]
@palisadoes Please assign it to me, there is a minor change to the Api which needs to be done for https://github.com/PalisadoesFoundation/talawa-admin/issues/531 to sync.

**Comment by xoldyckk** [comment]
@anshgoyalevil Make the PR
