### ISSUE TITLE
Feature Request: Implement tags for User in an organization

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1126]
**Is your feature request related to a problem? Please describe.**
As per the discussion in [this thread](https://github.com/PalisadoesFoundation/talawa-admin/issues/496), we must work on implementing support for `tags` on the `User` model as a part of an `Organization`.

**Describe the solution you'd like**
1. Create a new model called `UserOrgTags` which will have the following fields:
- `User`: Stores the userID
- `OrganizationID`: Stores the organization
- `tags`: Stores the array of tags that a user has been assigned for an organization

2. Create a new field called tags on the `User` schema which accepts a `OrgID` as an input and returns all the tags that the user has in that organization.
3. Create a new field called `allTags` on the `Organization` schema which returns all the `distinct` tags that have been allotted to across all users. 

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
Described above

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by beingnoble03** [comment]
@DMills27 Can these tags be used to select volunteers for the project idea [Improved Event Management](https://docs.talawa.io/docs/internships/internship-ideas/#admin-improved-event-management)?

**Comment by EshaanAgg** [comment]
@xoldyckk What do you think about the proposed architecture for the implementation of the same?

**Comment by EshaanAgg** [comment]
Update:
Thinking about the following business requirements as well:
1. A user can only have at most 10 different tags for an organisation.
2. Each tag can have a length of at most 25 characters.
3. Each tag can only consists of characters. digits and the symbols `-`, `_` and ` `.

We would also need to expose the following mutations:
1. AddTag(userID, orgID, tag)
2. RemveTag(userID, orgID, tag)

**Comment by palisadoes** [comment]
> @DMills27 Can these tags be used to select volunteers for the project idea [Improved Event Management](https://docs.talawa.io/docs/internships/internship-ideas/#admin-improved-event-management)?

They can be used in multiple ways.

1. We originally implemented tags for organizations thinking that there could be API instances handling hundreds of organizations.
    1. Tags were thought of being a suitable way of simplifying the selection of your favorite organization in the app.
    1. In reality most installations will be handling few organizations and therefore tags for this purpose were unsuitable
1. We also wanted tags to help with filtering people, but this was never implemented.

The aim of this issue is to create the building blocks of tag support for users. How tags are used will be subject to interpretation by GSoC applicants. This was outlined in the video below. It starts at the point of most interest for this topic.

[![YouTube Video](https://img.youtube.com/vi/-Kwgb3vfqQ0/0.jpg)](https://youtu.be/-Kwgb3vfqQ0?t=1919)

**Comment by palisadoes** [comment]
> Update: Thinking about the following business requirements as well:
> 
>     1. A user can only have at most 10 different tags for an organisation.
> 
>     2. Each tag can have a length of at most 25 characters.
> 
>     3. Each tag can only consists of characters. digits and the symbols `-`, `_` and ` `.
> 
> 
> We would also need to expose the following mutations:
> 
>     1. AddTag(userID, orgID, tag)
> 
>     2. RemveTag(userID, orgID, tag)

Ten tags are too few it may have to be unlimited and let the admins decide. Here are some examples that I can think of which exemplifies the point:

1. Status:
    1. Member
    1. Attender
    1. Visitor
    1. No Longer Attends
    1. Unassigned
1. Marital Status
    1. Single
    1. Engaged
    1. Married
    1. Divorced
    1. Widowed
    1. Separated
    1. Unassigned
1. Family Role
    1. Head of Household
    1. Spouse
    1. Adult
    1. Child
    1. Unassigned
    1. Not In Family
1. Family Contains
    1. Head of Household
    1. Spouse
    1. Adult(s)
    1. Child(ren)
    1. Unassigned
1. Campus
    1. North
    1. West
    1. East
    1. Unassigned    
1. School Grade
    1. Pre-Kindergarten
    1. Kindergarten
    1. 1st
    1. 2nd
    1. 3rd

Tags may need to be nested too like in Gmail or similar applications that use them for filtering

![image](https://user-images.githubusercontent.com/16875803/223280231-7f3ba809-9ce0-48cf-82ed-a7ff93b75049.png)

You'll probably need to:

1. Create tags in an org
1. Assign tags to people in the Org
1. Put tags in `folders`, or nest them like you can in Gmail for easy filtering

That should give basic functionality

**Comment by EshaanAgg** [comment]
Got it @palisadoes! Then my earlier proposal solution, simply wouldn't cut it. 
I would research more on it and update my strategy here.

**Comment by beingnoble03** [comment]
@EshaanAgg I think we might have to follow graph approach here if we want tags to look something like folders
https://www.mongodb.com/docs/manual/tutorial/model-tree-structures-with-parent-references/

**Comment by beingnoble03** [comment]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/62551163/223354517-48c55667-6e18-4023-a025-fcfaf8801263.png">

Can we create something like this? It fulfils every need.

- We can get all users belonging to a particular tag.
- We can get all sub tags belonging to a particular tag, in fact a complete tree [as mentioned in this answer](https://stackoverflow.com/a/40992353).
- We can get list of tags, a particular user belongs to.
- We can get list of tags, where a particular organization is involved.

**Comment by EshaanAgg** [comment]
I was thinking about the same. The proposed backend design would look something like the following now.

1. Model `TagFolders` - Used to store all the folders that a tag can be listed under
It will have the following fields:
- `organization`: `ID` of the organization
- `name`: Name of the category
- `parent`: `ID` of the parent folder so that we can use Mongo's Graph Lookup method to query for the same. The topmost folder would obviously will be `null`, denoting no folder. 

Note: This implementation would require each organization to have at least one parent folder if they wish to opt into using tags.

2. Model `Tag`: Used to store a tag 
It will have the following fields:
- `name`: Name of the tag
- `folder`: `ID` of the parent folder

3. Update the user model to have a `tags` property, which will be an array of the `ID`s of the Tags.

**Comment by EshaanAgg** [comment]
@beingnoble03 I'm thinking along similar lines, but we would need two models for `Tags` and `TagFolders` as they are fundamentally different objects from the UI as well as the implementation perspective. Also what is the requirement for the `ancestor` key?

What are your views on my proposed schema?

**Comment by EshaanAgg** [comment]
Yes! 
By the way, what are you using to generate these schemas?

Also @xoldyckk @palisadoes please review this architecture discussion before I can proceed with the implementation of the same.

**Comment by beingnoble03** [comment]
@EshaanAgg there are many tools for generating ER diagrams, you may use https://drawsql.app/ this one.

**Comment by xoldyckk** [comment]
@EshaanAgg @beingnoble03 These are incomplete entity relation diagrams. First of all ask yourselves some questions:-

1. Are tags(labels) private to an organization ? Can the tags be shared between organizations?

2. Can create as many tags as it wants(base or nested). By global I mean whether they're provided by talawa-api and locked up, so organizations will have to work with the tags that talawa-api provides.

3. How many tags are allowed for a particular organization. How many levels of nesting is going to be allowed for nested tags. Can users be grouped according to just parent tags even if it has child tags? Is numbering of tags going to be calculated for parent tags? `tag1(root/parent) -> tag2(child1)`  `tag1(root/parent) -> tag3(child2)` -> Here is is just 2 tags(2 child tags) or 3 tags(1 parent, 2 child tags).

4. Is there a unique constraint between names of parent and nested tags? `tag1(root/parent) -> tag1(child/parent) -> tag1(child)`?

5. How many tags can be assingned to one particular user within an organization? How will you model tags for a user who can be a member of many organizations?

6. What's the shape in which clients will provide input for querying/mutating tags?

These are just some of the many things, I can list many more. First lay out a clear plan for the idea then talk about implementing it.

**Comment by EshaanAgg** [comment]
Alright @xoldyckk, getting your concerns. Here is a more detailed description of the same:

We will be implementing two new models `TagFolders` and `Tag` as explained in the previous comment. We would also be exposing the following models as Types on the GraphQL Schema along with the following mutations:
```
Type TagFolder {
    id: ID!
    name: String
    parent: ID;
    organization: ID;
}

// This mutation would create a new folder. The user would need to specify one of the two optional arguments (parentFolder to create it as a subcategory or orgID to create it as a root folder in an organization)
Mutation AddFolder (folderName: String, parentFolder: ID, orgID: ID);
Mutation DeleteFolder(folderID: ID) // Would delete the folder and all the tags present in it
Mutation RenameFolder(folderID: ID, newName: String);
```

It is after the creation of a `TagFolder`, that the admin would be able to register a `Tag`:
```
Type Tag {
    id: ID!
    name: String
    folder: ID;
}

Mutation CreateTag (folder: ID, tagName: String);
Mutation DeleteTag(tagID: ID) // Would delete the tag and unassign all the users with the same
Mutation RenameTag(tagID: ID, newName: String);
```

These two models would be describing all the actions that could be done with respect to managing tags and their categorization. In the final step, we would be exposing the following mutations to actually assign a user with tags:
```
Mutation AssignTag(tagID: ID, userID:ID)
Mutation RemoveTag(tagID: ID, userID:ID)
```
All of these operations can only be performed by either `SUPERADMIN` or an `Admin` of the organization for which the tag is being created.

We would also expose the following Queries to the frontend:
```
// This query would return a hierarchal structure of JSON objects, so that the navigation pane of the tags can be rendered in the UI similar to [folder structure here](https://user-images.githubusercontent.com/16875803/223280231-7f3ba809-9ce0-48cf-82ed-a7ff93b75049.png)
Query getTagStructure(orgID: ID)

// Return all the tags that an user has for a particular organization for display on the user profile
Query getUserTags(userID: ID, orgID: ID)
```

**Comment by beingnoble03** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62551163/223405867-08de0ec9-587b-47b8-b41d-5d34dd651692.png">
@xoldyckk According to me, we are not talking about implementing nested tags instead we are talking about placing the tags into nested folders. So that it can be easy to search for members in an Organization. 
For reference we want to implement something like shown in the image.

**Comment by beingnoble03** [comment]
A member can exist in different tags.

**Comment by EshaanAgg** [comment]
As for the questions you asked,

1. `Tags` are private to the organization as it is the choice of the Admin of the organization how he/she wants to categorise the users. If we want to have a preset of tags for an organization, that can be integrated as a Plugin later (out of scope right now)

2. The whole point of this graph design is to allow ultimate flexibility to the Admin, so that he/she can choose to create as many tags as he/she likes, and categorise them as they want. There is no limit of any sort.

3. As of the current design, we don't have any limit on the number of tags or on the level of nesting. However, implementing the same wouldn't be difficult with the currently proposed design. There is no concept of `parent Tags`. Users can be only be identified using `tags`. Think of a tag as a file on your system, while `TagFolder` is quite literally the folders you put the file into. 
 The admins can create multiple folder and restructure them as they want to sort their tags, but the actual labelling can be only done with an `Tag` model (i.e. the file in the analogy)
 
 4. There is no such constraint, as again the `TagFolder` model is just for categorization.
 
5. No limit on the number of tags for a user as of now. Also since each `TagFolder` has an organization attribute and each `Tag` belongs to a `TagFolder`, it means that each `Tag` on the User would actually reference the organization it was created for. 

6. Described the shape in the previous message. 

Sorry for not clearing these design considerations earlier, and would love to hear your views on the same.
@xoldyckk

**Comment by xoldyckk** [comment]
Well whatever. It'll automatically become much clearer looking at the database models directly.

**Comment by EshaanAgg** [comment]
> 1. Model `TagFolders` - Used to store all the folders that a tag can be listed under
>    It will have the following fields:
> 
> * `organization`: `ID` of the organization
> * `name`: Name of the category
> * `parent`: `ID` of the parent folder so that we can use Mongo's Graph Lookup method to query for the same. The topmost folder would obviously will be `null`, denoting no folder.
> 
> Note: This implementation would require each organization to have at least one parent folder if they wish to opt into using tags.
> 
> 2. Model `Tag`: Used to store a tag
>    It will have the following fields:
> 
> * `name`: Name of the tag
> * `folder`: `ID` of the parent folder
> 
> 3. Update the user model to have a `tags` property, which will be an array of the `ID`s of the Tags.

These were the proposed changes in the database models. Maybe this provides a more clarity.

**Comment by palisadoes** [comment]
@EshaanAgg @beingnoble03 that's the general idea

**Comment by xoldyckk** [comment]
> > 1. Model `TagFolders` - Used to store all the folders that a tag can be listed under
> >    It will have the following fields:
> > 
> > 
> > * `organization`: `ID` of the organization
> > * `name`: Name of the category
> > * `parent`: `ID` of the parent folder so that we can use Mongo's Graph Lookup method to query for the same. The topmost folder would obviously will be `null`, denoting no folder.
> > 
> > Note: This implementation would require each organization to have at least one parent folder if they wish to opt into using tags.
> > 
> > 2. Model `Tag`: Used to store a tag
> >    It will have the following fields:
> > 
> > 
> > * `name`: Name of the tag
> > * `folder`: `ID` of the parent folder
> > 
> > 
> > 3. Update the user model to have a `tags` property, which will be an array of the `ID`s of the Tags.
> 
> These were the proposed changes in the database models. Maybe this provides more clarity.

You're showing sql table diagrams for something which has to be implemented with mongodb. It'll only become clear once you show your mongodb(mongoose) schema.

**Comment by beingnoble03** [comment]
@xoldyckk Sorry about that. SQL table diagram was meant to give only a general idea. Obviously, it would be clearer with schema.

**Comment by EshaanAgg** [comment]
I have updated the Mongoose Scheme for this implementation [here](https://github.com/PalisadoesFoundation/talawa-api/compare/develop...EshaanAgg:talawa-api:tagadd)

Hope it provides more clarity.

**Comment by EshaanAgg** [comment]
Update: I have started working on the implementation of the same queries and mutations, and have arrived at the following conclusion:
1. We should update the Tag Model to store the organizationID as well, as it would help us to reduce queries to tagFolder model (to check the rights of the user) in all our resolver implementations for mutations.
2. Instead of storing `tags` as an attribute on the User model, we should instead be storing the linked users for each `Tag` model for more efficient querying. 

I have updated the link in the previous comment to show my changes till now, and will be updating the same in a while after making these changes.

**Comment by EshaanAgg** [comment]
@xoldyckk 
I have completed the initial implementation of all the required changes and updated the same [here](https://github.com/PalisadoesFoundation/talawa-api/compare/develop...EshaanAgg:talawa-api:tagadd). I would please request you to review them once, as the introduction of this functionality was a big change, and thus I would like your views on the architecture of the same, before I work on making the same production ready by including unit-tests for all the files I have written.

A couple of highlights about the implementation:
1. The implementation introduces `0` new queries. Rather, all the relevant fields which would be required by the client are introduced as a field on the respective model itself. The reason for choosing this approach is simple, to provide client with the utmost flexibility.

For example, each `tagFolder` model stores its `subfolders` and `tags` on it as a virtual field (which does not exist in the database), thus the client can query the same as per its need of nesting. Suppose our current client supports only 3 levels of nesting to be shown at a time (in the sidebar as shown in the screenshots above), then the sample query would be of the form:
```
query organization{
  organizationsConnection(){
    tagFolders {
      title
      tags {
        title
      }
      subfolders {
        title
        tags {
          title
        }
        subfolders {
          title
          tags {
            title
          }
        }
      }
    }
  }
}
``` 

2. Implemented all the relevant mutations that I had described in my previous messages, but have renamed them to be better compliant with the naming scheme used across the codebase.

**Comment by xoldyckk** [comment]
@EshaanAgg I think current implementation of relations in talawa-api is bad. Same goes for your implementation for tags. You're not considering long term implications. Since, the related data is not constrained to some limits, using embedded documents or embedded foreign keys(list of object ids) is a bad practice. Especially the object ids list, it doesn't provide us complete database powers for perfomant filtering, sorting stuff. Those are only available on collections.

Here's a better architecture using mongoose schema:-

```

// User schema
const UserSchema = new Schema({
  username: { type: String, required: true, unique: true },
  // ...additional fields if any
});

// Organization schema
const OrganizationSchema = new Schema({
  name: { type: String, required: true, unique: true },
  // ...additional fields if any
});

// Define junction collection schema for user-organization relationship
const UserOrganizationSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  organizationId: { type: Schema.Types.ObjectId, ref: 'Organization', required: true },
  // This better represents a user's role on an organization than assigning
  // it on the user's object itself.
  role: "USER",
  // ...additional fields if any
})

UserOrganizationSchema.index({ userId: 1, organizationId: 1 }, { unique: true });

// Define junction collection schema for organization-label relationship
const OrganizationLabelSchema = new Schema({
  name: { type: String, required: true },
  parentLabelId: { type: Schema.Types.ObjectId, ref: 'OrganizationLabel', required:false },
  organizationId: { type: Schema.Types.ObjectId, ref: 'Organization', required: true },
  // The below on isn't needed but could be beneficial for bidirectional traversal if
  // the number of child labels doesn't get large. But I don't think that's the case
  // so this probably shouldn't be implemented.

  // childrenLabels: [
  //   {
  //     type: Schema.Types.ObjectId, ref: 'OrganizationLabel', required: false
  //   }
  // ]
  // ...additional fields if any
});

// Define junction collection schema for user-label relationship
const UserLabelSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  labelId: { type: Schema.Types.ObjectId, ref: 'OrganizationLabel', required: true },
  // ...additional fields if any
});

UserLabelSchema.index({ userId: 1, labelId: 1 }, { unique: true });

// Define models
const User = mongoose.model('User', UserSchema);
const Organization = mongoose.model('Organization', OrganizationSchema);
const UserOrganization = mongoose.model("UserOrganzation",UserOrganizationSchema);
const OrganizationLabel = mongoose.model('OrganizationLabel', OrganizationLabelSchema);
const UserLabel = mongoose.model('UserLabel', UserOrganizationLabelSchema);

``` 

I know this looks like sql tables but this is how mongodb itself recommends to use such type of relations. The whole embedding documents and embedding list of object ids is only optimal if you have small, limited amount of relations. User, organization and labels are all infinetely growable. Current architecture doesn't take that into consideration.

**Comment by EshaanAgg** [comment]
@xoldyckk Can't say that I didn't same thoughts myself when I was trying to implement all these functionalities. Using MongoDB felt like such a barrier there, because I wasn't able to define indexes properly that could be used to execute the queries in a scalable manner with support for filtering and sorting.

It's still going to take a while for me to digest the fact that `MongoDB` requires you to define a new model itself whenever you want to relate data in an efficient manner, but I guess that the price that one has to pay. Should I work on updating the Tag models to such SQL-like joined relation models, or such we continue using the relation approach that we have been using across all the database for consistency?

**Rant**: This can got to be the realest thing that I ever read about NoSQL databases, and Mongo in particular. While they advertise themselves to be the pioneers of NoSQL databases, and take pride in making themselves ACID complacent, the former has little meaning as soon as

**Comment by EshaanAgg** [comment]
@xoldyckk Got it. Will definitely do so to get the idea about embedded data.

**Comment by EshaanAgg** [comment]
@xoldyckk MongoDB tries to advertise it as the next big thing, but for "considerable data size". The benefits of embedding stem from the fact that you are getting the data then and there, but the same by definition becomes a barrier to the scalability of the implementation. 
This reminds of the classical example: Insertion sort in sorting is better than merge sort due to its small constant factor for "small" data sizes, but is useless otherwise. Using MongoDB for the highly inter-related type of nature that we are dealing with is just a bad design decision made earlier, hampering the current development.

**Comment by EshaanAgg** [comment]
@xoldyckk I am thinking of making the following changes:
1. Retaining the name `Tag` and `TagFolder` (which are right now analogous to `UserLabel` and `OraganizationLabel`) as they are more intuitive.
2. Removing the `users` field on the `Tag` model (more on this later). This is done so as to ensure that the `Tag` model represents the actual "tag" which can be given to a user, where `TagFolder` represents the "folder" under which the following tag is stored. In your implementation, we would be marking the user with a folder. 
3. Creating a new joined relation `UserTag` which which be used for allotting a user a particular tag. This is the table that we would index as you described. 

Obviously, this is mouthful, so here are the moongose schema's for the same:
```
const TagFolderSchema = new Schema({
  title: { type: String, required: true },
  organization: { type: Schema.Types.ObjectId, ref: "Organization", required: true },
  parent: {
    type: Schema.Types.ObjectId,
    ref: "TagFolder",
    required: false,
    default: null, // A null parent corresponds to a root folder in the organization
  },
});

const TagSchema = new Schema({
  organization: { type: Schema.Types.ObjectId, ref: "Organization", required: true },
  folder: { type: Schema.Types.ObjectId, ref: "TagFolder" },
  title: { type: String, required: true},
});

const UserTagSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
  tagId:   type: Schema.Types.ObjectId, ref: "Tag", required: true }
})

TagFolderSchema.index({ organization: 1 });
TagSchema.index({ organization: 1 });
UserTagSchema.index({userId:1, tagId:1}, { unique: true })

```

**Comment by xoldyckk** [comment]
> @xoldyckk I am thinking of making the following changes:
> 
> 1. Retaining the name `Tag` and `TagFolder` (which are right now analogous to `UserLabel` and `OraganizationLabel`) as they are more intuitive.
> 2. Removing the `users` field on the `Tag` model.
> 3. Use the `Tag` model to represent the actual "tag" which can be given to a user, and use `TagFolder` model to represent the "folder" under which the following tag is stored. This differs from your implementation where we would be marking the user with a folder, whereas the presence of two models would clearly distinguish this. In is compliant with the example @palisadoes earlier shared, where `tagFolder` represents groups like `Status`, `Martial Status` etc. and the `Tag` model represents their actual values.
> 4. Creating a new joined relation `UserTag` which which be used for allotting a user a particular tag. This is the table that we would index as you described.
> 
> Obviously, this is mouthful, so here are the moongose schema's for the same:
> 
> ```ts
> const TagFolderSchema = new Schema({
>   title: { type: String, required: true },
>   organization: { type: Schema.Types.ObjectId, ref: "Organization", required: true },
>   parent: {
>     type: Schema.Types.ObjectId,
>     ref: "TagFolder",
>     required: false,
>     default: null, // A null parent corresponds to a root folder in the organization
>   },
> });
> 
> const TagSchema = new Schema({
>   organization: { type: Schema.Types.ObjectId, ref: "Organization", required: true },
>   folder: { type: Schema.Types.ObjectId, ref: "TagFolder" },
>   title: { type: String, required: true},
> });
> 
> const UserTagSchema = new Schema({
>   userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
>   tagId: { type: Schema.Types.ObjectId, ref: "Tag", required: true }
> });
> 
> TagFolderSchema.index({ organization: 1 });
> TagSchema.index({ organization: 1 });
> UserTagSchema.index({userId:1, tagId:1}, { unique: true });
> ```
> 
> This implementation would mitigate all the challenges that had been introduced by my earlier one in the wake of your review.

I think you got the wrong idea about gmail's labels(tags here). Lemme explain how they work:-

```
Here each level represents a tag which will have a unique id.
Let's take a dummy organization member named john.


# tag start
1 School
# tag end

If john is assigned tag 1, he'll only get assigned to that tag.


# tag start
1 School

1.1 School/class1
1.2 School/class2
# tag end

If john is assigned tag 1, he'll get assigned to tags 1, 1.1, and 1.2.
If john is assigned to tag 1.1, he'll only get assigned to that tag.
If john is assigned to tag 1.2, he'll only get assigned to that tag.


# tag start
1 School

1.1 School/class1
1.2 School/class2

1.1.1 School/class1/Science
1.1.2 School/class1/Mathematics
1.2.1 School/class2/Science
1.2.2 School/class2/Mathematics
# tag end

If john is assigned tag 1, he'll get assigned to tags 1, 1.1, 1.1.1, 1.1.2,
1.2, 1.2.1 and 1.2.2.
If john is assigned tag 1.1, he'll get assigned to tags 1.1, 1.1.1, and 1.1.2.
If john is assigned tag 1.2, he'll get assigned to tags 1.2, 1.2.1, and 1.2.2.
If john is assigned to tag 1.1.1, he'll only get assigned to that tag.
If john is assigned to tag 1.1.2, he'll only get assigned to that tag.
If john is assigned to tag 1.2.1, he'll only get assigned to that tag.
If john is assigned to tag 1.2.2, he'll only get assigned to that tag.

```

So, using that `tagFolder` struture would be wasteful and introduces an extra hop to get to the tags data. Treat everything as tags, not folders. That's how gmail's labels(tags) work.

**Comment by palisadoes** [comment]
1. Could we add a `folder` flag for the tags and in the UI label them as folders?
    1. A person can never be assigned to a folder tag .
    1. A folder flag can never be converted to a person flag.

**Comment by EshaanAgg** [comment]
Introduction of such a flag seems unnecessary. We already have two separate ypes, folders and tags. Why would we want to interconvert them?

Can you provide an example to show the use case?

**Comment by palisadoes** [comment]
Don't differentiate folders at all with a different data structure. Only use tags. That way the infinite folder depth relationships that @xoldyckk is talking about can be maintained.

**Comment by EshaanAgg** [comment]
Alright got it!

**Comment by EshaanAgg** [comment]
@xoldyckk Updated the implementation, to reflect the requested schema changes! Can you review it once before I start writing tests for the same?

**Comment by xoldyckk** [comment]
@EshaanAgg Why don't you just make a PR? It'll be easier to manage and many other people could provide their input too. Doesn't matter if it doesn't have tests yet, it won't be merged without the tests.

**Comment by EshaanAgg** [comment]
I was waiting to make the PR as we do not entertain draft PRs here. And since the implementation of the same of the required a lot of changes to be implemented, I was hoping to get my work reviewed all along the way! Anyhow, I get the point you are trying to make, and I'll open an PR with the detailed description of all the changes I have made.

**Comment by xoldyckk** [comment]
@EshaanAgg I see. Then do this. Since tests are only required for resolvers, don't commit the resolvers yet. Just commit the mongoose models and graphql typeDefs.

**Comment by xoldyckk** [comment]
> > @xoldyckk I am thinking of making the following changes:
> > 
> > 1. Retaining the name `Tag` and `TagFolder` (which are right now analogous to `UserLabel` and `OraganizationLabel`) as they are more intuitive.
> > 2. Removing the `users` field on the `Tag` model.
> > 3. Use the `Tag` model to represent the actual "tag" which can be given to a user, and use `TagFolder` model to represent the "folder" under which the following tag is stored. This differs from your implementation where we would be marking the user with a folder, whereas the presence of two models would clearly distinguish this. In is compliant with the example @palisadoes earlier shared, where `tagFolder` represents groups like `Status`, `Martial Status` etc. and the `Tag` model represents their actual values.
> > 4. Creating a new joined relation `UserTag` which which be used for allotting a user a particular tag. This is the table that we would index as you described.
> > 
> > Obviously, this is mouthful, so here are the moongose schema's for the same:
> > ```ts
> > const TagFolderSchema = new Schema({
> >   title: { type: String, required: true },
> >   organization: { type: Schema.Types.ObjectId, ref: "Organization", required: true },
> >   parent: {
> >     type: Schema.Types.ObjectId,
> >     ref: "TagFolder",
> >     required: false,
> >     default: null, // A null parent corresponds to a root folder in the organization
> >   },
> > });
> > 
> > const TagSchema = new Schema({
> >   organization: { type: Schema.Types.ObjectId, ref: "Organization", required: true },
> >   folder: { type: Schema.Types.ObjectId, ref: "TagFolder" },
> >   title: { type: String, required: true},
> > });
> > 
> > const UserTagSchema = new Schema({
> >   userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
> >   tagId: { type: Schema.Types.ObjectId, ref: "Tag", required: true }
> > });
> > 
> > TagFolderSchema.index({ organization: 1 });
> > TagSchema.index({ organization: 1 });
> > UserTagSchema.index({userId:1, tagId:1}, { unique: true });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This implementation would mitigate all the challenges that had been introduced by my earlier one in the wake of your review.
> 
> I think you got the wrong idea about gmail's labels(tags here). Lemme explain how they work:-
> 
> ```
> Here each level represents a tag which will have a unique id.
> Let's take a dummy organization member named john.
> 
> 
> # tag start
> 1 School
> # tag end
> 
> If john is assigned tag 1, he'll only get assigned to that tag.
> 
> 
> # tag start
> 1 School
> 
> 1.1 School/class1
> 1.2 School/class2
> # tag end
> 
> If john is assigned tag 1, he'll get assigned to tags 1, 1.1, and 1.2.
> If john is assigned tag 1.1, he'll only get assigned to that tag.
> If john is assigned tag 1.2, he'll only get assigned to that tag.
> 
> 
> # tag start
> 1 School
> 
> 1.1 School/class1
> 1.2 School/class2
> 
> 1.1.1 School/class1/Science
> 1.1.2 School/class1/Mathematics
> 1.2.1 School/class2/Science
> 1.2.2 School/class2/Mathematics
> # tag end
> 
> If john is assigned tag 1, he'll get assigned to tags 1, 1.1, 1.1.1, 1.1.2,
> 1.2, 1.2.1 and 1.2.2.
> If john is assigned tag 1.1, he'll get assigned to tags 1.1, 1.1.1, and 1.1.2.
> If john is assigned tag 1.2, he'll get assigned to tags 1.2, 1.2.1, and 1.2.2.
> If john is assigned tag 1.1.1, he'll only get assigned to that tag.
> If john is assigned tag 1.1.2, he'll only get assigned to that tag.
> If john is assigned tag 1.2.1, he'll only get assigned to that tag.
> If john is assigned tag 1.2.2, he'll only get assigned to that tag.
> ```
> 
> So, using that `tagFolder` struture would be wasteful and introduces an extra hop to get to the tags data. Treat everything as tags, not folders. That's how gmail's labels(tags) work.

Turns out this explanation was wrong and I was fooled into believing this because of reading a random google article. LOL.

Here's how it works:-

```
Here each level represents a tag which will have a unique id.
Let's take a dummy organization member named john.


# tag start
1 School
# tag end

If john is assigned tag 1, he'll only get assigned to that tag.


# tag start
1 School

1.1 School/class1
1.2 School/class2
# tag end

If john is assigned tag 1, he'll only get assigned to that tag.
If john is assigned tag 1.1, he'll only get assigned to that tag.
If john is assigned tag 1.2, he'll only get assigned to that tag.


# tag start
1 School

1.1 School/class1
1.2 School/class2

1.1.1 School/class1/Science
1.1.2 School/class1/Mathematics
1.2.1 School/class2/Science
1.2.2 School/class2/Mathematics
# tag end

If john is assigned tag 1, he'll only get assigned to that tag.
If john is assigned tag 1.1, he'll only get assigned to that tag.
If john is assigned tag 1.2, he'll only get assigned to that tag.
If john is assigned tag 1.1.1, he'll only get assigned to that tag.
If john is assigned tag 1.1.2, he'll only get assigned to that tag.
If john is assigned tag 1.2.1, he'll only get assigned to that tag.
If john is assigned tag 1.2.2, he'll only get assigned to that tag.

```
So, it turns out there's no hierarchy of relations here. The nesting is only there for organizing related data together, but that's only on the surface level. At database level this relationship doesn't need to be implemented. Each tag has a unique id and can be uniquely assigned to emails. `school/class1` can be assigned without first assigning `school` to email.

**Comment by EshaanAgg** [comment]
@palisadoes Please reopen this issue. Resolver implementations are left for this.

**Comment by beingnoble03** [comment]
@xoldyckk @EshaanAgg 
Maybe we can use the `$project` aggregation pipeline stage to rename a field in your query results. Like this
```typescript
db.employees.aggregate([
  { "$project": { "employee": "$name", "salary": 1 }}
])
```
This renames `name` field to `employee`.

**Comment by DMills27** [comment]
@beingnoble03 I'm against changing userId to user. I feel like this will create a lot of confusion down the line.

**Comment by beingnoble03** [comment]
@DMills27 Yes, I agree. But I don't think sending a `User` document with the property name `userId` to the client side is a good idea too.

**Comment by palisadoes** [comment]
> @DMills27 @xoldyckk @EshaanAgg Till now there is no tags categorisation layout for managing user tags by administrators by Admin portal can I work on Admin navbar that can be used for categorise users according to tags. I can come up with a detailed plan of action if you guys approve to work on this implementation Admin side. It can further help in volunteer management for the events by the organisation as volunteers with proper tags corresponding event need to be assigned so that administrator as suggested here in event management ideas https://docs.talawa.io/docs/internships/internship-ideas/

We will not be working on ideas in the list until the beginning of the GSoC period. This work is preparatory only

**Comment by xoldyckk** [comment]
> @DMills27 Yes, I agree. But I don't think sending a `User` document with the property name `userId` to the client side is a good idea too.

`userId` won't be sent. Graphql only sends what you wrote in the schema. Even if you disclose private information like bank account number, it won't send it unless it's defined in the schema. Whatever object your return from a resolver get's stripped down to the object you defined in schema. `userId` refers to a relation, a nested resolver. In the schema you won't write it like `userId: String`, you'll write `user: User`, and also have a nested resolver to resolve that user using the `userId` present on the object `parent`.

**Comment by beingnoble03** [comment]
@xoldyckk Ohk. Got the idea. It was a silly doubt, sorry.

**Comment by palisadoes** [comment]
Will this issue be finally closed with the  remaining linked PR?

**Comment by EshaanAgg** [comment]
The following field-level resolvers are left:
- [ ] `UserTag/usersAssignedTo`
- [ ] `UserTag/childTags`
- [ ] `user/tagsAssignedWith`

The linked PR would close the first two, and I will raise a PR for the third one soon after. I am awaiting review for the implementation on the PR, so that I can then add tests for the same,

**Comment by palisadoes** [comment]
What's the progress on this, especially `user/tagsAssignedWith`?

**Comment by EshaanAgg** [comment]
@xoldyckk reviewed how the `GraphQL Connection Factory` should be implemented, and I am currently working on integrating the same. We should have the same ready by the end of this month, and then we can start using the same easily for all the relevant resolvers.

**Comment by palisadoes** [comment]
@EshaanAgg Should this be reopened?

**Comment by EshaanAgg** [comment]
I don't think so, @palisadoes. The tags were added by me in the first week of the GSoC period itself for the backend. Perhaps we forgot to close this issue.
