### ISSUE TITLE
Hardcoded BASE_URL is used instead of dynamic BASE_URL in ```image.ts```

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#1131]
**Describe the bug**
A hardcoded base URL with ```http://localhost:${process.env.port || 4000}/``` is being used for fetching of images. Due to this, the organization images would not be fetched if Talawa Admin is hosted on any service.

**To Reproduce**

1. Go to https://talawa.app
2. Login using email ```testuser1@gmail.com``` and password ```testuser1```
3. Try creating an org with an image
4. Image will not work

**Expected behavior**
The dynamic url should be fetched from the API using req parameter of ```context``` object of GraphQL resolver.

**Actual behavior**
A hardcoded localhost:4000 url is being used everywhere.

**Screenshots**
(Not working URL)
![image](https://user-images.githubusercontent.com/94157520/223183667-d25ab785-3b3e-475f-95fb-bb1fd529fd2b.png)
.
.
Using dynamic url, it would have been (Working URL)
![image](https://user-images.githubusercontent.com/94157520/223183861-c9d31788-e2f1-4a33-a915-6659aef3646d.png)

**Additional details**
This error is restricting the use of images to local environment only.
An application must be developed keeping Production Environment in mind. Otherwise, switching to production environments from local environ all of a sudden in future may require developer upfront.

**Comment by palisadoes** [comment]
Showstopper bug. Thanks
