### ISSUE TITLE
Optimising  Queries for Pagination

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#114]
Following queries needs to be optimised by pagination:
1. users
2. organizations
3. events
4. posts
5. comments
6. groups

I am working on this.

**Comment by sushantmahajan85** [comment]
@sumitra19jha i would like to work on this issue as my first contribution.
could you please elaborate what exactly need to be done.

**Comment by sumitra19jha** [comment]
Hi @sushantmahajan85 
The Queries are needed to be optimised for the pagination.

A sample structure might look something like this
```
usersConnection(
    where: UserWhereInput, 
    orderBy: UserOrderByInput, 
    skip: Int, 
    after: String, 
    before: String, 
    first: Int, 
    last: Int
): UserConnection!
```

**Comment by sumitra19jha** [comment]
I am currently working on this @sushantmahajan85
You can go through the queries once and see if any other query that may require pagination and that i have missed here.

**Comment by palisadoes** [comment]
@sumitra19jha please close this if you are no longer working on it
