### ISSUE TITLE
Activate the LAST_RESORT_SUPERADMIN_EMAIL feature on login

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1146]
**Describe the bug**

We automatically upgrade the the user with the email address defined with the LAST_RESORT_SUPERADMIN_EMAIL parameter to Super Admin on registration.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1120

We need to also enable this feature on login too, with the upgraded status occurring before the first dashboard screen is rendered so that the user automatically goes to the Super Admin screen.

**To Reproduce**

1. Set the LAST_RESORT_SUPERADMIN_EMAIL parameter
2. A previously registered user does not get upgraded on login when the parameter is set 

**Expected behavior**

1. The user gets upgraded.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

- See above

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by oreoluwadnd** [comment]
I would like to work on this, Pls Assign it to me

**Comment by jessy521** [comment]
hello @palisadoes ,
Jessy this side having experience on node js backend of 1.5+ years with stacks like express,mongo,SQL,jenkins,docker,k8s,aws, git,github,javascript,typescript and so on. I think I'm much able to fix this issues  and after 3 internships now I'm willing to contribute on some opensource projects, So here I've come to you, It would be so greatfull to me if you allow me to have some contribution on your project , you can check my github also.
Thanking you,
Jessy

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by EshaanAgg** [comment]
I would like to work on this issue @palisadoes.
