### ISSUE TITLE
jsonwebtoken vulnerable to signature validation bypass due to insecure default algorithm in jwt.verify()

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1151]
**Describe the bug**

1. The jsonwebtoken package is vulnerable to signature validation bypass due to insecure default algorithm in jwt.verify()
1. The version needs to be upgraded to at least v9

**To Reproduce**

- See screen shot

**Expected behavior**

- See screen shot

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

- See screen shot

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/224087908-669d56c6-897f-4e08-89ec-a916f5ab6392.png)

**Additional details**

- See screen shot

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anshgoyalevil** [comment]
@palisadoes 

I would like to work upon this issue.

**Comment by anshgoyalevil** [comment]
@palisadoes 

This issue needs to be closed. The jsonwebtoken version is already at v9.0.0
