### ISSUE TITLE
Adding warning message for LAST_RESORT_SUPERADMIN_EMAIL

### ISSUE THREAD

**Issue by BhuvaneshPatil** [PalisadoesFoundation/talawa-api#1154]
**Describe the bug**
As mentioned in the [discussion](https://github.com/PalisadoesFoundation/talawa-api/pull/1120#issuecomment-1460684524) of this PR - #1120 . We need to add the warnings in console based on super admin creation and presence of variable in env file.

**Expected behavior**
After #1120 is merged we don't need to set the property value from DB for super admin anymore. However, the process needs to be more verbose, because is someone doesn't follow the INSTALLATION process they can get stuck because of no super admin. This is the scenarios where we need to add the warning when user starts the talawa-api server.

- If there is super admin created
    - If the value exist for LAST_RESORT_SUPERADMIN_EMAIL in env
    - if the value doesn't exist in env
- If no super admin is created
    - If the value exist for LAST_RESORT_SUPERADMIN_EMAIL in env
    - if the value doesn't exist in env

There can be multiple scenarios where we want to show the warnings. Please let me know if you find any.

**Actual behavior**
There are no warnings for LAST_RESORT_SUPERADMIN_EMAIL in console.

**Screenshots**
NA

**Additional details**
This needs to be discussed if there are any other scenarios other than mentioned above we need to add for warnings.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by BhuvaneshPatil** [comment]
If this is valid issue, I want to work on it.

**Comment by BhuvaneshPatil** [comment]
I have added the warnings, please let me know if we I will need to improve the grammar - 
1. If super admin exists and variable in env exists - 
**You have created super admin, please remove the LAST_RESORT_SUPERADMIN_EMAIL variable from .env file if you don't require it**
2. Is super admin doesn't exist and variable in env is unset - 
**It looks like you don't have super admin created and LAST_RESORT_SUPERADMIN_EMAIL unset in .env file. Please set the appropriate parameter**

**Comment by palisadoes** [comment]
Submit the PR and let the reviewers fix the grammar

**Comment by BhuvaneshPatil** [comment]
okay
