### ISSUE TITLE
Add Member Mutation

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-api#1166]
**Describe the bug**
currently we dont have a way to convert a user to member...i was working on this issue on admin on side so i have to also create the mutation first to solve the issue...

**Comment by anurag0006** [comment]
Please assign this issue to me as discussed on admin side

**Comment by anurag0006** [comment]
While working on the issue, i observed something wrong in the code i think:

if (state == 0) {
    const {
      data: data_2,
      loading: loading_2,
      error: error_2,
      refetch,
    } = useQuery(ORGANIZATIONS_MEMBER_CONNECTION_LIST, {
      variables: {
        orgId: currentUrl,
        firstName_contains: '',
        event_title_contains: '',
      },
    });
    refetchMembers = refetch;
    data = data_2;
    loading = loading_2;
    error = error_2;
  } else if (state == 1) {
    const {
      data: data_2,
      loading: loading_2,
      error: error_2,
      refetch,
    } = useQuery(ORGANIZATIONS_MEMBER_CONNECTION_LIST, {
      variables: {
        orgId: currentUrl,
        firstName_contains: '',
        admin_for: currentUrl,
      },
    });
    refetchAdmins = refetch;
    data = data_2;
    loading = loading_2;
    error = error_2;
  } else {
    const {
      data: data_2,
      loading: loading_2,
      error: error_2,
    } = useQuery(USER_LIST);
    data = data_2;
    loading = loading_2;
    error = error_2;
  }

here state =  0 is for members while state= 1 is for admins but we are using the same query of  ORGANIZATIONS_MEMBER_CONNECTION_LIST for both these states.... @palisadoes  @xoldyckk  can you give me some advice on how to proceed on this?
![image](https://user-images.githubusercontent.com/107215525/224568900-5a171db5-f1b2-49fe-8eae-f2de9e379169.png)

**Comment by xoldyckk** [comment]
@anurag0006 When pasting code typescript code in discussions make use of tags "```ts" and "```" by pasting the code between them. It formats the code properly and gives syntax highlighting. Makes it easier to understand.

**Comment by jessy521** [comment]
hello @palisadoes ,
Jessy this side having experience on node js backend of 1.5+ years with stacks like express,mongo,SQL,jenkins,docker,k8s,aws, git,github,javascript,typescript and so on. I think I'm much able to fix this issues  and after 3 internships now I'm willing to contribute on some opensource projects, So here I've come to you, It would be so greatfull to me if you allow me to have some contribution on your project , you can check my github also.
Thanking you,
Jessy

**Comment by anurag0006** [comment]
> @anurag0006 Read this https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks. Their example shows how to do it for ruby, you just have to change it to `ts` for typescript code. It formats the code properly and gives syntax highlighting. Makes it easier to understand.



Thanyou for the advice, i have edited the above code and will keep it in mind next time...Along with can you please suggest me that the bug in code is intentional or a mistake as explained in the earlier comment

**Comment by jadeharr** [comment]
@jessy521 This issue has already been assigned.

**Comment by beingnoble03** [comment]
> While working on the issue, i observed something wrong in the code i think:
> 
> ```ts
> if (state == 0) {
>     const {
>       data: data_2,
>       loading: loading_2,
>       error: error_2,
>       refetch,
>     } = useQuery(ORGANIZATIONS_MEMBER_CONNECTION_LIST, {
>       variables: {
>         orgId: currentUrl,
>         firstName_contains: '',
>         event_title_contains: '',
>       },
>     });
>     refetchMembers = refetch;
>     data = data_2;
>     loading = loading_2;
>     error = error_2;
>   } else if (state == 1) {
>     const {
>       data: data_2,
>       loading: loading_2,
>       error: error_2,
>       refetch,
>     } = useQuery(ORGANIZATIONS_MEMBER_CONNECTION_LIST, {
>       variables: {
>         orgId: currentUrl,
>         firstName_contains: '',
>         admin_for: currentUrl,
>       },
>     });
>     refetchAdmins = refetch;
>     data = data_2;
>     loading = loading_2;
>     error = error_2;
>   } else {
>     const {
>       data: data_2,
>       loading: loading_2,
>       error: error_2,
>     } = useQuery(USER_LIST);
>     data = data_2;
>     loading = loading_2;
>     error = error_2;
>   }
> ```
> 
> here state = 0 is for members while state= 1 is for admins but we are using the same query of ORGANIZATIONS_MEMBER_CONNECTION_LIST for both these states.... @palisadoes @xoldyckk can you give me some advice on how to proceed on this? ![image](https://user-images.githubusercontent.com/107215525/224568900-5a171db5-f1b2-49fe-8eae-f2de9e379169.png)

@anurag0006 there's nothing wrong in the code here. Please check the variables, we are passing different variables. Notice the `admin_for` variable when we try to search for admins.

**Comment by anurag0006** [comment]
Yeah sorry, i got to know about it after i wrote the comment and  forgot to delete it

**Comment by xoldyckk** [comment]
> hello @palisadoes , Jessy this side having experience on node js backend of 1.5+ years with stacks like express,mongo,SQL,jenkins,docker,k8s,aws, git,github,javascript,typescript and so on. I think I'm much able to fix this issues and after 3 internships now I'm willing to contribute on some opensource projects, So here I've come to you, It would be so greatfull to me if you allow me to have some contribution on your project , you can check my github also. Thanking you, Jessy

Github issues section isn't for introductions. Join talawa's slack channel. That's a better place for this. Here's the link:-
https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-1qyqturxi-hVPAUyTCdpgTU9g9Buw2Uw

**Comment by xoldyckk** [comment]
@anurag0006 Should I close the issue?

**Comment by anurag0006** [comment]
Not right now...Some things are needed to be done here...i will close the issue myself or will let you know if its not needed anymore
