### ISSUE TITLE
UnblockUser Mutation doesn't work

### ISSUE THREAD

**Issue by prathamesh-mutkure** [PalisadoesFoundation/talawa-api#1169]
**Describe the bug**
The `unblockUser` Mutation doesn't seem to work because the `===` operator fails to check equality between the type of `user._id` and `organization.blockedUsers[i]`

This is most probably caused due to the type difference between `String` and `ObjectId`

**To Reproduce**

1. Run the API server and launch GraphQL Playground
2. Block a user using the `blockUser` mutation
3. See the list of blocked users by querying `blockedUsers` in `Organization`
4. The `id` of the blocked user should be visible
5. Unblock the user using the `unblockUser` mutation
6. Again query `blockedUsers` in `Organization`
7. The unblocked user is still present in the `blockedUsers` array

**Expected behavior**
The unblocked user must be removed from the `blockedUsers` array in `Organization`

**Actual behavior**
The unblocked user is not being removed from the `blockedUsers` array in `Organization`

**Screenshots**

After Blocking User 

<img width="851" alt="Screenshot 2023-03-13 at 1 15 33 AM" src="https://user-images.githubusercontent.com/28570857/224569242-594f157a-42d5-483a-9a95-38d86ef35eea.png">

Unblocking User

<img width="1734" alt="Screenshot 2023-03-13 at 1 18 23 AM" src="https://user-images.githubusercontent.com/28570857/224569388-4f12415e-bd36-4d0b-88dd-645d0d0c8111.png">

After Unlocking User

<img width="849" alt="Screenshot 2023-03-13 at 1 18 55 AM" src="https://user-images.githubusercontent.com/28570857/224569425-987d1563-83b0-4617-b786-d10d65708f8d.png">

**Additional details**
I came across this issue while solving the issue - https://github.com/PalisadoesFoundation/talawa-admin/issues/483, will continue work on that once this is merges.

Also, I've already solved this issue on my end, can this be assigned to me?

**Comment by prathamesh-mutkure** [comment]
Hi @noman2002, can I be assigned this issue? Already fixed on locak

**Comment by xoldyckk** [comment]
@prathamesh-mutkure Assigned to you.
