### ISSUE TITLE
Chore: Add CODE_OF_CONDUCT to the project

### ISSUE THREAD

**Issue by iamsaumya** [PalisadoesFoundation/talawa-api#117]
The project doesn't have CODE_OF_CONDUCT and it is recommended by GitHub to have a CODE_OF_CONDUCT for the projects looking for open source contributions. More info [here](https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project)

I will the email id of the project team to put in the conduct where anyone can reach out in case of violation. 

Thanks!

**Comment by apoorva1509** [comment]
I would like to work on this issue. Can someone please guide me how to get started.

**Comment by iamsaumya** [comment]
@apoorva1509 I am already working on this. Thanks!

**Comment by palisadoes** [comment]
A code of conduct file has been added.
