### ISSUE TITLE
Bug Report: Typo in installation.md

### ISSUE THREAD

**Issue by lata-11** [PalisadoesFoundation/talawa-api#1171]
**Describe the bug**
A typo in the installation.md 

**To Reproduce**

1. Open installation.md
2. Navigate to Setting up .env MAIL_USERNAME and MAIL_PASSWORD ReCAPTCHA Parameters
3.  In step 6 there should be "your" in place of "you"

**Expected behavior**
Copy your usual gmail address to the variable named MAIL_USERNAME in .env file.

**Actual behavior**
Copy you usual gmail address to the variable named MAIL_USERNAME in .env file.

**Screenshots**
![image](https://user-images.githubusercontent.com/103296906/224576440-a944223e-42f9-436f-9dd3-234c55c2932c.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
There is no difference between the expected and actual behavior in your description

**Comment by anshgoyalevil** [comment]
@palisadoes 

I guess, @lata-11 mean to show ```you``` and ```your``` in the expected and actual behavior.

We can ask https://github.com/PalisadoesFoundation/talawa-api/pull/1170 to do this change, since that PR is already open.

**Comment by palisadoes** [comment]
Closing. This very minor change is to be merged in the more substantial one referenced.
