### ISSUE TITLE
Bug Report - Correctly Implement Admin / Super Admin Roles

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1185]
**Describe the bug**

This Admin/Super Admin functionality is not currently implemented correctly. This is how it should work:

**Background**

Say for example that a chain of non-profit community centers with branches in multiple neighborhoods decides to use Talawa. They have a large membership across the region but each member tends to use only their local community center. From time to time members move into new neighborhoods where they decide to switch their membership to their new local branch.

The VP of community relations would want to be the Super Admin as they would be able to add new branches as they were established. The VP would then delegate the management of community relations to each branch manager who would then become an Admin for their local membership.

The VP doesn’t want the branch managers to manage the members who have joined other branches, just the branch they are running.

It is for this reason that we have two types of administrators. Admins and Super Admins.

1. **Admin**: These are members who use use Talawa Admin to manage the people in an organization. This would also include calendars and the organization's news feed.
    1. Admins can only manage a single organization and cannot access any data from other organizations. Expanding this capability is a long term goal.
    1. Admins can promote Users and Members to Admin status for their organization only
1. **Super Admin:** These are members who use use Talawa Admin to manage all organizations in a community.
    1. Super Admins can promote Users and Members to Admin or Super Admin status.
    1. Super Admins have access to all the privileges that an Admin may have over the Admin's organization.

Like other people, an administrator may or may not have joined an organization in the mobile app.

**Expected behavior**

The API needs to enforce these rules.

**Actual behavior**

Depending on the PR.

1. Admins can manage multiple organizations
2. Admins can freely upgrade and downgrade themselves to SuperAdmin status

**Screenshots**
N/A

**Additional details**
Read the core concepts document for more details
- https://docs.talawa.io/docs/applications/overview
- https://github.com/PalisadoesFoundation/talawa-admin/issues/727

**Comment by arushi2715** [comment]
Hey @palisadoes can I work on this?

**Comment by kayceeDev** [comment]
@palisadoes I can take this issue up.

**Comment by adi-uchiha** [comment]
@palisadoes In the description of the issue in the actual behavior section you said 

> Admins can manage multiple organizations

in the docs it says

> Admins can only manage a single organization and cannot access any data from other organizations. Expanding this capability is a long term goal.

I am confused

**Comment by palisadoes** [comment]
This was under the current behaviour section. This needs to be changed.
- Admins can manage multiple organizations

**Comment by arushi2715** [comment]
hey @palisadoes I was a bit confused.
I have to implement the actual behavior and the admin can manage multiple organizations?

**Comment by palisadoes** [comment]
The issue clearly stated what the expected behavior needs to be

**Comment by adi-uchiha** [comment]
@arushi2715 I am working on the admin side of this issue. We need to coordinate. First we need to fix this. 

- Admin should not be able to manage more than one org.

I hope you can do this. You need to add a error handling when an admin is already assigned to a org. You can reference other error handling in the app to take as a examples. After you are done with the PR I will implement this in the frontend.

**Comment by arushi2715** [comment]
hey @adi-uchiha yeah sure. I'll firstly fix the functionality of admin not being able to manage more than one org.
I'll do it asap.

**Comment by kb-0311** [comment]
@palisadoes @arushi2715  When it comes to mutation the desired behavior is already in check. Admin can only make admin mutations to the organization they are an admin of. The problem comes when making queries and ensuring that admins are not allowed all the data a SUPERADMIN is allowed. This is a tricky part would you like to discuss how would you go about it with respect to queries and responses?

**Comment by arushi2715** [comment]
Hey @kb-0311 the problem here is that admin should not be able to manage more than one org. That is not implemented yet.

**Comment by kb-0311** [comment]
@arushi2715 Take a look at the `adminCheck` utility in `src/utilities` directory. If by manage you mean "to make changes in", then that is already implemented for specific admin mutations.

I think what @palisadoes is saying is that the admin should only be able to access data on the admin portal of the for the orgs he/she is an admin of.

**Comment by palisadoes** [comment]
This is clearly defined here: https://docs.talawa.io/docs/applications/overview

**Comment by kb-0311** [comment]
@palisadoes that link does not work currently, here is the correct link.

https://docs.talawa.io/docs/introduction/core-concepts#people-in-communities

**Comment by palisadoes** [comment]
Committed are defined at the top of the page you linked

**Comment by palisadoes** [comment]
Unassigned due to inactivity

**Comment by KrutikaBhatt** [comment]
Sir, can I take up this issue?

**Comment by palisadoes** [comment]
@KrutikaBhatt What's the progress on this?

**Comment by KrutikaBhatt** [comment]
Yes sir, I have started the work and will try to complete is as soon as possible.

@prathamesh-mutkure, can you please give a look at a basic outline of how changes are going to be made. Please do let me know if we need something more to update.

Functions that we need implement :
1. Admin can only manage his organization 
2. Admins can promote Users and Members to Admin status for their organization only
3. Super Admins can promote Users and Members to Admin or Super Admin status
4. Super Admins have access to all the privileges that an Admin may have over the Admin's organization


Planning to procced with it :
1. In `talawa-admin`, if login as ADMIN, show only his organizations
2. Show users of that particular organizations to admin and give him privelage to promote user to Admin - (CreateAdmin Mutation)
4. Super Admins can promote Users and Members to Admin or Super Admin status (New mutations will be required for this)

**Comment by prathamesh-mutkure** [comment]
Hi @KrutikaBhatt, the changes you suggested seem to be valid

> Admin can only manage his organization

- To fix this, we will change the `OrgList` page to show only organizations for which the user is assigned an `ADMIN` role
- `SUPERADMIN` can view all organizations
- We can do this by adding a filter or something

> Admins can promote Users and Members to Admin status for their organization only

- We seem to already have an `adminCheck` utility function in the backend
- The ` createAdmin` mutation isn't properly implemented
- It has a `superAdminCheck` before `adminCheck`
- Thus, from my understanding admins cannot promote other users to the admin role
- This can be fixed by adding a new check, something like `adminOrSuperAdmin`

> Super Admins can promote Users and Members to Admin or Super Admin status
> Super Admins have access to all the privileges that an Admin may have over the Admin's organization

- These are already implemented I guess (make sure to cross-check once)

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by git-init-priyanshu** [comment]
Hey @palisadoes I have a doubt. Right now `adminCheck.ts` checks for admin and superadmin:
<img width="428" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/110045644/9a376634-3a4a-4cd9-bb9f-fe093a0901a6">
I think `adminCheck.ts` should only check for admin and to check for superAdmin we have another utitlity function called `superAdminCheck.ts`
