### ISSUE TITLE
organizationsBlockedBy is always empty

### ISSUE THREAD

**Issue by prathamesh-mutkure** [PalisadoesFoundation/talawa-api#1186]
**Describe the bug**
- The `User` and `Users` queries have `organizationsBlockedBy` set to an empty array
- This is done on purpose so that users are not able to see which organizations they've been blocked by
- This breaks the Block/Unblock functionality in Talawa Admin

**To Reproduce**

1. Start the Talawa API
2. Query for `Users`
3. The `organizationsBlockedBy` is always `[]`

**Expected behavior**
- The current implementation is supposed to return an empty array 
- but this causes problems in Talawa Admin when checking for Block/Unblocked user

**Actual behavior**
- The workaround can be to return an empty array if a regular user calls the query
- And return actual data if admin calls the query

This way the users don't know which organizations have blocked them, only admins can see this information in Talawa Admin.

**Screenshots**
<img width="849" alt="Screenshot 2023-03-17 at 12 34 32 AM" src="https://user-images.githubusercontent.com/28570857/225727081-8ebf13d4-5262-4c69-98f7-d880180047f2.png">

**Additional details**

I came across this issue while solving Issue 483 - https://github.com/PalisadoesFoundation/talawa-admin/issues/483

**Comment by prathamesh-mutkure** [comment]
Hi @noman2002 @prathamesh-mutkure @xoldyckk, can I work on this?

**Comment by xoldyckk** [comment]
@prathamesh-mutkure Since this will exist on the user object itself, can the user themselves also query for `organizationsBlockedBy`?

**Comment by prathamesh-mutkure** [comment]
Hi @xoldyckk, we can check if the user is querying for themselves, and in that case, we'll just return an empty array, like the current implementation.

I'm done with the changes and tests, submitting a PR in a few minutes.

**Comment by xoldyckk** [comment]
@prathamesh-mutkure Nah that's a weird response to clients. If the field cannot be accessed by a user other than admins and superadmins, the server should just return an `Unauthorized` error.

**Comment by prathamesh-mutkure** [comment]
@xoldyckk that makes quite a lot of sense, should this be implemented in the same issue?

**Comment by xoldyckk** [comment]
> @xoldyckk that makes quite a lot of sense, should this be implemented in the same issue?

If it's the intended behaviour then yes, if  `organizationsBlockedBy` field should not be accessible on talawa-mobile.

**Comment by prathamesh-mutkure** [comment]
Is it possible to have access control over just one field, `organizationsBlockedBy` in this case? How do I know if the client that is a normal user queried for the `organizationsBlockedBy` field and return `Unauthorized` error?

**Comment by xoldyckk** [comment]
@prathamesh-mutkure Normally you'd have information about the current user who has sent the request in graphql context object. Though there are inconsistencies in how roles are implemented for users in talawa applications and storing this information in context might not be possible in all cases. Take a look at this discussion for more info:- https://thepalisadoes-dyb6419.slack.com/archives/CSWH4PN0M/p1678636151401999

You should also ask yourself whether you actually need this functionality. Whether you need the information on which organizations the user is blocked from on the user object itself. Because you can have this information on the organization object itself, using a simple field like `isBlocked` boolean.

**Comment by palisadoes** [comment]
@prathamesh-mutkure Refer to this document too https://docs.talawa.io/docs/applications/overview
