### ISSUE TITLE
Fix tsdoc/syntax warnings

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-api#1200]
**Describe the bug**
Currently, there are too many **tsdoc/syntax** ESLint warnings in the **develop** branch. Most of them are **tsdoc-undefined-tag**, **tsdoc-param-tag-missing-hyphen** and **tsdoc-param-tag-with-invalid-type**.

**To Reproduce**

1. Clone the **talawa-api** repository.
2. Install the project dependencies. (npm i)
3. In .eslintrc.json, change "tsdoc/syntax": "off", to "tsdoc/syntax": "warn",
4. Run **npm run lint:check**

**Expected behavior**
Lint should report 0 Warnings and 0 Errors

**Actual behavior**
Lint now reports too many warnings.

**Screenshots**
![pic](https://user-images.githubusercontent.com/58592306/226182777-952bff94-b5cc-478f-9fd3-4f81c1edea45.PNG)

**Additional details**
Multiple contributors can work together as there are too many warnings.

**Comment by palisadoes** [comment]
@tasneemkoushar how do you propose we split this up? By folder? 

Please create the other issues with the split so it can be easily shared.

**Comment by tasneemkoushar** [comment]
> @tasneemkoushar how do you propose we split this up? By folder?
> 
> Please create the other issues with the split so it can be easily shared.

I believe we can merge a contributor's pull request if they are able to resolve at least 5 warnings, but we won't mark this issue as resolved until all warnings have been fixed. This allows for the creation of pull requests by many users, which we will then merge one at a time. While the remedy is minor, it is possible that two persons worked on the same warning. In that case, whoever solves it first will have their modifications merged.

**Comment by palisadoes** [comment]
I'll let you manage the process.

**Comment by SatyarajRana** [comment]
@tasneemkoushar , Can you please assign this issue to me?
