### ISSUE TITLE
Tests for `src/resolvers/Query/getDonationByOrgIdConnection.ts`

### ISSUE THREAD

**Issue by KrutikaBhatt** [PalisadoesFoundation/talawa-api#1206]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage covering all the file

* Tests need to be written for file `src/resolvers/Query/getDonationByOrgIdConnection.ts`. 
* We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
* When complete, all methods, classes, and/or functions in the refactored file will need to be tested. 
* These tests must be placed in a single file with the name `tests/resolvers/Query/src/resolvers/Query/getDonationByOrgIdConnection.ts` You may need to create the appropriate directory structure to do this.

Screenshot:
Please find the screenshot of the codecov report generated for the application.
![image](https://user-images.githubusercontent.com/65107474/226269900-5d99adbe-717a-4276-8aed-ad3f62e0792f.png)
IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly: #490

**Comment by anshgoyalevil** [comment]
@KrutikaBhatt 

There is a separate idea for GSoC'23 regarding the donations system as a plugin.
This file would be therefore modified thereafter.

**Comment by KrutikaBhatt** [comment]
Yes yes, got it! Should I close this issue? It can be reopened once the work is completed later

**Comment by anshgoyalevil** [comment]
@KrutikaBhatt 

Yes. You may close it as of now.
