### ISSUE TITLE
Bug allowing Superadmins to downgrade themselves to lower roles

### ISSUE THREAD

**Issue by Kelvyn2012** [PalisadoesFoundation/talawa-api#1207]
**Describe the bug**
There is a feature that allows superadmin/admin users to downgrade their roles. This can potentially result in a superadmin or admin being locked out of the system if they are the only users with that high level of access. which could cause disruptions in the system's workflow.

**Proposed Solution**
To address this issue, I propose preventing an admin/superadmin from updating their own role by disabling the role update input

**Comment by palisadoes** [comment]
@Kelvyn2012 Do you want to work on this, if so please ask to be assigned immediately it helps us because we don't have to visit the issue twice.

**Comment by SatyarajRana** [comment]
> **Describe the bug** There is a feature that allows superadmin/admin users to downgrade their roles. This can potentially result in a superadmin or admin being locked out of the system if they are the only users with that high level of access. which could cause disruptions in the system's workflow.
> 
> **Proposed Solution** To address this issue, I propose preventing an admin/superadmin from updating their own role by disabling the role update input

Where can I find this function that is used to downgrade a user?

**Comment by SatyarajRana** [comment]
> **Describe the bug** There is a feature that allows superadmin/admin users to downgrade their roles. This can potentially result in a superadmin or admin being locked out of the system if they are the only users with that high level of access. which could cause disruptions in the system's workflow.
> 
> **Proposed Solution** To address this issue, I propose preventing an admin/superadmin from updating their own role by disabling the role update input

So do we want to throw an error saying "Admin/Superadmin cannot change their own role"?

**Comment by palisadoes** [comment]
There needs to be suitable multilingual messaging for all prohibited actions.

**Comment by EshaanAgg** [comment]
I would like to work on this issue. 
@palisadoes
