### ISSUE TITLE
Bug Report: Migrate all the Test Type Names to PascalCase from snakeCase

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1219]
**Describe the bug**
As per convention, all the interface names and type names must be in `PascalCase`, whereas in our tests, they are implemented in `snakeCase`. This must be refcatored so as to create consistency across the repository.

**To Reproduce**
1. Check the source code for tests.

**Expected behavior**
NA

**Actual behavior**
NA

**Screenshots**
NA

**Additional details**
NA

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by EshaanAgg** [comment]
@palisadoes 
Please check the following comments by @xoldyckk in the recently merged PRs.
[Comment 1](https://github.com/PalisadoesFoundation/talawa-api/pull/1191#discussion_r1140190202)
[Comment 2](https://github.com/PalisadoesFoundation/talawa-api/pull/1192#issuecomment-1474917481)

**Comment by EshaanAgg** [comment]
You can also see the most common style recommendations [here too](https://basarat.gitbook.io/typescript/styleguide#type).

**Comment by palisadoes** [comment]
Thanks

- This says it's an unofficial style guide https://basarat.gitbook.io/typescript/styleguide
- Google has one too, which I'm assuming is more official:https://google.github.io/styleguide/tsguide.html 

So answer these questions:

1. Which one should we use as the definitive source in your opinion?
2. What can we do to automatically as GitHub actions enforce some of there style elements?

**Comment by EshaanAgg** [comment]
1. I don't think so that these style guides would have many conflicts amoung themselves, as the practices are pretty standard. 
Anyhow if we had to choose one, the Google one is more appropriate to be the official one as I see it.

2. There is no direct way to enforce complete style guides all at once, but we can use ESLint to enforce some of the styles that we want to opt into. 
Like for our PascalCase for Types and Interfaces style, we can use [this](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/naming-convention.md) Typescript-ESLint rule to enforce the same.

**Comment by palisadoes** [comment]
1. Would we be able to apply the eslint to a GitHub action for the deltas in PRs? 
2. Or would we have to lint the entire codebase first?

**Comment by EshaanAgg** [comment]
They would run as a part of the already existing lint:check script in our workflows. We would just be configuring an additional rule to the linting operation.

**Comment by palisadoes** [comment]
Please open an issue for that. Then I'll assign this issue.
