### ISSUE TITLE
Bug Report: "instructions" spelling error on INSTALLATION.md page

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-api#1227]
**Describe the bug**
"instructions" spelling is wrong on [INSTALLATION.md page](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md)

**To Reproduce**

1. Go to [INSTALLATION.md page](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md)

**Expected behavior**
Correct the spelling error

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![WhatsApp Image 2023-03-26 at 3 19 08 PM](https://user-images.githubusercontent.com/62856848/227767883-22d0bb0a-af0b-4290-9a20-3aec53ba6fb7.jpeg)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by palisadoes** [comment]
Please include all the errors you find in this document in a single PR. Please be cognizant of the limited time of our volunteer reviewers and other stakeholders. Each pull request and issue requires attention and we want to make sure everyone gets a chance to participate. Cases like these divert our resources that could be more effectively deployed. Closing.

**Comment by tinniaru3005** [comment]
Sure I will keep that in mind and I will correct all the errors in a single PR. Thanks a lot for the guidance
