### ISSUE TITLE
Correct the errors in INSTALLATION.md

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-api#1228]
**Describe the bug**
There is no Hyperlink to the docker docs in the [INSTALLATION.md page](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md). This might create problems for users who don't know about docker. 
**To Reproduce**

1. Go to [INSTALLATION.md page](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md)

**Expected behavior**
Add a hyperlink to docker docs so that if someone doesn't have an idea about Docker then they can know about it from the docker docs.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![WhatsApp Image 2023-03-26 at 3 40 24 PM](https://user-images.githubusercontent.com/62856848/227769127-79b20fa0-b9c3-4cdb-9b62-9766f1e6cda3.jpeg)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by palisadoes** [comment]
If you are adding a link, make it to the docker home page. That way we don't have to keep editing it.
