### ISSUE TITLE
Bug Report: Change Admin to API in the INSTALLATION.md

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-api#1231]
**Describe the bug**
The API configuration part of the IMSTALLATION.md file has a typing mistake. THis might create confusion for beginners to the project

**To Reproduce**

1. Go to [INSTALLATION.md page](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md)

**Expected behavior**
Change Admin to API

**Actual behavior**

**Screenshots**
![WhatsApp Image 2023-03-26 at 7 36 04 PM](https://user-images.githubusercontent.com/62856848/227781584-a7abe84f-61e5-461b-bb32-0f915554b07f.jpeg)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by palisadoes** [comment]
Please include all the errors you find in this document in a single PR. Please be cognizant of the limited time of our volunteer reviewers and other stakeholders. Each pull request and issue requires attention and we want to make sure everyone gets a chance to participate. Cases like these divert our resources that could be more effectively deployed. Closing.
