### ISSUE TITLE
Remove extra spaces in command to avoid errors

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-api#1232]
**Describe the bug**
``cp .env.sample .env`` has extra spaces at the start which can create error.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [INSTALLATION.md page](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md)

**Expected behaviour**
Remove the extra spaces at the start.

**Actual behaviour**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![WhatsApp Image 2023-03-26 at 9 21 10 PM](https://user-images.githubusercontent.com/62856848/227787554-ee34e76b-8552-402e-b77a-d72f03befdd3.jpeg)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by palisadoes** [comment]
Extra `line feed` spaces do not cause errors.

Please include all the errors you find in this document in a single PR. Please be cognizant of the limited time of our volunteer reviewers and other stakeholders. Each pull request and issue requires attention and we want to make sure everyone gets a chance to participate. Cases like these divert our resources that could be more effectively deployed. Closing.
