### ISSUE TITLE
Bug Report: Module '"apollo-server-express"' has no exported member 'SchemaDirectiveVisitor'.

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-api#1235]
**Describe the bug**
Module '"apollo-server-express"' has no exported member 'SchemaDirectiveVisitor'.

**To Reproduce**

1. Go to [authDirectives.ts](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/directives/authDirective.ts)

**Expected behavior**

**Actual behavior**

**Screenshots**
![error-api](https://user-images.githubusercontent.com/62856848/228372397-e1a2dd63-c5c8-4c38-b232-7f56651a2847.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by KrutikaBhatt** [comment]
Hey @tinniaru3005, this same issue does not reflect on my local application. I am currently using node version `v18.13.0`. Can you try updating the packages and see if this issue gets resolved
