### ISSUE TITLE
Bug Report: Create Validators in utilities

### ISSUE THREAD

**Issue by beingnoble03** [PalisadoesFoundation/talawa-api#1238]
**Describe the bug**
To check if a user with matching `id` exists, the code has been repeated in many resolvers. Instead validator `getValidUserById` or `ValidateUserById` can be created in utilities, this will make our code base more modular.
A similar approach can be followed for Event and Organization.

**Expected behavior**
Validators in utilities

**Actual behavior**
Code repetition in resolvers.

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by beingnoble03** [comment]
@palisadoes please assign this issue.

**Comment by EshaanAgg** [comment]
@beingnoble03 
Just a caution. 
1. You would find that the checking for the existence of users is being done in two ways across the resolvers:
     A. Using the `.exists()` method when no information about the particular object is needed.
     B. Using the `.findOne()` method when some properties of the particular object must be accessed later.
You would need to handle both of them separately.

2. There are many such existence checks in all of the resolvers for the existence of different objects. Can you think of prospective ideas as to how we can abstract away all of those checks to some common utility? Maybe with the use of a higher-order function with generic input type?

This would help to reduce code duplication to an even greater extent and make our resolvers look a lot better!

**Comment by beingnoble03** [comment]
@EshaanAgg 
1. Yeah, I have already taken these cases into consideration. Thanks for the confirmation btw.
2. Yeah, we can create a common utility like 'getValidObjectById()'. I'll think of implementing this approach if possible. Thanks!

@xoldyckk can you please confirm if implementing a common utility like 'getValidObjectById()' would be a right step?

**Comment by beingnoble03** [comment]
But I do think creating different utils for different objects like 'getValidUserById()', 'getValidEventById()' etc. would be better than a common function using generics because we need to throw corresponding errors for each type of object.
Also, 
In resolvers, 

writing 'const event = await getValidEventById(id);' would be more understandable than 

'const event = await getValidObjectById(id);'

**Comment by EshaanAgg** [comment]
@beingnoble03 
Readability does not have to come at the cost of verbosity!
You can always pass in the type of object you are verifying into the function to make sure of the same.

For example:
```ts
const requestUser = await fetchValid<Interface_User>(request.user.id, USER_NOT_FOUND_ERROR);
``` 
Now it the simply the job of the `fetchValid` to perform the same:
1. Map the `Interface_User` to determine which database model needs to be queried.
2. Query the respective model with the provided id.
3. Return the same if found, or throw an error (even the error to be thrown can be passed in as an argument to ensure more granular control).

In the above implementation, all of the major points (the model and the error if not found), are conveyed in a single line.

**Comment by EshaanAgg** [comment]
Anyhow this is just a very bird-eyed overview of all of this, and more comments on the same can only be made after seeing some sample implementation!

**Comment by CevoJohnson** [comment]
**Observation**
User ID check is repeated in many resolvers.

**Solution**
Create a Validator to handle the id check functionality

**Comment by palisadoes** [comment]
@CevoJohnson Would you like to work on your proposed solution?

**Comment by palisadoes** [comment]
@beingnoble03 Should this be closed? It's over 3 months old.

**Comment by beingnoble03** [comment]
@palisadoes According to this https://github.com/PalisadoesFoundation/talawa-api/pull/1255#issuecomment-1503338866 comment, now, I don't think creating separate validators would be a feasible idea. So, I think we can close this issue.
