### ISSUE TITLE
Automatically Update Talawa-Docs with the latest API Schema

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1240]
**Is your feature request related to a problem? Please describe.**
The API GraphQL schema is constantly changing and it is difficult to manually document it for all the developers who need to use it in the following repos:

1. Talawa
2. Talawa-API
3. Talawa-Admin

**Describe the solution you'd like**
We have identified an open source project that can convert schema files, or query a GraphQL url, to generate a markdown file containing all the elements of the schema using whatever comments the developers have added to the schema definitions.

- https://github.com/exogen/graphql-markdown 

We would like to:

1. use this software to automatically add the latest schema to the appropriate file in Talawa Docs with every post PR push
2. keep the generator code within the Talawa-API repo in a directory tree reserved for GitHub automation (if advisable)

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

See above

**Additional context**

1. The https://github.com/exogen/graphql-markdown installation is incorrect.
2. The build process creates a src/index.js file which the documentation refers to as the `graphql-markdown` executable.

**Comment by EshaanAgg** [comment]
I would like to work on this issue @palisadoes.

**Comment by anwersayeed** [comment]
> I would like to work on this issue @palisadoes.

[SpectaQL](https://github.com/anvilco/spectaql), you may try this library too.

**Comment by palisadoes** [comment]
@EshaanAgg 

You may want to work on this one simultaneously

- #1244

**Comment by palisadoes** [comment]
> > I would like to work on this issue @palisadoes.
> 
> [SpectaQL](https://github.com/anvilco/spectaql), you may try this library too.

This format looks better.

@EshaanAgg try both and let us know which one you think gives a more readable output

**Comment by EshaanAgg** [comment]
@palisadoes @anwersayeed 
The problem that I am facing while using both of the tools is that they need the `.graphql` file of the schema to generate the documentation automatically.

They can do the same themselves, but with some caveats:
1. We can provide them with the URL of the hosted API service, and then they would use Introspection queries to generate the same. The same is not possible for us as we do not host the API anywhere.
2. We can provide them with the schema in `.json` or `.gql` files, but the same isn't generated by us as of now(or I am not aware of the same). Thus even this option goes out of the window for us.

If someone with some prior experience can help me in the same, I would greatly appreciate it.

**Comment by EshaanAgg** [comment]
@palisadoes 
Can we consider hosting the API online? That way we can directly make a cron job in the Talawa-Docs repository to fetch the GraphQL schema from the hosted API, and update the same if any schema definitions have changed. 
We have a hosted API URL linked to the repository, but I don't think so the same is functional any more.

**Comment by anshgoyalevil** [comment]
@palisadoes @EshaanAgg 

We would be integrating Squash CI, which would orchestrate a development server with each PR, and thus we can generate the Schema using that server's link

**Comment by palisadoes** [comment]
Can this be used with a simplified installation process for GitHub? 

- https://github.com/marketplace/actions/mongodb-in-github-actions

**Comment by EshaanAgg** [comment]
@palisadoes @anshgoyalevil 
The problem isn't starting a MongoDB container, it's running the server and executing the Markdown Generator script parallely. Because after we run the 'npm run dev' command, the terminal would be engaged in the same process. 

One prospective way of doing so may be using a docker image.

**Comment by palisadoes** [comment]
GitHub actions allows you to create jobs in which you can make one job dependent on another. We had that before for the API workflow:

- https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow

Docker example:

- https://thetechdarts.com/setup-mongodb-database-in-github-actions-workflow/

We have a limited number of minutes (2000) per month for GitHub actions. Ideally we will want to do this on the push when the PR is merged.

**Comment by palisadoes** [comment]
@EshaanAgg @anwersayeed Which one do you think we should go with?

1. **SpectaQL:** 
    1. is much more visually appealing and usable, though it outputs as HTML versus markdown. 
    1. It uses frames so that the menu items on the left are always visible.
    1. It allows you to have a custom introduction at the top of the page obtained from a pre-defined markdown file.
1. **GraphQL Markdown:** 
    1. Will blend in better with our Docusaurus site as it doesn't have any custom CSS
    1. Doesn't have the customizations

## SpectaQL

![image](https://user-images.githubusercontent.com/16875803/229656596-2e86cbc8-1c63-4fd1-9b0a-2b4dfe6d8f26.png)

## GraphQL Markdown

![image](https://user-images.githubusercontent.com/16875803/229656712-51930ab2-70ca-4f7a-a253-09b5b5f0a8a4.png)

**Comment by palisadoes** [comment]
I've been playing around with this. If you put the SpectaQL output in an HTML iframe the rendering of the query strings becomes a single line of text that scrolls off the page versus what we see in the black sections above.

Let's stick with the Markdown solution, then we can figure out SpectaQL later.

**Comment by EshaanAgg** [comment]
I also advocate for GraphQL Markdown because of its simplicity and the fact that it generates a simple markdown file. It would be much easier to configure the same into Talawa Docs than a complete HTML file! SpectaQL has a nice look and feel, but introduces overhead that I don't think so we need right now.

**Comment by xoldyckk** [comment]
I advocate for this:-
https://magidoc.js.org/introduction/welcome

**Comment by anshgoyalevil** [comment]
@xoldyckk 

I checked Magidoc. The features like Example Query, Sidebar, etc looks good. 

For it to work, custom scalers would need to be configured with ```queryGenerationFactories``` which could increase the implementation complexity.

**Comment by EshaanAgg** [comment]
I agree with @anshgoyalevil. While the look and feel of `Magidoc` is great, I feel it would be much easier to integrate `GraphQL Markdown` into both the workflows and Talawa Docs.

**Comment by palisadoes** [comment]
I just discovered this: 

- https://graphql-markdown.github.io/ A GraphQL plugin for Docusaurus. It imports a `schema.graphql` file.
- [This site shows you how to create the schema file using curl](https://medium.com/@mrthankyou/how-to-get-a-graphql-schema-28915025de0e#:~:text=How%20To%20Get%20The%20Schema%20%E2%80%94%20Introspection%20Queries,called%20a%20GraphQL%20introspection%20query.).
