### ISSUE TITLE
Inefficient Workflows for PR

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1241]
**Describe the bug**
Currently, we are running 4 jobs in the workflow file (`Linter`, `Formatter`, `Type-Checker` and `Testing-Application`) all of which require checking out the content of the repository and installing the dependencies via `npm ci`. The same is inefficient, as the content of the repository does not change, and thus the dependencies must not be installed more than once. These jobs should be clubbed into a single job with multiple steps.

**To Reproduce**
NA

**Expected behavior**
NA

**Actual behavior**
NA

**Screenshots**
NA

**Additional details**
NA

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by EshaanAgg** [comment]
@palisadoes Retagging for assignment and issue approval.

**Comment by palisadoes** [comment]
What are you planning to do?

**Comment by EshaanAgg** [comment]
Same as we did in `Talawa-Admin` repository, I would be editing the `Pull Request` action to run `Linter`, `Formatter` and `Typechecker` in the same job with multiple steps. This would cause the `npm ci` command to run only once, instead of three times, thus reducing the Workflow run time.

**Comment by palisadoes** [comment]
You'll see that we are already spinning up an instance of mongodb for the pull request action.

**Comment by EshaanAgg** [comment]
Yes, @palisadoes I'm aware. We do the same for testing the application.
