### ISSUE TITLE
Create interactive GraphQL visual tool

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1243]
**Is your feature request related to a problem? Please describe.**
The API GraphQL schema is constantly changing and it is difficult to manually document it for all the developers who need to use it in the following repos:

1. Talawa
2. Talawa-API
3. Talawa-Admin

**Describe the solution you'd like**
We have identified an open source project that can visually represent a GraphQL schema which would be useful to be integrated into the API for all future development.  

Visualizer:

- https://ivangoncharov.github.io/graphql-voyager/
- https://github.com/IvanGoncharov/graphql-voyager 

We would like to:

1. use this software to automatically visualize the latest schema, preferably with optional activation.
2. keep the generator code within the Talawa-API repo in a directory tree reserved for GitHub automation (if advisable)

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

See above

**Additional context**

1. The https://github.com/exogen/graphql-markdown installation is incorrect.
2. The build process creates a src/index.js file which the documentation refers to as the `graphql-markdown` executable.

**Comment by EshaanAgg** [comment]
I would like to work on this issue.
