### ISSUE TITLE
Generate image of GraphQL schema with each PR

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1244]
**Is your feature request related to a problem? Please describe.**
The API GraphQL schema is constantly changing and it is difficult to manually document it for all the developers who need to use it in the following repos:

1. Talawa
2. Talawa-API
3. Talawa-Admin

**Describe the solution you'd like**
We have identified an open source project that can visually represent a GraphQL schema which would be useful to be integrated into the API for all future development.  

Visualizer:

- http://nathanrandal.com/graphql-visualizer/ 

We would like to:

1. Use this software to automatically visualize the latest schema
1. Output an image of the schema with each PR and have it automatically update:
    1. This repository
     1. The Talawa docs website
2. Keep the generator code within the Talawa-API repo in a directory tree reserved for GitHub automation (if advisable)

The package offers multiple formats. We should provide a similar array for this to have maximum utility.

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

See above

**Comment by EshaanAgg** [comment]
@palisadoes @anurag0006 
Perhaps [the CLI version of the same tool](https://github.com/sheerun/graphqlviz) would be more relevant to us.

But again, the problem with introspection queries remains that they need the development server to be running to be executed, which, as far as I was able to research, is not possible (and recommendable) to do within GitHub workflows.
I would love to hear if you find any solutions to bypass the same problem.

**Comment by anshgoyalevil** [comment]
@EshaanAgg @palisadoes 

I guess we can integrate this thing while implementing Squash, since it provides the development server to be running, which ultimately would help us in generating the images using CLI version.

**Comment by palisadoes** [comment]
@anurag0006 Here are some reference issues 

- https://github.com/PalisadoesFoundation/talawa-api/issues/1243
- https://github.com/PalisadoesFoundation/talawa-api/issues/1240

**Comment by anurag0006** [comment]
```
"scripts": {
  "generate-docs": "graphql schema:download --endpoint=https://your-api-endpoint/graphql --output=docs/schema.graphql && graphql viz docs/schema.graphql -t html -o docs/schema.html"
}
```

hii guys, sorry for inactivity for last few days...For using these packages, all of these demand for a "api-endpoint" which means we need a server running for the API to put its link here which is possible for the Local server but how do we do it for the workflows,any advice?

**Comment by anurag0006** [comment]
> @palisadoes @anurag0006 Perhaps [the CLI version of the same tool](https://github.com/sheerun/graphqlviz) would be more relevant to us.
> 
> But again, the problem with introspection queries remains that they need the development server to be running to be executed, which, as far as I was able to research, is not possible (and recommendable) to do within GitHub workflows. I would love to hear if you find any solutions to bypass the same problem.


This is what I was talking about, the cli version of tool would be more implementable

**Comment by anurag0006** [comment]
@palisadoes, any guidance on how to proceed further

**Comment by palisadoes** [comment]
This PR has created an instance in the `push.yml` file of the  `.github` directory. Please take a look.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1247

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by anurag0006** [comment]
I did some research on it and came to know that to build the graphql schema on run time, we need the API server to be running at the time which is not a possible in the github workflows(and not a good practice even we find a way to run it)...So we are left with the the command line tool which can be implemented and will create the schema in the CLI...I didn't went with the PR because of Eshaan has already implemented the graphql visualizer which can be accessed in the browser going to : "https://localhost:4000/visualizer" where we get the required Graphql schema on the web...Should I implement the CLI version or its not needed?

**Comment by palisadoes** [comment]
Closing as we have a solution for visualizing the data.
