### ISSUE TITLE
Root directory cleanup

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1248]
**Is your feature request related to a problem? Please describe.**

We have too many extraneous executable files in the root directory of the repo. This causes some risk:

1. Increases the likelihood of someone deleting a file or executing it accidentally or incorrectly
2. Increases the likelihood of files not being used at all because they addressed some legacy requirement

**Describe the solution you'd like**

1. Create a `tools/` directory
1. Migrate all `.ts`, `.tsx`, `.js` and `.py `files to this directory if possible
1. Update the documentation and scripts that rely on these files so that repo works correctly

**Describe alternatives you've considered**
None

**Approach to be followed (optional)**

N/A

**Additional context**

N/A

**Comment by anshgoyalevil** [comment]
@palisadoes 

Please assign this issue to me.

**Comment by palisadoes** [comment]
Do the best that you can.

I first noticed that `[setupFile.ts](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/setupFile.ts)` was only referenced once in the repo, an wondered why it needed to be in `root` . That's when I started noticing the other files.
