### ISSUE TITLE
Remove `createGroup` mutation from resolvers

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1254]
**Describe the bug**
We have defined a mutation called `createGroup` in the typeDefs, but there are no resolvers for the same. 

**To Reproduce**
NA

**Expected behavior**
The particular mutation must have a resolver implemented for it.

**Actual behavior**
NA

**Screenshots**
NA

**Additional details**
NA

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by EshaanAgg** [comment]
@palisadoes 
What is the intended feature of group? Who will access to creating to creating a group? (It is something can all members of an organization can do, or is it something that only the organization admins can do?)

**Comment by palisadoes** [comment]
This may be related to group chats. @nishnatadebnath is this the case?

**Comment by nishnatadebnath** [comment]
No group chats are not related to this.The workflow as planned should be after you create a group , a group chat will automatically be created.

**Comment by palisadoes** [comment]
@EshaanAgg I'm not sure what this is for. You'll have to check the other repos.

**Comment by EshaanAgg** [comment]
@palisadoes @nishnatadebnath 
As far as I could understand, the same isn't being used anywhere as of now, neither in Talawa-Admin or in Mobile (as group chats do not work in the app)
What do you think we should do with the same? What would be the intended functionality of the same?

**Comment by palisadoes** [comment]
It looks like we should remove this.

**Comment by EshaanAgg** [comment]
Got it @palisadoes.
