### ISSUE TITLE
Require Developer Certificate of Origin to All Commits

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#1257]
**Is your feature request related to a problem? Please describe.**
In open source projects, a lot of contributors tend to add the lines of code from outer sources. This makes the project subject to legal rules.

The Developer Certificate of Origin (DCO) is a lightweight way for contributors to certify that they wrote or otherwise have the right to submit the code they are contributing to the project. Here is the full [text of the DCO](https://developercertificate.org/), reformatted for readability:

> By making a contribution to this project, I certify that:
>
> (a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or
>
> (b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or
>
> (c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.
>
> (d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

**Describe the solution you'd like**

Contributors sign-off that they adhere to these requirements by adding a Signed-off-by line to commit messages.
```
This is my commit message

Signed-off-by: Random J Developer <random@developer.example.org>
```
Git even has a -s command line option to append this automatically to your commit message:
```
$ git commit -s -m 'This is my commit message'
```

For this to be enforced among all commits, a DCO bot can be added.
Once installed, this integration will create a [check](https://developer.github.com/v3/checks/runs/) indicating whether or not commits in a Pull Request do not contain a valid Signed-off-by line.

**Describe alternatives you've considered**
None

**Approach to be followed (optional)**
- Go to https://probot.github.io/apps/dco/
- Click ```Add to Github```
- Select the org and repo where it has to be enabled.

**Additional context**
This feature is used by many open source projects since maintaining legal contracts is a good practice.
Example project which use this:
- https://github.com/meshery/meshery.io
- https://github.com/meshery/meshery

Example Check: https://github.com/meshery/meshery/pull/7259/checks?check_run_id=11720541887

After integrating this feature, we can update the ```contributing.md``` to tell developers to include the ```-s``` flag in their commits.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anshgoyalevil** [comment]
@palisadoes 

Please review this issue if its valid.

**Comment by KrutikaBhatt** [comment]
@anshgoyalevil, This is a very important and a needed feature
