### ISSUE TITLE
Add image upload in updatePost mutation

### ISSUE THREAD

**Issue by akankshat05** [PalisadoesFoundation/talawa-api#1258]
**Describe the bug**
Currently, there is no implementation of image upload in the updatePost mutation due to which the images are not getting updated.

Issue - https://github.com/PalisadoesFoundation/talawa-admin/issues/844
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Closing this issue until we have a permanent image upload solution.
