### ISSUE TITLE
bug: Usage of helmet in default configuration blocks graphql playground to open

### ISSUE THREAD

**Issue by iamsaumya** [PalisadoesFoundation/talawa-api#126]
![Screenshot (16)](https://user-images.githubusercontent.com/40148448/111009400-8811fa00-83b9-11eb-9d25-619dfd42c86b.png)

**Comment by yasharth291** [comment]
there was no such problem while i and @Laurell876  ran it on our systems

**Comment by iamsaumya** [comment]
@yasharth291 It's strange 🤔 because this is a well-known issue https://github.com/graphql/graphql-playground/issues/1283.

Sorry to put you through this work but could you check again pulling the lastest codebase, please?

**Comment by yasharth291** [comment]
its working
in my computer very well i think you should fix yourself up

**Comment by yasharth291** [comment]
![Capture](https://user-images.githubusercontent.com/55004621/111027149-672ac280-8414-11eb-8aa3-ef69d05aec43.JPG)

**Comment by iamsaumya** [comment]
Could you visit the playground and share the logs from the browser console please?

**Comment by Sagar2366** [comment]
@iamsaumya, are you getting this error log for specific API or in the initial stage only while accessing GraphQL playground ? I checked browser console log, no error logs present.

**Comment by yasharth291** [comment]
yeah same with me i went for the same process and there was no error in the api may it is problem with his local variables

**Comment by iamsaumya** [comment]
Hey @Sagar2366 ,  Do you mind sharing your index.js? Is this file is the same as your [index.js](https://github.com/Sagar2366/talawa-api/blob/master/index.js)?

**Comment by iamsaumya** [comment]
@yasharth291 what do you mean by local variables?

**Comment by Sagar2366** [comment]
Sure, I don't mind. But it is same as 2020-Q4 branch inde.js file. No changes made to the index.js file.

**Comment by iamsaumya** [comment]
@Sagar2366 Your `index.js` will run completely fine. It is not the same as the master branch lastest `index.js` ([here](https://github.com/PalisadoesFoundation/talawa-api/blob/d9be7bdee0934d01e8c56ff5c87278f467ec7905/index.js#L95)). Your graphql playground should work fine. 

The bug was introduced when the helmet configuration was added. 

For reference, Your index.js doesn't contain this line.

https://github.com/PalisadoesFoundation/talawa-api/blob/d9be7bdee0934d01e8c56ff5c87278f467ec7905/index.js#L94-L96

**Comment by iamsaumya** [comment]
Closing the issue as the PR is merged
