### ISSUE TITLE
Users query returns error when no user match filters

### ISSUE THREAD

**Issue by prathamesh-mutkure** [PalisadoesFoundation/talawa-api#1260]
**Describe the bug**

**To Reproduce**

1. Run Talawa API and open Playground
2. Run the `Users` query with filters that don't match any user
3. It returns an error
4. Instead of an empty array

**Expected behavior**

- When no filters match, the query should return an empty array
- This is useful when filtering all the users in the `Organization People` page
- And the filters don't match
- Like how the `organizationsConnection` query works

**Actual behavior**

- It returns 422 error which caused frontend to fail

**Screenshots**

`Users` Query -

<img width="1769" alt="Screenshot 2023-04-06 at 7 25 30 PM" src="https://user-images.githubusercontent.com/28570857/230399629-fa948480-0e0b-45c9-827b-a4fa8f8361c3.png">

`organizationsConnection` Query -

<img width="1769" alt="Screenshot 2023-04-06 at 7 26 13 PM" src="https://user-images.githubusercontent.com/28570857/230399819-f851d544-742f-4bd0-b60a-5f291b26e388.png">

**Additional details**

I discovered this issue while working on [this](https://github.com/PalisadoesFoundation/talawa-admin/issues/730) issue in Talawa Admin

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@prathamesh-mutkure Do you want to work on this?

**Comment by prathamesh-mutkure** [comment]
Yes, I’d like to work on this @palisadoes

**Comment by palisadoes** [comment]
In future, please ask when you are creating the issue so that we don't have to return to this twice.
