### ISSUE TITLE
Minor changes in removeOrganization.ts to enhance the performance and efficiency

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-api#1261]
**Describe the bug**
The removeOrganization.ts file has many flaws which can cause slower performance like,

- The organization.posts.forEach loop uses async/await syntax to delete each post and comments associated with it one by one, which can result in slower performance. A better approach would be to use Promise.all to run all the delete operations concurrently.
- In the current implementation, when removing an organization, we are fetching each user that has joined the organization and removing the organization ID from their joinedOrganizations field one by one. This is not efficient for large organizations with many members. A better approach would be to use the $pull operator to remove the organization ID from all affected users' joinedOrganizations field in one go.
- The code has several nested if statements to handle errors and check user roles. This can make the code harder to read and follow. We can use early returns to exit the function early.
- The code currently calls the lean() method on several MongoDB queries. While this can improve performance, it can also cause issues with accessing related models or fields. Unless you're sure you don't need the functionality provided by the full model object, it's better to avoid calling lean().

**To Reproduce**

1. run the local server 'using npm run dev'
2. run the query removeOrganization

**Expected behavior**
The following changes can result in enhanced performance,

- Remove unnecessary lean() calls
- Use $pull operator to remove organization IDs from users' fields.
- Use Promise.all to delete posts and comments associated with the organization.

**Actual behavior**
The current implementation can can result in slow performance

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/230422331-79ed1d7a-88e6-43b3-9689-665c96651c04.png)
![image](https://user-images.githubusercontent.com/76558924/230427097-6997afbb-3c79-4e65-b7db-15a7f853d646.png)

**Additional details**
Not required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishant3721** [comment]
@palisadoes I would like to work on it.

**Comment by palisadoes** [comment]
Add @xoldyckk to the PR reviewers for this.
