### ISSUE TITLE
Error handling that can occur during the file upload process for the file uploadImage.ts

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-api#1264]
**Describe the bug**
Currently, the function only rejects the promise if an error occurs during the createReadStream call.

**To Reproduce**

1. run the server using 'npm run dev'
2. upload the file using the query which has the upload file feature

**Expected behavior**
Error handling should be done for the upload process also.

**Actual behavior**
Currently, the errors are handled for the createReadStream call, not during the upload file process.

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/230475509-a54f28ab-a169-4d33-8420-e96693aeb4c7.png)

**Additional details**
Not required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishant3721** [comment]
@palisadoes please assign me this.

**Comment by palisadoes** [comment]
Closing.  GSoC 2024 potential project
