### ISSUE TITLE
Bug Report: Cursor pagination implementation for `connection` queries.

### ISSUE THREAD

**Issue by beingnoble03** [PalisadoesFoundation/talawa-api#1273]
**Describe the bug**
Cursor pagination implementation for `connection` queries. This issue is linked with [this talawa-admin issue](https://github.com/PalisadoesFoundation/talawa-admin/issues/676).

**Expected behavior**
Cursor pagination implementation for `connection` queries.

**Actual behavior**
Wrong implementation for `connection` queries.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by beingnoble03** [comment]
@palisadoes please assign this issue to me.

**Comment by beingnoble03** [comment]
@palisadoes please assign this issue to me.

**Comment by EshaanAgg** [comment]
@beingnoble03 Please review #1187 as it aims to create a connection factory that would help to reduce the boilerplate that is used in creating the current connection queries. You can comment on whether it is flexible enough yet or not.

**Comment by stephanmingoes** [comment]
The problem at hand revolves around improving pagination methods. The proposed solution introduces cursor-based pagination as an alternative to the conventional approach. Cursor-based pagination offers distinct advantages by using a unique identifier to pinpoint the current position within a list. This enables us to easily specify whether we want to retrieve items before or after the identified position.

To do this I would have to update the relevant fields in the schema to include the necessary cursor-based pagination parameters and response types and implement the cursor-based pagination logic in the resolver.

May I be assigned this issue.

**Comment by jordan-barrett-jm** [comment]
Assigned to @stephanmingoes due to lack of previous activity

**Comment by palisadoes** [comment]
Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.
