### ISSUE TITLE
Improve and Standardize Automated Linting Tests

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1275]
**Is your feature request related to a problem? Please describe.**

1. We currently have automated linting included in our PR process. 
2. Unfortunately we keep having issues where tests have warnings that could have been prevented with better linting. 
3. We need to look at the eslint plugin that we use and determine which additional linting rules should be enforced and implement them as part of our PR process. 
4. This will need to be synchronized between Talawa-API and Talawa-Admin
     - https://github.com/PalisadoesFoundation/talawa-api/issues/1275
     - https://github.com/PalisadoesFoundation/talawa-admin/issues/861

The list of potential rules can be found here:

- https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin/docs/rules 

**Describe the solution you'd like**

See above

**Describe alternatives you've considered**

See above

**Approach to be followed (optional)**

See above

**Additional context**

See above

**Comment by KrutikaBhatt** [comment]
Can I work on this issue ?
