### ISSUE TITLE
chore: Remove unused packages

### ISSUE THREAD

**Issue by iamsaumya** [PalisadoesFoundation/talawa-api#128]
Right now there are three unused packages in the app

1. `apollo-server`
2. `babel-jest`
3. `config`

I could not find any useful occurrences of these packages in the codebase. I think it is better to uninstall them.

**Comment by yasharth291** [comment]
config is being used in the index.js that is why it was giving error lately.
apollo-server is being used to host the mongo db 

so i think these 2 are important and you should not close them and change you pull request accordinly

**Comment by iamsaumya** [comment]
I think I must've missed something, Could you please point me to the line of code where these packages are being used?

**Comment by yasharth291** [comment]
have you pulled the current repo?

**Comment by yasharth291** [comment]
there were changes done in the night. i think you should pull it once and see the index.js page

**Comment by iamsaumya** [comment]
> have you pulled the current repo?

I have. It'd be very helpful if you can help me find the LOC where these packages are being used. I will make the changes appropriately.

**Comment by yasharth291** [comment]
config was used before but removed from db.js now you can remove them as well

**Comment by iamsaumya** [comment]
Thanks for the confirmation!

> apollo-server is being used to host the mongo db

What about this? Is apollo-server being used?

**Comment by iamsaumya** [comment]
@Laurell876 and @Sagar2366, Could you please review this issue? If this needs to be fixed then we can merge #129 otherwise feel free to close the issue and PR. 

Thanks!

**Comment by iamsaumya** [comment]
Closing the issue as the PR is merged.
