### ISSUE TITLE
Bug Report - `createGroup` mutation

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-api#1283]
**Describe the bug**
Right now there is no `createGroup` mutation that exists even though it is defined and returned as a resolver.

We will need to create this missing resolver.
**To Reproduce**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
pls assign this to me

**Comment by beingnoble03** [comment]
@kb-0311 `createGroup` mutation was removed from this issue -> #1254

**Comment by kb-0311** [comment]
ohh okay got it thanks @beingnoble03

**Comment by kb-0311** [comment]
closing thus issue
