### ISSUE TITLE
Rename TypeScript interfaces according to standard naming rules

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#1286]
**Describe the bug**
Shared coding conventions allow teams to collaborate effectively. This rule allows to check that all class names (and interfaces for TypeScript) match a provided regular expression.

The Interfaces should have names matching regex ```^[A-Z][a-zA-Z0-9]*$```

**Expected behavior**
Example:
```export interface InterfacePlugin```

**Actual behavior**
Example:
```export interface Interface_Plugin```

**Screenshots**
NA

**Additional details**
There are over 50+ such names which need to be changed.
This is affecting the code smell rate on SonarCloud

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anshgoyalevil** [comment]
@palisadoes 

Please assign it to me.

**Comment by palisadoes** [comment]
Can this be included in this work? 

- https://github.com/PalisadoesFoundation/talawa-api/issues/1275

We'll need to add an eslint rule to prevent this from happening again.

**Comment by anshgoyalevil** [comment]
@palisadoes 

Yes, it may be included. Or I will include the rule with this issue's PR.

**Comment by palisadoes** [comment]
Let the assignees for :

- https://github.com/PalisadoesFoundation/talawa-api/issues/1275
- https://github.com/PalisadoesFoundation/talawa-admin/issues/861

know that you will be adding this.

**Comment by anshgoyalevil** [comment]
I just checked, the rule is already included in the codebase

```
{
        "selector": "interface",
        "format": ["PascalCase"],
        "prefix": ["Interface_", "Test_Interface_"]
      },
```
This is wrong, since there should not be an underscore.

I would modify this rule.

**Comment by palisadoes** [comment]
OK, please go ahead.
