### ISSUE TITLE
Load Sample Data into MongoDB via a NPM Command

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#1293]
**Is your feature request related to a problem? Please describe.**
Currently, whenever a contributor starts the server for the first time, they need to create user account, posts, events, etc by themselves.

**Describe the solution you'd like**
Like we have a script to start the server ```npm run dev```

We can create another script ```npm run load:sample```

We need to define different sample JSON data of the collections, and import them using the mongo function.

A contributor changing the Database Collection names or adding some new fields would require to make changes in JSON data also, so imports can work in future too.

**Describe alternatives you've considered**
No Alternative currently

**Approach to be followed (optional)**
1. Create a script ```loadSampleData.ts``` 
2. Import JSON files and insertMany function will do the rest.
3. Create a command to trigger the script

**Additional context**
It would help in implementing tons of features in future, like on-the-fly development environments.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anshgoyalevil** [comment]
@palisadoes 

Please assign it to me.

**Comment by EshaanAgg** [comment]
@anshgoyalevil I feel that `CSV` files would be better suited for this. 
We can create one csv for each table, a Python file that can allow the users to select the tables they want to populate, so that we do not bloat the database with objects that the developer may never use.

**Comment by anshgoyalevil** [comment]
@EshaanAgg 

I am not focusing on Python for the moment. I am thinking of creating a headless script, which do not need any human interaction. It is much needed in context of CD.

**Comment by EshaanAgg** [comment]
But the problem with the same is that such a script will definitely insert the data for all the tables into the database. I am just thinking about the use case if which the user would want to import only some of the data, lets say User and Organization.

**Comment by anshgoyalevil** [comment]
Like, you may have seen BreezeChms, there we have some prepopulated data, and we cannot say it's bloating the database. It is needed to test all functionalities afterall.

**Comment by EshaanAgg** [comment]
Well if not bloating, I feel that some of it are un-necessary at least. But I see the merit in your approach too. It is must simpler to implement and would be easier to use too. I guess @palisadoes would be able to better comment on the level of granularity that the API needs right now.

**Comment by anshgoyalevil** [comment]
In case a user want to choose the data, we can have an option parameter passed to the npm script, which would detect what data is needed to be inserted, for example 

```npm run import:sample```
 For complete data import

```npm run import:sample --users```
For importing only users..
.
.
Etc


But that would be redundant, since it would increase logical complexity, and we need a solution, which could work without the user interaction.

**Comment by EshaanAgg** [comment]
The aditional flag option seems great to me to be honest. As I see it, at the end, the implementational complexity is a small overhead that we must bear to provide the end user and future developers with finer control over the data and all the relevant features of the Talawa ecosystem.

**Comment by anshgoyalevil** [comment]
@EshaanAgg 

Yes, it would require changes, but to the small sample dataset.

For example, 

- in the complete import, there would be one user with SUPERADMIN access. 

- But, in case of data with ```--users``` flag, there would be several sample users. 

Changing the data in the later one seems more challenging. 

Nonetheless, having complete control over the sample data set would provide the best UX, as you said, so I think we can handle that developer overhead part in changing the sample dataset

**Comment by anshgoyalevil** [comment]
@palisadoes 

Please assign it to me.

**Comment by palisadoes** [comment]
We need to investigate ways to pre-populate data into the database. This would be useful to:

1. use as test data for our CI/CD pipeline
1. create dummy data that simulates a real organization to use for a live demo of the MVP that we hope we can have by the end of summer. Having the ability to schedule the automatic overwriting of the data on a live demo site would help reduce the risk of disruptive actors. We would need to figure out security model for this, but the first step is to have the data.

**Comment by anshgoyalevil** [comment]
@palisadoes 

Yes Sir, I will handle all of these cases.

For the automatic overwriting of the data, I am thinking of using cron-job which would get triggered only if the server is running with ```node.environment``` as ```test```
