### ISSUE TITLE
Talawa-Docs update for API pushes is failing

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1298]
Example:

1. This push action https://github.com/PalisadoesFoundation/talawa-api/actions/runs/4689169073/jobs/8310580892
1. Created by merging this PR: https://github.com/PalisadoesFoundation/talawa-api/pull/1295
1. Created this error in Talawa-Docs: https://github.com/PalisadoesFoundation/talawa-docs/actions/runs/4691260612

Why is that?

**Comment by EshaanAgg** [comment]
Ill check it out and post my updates here. @palisadoes

**Comment by EshaanAgg** [comment]
@palisadoes You can close this issue as completed, as the same is not related to Talawa API.
