### ISSUE TITLE
Add or Throw error if users are not found to work with errors easily in admin panel.

### ISSUE THREAD

**Issue by Pranauv-Kumar1803** [PalisadoesFoundation/talawa-api#1301]
**Is your feature request related to a problem? Please describe.**
When returning the response for search or filtering of people, if users are not found, it is not throwing the userNotFound error.
This is vital as this is what we check in the admin panel to show appropriate userNotFound results or toast messages.

**Describe the solution you'd like**
Fetching people's details should be returning an error if user is not found so as to work with that in the admin panel.

**Approach to be followed (optional)**
Approach that I would follow would be to make new or use existing constants from the constants.ts file to throw error if user is not found as it would be easier to work with errors from responses in the admin panel.

This is just one idea of mine! If anybody has any other idea, it is welcome!

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by prathamesh-mutkure** [comment]
Hi @Pranauv-Kumar1803, isn't that how it's supposed to work?

We made a change to return an empty array instead of the `UserNotFound` error some time ago.

**Comment by Pranauv-Kumar1803** [comment]
yeah i saw that and that is why i closed this :) Sorry lol

**Comment by palisadoes** [comment]
Do you want to work on this?

**Comment by Pranauv-Kumar1803** [comment]
No sir, I actually made this issue and after that only saw that there was a better method as @prathamesh-mutkure told before!

**Comment by Pranauv-Kumar1803** [comment]
No sir, I actually made this issue and after that only saw that there was a better method as @prathamesh-mutkure told before!
