### ISSUE TITLE
Create a NPM Script to automate the local environment setup

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#1313]
**Is your feature request related to a problem? Please describe.**
Currently, a new developer setting up the talawa api project locally may not want to manually go through the installation process which include running ```openssl rand -hex 32``` for access tokens, pasting the mongodb url, copying the .env file from .env.sample file, etc.

**Describe the solution you'd like**
We have a installer.py script in this project, which can be used to automate this process, but, wouldn't it be better if we also have a npm script to automate it.

Many Node.JS developers are not comfortable with python, as their primary stack is Django. Python is also not installed in the Windows OS by default, which is the default OS for many contributors/developers.

We can have a npm command
```npm run setup```

which will start the interactive CLI session which will ask questions if things can't be generated automatically, or would have an option if that .env variable is not mandatory.

**Describe alternatives you've considered**
There's no alternative to this

**Approach to be followed (optional)**
- Use the popular npm package ```Inquirer``` to create an interactive session
- Update documentation to include this command.

**Additional context**
This would improve the new developer onboarding process a lot.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
1. We created a python script to do this.
2. I prefer the idea of using npm as we'll only need expertise in one language for the repo.
3. Look at the functionality of the python script and duplicate its key elements.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by anshgoyalevil** [comment]
@palisadoes 

Yes sir, I have my exams going on.
They would be over in 4 days, after that, I will submit a PR for this issue.
The work is midway in my local machine.

**Comment by saiteja13427** [comment]
@palisadoes Seems like this issue is open to take up.
Can I work on this?
If yes, can you please assign this to me, I can start working on this immediately and will raise a PR within a day.

**Comment by saiteja13427** [comment]
@palisadoes I have completed writing the script, before raising the PR just wanted to confirm where to update the docs about this.

Shall I add it right under the configuration heading? Here: https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#configuration

**Comment by palisadoes** [comment]
Yes. We should also remove the existing python script for completeness.

**Comment by saiteja13427** [comment]
Sure, let me delete the python script and push it to the PR

**Comment by palisadoes** [comment]
Unassigning due inactivity

**Comment by itzMik3y** [comment]
Please assign this issue to me

**Comment by palisadoes** [comment]
@itzMik3y The originally proposed changes were included in the linked PR below

- https://github.com/PalisadoesFoundation/talawa-api/pull/1334

If you feel there could be improvements to the solution. Please open an issue and ask to be assigned. Thanks for participating.
