### ISSUE TITLE
Async functions withour any await expresssions

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-api#1322]
**Describe the bug**
A function that does not contain any await expressions should not be async (except for some edge cases in TypeScript which are discussed below). Asynchronous functions in JavaScript behave differently than other functions in two important ways:

- The return value is always a Promise.
- You can use the await operator inside them.

**To Reproduce**
Not required

**Expected behavior**
NA

**Actual behavior**
NA

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/233727168-34494ee8-5639-4caf-9131-c6f644277a7e.png)
![image](https://user-images.githubusercontent.com/76558924/233727255-f6c5d65d-6e06-4484-b9bb-f5140ca571c5.png)
![image](https://user-images.githubusercontent.com/76558924/233727318-4e70d354-7180-450f-b30e-bf5a7480b01b.png)

**Additional details**
Not required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishant3721** [comment]
@palisadoes I would like to work on this

**Comment by palisadoes** [comment]
Please be clearer about what you want to achieve:

1. Are you going to correct async functions that don't have await expressions or
2. Are you going to look for functions that have await expressions that are not async?
