### ISSUE TITLE
The GitHub PR workflow does not check whether the API can start

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1329]
**Describe the bug**

The GitHub PR workflow does not:

1. check whether the API can start
2. verify that data can be retrieved from the running API

**To Reproduce**

1. Run workflow
3. API doesn't start

**Expected behavior**

1. Run workflow
2. API starts
4. Workflow checks that the API starts

We now have a test data that can be loaded that resides in the repo. This should be used as part of the test.

**Actual behavior**

- The API isn't started and tested in the PR workflow

**Screenshots**

- N/A
**Additional details**

- N/A

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
@palisadoes sir can I take this issue?

**Comment by niladrix719** [comment]
@palisadoes can i take on this

**Comment by AyushiitrFreedom** [comment]
@palisadoes her Peter can i take this issue , I feel pretty confident on this

**Comment by palisadoes** [comment]
Unassigning due to lack of activity

**Comment by adi790uu** [comment]
Hey @palisadoes I would like to work on this issue

**Comment by palisadoes** [comment]
Closing. Duplicate
- https://github.com/PalisadoesFoundation/talawa-api/issues/1343
