### ISSUE TITLE
Use of for-of loop instead of a for loop

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-api#1330]
**Describe the bug**
A for-of-loop is recommended when the loop index is only used to read from the collection. Also, it becomes easy to maintain, read, and understand the code.

**To Reproduce**
Not Required

**Expected behavior**
NA

**Actual behavior**
NA

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/233959168-8c243f1a-ae71-4302-9f75-c2735b388521.png)

**Additional details**
Not required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishant3721** [comment]
@palisadoes I would like to work on this.

**Comment by palisadoes** [comment]
Closing. This issue is to generic.

**Comment by nishant3721** [comment]
Okay sir
