### ISSUE TITLE
Cyclomatic complexity more than allowed in getSort.ts

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-api#1331]
**Describe the bug**
Cyclomatic complexity is a measure of how complex a software program is. It counts the number of different ways a program can run based on its decision points. Decision points are places in a program where a decision is made, such as an "if" statement or a "while" loop.
So, the more decision points a program has, the higher its cyclomatic complexity. This means that the program has more possible paths to take, and therefore can be harder to understand, test, and maintain.

**To Reproduce**
Not Required

**Expected behavior**
NA

**Actual behavior**
NA

**Screenshots**
Not required

**Additional details**
Not required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishant3721** [comment]
@palisadoes I would like to work on it.

**Comment by palisadoes** [comment]
This is too generic. You haven't stated:

1. where you plan to make these changes and 
2. whether it is a good idea to do so in each case. 

Please spend more time in identifying and defending its use in the repo.

Don't be discouraged. Think this through some more and try again.

Closing.

**Comment by nishant3721** [comment]
Okay sir
