### ISSUE TITLE
Bug Report: Update `package-lock.json`

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1335]
**Describe the bug**
Currently, on running the workflows, we get the following warning while installing dependencies:
![image](https://user-images.githubusercontent.com/96648934/237055955-0d2a2375-6815-4dab-a938-cc3e0d3a7a09.png)
The lock file must be upgraded from version 1 to version 3.

**Comment by EshaanAgg** [comment]
I would like to work on this issue. I can fix it as a part of my already open PR #1332.

**Comment by perminder-17** [comment]
//assign

**Comment by palisadoes** [comment]
Reassigning due to inactivity

**Comment by perminder-17** [comment]
Sorry for the inconvenience, I am unable to understand the bug. Is I just have to update the package-lock.json file?
Please reply, I am working on this issue.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by swaaap-nil** [comment]
@palisadoes please assign this to me

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by Anubhav-2003** [comment]
I want to work on this issue... please assign me

**Comment by Anubhav-2003** [comment]
@palisadoes Can you please look into my pull request and approve/merge it. Thank you.
