### ISSUE TITLE
Feature Request: auto populating plugin data during the initial server setup.

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#1337]
**Is your feature request related to a problem? Please describe.**
To make plugins work there must be some default plugin data present in the database. Previously, it was supposed that the data should be added manually by the developers but it was not a feasible approach as new contributors were not aware about this and they were unable to use or test plugins.

**Describe the solution you'd like**
Some default plugin data should be automatically populated in the mongoDB collection to make sure that all plugin work smoothly

**Describe alternatives you've considered**
  N/A
**Approach to be followed (optional)**
A clear and concise description of approach to be followed.
 
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
I'd like to get assigned to fix this.

**Comment by SiddheshKukade** [comment]
@palisadoes please assign

**Comment by JamarTG** [comment]
I'd like to work on this issue

**Comment by SiddheshKukade** [comment]
@JamarTG I'm actually working on it.
