### ISSUE TITLE
Bug Report: Adding the `generatedGraphQLTypes.ts` to gitignore

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#1338]
**Describe the bug**
I'm getting this  `generatedGraphQLTypes.ts`  file generated automatically after compiling the project with `npm run dev` should we add it to gitignore

**To Reproduce**

1. Clone repo
2. Do `npm run dev`
3. File  `generatedGraphQLTypes.ts` gets generated and it's untracked on git.

**Expected behavior**
It can be ignored to git if not important.

**Actual behavior**
The files getting untracked unnecessarily.
**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/65951872/2694e2fd-e6d5-413f-a425-425f8a2e6f7e)
 **Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by xoldyckk** [comment]
@SiddheshKukade I guess you can get rid of it but you have to make sure that it's generated during all workflows and processes where typescript is concerned. One example is, it should be automatically generated each time someone clones and installs the dependencies on their local systems. I doubt there are many places where that's needed tho.

**Comment by SiddheshKukade** [comment]
So @xoldyckk would it be better to merge this file in the repo can it solve the issues ? What do you think?

**Comment by xoldyckk** [comment]
> So @xoldyckk would it be better to merge this file in the repo can it solve the issues ? What do you think?

I didn't understand what you meant by that.

**Comment by palisadoes** [comment]
@SiddheshKukade  What is the status of this?

**Comment by SiddheshKukade** [comment]
@palisadoes sir, I'm actually having practical exams untill 3rd june and I've requested to take break for some days from my mentor tasneem mam.
I'll get started to work on this in a few days.

**Comment by palisadoes** [comment]
What's the status on this?
