### ISSUE TITLE
`CI/CD` : Check for Starting a Server.

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-api#1343]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

For PR workflow under talawa-api repository, there should be a job that checks whether the development server starts successfully or not.

**Describe the solution you'd like**

A job that checks whether the apollo server can start or not.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
@palisadoes Did not realize I was assigned this issue. Unassigning myself, for now, to let newer contributors get a chance. If the issue becomes stale, tag me here.

Please do put the good first issue as a label on this one.

**Comment by Shub3am** [comment]
Hey, Is this issue assigned?

**Comment by kb-0311** [comment]
@Shub3am no it is not, You can ask for an assignment.

**Comment by Shub3am** [comment]
@kb-0311 Can i get some guidance on this issue?

**Comment by kb-0311** [comment]
@Shub3am Sure, so basically the idea of this CI/CD check is to make sure that the Apollo server with the given schema at that point can be started. No need to create all the specifications for that complete server which will require a lot of env variables to be defined but rather try to create a mock Apollo server which has only the basics of the actual talawa-api apollo server defined as specs like schema , context , format error etc.

**Comment by ishtails** [comment]
can this issue be assigned to me?

**Comment by palisadoes** [comment]
Reopening due to a syntax error in the PR.

**Comment by ishtails** [comment]
hey there, sorry for the inconvenience. Could you point out what's  wrong so that I could fix it asap?

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment]
My pr has a lot of errors. I think someone else should solve it.
@palisadoes

**Comment by adi790uu** [comment]
Hey @noman2002 @xoldyckk I would like to work on this!

**Comment by adi790uu** [comment]
Hey @noman2002 @xoldyckk would like to work on this

**Comment by MikiPAUL** [comment]
Hey @noman2002 I would like to work on this issue

**Comment by noman2002** [comment]
@adi790uu Let him work on this one. As he is new here.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Ayu5hsingh** [comment]
Can i work on this issue?

**Comment by shankeleven** [comment]
Please assign the issue to me, would be gald to work

**Comment by Veer0x1** [comment]
I would like to work on this issue.

**Comment by shankeleven** [comment]
sir, in this issue do i have to just write a job in workflow or do i have to write a test file for sending queries to graphl server and validating responses?

**Comment by kb-0311** [comment]
@shankeleven you first have to write a test file for the same and then execute it in the workflow as a check.

**Comment by shahzamaahmad** [comment]
How can i contribute

**Comment by Cioppolo14** [comment]
@shahzamaahmad Please look through the unassigned issues in our repositories, and find one that fits your skill set. Comment on an unassigned issue that you feel you can complete, and mention that you'd like to work on it.  Please make sure to review this page: https://github.com/PalisadoesFoundation, and the important documents in each repo before contributing to that repo.  Thank you for wanting to contribute!

**Comment by dhruvgupta0503** [comment]
I can work on this issue pls assign it to me

**Comment by Cioppolo14** [comment]
@dhruvgupta0503 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.
