### ISSUE TITLE
Events are not returned

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa-api#1346]
**Describe the bug**
On query, event field is not populated, problem in flutter app  

**To Reproduce**

1. Start App and try to join any org
2.
3.
4.

**Expected behavior**
It should return the Event list for the organization as it is needed
**Actual behavior**
Event field is NULL

**Additional details**
error message
`[ +650 ms] I/flutter (14107): [GraphQLError(message: Cannot return null for non-nullable field Event.creator., locations: null, path: null, extensions: null), GraphQLError(message: Cannot return null for non-nullable field Event.creator., locations: null, path: null, extensions: null)]`

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
@kb-0311 @EshaanAgg Can you shadow some light here, can we just populate the field?

**Comment by EshaanAgg** [comment]
@Ayush0Chaudhary Which query is the flutter client using?

**Comment by palisadoes** [comment]
Should this be closed?

**Comment by Ayush0Chaudhary** [comment]
@EshaanAgg 
    mutation {
      joinPublicOrganization(organizationId: "$orgId") {
          joinedOrganizations{
            _id
            name
            image
            description
            isPublic
            creator{
              _id
              firstName
              lastName
              image
            }
            
          }
      }
	}

**Comment by Ayush0Chaudhary** [comment]
> Should this be closed?

not yet sir @palisadoes

**Comment by Ayush0Chaudhary** [comment]
@EshaanAgg 
```
  String fetchOrgEvents(String orgId) {
    return """
      query {
        eventsByOrganization(id: "$orgId"){ 
          _id
          organization {
            _id
            image
          }
          title
          description
          isPublic
          isRegisterable
          recurring
          recurrance
          startDate
          endDate
          allDay
          startTime
          endTime
          location
          creator{
            _id
            firstName
            lastName
          }
          admins {
            firstName
            lastName
          }
          registrants {
            user {
              _id
            }
          }
        }
      }
    """;
  }
```

**Comment by Ayush0Chaudhary** [comment]
We can close this, apologize
