### ISSUE TITLE
Automated Talawa API docs generation workflow

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-api#1347]
**Describe the bug**
As of now, the documentation generation is manual. This issue aims for generation of Talawa API documentation through Typedoc, and then converting the generated html files to markdown, via Turndown.

**Solution**
The current process for maintaining the Talawa API documentation involves manual steps. Typedoc would be used to generate the initial API documentation in HTML format. However, to align with the project's workflow, the HTML files would then be converted to Markdown using Turndown, and later transffered to Talawa-docs repository. This will ensure consistency of design throughout the documentation.

**Comment by palisadoes** [comment]
@Nitya-Pasrija Do you want to work on this?

**Comment by Nitya-Pasrija** [comment]
Yeah I do
