### ISSUE TITLE
Remove redundancy across resolvers

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1352]
**Is your feature request related to a problem? Please describe.**
There are too many redundant checks inside resolvers for whether the user is authenticated or is normal users, admins, or super admins. The same must be abstracted away into convenient functions.

**Describe the solution you'd like**
The redundancy in all the resolvers can be removed using the resolver composition. Reference:-
https://the-guild.dev/graphql/tools/docs/resolvers-composition

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Comment by EshaanAgg** [comment]
@palisadoes 
Unassigning myself as I am currently working on the `Event Management project. Hopefully, new contributors can pick this issue (a `Good First Issue` tag would help), or I can work on it later after completing the project.

**Comment by vednp** [comment]
I would like to work on this issue

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by anurag0006** [comment]
I would like to work on this issue

**Comment by anurag0006** [comment]
sorry, am busy this week so won't be able to work on this issue so unassigned myself...Please assign it to someone else...

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by vashuraghav** [comment]
Please assign it to me @palisadoes. I would like to work on it.

**Comment by palisadoes** [comment]
Assigning to @EshaanAgg as it is part  of his GSoC project plan
