### ISSUE TITLE
Remove mongoose deprecation warning

### ISSUE THREAD

**Issue by KunalAnkur** [PalisadoesFoundation/talawa-api#136]
Right now I am getting this deprecation warning when I send a request for creating a new organisation

![Screenshot from 2021-03-14 19-22-27](https://user-images.githubusercontent.com/57923976/111071404-08407880-84fc-11eb-840d-d3e9d1516b4d.png)

**Comment by KunalAnkur** [comment]
I am working on this!

**Comment by gauravdas014** [comment]
@KunalAnkur I am not getting this warning. Can you please tell me how can I reproduce it?

**Comment by KunalAnkur** [comment]
@gauravdas014  Try this query along with the token in the header.

```
mutation createOrganisation {
  createOrganization(data:{name:"The great organisation",description:"this organisation is the best in the world",isPublic:true,apiUrl:"https://www.apiurl.com/",visibleInSearch:true}){
    _id
    name
    description
    isPublic
    creator{
      _id
    }
    members{
      _id
    }
    admins{
      _id
    }
    membershipRequests{
      _id
    }
  }
}
```
I got this warning when I create new organisation.
![Screenshot from 2021-03-15 13-02-44](https://user-images.githubusercontent.com/57923976/111118588-fa880300-858e-11eb-9cd4-d2e853715e37.png)

**Comment by gauravdas014** [comment]
@KunalAnkur okay, I got it. we need to set ` useFindAndModify: false`
