### ISSUE TITLE
 tough-cookie Prototype Pollution vulnerability #60 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1361]
- You will need to update to v4.1.3
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/80867b14-f8cd-45c2-9d09-c865ffb9217e)

- You will also need to update some dependencies. Here are some that you'll need to consider:
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/4530e878-3d22-458b-a8c7-700e67fd4813)

**Comment by ishtails** [comment]
Can you assign it to me? I'd like to fix it by updating the package-lock.json file
