### ISSUE TITLE
[Proposal] - Implementing Social Media Authentication

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa-api#138]
I had this idea when I was trying to setup the Talawa-Api Server as well as the App locally.

It would take me sometime to fill in those fileds and that's when I realized we can simply the whole process by using Social Media Authentication for SignIn & SignUp based on Google/FB/Twitter.

This can be implemented using passport.js

**Willing to work on this?** 
Yes

**Comment by Priyaraj17** [comment]
Is this issue open? I would like to work on it.

**Comment by adithyaakrishna** [comment]
I have taken this issue and I'm waiting for the mentors approval, once its done I will be working on it

**Comment by Priyaraj17** [comment]
@adithyaakrishna Okay sure.

**Comment by Sagar2366** [comment]
Let's keep this feature on hold. Please focus on bug fixes in code freeze period.

**Comment by Priyaraj17** [comment]
Sure sir

**Comment by palisadoes** [comment]
@adithyaakrishna have you given this any further thought? How would you implement it?

**Comment by adithyaakrishna** [comment]
Hey @palisadoes 

- The points to consider for this are, what are the different authentication types which are needed by the user.
- Also, I'm not exactly sure how we can implement this in `talawa-admin` or `talawa-api` but I can learn and do it, If it would involve `talawa-api` I would take some help from @sumitra19jha regarding this
