### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [PalisadoesFoundation/talawa-api#1386]
**Describe the bug**
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

**To Reproduce**
Scroll to the bottom and see Twitter old logo

**Expected behavior**
The Twitter logo should be changed to X.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
<img width="960" alt="Screenshot 2023-09-08 154641" src="https://github.com/PalisadoesFoundation/talawa-api/assets/91591901/10e81d39-e9db-41da-921b-ba4ebcfcb2d2">

**Additional details**
@palisadoes 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Thanks for noticing this, however this is the wrong repo for changing the Icon. It needs to be opened on Talawa-Docs. Closing.
