### ISSUE TITLE
File gets deleted from FileSystem if it already exists

### ISSUE THREAD

**Issue by nitishkumar333** [PalisadoesFoundation/talawa-api#1396]
**Describe the bug**
If we upload a file which already exists in database as base64 encoded, then the file gets deleted from database as well as FileSystem. But the name of the file (reference) still remains in the database.

**To Reproduce**

1.  Upload a image in UserUpdate or Organization settings.
2.  Upload the same image again

**Expected behavior**
Image should not be deleted from FileSystem even if its uploaded again. Only the "numberOfUses" in mongobd should be increased by +1.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-api/assets/123248648/8f06d2c8-48cf-41ee-a764-f333c7989c08

**Comment by nitishkumar333** [comment]
please assign it to me.

**Comment by nitishkumar333** [comment]
Hi @palisadoes , can I work on this issue ?

**Comment by tushar-glitch** [comment]
Hi @nitishkumar333, are there any updates regarding this issue. If not, I can try solving it.

**Comment by nitishkumar333** [comment]
Hi @tushar-glitch, I am working on it in the pr #1403
