### ISSUE TITLE
Feature Request: Improving the ui of the buttons in the mobile view

### ISSUE THREAD

**Issue by DhairyaMajmudar** [PalisadoesFoundation/talawa-api#1400]
**Is your feature request related to a problem? Please describe.**
In the responsive view the UI of the Next button located in the Introduction section of the docs page must be chnged

**Describe the solution you'd like**
The button shall take a full width instead of taking only the half-width when prev. button is not present 

**Describe alternatives you've considered**
Changing the half-width button with the full width button 

**Approach to be followed (optional)**

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/124715224/56a2ddca-7db5-4ff6-ba59-ca5aef559f7f)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by DhairyaMajmudar** [comment]
@xoldyckk I would love to contribute in this issue. pls. self assign this issue to me

**Comment by xoldyckk** [comment]
@DhairyaMajmudar make this feature requests for docs on [talawa-docs](https://github.com/PalisadoesFoundation/talawa-docs) repo, this isn't the repo for this. Also, seems like a useless improvement to me. Tag @palisadoes for more info.
