### ISSUE TITLE
Replace the `request` package with a currently maintained equivalent

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1417]
**Describe the bug**
The `request` package is no longer supported by the maintainer.

1. We need to replace all references to the `request` package with a supported package to maintain the `request` package functionality. Deleting `request` functionality is not an option.
2. You must also ensure that all code base tests pass and are valid. Tests without actual executable code does not benefit the community of users, we have experienced this unfortunate fact in the past.
3. The overall code coverage level must be maintained.

**Comment by Anubhav-2003** [comment]
@palisadoes I would like to work on this issue.

**Comment by noman2002** [comment]
@RunTerror Any update on this one ?

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by adi790uu** [comment]
Hey! I would like to work on this issue

**Comment by adi790uu** [comment]
@palisadoes , I have gone through the codebase, and I couldn't locate any instances of the request package being used. I'm wondering if the issue might be related to the Type Request. Can you provide some guidance or assistance in understanding this aspect?

**Comment by palisadoes** [comment]
We got this alert from GitHub's automated system. So it may be a dependency. Please take a look.

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/032d7a04-e85d-46ee-a338-20083b532475)

**Comment by palisadoes** [comment]
1. If the package is not used, then we should close this issue. The advisory may be stale.
2. Closing
