### ISSUE TITLE
Issue with implementing token refresh functionality

### ISSUE THREAD

**Issue by chandel-aman** [PalisadoesFoundation/talawa-api#1419]
**Describe the bug**
Currently, the talawa-api lacks the functionality to handle token refresh using the provided refreshToken. The missing functionalities include but are not limited to saving the refreshed tokens in the database, revoking tokens after single use, and implementing security measures for secure token exchange.

**To Reproduce**

1. Login a user.
2. Check the database if the refresh token has been stored in user document (it is not getting stored now).
3. Let the user get logged out automatically after the access token has expired.
4. Check if a new refresh and access token is generated and set to the user.

**Expected behavior**
1. Save refreshed tokens in the database.
2. Revoke used tokens after a single exchange.
3. Send the newly generated access token and refresh token to the user.

**Actual behavior**
The talawa-api code currently lacks the aforementioned functionalities for token refresh, leading to an inability to perform the intended token exchange.

**Screenshots**
N/A

**Additional details**
The token refresh functionality in the talawa-api is partially implemented but lacks the final steps for saving tokens in the database, revocation after single use, and implementing essential security measures.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
@palisadoes please assign me this issue

**Comment by palisadoes** [comment]
@rishav-jha-mech @kb-0311 Please comment on this.

**Comment by chandel-aman** [comment]
@palisadoes @kb-0311 

I've added an environment variable in env file.

**Added/Modified:**
**NODE_ENV** - This variable is now used to determine the development or production environment.

> NODE_ENV=development

**Purpose:**
* To check the environment and restrict access to the backend server. If NODE_ENV is set to 'production', the backend will only allow requests from specified origins, such as talawa-admin.

**Note:** No changes are required in the README since the default value is clearly specified.

So should I update the sample env too?

**Comment by kb-0311** [comment]
Yes add them in the sample file too.
