### ISSUE TITLE
Custom Fields and Custom Data For Talawa Admin

### ISSUE THREAD

**Issue by JamarTG** [PalisadoesFoundation/talawa-api#1431]
**Is your feature request related to a problem? Please describe.**
When a member signs up on the mobile app, the information they initially provide creates their profile. Howwever, this data might not cover all the necessary details required by the organization. This feature enables the organization to define additional fields to gather specific data beyond what members initially provide

**Describe the solution you'd like**
The "CustomFields" attribute expands an organization by specifying a list of desired fields, allowing members to register additional data in JSON format. 

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
  1. Create mutations to add a user's custom data, and an organization's custom field as well as remove a member's custom data and member custom fields
  2. Create a query to view customFieldsByOrganization and customDataByOrganization

**Additional context**

**Comment by JamarTG** [comment]
@palisadoes I'd like to be assigned this issue

**Comment by palisadoes** [comment]
@JamarTG

1. Does this allow the administrator to add a custom field to be used for all users?
2. We have a tags feature that can be used for adding one or more labels to each user and event to help with filtering. This may not be relevant, but you should be aware of it. It's in the API, it's not yet added to the Admin portal.

**Comment by JamarTG** [comment]
> @JamarTG
> 
> 1. Does this allow the administrator to add a custom field to be used for all users?
> 2. We have a tags feature that can be used for adding one or more labels to each user and event to help with filtering. This may not be relevant, but you should be aware of it. It's in the API, it's not yet added to the Admin portal.

Yes. when they are registering

**Comment by palisadoes** [comment]
1. Are you proposing the user add the custom fields just for themselves? Or that the Administrator would add the field for use by all users?   
2. When you say "when the user is joining the organization", which user? The end user or the administrator?

I ask as this feature would best be handled by an administrator and they should be able to add custom fields at any time and the fields visible on the user details screen. This is what @rishav-jha-mech and @aashimawadhwa are working on. 

We need clarity on this before you start.

**Comment by JamarTG** [comment]
> 2\. hen the user is joining the organization

No, the organization administrators add the custom fields that they want. (they require certain data from the members in their organization). 

The custom field consists of the type and the name of the data the organization is collecting . For example. an organization that wants "age". The type would be a number and the name of the field is "age". So they want the age of members of their organization.

The custom data is different. Now this is what the user provides to the organization. So in their custom data property they would have

custom fields of the organization

[
   {
   type : "Number",
   name : "age"
   }
]

customdatas of the user

 {
    age : 12,
    nationality : "Jamaican"
}

**Comment by JamarTG** [comment]
I think the confusion is from me saying "user" instead of members

**Comment by palisadoes** [comment]
OK, thanks for the clarification. That helps. Go ahead.
