### ISSUE TITLE
Feature Request: PR Workflow Enhancement - Delta Error/Warning Checks

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-api#1433]
**Description**
  Currently, our PR Workflow checks the entire codebase for linting, formatting, and type errors, which can be time-consuming. This enhancement request is to optimize the workflow to only check for errors and warnings in the lines of code that are changed or added in the pull request.

**Details**:
- Linting: Only check for linting errors and warnings in the modified or added lines of code.
- Formatting: Run formatting checks only on the changes introduced in the pull request.
- Type Errors: Optimize the type-checking process to focus on the modified or added code.

**Context**
- This is the required check - `PR Workflow / Check for linting, formatting and type errors (pull_request)`
- This enhancement aims to speed up the PR review process by narrowing down the scope of checks to the code that is directly affected by the pull request. It helps in quicker identification and resolution of issues related to the changes introduced in the PR.

**Expected Behavior**
The PR Workflow should only check for linting, formatting, and type errors in the modified or added lines of code.
The workflow should be optimized to reduce processing time for pull requests.

**Additional Information**
 - [ ] I have reviewed the current PR Workflow configuration.
 - [ ] I have considered potential impacts on existing workflows.
 - [ ] This enhancement aligns with our project goals.

**Comment by skbhagat0502** [comment]
@tasneemkoushar please assign me this issue.

**Comment by tasneemkoushar** [comment]
@skbhagat0502  assigning, but kindly take this issue on priority.

**Comment by skbhagat0502** [comment]
> @skbhagat0502 assigning, but kindly take this issue on priority.

Ok @tasneemkoushar

**Comment by tasneemkoushar** [comment]
@skbhagat0502 any update on this PR?

**Comment by skbhagat0502** [comment]
> @skbhagat0502 any update on this PR?

@tasneemkoushar I made a PR now which will fix this.
