### ISSUE TITLE
Use `yarn` instead of `npm`

### ISSUE THREAD

**Issue by gauravdas014** [PalisadoesFoundation/talawa-api#144]
currently, the talawa-api uses `npm` as the package manager. We can use `yarn` instead of npm. `Yarn `is faster than npm and it's better than npm in terms of performance. Even `talawa-docs` repository is using yarn.

I would like to give a PR that will make yarn the default package manager for this project.

**Comment by Pratik1234agarwal** [comment]
Hello, I am new here. Can I work on this issue?

**Comment by Gautam-Arora24** [comment]
Sagar, I want to work on this issue. Kindly assign it to me

**Comment by Sagar2366** [comment]
Because of code freeze and considering this is enhancement will keep this issue on hold for now.

Before accepting yarn as package manager for talawa-api project, will need complete analysis of how it is better over existing npm package manager.

**Comment by Sagar2366** [comment]
> Sagar, I want to work on this issue. Kindly assign it to m

@Gautam-Arora24 just in case if you have missed my previous comment on this issue. We will be focusing only on bugs in code freeze period and not adding any new feature or enhancement.

**Comment by palisadoes** [comment]
@Gautam-Arora24 are you still available to work on this?

**Comment by Gautam-Arora24** [comment]
So sorry @palisadoes but I am not available right now to work on this.

**Comment by saymedgm** [comment]
@palisadoes please assign me this issue I would love to contribute to your organization

**Comment by saymedgm** [comment]
@Sagar2366  I have created pull request for same please have a look at it
branch name => saymedgm

**Comment by saymedgm** [comment]
@palisadoes please have a look at my pull request
