### ISSUE TITLE
Standardize the location of repository assets

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1441]
**Describe the bug**

1. Our typescript repos store image and video assets in different locations.
2. This needs to be standardized as we may have unwanted images and videos uploaded to the repo

**To Reproduce**
You can see that these assets are stored in the root directory
- https://github.com/PalisadoesFoundation/talawa-api

**Expected behavior**

1. Standardize on the `src/assets` directory structure used in Talawa Admin
    1. https://github.com/PalisadoesFoundation/talawa-admin/tree/main/src/assets
1. Move the files referenced in the root directory markdown files to the appropriate sub directory under the assets directory
1. Update the markdown files to reference these new locations 
1. Delete any of these assets files not referenced in the markdown files, but verify that they are not referenced in the code base in any of the other Talawa repos first. If so propose a methodology to make sure these repos' functionality is maintained.
1. The code base mutations may be uploading files to the `video/` and `image/` directories. If this is the case
    1.  Make sure that files are never uploaded to these directories in the code base (This can be assured by configuring the `.gitignore` file)
    1.  Make sure that the directories remain. (This can be assured by configuring the `.gitignore` file)
1. Make sure no objects in the markdown files refer to these locations and if so move them to the new directory structure.
     1. other people's repos

**Actual behavior**
- See Above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by zakhaev26** [comment]
I am interested in working on this

**Comment by zakhaev26** [comment]
@palisadoes 
Is unit testing required for this kind of PR?
I did the changes as per requested.

**Comment by palisadoes** [comment]
No new testing, but all the existing tests must pass without affecting their effectiveness in creating stable code

**Comment by palisadoes** [comment]
1. Unassigning due to inactivity
2. The PR above can be used as a reference

**Comment by Veer0x1** [comment]
I would like to work on it.
