### ISSUE TITLE
Bug - RECAPTCHA SITE KEY is also required in .env file

### ISSUE THREAD

**Issue by ShubhamTiwari55** [PalisadoesFoundation/talawa-api#1444]
**Describe the bug**
In the installation.md file (the installation guideline), while filling all details in the .env file, RECAPTCHA_SITE_KEY is also required as without it, an error was thrown

**To Reproduce**

1. While installing and starting server, if you don't include the above field it will throw an error.

**Expected behavior**
.env file should not throw any error and should be complete

**Actual behavior**
error 2023-12-04 13:17:58 - Invalid environment variables found in your .env file, check the errors below! {}
[0] Code: invalid_type ~ Path: RECAPTCHA_SITE_KEY ~ Message: Required

**Screenshots**

<img width="591" alt="Screenshot 2023-12-04 131340" src="https://github.com/PalisadoesFoundation/talawa-api/assets/125534462/e46aba15-6938-4eea-9c0e-5c70133e1b0f">
<img width="633" alt="Screenshot 2023-12-04 131833" src="https://github.com/PalisadoesFoundation/talawa-api/assets/125534462/0f92dd09-3e25-439b-aa89-db4b6a2ec193">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by noman2002** [comment]
Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by ShubhamTiwari55** [comment]
> Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

Sorry but I have already created a PR as it was necessary so that anyone installing the server won't have an error. If you want, I can close the PR

**Comment by MahendraDani** [comment]
@noman2002 
I would like to solve this issue.
I will implement the functionality to setup the Recaptcha site key in .env file by running the script `npm run setup` and will also add the docs for it in `INSTALLATION.md`.

**Comment by noman2002** [comment]
> > Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.
> 
> Is the limit is 2 issue per repo or collectively 2 issues only ? Sorry but I have already created a PR as it was necessary so that anyone installing the server won't have an error. If you want, I can close the PR

Collectively 2 issue.
