### ISSUE TITLE
 Expand the demographic data for users

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-api#1447]
**Is your feature request related to a problem? Please describe.**
Currently we only have name and email of the user there is no other demographic, contact and work details

**Describe the solution you'd like**
we would like to add demographic data, contact data and education and work data  of the user

In the main section we will have :
- gender
- age
- address
- marital status

education and work section:
- highest degree obtained:
- employee status

In contact section:
- mobile
- home
- work

**Additional context**
reference for  additional fields

![Screenshot 2023-11-30 at 11 38 06 PM](https://github.com/PalisadoesFoundation/talawa-api/assets/73706697/feee55d2-dec1-4fec-b9b8-56b40a66d827)
![Screenshot 2023-11-30 at 11 37 48 PM](https://github.com/PalisadoesFoundation/talawa-api/assets/73706697/cfd02eff-75d7-4bf3-8bde-44b9dbb9008e)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by LakshyaSatpal** [comment]
I can take this. Please assign this to me.
