### ISSUE TITLE
Feature Request: Implement Error Handling in Talawa 

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1450]
**Is your feature request related to a problem? Please describe.**
We have detailed documentation on the kind of error handling we desire to have in `Talawa API` and consequently use in `Talawa Admin` as [listed here](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/docs/developers/talawa-api/error-handling.md). We need to migrate the backend resolvers piecewise to adhere to use the same in Talawa API, and then make the changes in Talawa Admin parallelly. 

**Approach to be followed**
This is a parent issue on which multiple contributors can work. The expected process is as follows:
- Open a new issue with the name `Implement GraphQL Error Handling: Resolver ABC` where `ABC` is the name of the backend resolver that you want to change. Mention this issue as the parent issue in the same.
- Give a clear and concise explanation of what changes you want to make to the schema to handle errors; that is, what `Error schemas` would you introduce and how they can be used with other resolvers.
- Wait to be assigned the issue.
- Open two PRs parallelly in Talawa API and Admin that make the changes to the API and the Admin to use the newly proposed error handling. 

**Additional context**
For reference, you can check out some sample [error schemas](https://github.com/PalisadoesFoundation/talawa-api/tree/develop/src/typeDefs/errors) used in [pagination resolvers](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/resolvers/UserTag/usersAssignedTo.ts) and [utilities](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/utilities/graphqlConnectionFactory.ts). 

Please research and ensure you understand the impact before opening a child issue for the same, and present the advantages of your solution in the issue description. Those lacking the proper research and intent would be closed immediately. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@Harsh1s Has this been pursued further? Are you still interested?

**Comment by Harsh1s** [comment]
> @Harsh1s Has this been pursued further? Are you still interested? 

Yes, I've had some personal issues for a few last days. I'll fix it in the next 24 hours. I'm sorry for the delay.

**Comment by techmannih** [comment]
hello @Cioppolo14 ,
can I work on this  issue

**Comment by EshaanAgg** [comment]
Closing as the same has been decided against of. Thanks for all your interest.
