### ISSUE TITLE
Upgrade package `graphql-voyager` from 1.3.0 to 2.0.0

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1461]
For security purposes, we need to bump package  [graphql-voyager](https://github.com/graphql-kit/graphql-voyager) from 1.3.0 to 2.0.0.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1456

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105164981/job/19341737491?pr=1456
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105165165/job/19341738218?pr=1456

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

### Please ask to be assigned by the contributors mentioned in slack. They will also answer all questions. I no longer assign issues due to the workload with no exceptions.

**Comment by Min2who** [comment]
Hi @noman2002 @Ayush0Chaudhary i am taking this up

**Comment by noman2002** [comment]
Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Min2who** [comment]
@noman2002 I have made a PR regarding a issue that i have been assigned ? cant i take this one

**Comment by noman2002** [comment]
@Min2who Wait the PR to get merged.

**Comment by Min2who** [comment]
@noman2002 can i work on that?

**Comment by duplixx** [comment]
@noman2002 can i take this task
thanks!!

**Comment by noman2002** [comment]
Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.
