### ISSUE TITLE
Upgrade package  `jwt-decode` from 3.1.2 to 4.0.0

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1462]
For security purposes, we need to bump package [jwt-decode](https://github.com/auth0/jwt-decode) from 3.1.2 to 4.0.0.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1457

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105169729/job/19341754667?pr=1457
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105169948/job/19341755455?pr=1457
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105169723/job/19341754708?pr=1457

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue
- If this package is no longer used, then references to it must be removed from the code base

### Please ask to be assigned by the contributors mentioned in slack. They will also answer all questions. I no longer assign issues due to the workload with no exceptions.

**Comment by Min2who** [comment]
Hi @palisadoes can i take this one

**Comment by noman2002** [comment]
Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by racky7** [comment]
@noman2002 can you assign this to me?
