### ISSUE TITLE
Upgrade package `express-rate-limit` from 5.5.1 to 7.1.5

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1463]
For security purposes, we need to bump package  [express-rate-limit](https://github.com/express-rate-limit/express-rate-limit) from 5.5.1 to 7.1.5.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1459

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105185828/job/19341811113?pr=1459
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105186275/job/19341812520?pr=1459

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue
- If this package is no longer used, then references to it must be removed from the code base

### Please ask to be assigned by the contributors mentioned in slack. They will also answer all questions. I no longer assign issues due to the workload with no exceptions.

**Comment by Min2who** [comment]
Hi @noman2002 @Ayush0Chaudhary i am taking this up

**Comment by palisadoes** [comment]
@Harsh1s Please resubmit the PR. It looks like the errors we were getting were related to something else.

**Comment by alanansari** [comment]
I can work on this since it hasn't been solved for so long. Assign me this please.

**Comment by monkCommits** [comment]
Hey can I work on this please.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR

**Comment by Veer0x1** [comment]
@palisadoes can I work on it?
