### ISSUE TITLE
[Discussion]: Use a specific type of commit message instead of random commit messages

### ISSUE THREAD

**Issue by gauravdas014** [PalisadoesFoundation/talawa-api#147]
While going through the contributions in this repository, I observed that the commit messages are not formatted in a specific way, some commit messages are imperative, while some are in the past tense and many other random types of commit messages can be seen. Being in the open-source community for a long time, I think the commit messages should follow a specific format so that new people starting to contribute can easily look at the past commits and understand the previous changes done in the repository. Commits can be of different types. Example:

- **chore** : Updating deps, docs, linting, etc.
- **ci** : Changes to our CI configuration files and scripts
- **docs** : Documentation only changes.
- **feat** : A new feature.
- **fix** : A bug fix.
- **perf** : A code change that improves performance.
- **refactor** : A code change that neither fixes a bug nor adds a feature.
- **revert** : Reverts the previous commit.
- **style** : Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc).
- **test** : Adding missing tests or correcting existing tests.

For example: we have added some tests , so the commit messages can be: 

**test**: add tests for example.js

I kindly request the maintainers to give their views on this, if they also feel the necessity of this, I will be more than happy to add this to the contributing guide.

**Comment by Pratik1234agarwal** [comment]
Hey, we can also attach a emoji pertaining to each commit type mentioned above. That makes them a little more pretty and makes it easy to keep track of the type of commit for contributors working on this project on the daily basis. 

Your views on this?

**Comment by gauravdas014** [comment]
According to my, that will just make it look fancy, nothing else. I don't feel any necessity of that.
