### ISSUE TITLE
Feature Request: Cache npm dependencies in workflows

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#1471]
**Is your feature request related to a problem? Please describe.**
We can cache the `node_modules` folder in workflows with artifacts to ensure faster workflow runs. 

**Describe the solution you'd like**
[Refer to this guide](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ibishal** [comment]
@EshaanAgg could you assign this to me?

**Comment by Veer0x1** [comment]
Can you assign me?

**Comment by EshaanAgg** [comment]
@Veer0x1 We are waiting fro @ibishal to make some progress. If he does not give any updates in a week's time, I would assign you then.

**Comment by ibishal** [comment]
> Can you assign me?

@EshaanAgg assigned @Veer0x1
