### ISSUE TITLE
The GitHub Action `push.yml` workflow is failing

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1477]
**Describe the bug**

After merging this PR
- https://github.com/PalisadoesFoundation/talawa-api/pull/1473

We started getting this error message with our `push.yml` workflow
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7152424123

The workflow file can be found in this directory
- https://github.com/PalisadoesFoundation/talawa-api/tree/develop/.github/workflows

We reverted the PR and the error remains
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7152285097

It looks like the app isn't starting correctly. We need to get this fixed quickly

**To Reproduce**

See above

**Expected behavior**

- The GitHub `https://github.com/PalisadoesFoundation/talawa-api/tree/develop/.github/workflows/push.yml` related error goes away
- The app starts as expected

**Actual behavior**
- See above

**Screenshots**
- N/A 

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by LakshyaSatpal** [comment]
I can fix this. Please assign it to me.

**Comment by palisadoes** [comment]
Fixed
