### ISSUE TITLE
Feature Request: Add update Advertisement feature

### ISSUE THREAD

**Issue by Vaishali054** [PalisadoesFoundation/talawa-api#1478]
**Is your feature request related to a problem? Please describe.**
Add update advertisement feature in talawa-api to enable editing and updating advertisement once created

**Describe the solution you'd like**
Add necessary inputs and resolvers

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by racky7** [comment]
Please assign it to me.

**Comment by noman2002** [comment]
@Vaishali054 Do you want this to get assigned to you as you created this issue ?

**Comment by noman2002** [comment]
@racky7 Assigned to @Vaishali054 As she requested to get assigned on slack.

**Comment by NamitBhutani** [comment]
If no one is working on this issue, I'd like to work on it! @noman2002

**Comment by Vaishali054** [comment]
@NamitBhutani I am working on this, already have a PR for this issue.

**Comment by Cioppolo14** [comment]
@NamitBhutani If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by palisadoes** [comment]
@Vaishali054 Reopening so that you can add the missing functionality
