### ISSUE TITLE
Feature Request: Create Transaction Log Collection for Database

### ISSUE THREAD

**Issue by LakshyaSatpal** [PalisadoesFoundation/talawa-api#1480]
**Is your feature request related to a problem? Please describe.**
We don't track when a record is created or updated in the database.

**Describe the solution you'd like**
Setting up a new collection dedicated to logging all transactions or changes made within the database. This collection will serve as a detailed history of all data interactions, providing an extensive audit trail.

**Comment by LakshyaSatpal** [comment]
@xoldyckk Please assign this to me.

**Comment by xoldyckk** [comment]
@LakshyaSatpal Dunno what u mean by a new collection for logging transactions/changes, isn't this something that should be handled by the database provider itself?

**Comment by LakshyaSatpal** [comment]
As discussed [here](https://github.com/PalisadoesFoundation/talawa-api/pull/1475#issuecomment-1849206862), the goal was to log the CRUD operations on the database. However, I get your point database-level logging.
 
I see MongoDB does provide some auditing features https://www.mongodb.com/docs/manual/core/auditing/. But, it's not exactly a collection in the database, I believe. So, I'm not sure if this solves our purpose. @palisadoes  Thoughts on this?

**Comment by palisadoes** [comment]
Yes, that would work and should be enabled by default in our setup to a well known location outside of our code base tree that would be installed on the system.

**Comment by palisadoes** [comment]
Unassigning due to no issue activity and no submitted pull request

**Comment by LakshyaSatpal** [comment]
Still working on it. Will raise a PR this weekend. Please assign

**Comment by LakshyaSatpal** [comment]
Based on the previous discussion, seems to me, that there are 2 possible solutions to this:
1. If we want to implement database-level logging, then we have to just edit the MongoDB configuration on the server. So, MongoDB will listen to all events and log to some place (a JSON file or something) on the server. So, this will be related to server configuration and not to the application codebase.
reference: https://severalnines.com/blog/audit-logging-mongodb/

2. We create a new collection, and we manually update that collection on every mutation, storing everything according to our requirements. This is something we can implement and add to the codebase.

@palisadoes @xoldyckk Need your thoughts.

**Comment by LakshyaSatpal** [comment]
@noman2002 @aashimawadhwa Can you please check this? This issue has been assigned to me for a while now.

**Comment by palisadoes** [comment]
1. We should consider updating our documentation to show how to log transactions with MongoDB first
2. Then we should add a collection to store all the transaction logs for mutations.

**Comment by LakshyaSatpal** [comment]
found out that audit logging is only in the MongoDB enterprise edition. Proceeding with the second choice now.
