### ISSUE TITLE
Automated Documentation GitHub Action Fails

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1487]
**Describe the bug**

We recently updated the `graphql-ws` package as part of our weekly dependabot security update process. It passed our PR workflows.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1481

This was quickly followed by these PRs

1. https://github.com/PalisadoesFoundation/talawa-api/pull/1482
1. https://github.com/PalisadoesFoundation/talawa-api/pull/1483
1. https://github.com/PalisadoesFoundation/talawa-api/pull/1485

Unfortunately the upgrade seems to have broken our documentation workflow

1. https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7169787735
1. https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7169800624
1. https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7169806847
1. https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7169811098

We need to fix the PR workflow.

**To Reproduce**

1. Merge PR
1. The documentation workflow fails

**Expected behavior**
- The documentation push workflow passes

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- **NOTE:** I will not be assigning people to issues, no exceptions. Please watch this video on how to proceed.

[![Click me to start video](https://img.youtube.com/vi/GlqUm1UO-xM/0.jpg)](https://www.youtube.com/watch?v=GlqUm1UO-xM)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ibishal** [comment]
can i work on it?

**Comment by hharshas** [comment]
please assign me this issue

**Comment by Veer0x1** [comment]
Can I take over this issue??

**Comment by palisadoes** [comment]
We may have to close this.

Our GitHub member @anwersayeed has been working on this for some time. Anwer, should this be closed?

**Comment by anwersayeed** [comment]
@palisadoes I'm currently working on a similar but different issue.

**Comment by Veer0x1** [comment]
@anwersayeed can I work you along with this issue?

**Comment by palisadoes** [comment]
Closing. This is being handled by:
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1279 
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1559
