### ISSUE TITLE
Removal of firebase messaging from Create Event

### ISSUE THREAD

**Issue by Abhisheksainii** [PalisadoesFoundation/talawa-api#1500]
**Describe the bug**
When we create an event in Talawa mobile app, we get an exception from backend that notifications are not enabled. This prevents from creating an event. We have discontinued using Firebase Notifications in our app. So I would request to get the code removed or commented out from the backend as well.

**To Reproduce**

1. Login to Talawa App.
2. Click on create Event.
3. Type in the details.
4. Click Add

**Expected behavior**
• A message based on the success or failure(apart from notifications) of the event creation process.

**Actual behavior**
• Getting an exception that says notifications are not enabled.

**Screenshots**

**Additional details**
• You can find the code that needs to be removed in resolvers/creatEvent.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
I would like to work on this

**Comment by Veer0x1** [comment]
can you assign me this issue?

**Comment by AdityaRaimec22** [comment]
Hii @Abhisheksainii I am new to Talawa and I think this issue would be the perfect one to make my first contribution in Talawa. Can you assign this issue to me

**Comment by Abhisheksainii** [comment]
@noman2002 can you request someone from the API team to assign this task

**Comment by Veer0x1** [comment]
@Cioppolo14 @Abhisheksainii , I require further clarification on this issue. Currently, the `createEvent.ts` file sends notifications to all users within the organization. However, the new requirement is to send a message specifically to the user initiating the event, indicating whether the process was successful or failed.

Something like this?


<img width="893" alt="Screenshot 2023-12-17 at 1 45 28 AM" src="https://github.com/PalisadoesFoundation/talawa-api/assets/96714915/cecb70a2-e563-453b-8c27-3d37f8a8306c">

**Comment by Abhisheksainii** [comment]
We have discontinued using firebase notifications in the app, so you need to remove the code that is sending notifications to users in CreateEvent file

**Comment by Abhisheksainii** [comment]
> @Cioppolo14 @Abhisheksainii , I require further clarification on this issue. Currently, the `createEvent.ts` file sends notifications to all users within the organization. However, the new requirement is to send a message specifically to the user initiating the event, indicating whether the process was successful or failed.
> 
> Something like this?
> 
> 
> <img width="893" alt="Screenshot 2023-12-17 at 1 45 28 AM" src="https://github.com/PalisadoesFoundation/talawa-api/assets/96714915/cecb70a2-e563-453b-8c27-3d37f8a8306c">
>  

Yes, you just need to comment the notifications code

**Comment by palisadoes** [comment]
The Firebase related installation and configuration instructions will need to be removed too.
