### ISSUE TITLE
Remove Dynamic Linking (MVP Prerequisite)

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1510]
We need to have an Talawa MVP by the end of the year. The MVP will be the master branch. To do this we will need to remove features that either don’t work or have insufficient functionality. 

The feature to remove include:

1. Dynamic linking 

Other

1. You need to work on removing these functionalities from this repo and work with the contributors below to make sure the correct functionality occurs in the other repos.
1. No other functionality must be removed
1. Documentation related to configuring these features needs to be removed as they will be no longer valid.
1. Test code coverage needs to be maintained. Coverage for the PR patches needs to be 100%

The plan is to:

- remove these features from the develop branch by commenting out the code.

Please work with @Ayush0Chaudhary (Talawa impacts), @kb-0311 & @xoldyckk (Talawa-API impacts) @beingnoble03 (Talawa-Admin impacts). Ask to be assigned this task by them.
Issues related to this one include:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1069
- https://github.com/PalisadoesFoundation/talawa-api/issues/1427
- https://github.com/PalisadoesFoundation/talawa/issues/2108

**Comment by Min2who** [comment]
@EshaanAgg can i work in it?

**Comment by Veer0x1** [comment]
Would like to work on it.

**Comment by EshaanAgg** [comment]
Assigned @Min2who as he asked first. If he is unable to make meaningful progress in a week's time, @Veer0x1 you can take up the issue.

**Comment by Min2who** [comment]
@Veer0x1 go ahead?

**Comment by AdityaRaimec22** [comment]
@EshaanAgg can you please assign me this issue.

**Comment by AdityaRaimec22** [comment]
@kb-0311 @xoldyckk Could you please assist me with this issue? I'm relatively new to Talawa and would appreciate guidance on how to proceed.

**Comment by AdityaRaimec22** [comment]
@palisadoes I've thoroughly reviewed the Talawa codebase and consulted with several contributors, but unfortunately, I couldn't gather substantial information about the issue. Can you provide further guidance on how I can resolve this issue?

**Comment by Veer0x1** [comment]
I would like to work on it.

**Comment by Veer0x1** [comment]
@palisadoes I have asked @noman2002 about this, and he said the dynamic linking was done through firebase, and all firebase code has been already removed from the repo in this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1503). I tried to find its resolver but I didn't found any. Can you tell me where in repo actually this functionality was implemented?

**Comment by palisadoes** [comment]
Thanks, if that is the case, then we should close this issue. 
Closing
