### ISSUE TITLE
Upgrade package `graphql-codegen/typescript-resolvers` from 2.7.13 to 4.0.1

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1511]
For security purposes, we need to bump package [@graphql-codegen/typescript-resolvers](https://github.com/dotansimha/graphql-code-generator/tree/HEAD/packages/plugins/typescript/resolvers) from 2.7.13 to 4.0.1.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1507

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7245533524/job/19735734837?pr=1507

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue
- You PR should have no warning messages
- If this package is no longer used, then references to it must be removed from the code base

### Please ask to be assigned by the contributors mentioned in slack. They will also answer all questions. I no longer assign issues due to the workload with no exceptions.

**Comment by AdityaRaimec22** [comment]
@palisadoes can I work on this

**Comment by RAGHAV-N5** [comment]
can I work on this?

**Comment by techmannih** [comment]
@palisadoes , 
I want to work on this issue. please assign me

**Comment by RAGHAV-N5** [comment]
Can anyone please guide me through this, 
![Screenshot 2023-12-22 105635](https://github.com/PalisadoesFoundation/talawa-api/assets/135726978/6a315b9d-f6df-42a6-a6ac-0c872d8114ff)
I tried --save-dev / --save-exact too but  the version is not being updated in the package-lock.json file. This refers to the issue #1511 upgrading the graphql-codegen/typescript-resolvers from version 2.7.13 to 4.0.1. But initially the version was 2.6.6 which on upgrading using the command: npm i @graphql-codegen/typescript-resolvers was updated to 2.7.13 but it's not upgrading to 4.0.1 using this command:  npm i @graphql-codegen/typescript-resolvers@4.0.1.

**Comment by Veer0x1** [comment]
can I upgrade this package?

**Comment by Veer0x1** [comment]
@Cioppolo14 can you assign me this issue?
