### ISSUE TITLE
Upgrade package ` xss-clean`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1518]
**Describe the bug**
When installing the application we get this error on the console

```
npm WARN deprecated xss-clean@0.1.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

```

The package needs to be upgraded

**To Reproduce**
- Run the `npm install` command

**Expected behavior**
1. The error message goes away after the upgrade. No error message must be suppressed
1. All PR tests pass
1. No functionality is affected by the change
1. You must verify whether the package is still used at all and if not, remove it from any configuration files

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I would like to work on this. Please assign me : )
// @noman2002

**Comment by Veer0x1** [comment]
would like to work on this.

**Comment by rahularora27** [comment]
I would like to work on this issue.

**Comment by hharshas** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14, thank you for assigning this issue.

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14, this issue can be closed as the PR has been merged.
