### ISSUE TITLE
Replace package `vm2` with `isolated-vm`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1519]
**Describe the bug**
When installing the application we get this error on the console

```
npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
```

The package needs to be replaced with ` isolated-vm`

**To Reproduce**
- Run the `npm install` command

**Expected behavior**
1. The error message goes away after the upgrade. No error message must be suppressed
1. All PR tests pass
1. No functionality is affected by the change
1. You must verify whether the package is still used at all and if not, remove it from any configuration files

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Community-Programmer** [comment]
@noman2002 
I want to work on this ,please assign

**Comment by Veer0x1** [comment]
I would like to work on this.

**Comment by RAGHAV-N5** [comment]
Please assign me this issue.

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by palisadoes** [comment]
1. Make modifications to the develop branch
2. Please resubmit the PR against the develop branch. 
3. We are not deploying to main any more
