### ISSUE TITLE
API Startup Error Messages Need Resolving

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1521]
**Describe the bug**
When starting the API the following error messages are displayed. It doesn't affect operations

```
[0] error 2023-12-20 17:19:16 - Invalid environment variables found in your .env file, check the errors below! {}
[0] Code: invalid_type ~ Path: apiKey ~ Message: Required
Code: invalid_type ~ Path: appId ~ Message: Required
Code: invalid_type ~ Path: messagingSenderId ~ Message: Required
Code: invalid_type ~ Path: projectId ~ Message: Required
Code: invalid_type ~ Path: storageBucket ~ Message: Required
Code: invalid_type ~ Path: iOSapiKey ~ Message: Required
Code: invalid_type ~ Path: iOSappId ~ Message: Required
Code: invalid_type ~ Path: iOSmessagingSenderId ~ Message: Required
Code: invalid_type ~ Path: iOSprojectId ~ Message: Required
Code: invalid_type ~ Path: iOSstorageBucket ~ Message: Required
Code: invalid_type ~ Path: iosClientId ~ Message: Required
Code: invalid_type ~ Path: iosBundleId ~ Message: Required
```

**To Reproduce**
- Start non docker API instance

**Expected behavior**
- No error messages because the root cause is fixed. Suppressing error messages is not an acceptable solution.
- No change to the app's functionality
- All tests pass

**Actual behavior**
- Error messages

**Screenshots**
- N/A

**Additional details**
-N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by techmannih** [comment]
Hello @palisadoes ,
I want to work on this issue please assign me this issue

**Comment by AdityaRaimec22** [comment]
@palisadoes Please assign the issue to me.

**Comment by VaibhavTalkhande** [comment]
I would like to work on this issue

**Comment by techmannih** [comment]
I m working on it

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by adi790uu** [comment]
would like to solve this @palisadoes
