### ISSUE TITLE
Bug Report: Typo error in readme

### ISSUE THREAD

**Issue by samyabrata-maji** [PalisadoesFoundation/talawa-api#1522]
There's a typo error in the ["Setting up this repository"](https://github.com/PalisadoesFoundation/talawa-api/blob/main/INSTALLATION.md#setting-up-this-repository) section of the installation guide, point no.2.

Actual:
Navigate to the folder and open a terminal in this folder (you can right-click and choose appropiate option based <ins>onn</ins> your OS). Next, we'll fork and clone the talawa-api repository.

Expected:
Navigate to the folder and open a terminal in this folder (you can right-click and choose appropiate option based <ins>on</ins> your OS). Next, we'll fork and clone the talawa-api repository.

**Comment by rahularora27** [comment]
Can I fix this?

**Comment by palisadoes** [comment]
We are focusing on the types of issues listed in this video
- https://www.youtube.com/watch?v=3mjap16GYiY

Closing
