### ISSUE TITLE
The setup script does not prompt for `LAST_RESORT_SUPERADMIN_EMAIL`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1524]
**Is your feature request related to a problem? Please describe.**
The setup script does not prompt for the `LAST_RESORT_SUPERADMIN_EMAIL` parameter. This causes difficulty for people to set up the application as it is a prerequisite parameter for smooth operation.

**Describe the solution you'd like**
1. The setup script must prompt for the `LAST_RESORT_SUPERADMIN_EMAIL` parameter in both the initial setup and whenever the script is re-run
2. The parameter must be added to the configuration file
4. No other features must be affected

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
-N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AdityaRaimec22** [comment]
@palisadoes please assign this issue to me.

**Comment by VaibhavTalkhande** [comment]
I would like to work on it

**Comment by RAGHAV-N5** [comment]
I want to work on this issue please assign me.

**Comment by hharshas** [comment]
would like to work on this

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by AdityaRaimec22** [comment]
@palisadoes please review PR #1535

**Comment by AdityaRaimec22** [comment]
@palisadoes you can close this issue as this is completed in PR #1540. Thanks
