### ISSUE TITLE
Setup script doesn't verify `Redis` functionality

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1526]
**Is your feature request related to a problem? Please describe.**

The installation of Redis is recommended in the installation instructions, however the setup script ignores this performance improving feature.

**Describe the solution you'd like**
1. The setup script should prompt for Redis information with the option to skip over adding this information. 
1. The script must check for a valid Redis connection when the parameters are provided
1. The parameter must be added to the configuration file
1. This information must be prompted for every time the script is run
1. No other features must be affected

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
-N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Doraemon012** [comment]
@palisadoes I want to work on this issue. Please assign this to me.

**Comment by RAGHAV-N5** [comment]
I want to work on this issue pelase assign me.

**Comment by monkCommits** [comment]
Hey I want to work on this issue please assign me.
