### ISSUE TITLE
The `http://localhost:4000/` test does not check for Redis functionality

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1527]
**Is your feature request related to a problem? Please describe.**

The installation of Redis is recommended in the installation instructions, however accessing the test URL  `http://localhost:4000/` does not report whether or not Redis is running.

the setup script ignores this performance improving feature.

**Describe the solution you'd like**
1. Accessing `http://localhost:4000/`  must report whether Redis is running
1. If it is not running, then: 
     1. the overall status cannot be positive
     1. the report must state whether or not Redis is running
1. No other features must be affected

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
-N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RAGHAV-N5** [comment]
I want to work on this issue. Please assign me.

**Comment by hharshas** [comment]
would like to work on this

**Comment by noman2002** [comment]
@hharshas You have commented on so many issues across the repos. You already know that a person can only assigned 2 issues at once. Make sure not to repeat this and delete your comments except 2 which you want to work on.

**Comment by hharshas** [comment]
@noman2002 understood the procedure, did as you told. Will work further through proper behavior.

**Comment by adi790uu** [comment]
Hey @noman2002 would like to work!

**Comment by RAGHAV-N5** [comment]
@palisadoes 
This is the output when Redis is connected
![Screenshot 2023-12-28 132104](https://github.com/PalisadoesFoundation/talawa-api/assets/135726978/3dcd9235-64d0-4977-984b-0f6d25effdc9)
But when the redis is not connected, by default the server cannot be reached and thus not being able to display the failure of redis connection. Hence it is not possible to display it when redis is connected. Please correct me if I'm wrong. Therefore should I proceed with the pull request bringing in the changes shown in the above image? Or if there any improvements required please do inform.

**Comment by palisadoes** [comment]
@RAGHAV-N5 

You have closed 6 PRs, of which 5 were not merged. For each of these we had to assign reviewers whose time was wasted.
- https://github.com/PalisadoesFoundation/talawa-api/pulls?q=is%3Apr+is%3Aclosed+author%3ARAGHAV-N5

You also currently have 4 open PRs and 3 assigned issues. This is against our policy and further wastes our time as we are duplicating our efforts
- https://github.com/PalisadoesFoundation/talawa-api/pulls/RAGHAV-N5
- https://github.com/PalisadoesFoundation/talawa-api/issues/assigned/RAGHAV-N5

I am going to close this PR and unassign you from all issues except one. You have not complied with our policies stated in our documentation and videos that explicitly discourage this type of behavior

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/1d3c167a-449c-4eb9-852c-ca01c7898601)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/a096c04d-abec-4e2a-be7f-433edb3a89c8)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/bf6436ab-cb60-40d4-9406-5f680f5a94b9)

**Comment by AdityaRaimec22** [comment]
@palisadoes can I get assigned to this issue.

**Comment by AdityaRaimec22** [comment]
@palisadoes when redis server is not running then `http://localhost:4000/` can't be accessed and only the error can be seen in the terminal.
So should I try to make such functionality like if redis server is not running then also `http://localhost:4000/` can be accessed and a message saying `redis server is not running` is shown?

**Comment by palisadoes** [comment]
> @palisadoes when redis server is not running then `http://localhost:4000/` can't be accessed and only the error can be seen in the terminal. So should I try to make such functionality like if redis server is not running then also `http://localhost:4000/` can be accessed and a message saying `redis server is not running` is shown?

I didn't realize that Redis is mandatory for the API to work now. Before it wasn't. In that case it doesn't make sense to have this issue.

I'll close it.
