### ISSUE TITLE
The `INSTALLATION.md` file needs a newly generated table of contents

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1528]
**Is your feature request related to a problem? Please describe.**
1. There are many missing table of contents (TOC) entries in the INSTALLATION.md file.
1. Many of the existing TOC entries are under an inappropriate parent heading

This increases the risk of installation instructions being overlooked.

**Describe the solution you'd like**
1. Add the missing table of contents (TOC) entries in the INSTALLATION.md file.
1. Adjust the resulting TOC entries under the appropriate parent headings
1. Ideally, the auto-generation of the TOC should be automatic as part of the `git` process

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- Consider using a markdown TOC autogenerator

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
would like to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by hharshas** [comment]
@palisadoes  I was not assigned to anyone of those, I would keep in mind with that from now onwards.

**Comment by palisadoes** [comment]
> @palisadoes I was not assigned to anyone of those, I would keep in mind with that from now onwards.

If you are first in line, you will be assigned. This is clearly stated in our orientation videos. There is no need to SPAM the issues with your requests. Please be more considerate of the needs of the repository contributors, and not just your own. Together we can make Talawa better, I'm sure you will agree.

**Comment by hharshas** [comment]
@palisadoes apologies for misconduction related spam, i let that happen without proper consideration. Would be happy to continue my learning and contribution.

**Comment by Veer0x1** [comment]
would like to work on it.

**Comment by palisadoes** [comment]
The schema test failed.

**Comment by Veer0x1** [comment]
> The schema test failed. I had to revert the PR

Schema test has been failing since 20th December, I'm checking what wrong with that workflow.

**Comment by palisadoes** [comment]
> > The schema test failed. I had to revert the PR
> 
> Schema test has been failing since 20th December, I'm checking what wrong with that workflow.

This may be the cause of the problem:
- https://github.com/PalisadoesFoundation/talawa-api/issues/1599

**Comment by palisadoes** [comment]
Please link your PRs to issues. It took some time to find this. We missed our procedure accidentally
