### ISSUE TITLE
The `INSTALLATION.md` file doesn't tell you to install typescript

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1529]
**Is your feature request related to a problem? Please describe.**
1. The `INSTALLATION.md` file doesn't tell you how to install typescript
1. This is an obvious omission and must be fixed

**Describe the solution you'd like**
1. Update the `INSTALLATION.md` file to explain how to install typescript in the correct order after installing `npm`
2. Make this a separate section in the procedure
3. Ensure that the table of contents is correctly updated

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by techmannih** [comment]
Hello @palisadoes ,
I want to work on this issue please assign me

**Comment by Cioppolo14** [comment]
@techmannih I just assigned you another issue, so now you have two. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by techmannih** [comment]
Okay @Cioppolo14 
Thanks

**Comment by Veer0x1** [comment]
@Cioppolo14 can you assign me?

**Comment by Veer0x1** [comment]
Why hasn't this issue got closed, when the PR got merged?

**Comment by Cioppolo14** [comment]
@Veer0x1 I am looking into it.
