### ISSUE TITLE
The `INSTALLATION.md` file doesn't tell you to create a `.env` file before running setup

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1530]
**Is your feature request related to a problem? Please describe.**
The `INSTALLATION.md` file doesn't tell you to create a `.env` file before running setup

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/c1a7d013-f9a8-4b5d-bc3e-bdfb282b40b1)

It should let you know that the  `.env` file needs to be created first. Possibly like this

```
cp .env.sample .env
npm run setup
```

**Describe the solution you'd like**
- See above

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
This is the setup command output when the `.env` file is missing
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/7127af06-1e7c-4058-b288-16fa8c2416d0)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by techmannih** [comment]
Hello @palisadoe ,
Can I work on this issue

**Comment by RAGHAV-N5** [comment]
Plese assign me this issue.

**Comment by techmannih** [comment]
@palisadoes  @Cioppolo14 ,
INSTALLATION.md seems look like this after changing
![Screenshot 2023-12-23 084607](https://github.com/PalisadoesFoundation/talawa-api/assets/125847751/ba2b9add-d829-4ba7-b332-20ec74d6bec5)

is it correct or not ?
