### ISSUE TITLE
Remove all unused packages from `package.json`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1538]
**Is your feature request related to a problem? Please describe.**

1. We have implemented dependabot alerts to let us know when we have outdated packages
2. We have noticed in the past that in some cases the packages listed in `package.json` are no longer being used

**Describe the solution you'd like**
1. Remove all references to unused packages from `package.json`
2. Generate `package-lock.json` appropriately

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Community-Programmer** [comment]
I want to work on this, please assign

**Comment by AdityaRaimec22** [comment]
@palisadoes can I get assigned to this issue. Thanks

**Comment by Yashkhamkar** [comment]
@palisadoes can I get assigned to this issue. Thanks

**Comment by sethum3001** [comment]
@noman2002 I would like to work on this issue. Can you please assign this to me?

**Comment by dhruvgupta0503** [comment]
hi, i want to work on this issue

**Comment by Pranavx1** [comment]
Can i work on this?
