### ISSUE TITLE
Fix Puny Code Error

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1547]
**Describe the bug**
Whenever the API is started or a commit is made there is a Puny Code deprecation error

**To Reproduce**

1. Start API or,
2. Commit code

**Expected behavior**
1. Fix the Puny Code requirement **_IF IT IS_** being used by the application 
2. The removal of the Puny Code requirement  **_IF IT IS NOT_**  being used. This would include removing it from the `package.json` file
3. All tests must pass
4. No app functionality must be affected

**Actual behavior**
- See above

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/1c169cce-38d5-46af-a111-bcf73632cc70)

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RAGHAV-N5** [comment]
I want to work on this issue. Please assign me.

**Comment by imshivam-gupta** [comment]
@palisadoes Can I work on this issue?

**Comment by imshivam-gupta** [comment]
@palisadoes, I have observed that the `PunyCode` module has been deprecated in Node.js version 21.5. This poses an issue as it is utilized by the `fast-url-parser` library, which, in turn, is a dependency of `@graphql-tools`. Unfortunately, `fast-url-parser` is not actively maintained, and there is already an open issue regarding this matter - [Link](https://github.com/petkaantonov/urlparser/issues/20).

Presently, we find ourselves with two potential courses of action:

1. Wait for the next release of `@graphql-tools` and, in the meantime, switch to Node.js version 18.
2. Explore alternatives to `@graphql-tools`, although this is not a preferred option given its status as a well-maintained repository.

Your insights on this matter would be greatly appreciated.

**Comment by palisadoes** [comment]
1. The first option.
2. Add the recommendation to INSTALLATION.md that the preferred node version is at least v18 as part of the PR. There is a node section in that document that would be suitable

**Comment by palisadoes** [comment]
Hold on. Why upgrade to node v18?

**Comment by imshivam-gupta** [comment]
I found online that the deprecation warning for Punycode appeared after Node `v18`. The API worked perfectly with `v18`, and in all the GitHub discussions I read, a common solution was identified.

**Comment by palisadoes** [comment]
1. Upgrading to node v18 ignores the problem, it doesn't solve it.
2. I'd prefer to focus on making the Talawa typescript repositories support the latest LTS versions of node
3. I'll close this issue as "will not fix" and the PR too.
