### ISSUE TITLE
Create an `User Type` Flag Field

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1552]
**Is your feature request related to a problem? Please describe.**

Currently our application assumes that all persons tracked in the database are Talawa users. This may not be the case in practice. Administrators will require the ability to manage people who either cannot access our apps or don't want to.

**Describe the solution you'd like**

1. We need to update the `User` collection to have a `User Type` field that could have at a minimum these possible values
     1. `App User`
     1. `Non App User`
1. This will need to be a mandatory field
1. Mutations for this field will need to be created for the `User` and related collections

The aim is that this field will be automatically populated during the registration process. Here are some examples:
1. Registrations through the mobile app would automatically be by an `App User`
1. Registrations through the User Portal web app would automatically be by an `App User`
1. Admins may want to manually add Users who may be an `App User` or a `Non App User`
1. Persons attending events may need to be checked in. If they are new to the organization, then the event organizer may want to add them as a `Non App User`

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
Related issues include:
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1552 (This issue - Prerequisite)
1. https://github.com/PalisadoesFoundation/talawa/issues/2269
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1273

**Other**
- Valid tests for this must be created as part of the resolution of this issue

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Doraemon012** [comment]
@palisadoes I would like to work on this. Please assign this to me.

**Comment by imshivam-gupta** [comment]
@Doraemon012 are you still working on this because it's a prerequisite for issue assigned to me

**Comment by Doraemon012** [comment]
@imshivam-gupta Yes, I'm working on it,  I'll complete as soon as possible.
