### ISSUE TITLE
Upgrade to Node 20 (LTS)

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1555]
**Is your feature request related to a problem? Please describe.**

1. We need to ensure that the app runs on an LTS version of Node.js
    1. https://nodejs.org/en/about/previous-releases
1. The installation guide doesn't specify the required LTS version of Node.js to be used
1. The application needs to be tested to make sure that it works with an LTS version of Node.js
1. Our GitHub Actions need to be updated to specify the LTS version of Node.js to be used

**Describe the solution you'd like**
1. Upgrade to Node 20 LTS
1. Update the installation guide to specify this LTS version of Node.js to be used
1. Update the installation or automated setup process to fail if the minimum LTS version isn't being used
1. Test the application to make sure that it works with this LTS version
1. Our GitHub Actions need to be updated to specify this LTS version of Node.js to be used
1. Address all warnings and errors (especially those related to deprecation) to the best of your ability according to industry best practice
1. All existing tests must pass

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AVtheking** [comment]
@palisadoes  assign this issue to me

**Comment by dhruvgupta0503** [comment]
@palisadoes I would like to work on this issue

**Comment by indiansamaltman** [comment]
is this issue still open can i work on it ?
