### ISSUE TITLE
GitHub Actions Test - Fail When Too Many Files Submitted

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1556]
**Is your feature request related to a problem? Please describe.**

1. The repository's MVP is now based on the code in the `main` branch. We make all new changes to the `develop` branch and periodically merge `develop` into `main`
2. Contributors are now frequently submitting pull requests (PR) either merging `main` into `develop` or vice versa. This causes PRs with hundreds of submitted files.

**Describe the solution you'd like**

1. We need a GitHub Action added to the repository that counts the number of files submitted and fails if they exceed 20, which is a reasonable number in most cases.
2. The message must indicate that the contributor may either be merging into an incorrect branch or the source branch is incorrect.
3. If any scripting is required, this must be done in python3 with python `black` and `pydocstyle` linting and formatting rules applied. We have examples in the `.github/workfows` directory.
4. The action must run in it's own section after the `Code-Quality-Checks` section in this workflow file
    - https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Anubhav-2003** [comment]
@palisadoes I would like to work on this issue

**Comment by palisadoes** [comment]
I normally don't assign issues. I'm just helping out today due to the holiday.

**Comment by Anubhav-2003** [comment]
@palisadoes ok sir. Thank you for assigning:)

**Comment by Anubhav-2003** [comment]
@palisadoes I have a question. If the github action is failing due to them submitting more than 20 files during PR at a time. Then should not the error message indicate that, along with "may either be merging into an incorrect branch or the source branch is incorrect". I was writting the error message and thought about it.

**Comment by palisadoes** [comment]
Please create a suitable message and submit a PR

**Comment by Anubhav-2003** [comment]
Ok sir. Thank you.

**Comment by xoldyckk** [comment]
@palisadoes is this related to git merge vs rebase?

**Comment by palisadoes** [comment]
Before the merge, for all the updated files in the PR
