### ISSUE TITLE
Restore countline.py functionality to our GitHub Action workflow

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1558]
**Is your feature request related to a problem? Please describe.**

We used to have a GitHub action section in this file that would count the number of lines in the code submitted and fail if they were too many lines in any one file. This greatly helped with our code quality

- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml

**Describe the solution you'd like**

1. Go through the history of this file
1. Restore the functionality of countline.py that was **most recently** in effect.
1. Ensure that all the files in the repository are in compliance. If not, refactor the code to make it compliant.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
1. The other repositories have maintained this functionality.
1. You can use their pull request YAML GitHub actions file as a guide
1. You can get help on countline.py by running the script like this:
```
./countline.py --help 
```
**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AdityaRaimec22** [comment]
@palisadoes can I get assigned to this issue.

**Comment by palisadoes** [comment]
@AdityaRaimec22

1. Set the line count to limit to 600 lines.
3. You can also ignore the test directory.
4. Running the `./countline.py --help` command will explain how to do this.

**Comment by palisadoes** [comment]
Please fix. Something went wrong
