### ISSUE TITLE
Fix Documention Workflow - Talawa-API

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1559]
## Bug Description
Our automated documentation GitHub action PUSH workflow is failing. 

Under normal operation it:

1. Uses the `typedoc` package to generate documentation
1. Commits any newly changed documentation files to a dedicated documentation directory
1. Copies these files to the Talawa-Docs repository

This process has recently started to fail for both Talawa-API and Talawa Admin. 

1. We are not sure why and it needs to fixed.
1. The workflows help our developers understand the codebase through easily indexed HTML on the docs.talawa.io site

The push workflow files in question are:

- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/push.yml
- https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/push.yml

Part of the troubleshooting difficulty is that:

1. The two workflows use different package managers (NPX vs Yarn)
1. One workflow uses package caching, while the other doesn’t
1. We are uncertain whether there is an underlying GitHub secret misconfiguration, possibly an expiry.
1. The files produced by the API workflow are compatible, but the Admin files are not. We don't know why. It could be because the API workflow broke before that of Admin, or vice versa.

To complicate matters, we also recently upgraded Talawa-Docs to Docusaurus v3 as the previous version has been deprecated. 

1. Version 3 uses the new MPX standard for markdown files where all `<`, `>`, `{` and `}` characters need to be escaped with a `\` character.
1. More details can be found here https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3

We need the markdown files generated by `typedoc` to be MPX compatible.

## Related difficulties

The non MPX compatible files are causing our Talawa-Docs PRs and pushes to fail. This means that it is difficult for us to update our GSoC ideas page. We have to manually do search and replacement of the incompatible characters.

## Requirements

These are the requirements to fix this issue

1. Get one workflow working
1. Get the other workflow working using the package manager of the first workflow
1. Standardize on a caching mechanism, or none
1. Ideally, use identical standardized workflows with environment variables to differentiate between the repos where necessary
1. The markdown files generated must be MPX compatible using the `npx docusaurus-mdx-checker` command. This may mean finding a typedoc parameter to make the output markdown files MPX compatible or writing a script to do a search and replace operation in the API and Admin documentation directory tree to fix the issue.
1. Create a markdown document describing how the fixed workflow works, including any GitHub configuration parameters, so that our team can use it as a reference. This should be added to Talawa Docs. Please coordinate this activity with the members below.

## Issue assignment
1. We greatly prefer a single person working on the equivalent issue in both repositories. Who ever gets assigned this issue must ask to be assigned to the issue below in the other repository.
    - https://github.com/PalisadoesFoundation/talawa-admin/issues/1279
2. This means we will need to assign the issue to someone who currently has **no assigned issues**

## Additional details
Please work with these contributors who have been focused on this issue for some time

1. @anwersayeed 
2. @tasneemkoushar 

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by dhiraj0911** [comment]
I would like to work on this

**Comment by alanansari** [comment]
Assign me this please

**Comment by indiansamaltman** [comment]
is this issue still open can i work on it ?

**Comment by palisadoes** [comment]
@dhiraj0911

Please also comment on this issue so that you can be assigned. The two need to worked on together.
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1279

**Comment by dhiraj0911** [comment]
Done with all the changes
```[SUCCESS] All 8 MDX files compiled successfully!```
```
        modified:   INSTALLATION.md
        modified:   package-lock.json
        modified:   package.json
        modified:   src/typeDefs/README.md
```

**Comment by palisadoes** [comment]
@dhiraj0911

1. What's the update on this?
2. We need to get this fixed soon.
3. It's creating a real hardship for us.

@noman2002 @Nitya-Pasrija Please follow up on this

**Comment by Veer0x1** [comment]
Is this issue still open for work? If yes then I would love to work on it.

**Comment by palisadoes** [comment]
1. This is open for assignment
2. You can work with @tasneemkoushar to get this implemented. 
3. It was working in the Admin repo, but stopped earlier this week. 
4. We know the Admin code works:
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1279
6. It may be related to expired repo secrets

**Comment by adi790uu** [comment]
Hey @palisadoes can you please describe the exact problem we are facing with the api github workflows just for clarity.

**Comment by palisadoes** [comment]
1. It's completely explained above.
1. It's been 10 days since assignment, with neither a PR nor updates. 

This has been causing real difficulties for weeks without resolution. Developers cannot easily browse out updated documentation. This is important as the code is changing daily.

When do you plan to submit a PR?

**Comment by adi790uu** [comment]
@palisadoes within the next few days, will create a PR for this.

**Comment by adi790uu** [comment]
hey @palisadoes i tested the workflows locally and it has worked for me :
<img width="1373" alt="Screenshot 2024-01-30 at 7 50 52 PM" src="https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/a2d6198b-b6e8-4546-b075-b4b722fd23f3">
<img width="1373" alt="Screenshot 2024-01-30 at 7 51 24 PM" src="https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/8492e0c0-134d-4817-840f-1653e279dfc0">

Am i missing something if not then maybe its an issue with expired repo secrets!

**Comment by adi790uu** [comment]
hey @palisadoes sorry for bothering you, can you check the above comment and give feedback so that I can proceed forward.

**Comment by palisadoes** [comment]
1. Go ahead. 
2. We suspect that it's due to access token expiry. 
3. We'll need a procedure to

**Comment by adi790uu** [comment]
> 3. We'll need a procedure to 

This point is incomplete @palisadoes.

**Comment by palisadoes** [comment]
A procedure to recreate the secrets, specifically the permissions

**Comment by palisadoes** [comment]
What permissions did you grant your secrets to do this?

**Comment by adi790uu** [comment]
@palisadoes repo and workflow
