### ISSUE TITLE
[Bug] Wrong import path name

### ISSUE THREAD

**Issue by gauravdas014** [PalisadoesFoundation/talawa-api#157]
In `resolvers/template.js` the import path of `authCheck.js` is wrong. I am attaching the screenshot of the same

![3](https://user-images.githubusercontent.com/51530678/111442919-e11dbd00-872e-11eb-8627-e8a603de00da.png)

It should be 
```js
const authCheck = require("./functions/authCheck");
```
instead of 
```js
const authCheck = require("../functions/authCheck");
```
@Sagar2366 Can you assign me this issue?

**Comment by Sagar2366** [comment]
Hey @gauravdas014, good finding. Can you check for similar issues and send our PR for review ? 
Check for unused variables, syntax errors, etc and cover under this issue.

**Comment by gauravdas014** [comment]
@Sagar2366 Sure. I have found a couple of errors. I will report them in the PR.
