### ISSUE TITLE
Ensure all non-test Typescript files have < 600 lines - API

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1578]
**Is your feature request related to a problem? Please describe.**

We recently restored the `countline.py` script to our repository

- https://github.com/PalisadoesFoundation/talawa-api/issues/1558
- https://github.com/PalisadoesFoundation/talawa-api/pull/1568

We need to also restore our goal of having no typescript files with > 600 lines of code. We do this for readability and to force better coding standards by encouraging the use of more reusable code.

**Describe the solution you'd like**

1. Update our pull request github action to make the `countline.py` script fail for files with > 600 lines of code. Run the  `./countline.py --help` command to see how that is done.
1. Run  the `countline.py` script with the 600 line limit to identify the offending files.
1. Refactor the code in the offending files so that the script does not fail.
**Describe alternatives you've considered**

**Approach to be followed (optional)**
- See above

**Additional context**
- Please work with @noman2002 in reviewing your PR

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by LakshyaSatpal** [comment]
Can I work on this?

**Comment by Pranavx1** [comment]
Can i work on this?

**Comment by monkCommits** [comment]
Can I work on this?

**Comment by AVtheking** [comment]
please assign this issue to me

**Comment by karthxk07** [comment]
Hey @noman2002 , new to the repo hi!!. This looks like a good first issue , i think i might be able to work on this issue, can i get this assigned to me ?

**Comment by Cioppolo14** [comment]
I have assigned the first person who asked who did not already have 2 issues.

**Comment by Pranavx1** [comment]
There are no offending files.So,do i just submit a PR?

**Comment by palisadoes** [comment]
No. Closing. The script was removed and this issue was created as a precaution. Thanks.
