### ISSUE TITLE
Talawa-Api Dev setup shows GraphQL Loading due to content Security Policy directive

### ISSUE THREAD

**Issue by kernelpanic77** [PalisadoesFoundation/talawa-api#158]
![Screenshot from 2021-03-17 17-29-28](https://user-images.githubusercontent.com/42925218/111464263-8b550f00-8746-11eb-8f54-9d828f0acd2d.png)
As the following image shows there are issues with the contetSecurityPolicy directive, while setting up the dev environment. 
The localhost:4000/graphql gets stuck on Loading GraphQL Playground
Can I work on this issue ?

**Comment by gauravdas014** [comment]
@kernelpanic77 I think this issue is resolved now. Please run the latest code from dev and verify.
