### ISSUE TITLE
Rename variable link to mediaUrl

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-api#1581]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Recently we've added support for uploading media instead of accepting a link when creating an advertisement to minimise chances of error. 

https://github.com/PalisadoesFoundation/talawa-admin/pull/1248

As discussed [here](https://github.com/PalisadoesFoundation/talawa-admin/pull/1248#issuecomment-1869562680), the link parameter needs to be renamed to mediaUrl.

**Describe the solution you'd like**
Rename the variable link to mediaUrl

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by monkCommits** [comment]
Could you please assign me this issue

**Comment by disha1202** [comment]
Hi @monkCommits 

This issue is dependent on https://github.com/PalisadoesFoundation/talawa-admin/pull/1248. 

Can you please look for other open issues.

Thanks:)
