### ISSUE TITLE
Typo in Paragraph

### ISSUE THREAD

**Issue by pankaj-2503** [PalisadoesFoundation/talawa-api#1582]
**Is your feature request related to a problem? Please describe.**
Typo in Paragraph

**Describe the solution you'd like**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/90036864/cbb28d08-a254-4b7f-9e03-b4d127c67e05)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pankaj-2503** [comment]
Assign this to me i can fix this

**Comment by palisadoes** [comment]
1. This is not an error in our repositories.
2. Thanks for pointing it out.
3. Closing
