### ISSUE TITLE
Create Support for Event Agendas

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1588]
**Is your feature request related to a problem? Please describe.**
Community based organizations will often need to have agendas for their events. Reasons for this requirement would include:

1. The order of ceremony for a wedding
2. The order of ceremony for a concert
3. Agendas for committee meetings

**Describe the solution you'd like**
We need the ability to make events have agendas. The agenda would have sequence of agenda items with the following characteristics:

1. Title
1. Description
1. Agenda item type (See "Note" type below)
1. Agenda item type information (For example if an organization creates a type called "Song, they may want to make this track the key of the music)
1. Duration of the agenda item
1. Multiple Attachments stored on the system
1. Multiple URL links
1. Agenda item "User" to indicate a speaker, performer or similar party
1. Agenda item category which would come from a Agenda category list that is universal to the organization.
1. Agenda section which would allow agenda items to be grouped together. The section will require:
    1. A description
    1. An ordered sequence of sections so that they can follow one another
    1. An ordered sequence of agenda items belonging to a section
1. updatedBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. updatedAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. createdBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. createdAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542

We will need schema, mutations and queries created for:

1. Agenda sections and their sequencing within an event
1. Agenda items and their sequencing with a section
1. Agenda item URLs
1. Agenda item attachments
1. Agenda categories within an organization

Other schema, mutation, query requirements:
1. Mutations would include typical CRUD actions. 
1. Document the schema, mutations and query requirements well so that it exports with meaningful information to our automatically generated schema, mutations, and queries documentation page used by our developers.
    1. https://docs.talawa.io/docs/schema

There will also be a need for a special type of agenda item:

1. Called a "Note"
1. Contains a description
1. No duration, no title, attachments, URLs, user 
1. Has all the other characteristics of an Agenda item in terms of sequencing
1. Could be identified by a `Note` flag field in the Agenda schema

Therefore the schema will need an enum for the agenda item type  which would cover regular vs note type items, with a consideration for future support of other item types

There are some additional requirements:

1. When the first section is created, all existing agenda items must be tied to it while maintaining the agenda item order.
1. Changing the sequencing of an agenda section must not alter the sequencing of the agenda items within each section.
1. Changing the sequencing of agenda items must not alter:
    1. The sequencing of sections
    1. The sequencing of any other sections should other sections exist
1. You will need to write valid tests for this work
1. No other functionality must be affected

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1.  This is a prerequisite for our menu of GSoC 2024 project ideas
1. This issue would be best handled by someone who already has experience with updating our schema, mutations etc or can prove it in other scenarios. 
1. Please work with @xoldyckk on the details of this issue and the subsequent PR

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@noman2002, @Cioppolo14, @aashimawadhwa, @kevoniat

1. We need really an experienced person for this issue. 
1. Preference will need to be given to the first person requesting assignment with a proven track record.

**Comment by disha1202** [comment]
Hi 
Can I work one this?

**Comment by aialok** [comment]
I can work on this issue. I have experience in Rest API, MongoDB, and building backend systems. I am currently exploring GraphQL.
I want to contribute to something significant.
I will try my best to complete it.

**Comment by palisadoes** [comment]
@disha1202 @aialok Both of you have at least two issues across repositories. Others need to get a chance

**Comment by Community-Programmer** [comment]
@palisadoes 

If you want, In addition to the ongoing work on `Fix Recurring Events`, I'm open to taking on this issue as `Fix Recurring Events` issue also require updating schema and mutation.
Otherwise,
If anyone else is interested in contributing or taking ownership of a this issue, please feel free to take this issue.
At end, if there are no takers, consider me as the backup option. I'd be glad to step in and address the issue if needed

Thank you

**Comment by Atharva-Kanherkar** [comment]
I would like to work on this issue. Although, i will be able to create and define schema, do mutations and queries and CRUD operations. But, as i am a new contributor,  i will require some help. @Community-Programmer  can we collaborate on this issue and work together? Or maybe someone can help me a little bit on documentation stuff as i am a little new?

**Comment by aialok** [comment]
> @disha1202 @aialok Both of you have at least two issues across repositories. Others need to get a chance

I can unassign myself from one of the issues. As this issue is more impactful, the other issue is a good first issue, allowing another fellow contributor who is starting to work on it.

**Comment by rajkulx** [comment]
Hi, can you please give me chance, I can do this I have experience with mongo and js, ts. Thanks

**Comment by AdityaRaimec22** [comment]
@palisadoes can I get assigned to this issue.

**Comment by Community-Programmer** [comment]
@Atharva-Kanherkar

For sure, to whomever will be assigned this issue, I'm ready to help you as best I can with any problems you may face during the resolution of this issue.

**Comment by palisadoes** [comment]
> @Atharva-Kanherkar
> 
> For sure, to whomever will be assigned this issue, I'm ready to help you as best I can with any problems you may face during the resolution of this issue.

One issue, one assignee

**Comment by palisadoes** [comment]
@Community-Programmer In retrospect, the recurring event solution is going to require significant effort. I'd prefer that you focus on that. We also should consider giving others a chance.

**Comment by Community-Programmer** [comment]
@palisadoes 

I understand the importance of addressing the recurring event solution and will prioritise my efforts towards resolving that issue. I appreciate your consideration in giving others a chance as well.

Thank you

**Comment by palisadoes** [comment]
https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github%2Fworkflows%2Finspect.yml

There are two schema generators at the end of this GitHub action file. One of them exports markdown files that we commit to the Talawa Docs repo to create the Talawa website. It will have the information you require on how to document your code to make the markdown user friendly

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Thank you so much!

**Comment by palisadoes** [comment]
How's progress on this going?

**Comment by palisadoes** [comment]
@Atharva-Kanherkar 

Make sure you add support for these fields in your schema and allow for logging as seen in this PR.
1. updatedBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. updatedAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. createdBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. createdAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542

**Comment by Atharva-Kanherkar** [comment]
The work is in progress, have been making schemas and mutations. I had a doubt if i may ask, can we submit a work in progress PR so that the community also gets a sense how I am working? is it allowed? @palisadoes

**Comment by palisadoes** [comment]
1. If you feel that the work could be split into discrete stages then the best approach would be to create PRs for each stage tied to this issue.
2. PRs should be submitted when you are fairly certain of your solution and are sufficiently confident of defending your choices.
3. Draft PRs are a burden for our reviewers as they get alerted to each commit. That is why we prefer PRs being submitted when only a few minor rectification commits are required before merging.
4. Remember to include tests
5. Contact @xoldyckk either here or on slack too. But the best way is to submit the PR.
6. You can also ask the `#talawa-api` slack channel for feedback
7. If you are uncertain of the requirements before submitting the PR, ask the questions here.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes  okay sure. thank you!

**Comment by palisadoes** [comment]
Agenda capability should be granted to whoever created the event,  org Admins and Super Admins

**Comment by Atharva-Kanherkar** [comment]
### **Progress till now :**
**Created MongoDB schemas for:**

1.Agenda Items
2.Agenda Sections
3.Agenda Categories



### Defined Fields for Agenda Items:
`Title`,` descp`, the event related to it(ref to` "Event")`, `created by`, `updated by`, etc.
There is a bool field for `isNote`, which acts as a flag if it is a note type agenda item or not. The enum` itemType `has also been added, which asks if the agendatype is a  note type or regular type. There is a field sequence, which is an integer, through which we will be seeing the order of the agenda item 

### Defined Fields for Agenda Section : Description, sequence of the agenda section, and the organization it belongs to (ref to organization)


### Defined Fields for Agenda Category : Description, name and the organization it belongs to (ref to organization)

 I have defined the graphQL types too. And have been consistent with the best practices of the project. Is there anything else which will be required in the schemas? Any  more fields, references etc? ( i have covered all which were in the issue). I have begun writing the logic for sequencing etc. It will take some time. Thank you! @palisadoes @xoldyckk

**Comment by palisadoes** [comment]
1. This is hard to decipher.
1. If you are ready and can defend your choices, then open a PR 
1. The schema will be easier to read and understand

**Comment by Atharva-Kanherkar** [comment]
> 1. This is hard to decipher.
> 2. If you are ready and can defend your choices, then open a PR
> 3. The schema will be easier to read and understand

I have just made the schemas right now. Is it okay to draft a PR if there are only schemas on it? I mean the work is in very initial stage. Sorry, if it was hard to decipher, ill keep in mind next time.

**Comment by palisadoes** [comment]
1. Yes, with an aim of merging the schema immediately or soon thereafter submission.
2. We have to be respectful of volunteer time, they are reviewing dozens of PRs and the more complete each one is, the better.

**Comment by Atharva-Kanherkar** [comment]
![Screenshot from 2024-01-05 12-43-09](https://github.com/PalisadoesFoundation/talawa-api/assets/142440039/065b45a7-af51-4607-83e5-ec49a7c2f796)

**Comment by Atharva-Kanherkar** [comment]
![Screenshot from 2024-01-05 12-43-09](https://github.com/PalisadoesFoundation/talawa-api/assets/142440039/5c2bc7c0-f477-4f23-8608-7c44eed09b43)

@palisadoes When i am try to committing to this org, this issue is arising. I have just added graphQL schemas, and mongoDB schemas. I have just added new files, the tests fail when i run the `git commit ` command. My code seems correct and consisten with the writing style of the project.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes  @xoldyckk  This is an example of how i defined the mongoDB schemas. I Just committed for reference manually, otherwise i could not commit them with the CLI(Along with the graphql schemas and resolvers) But it gave me a bunch of errors. Can you please review this code and see what syntax i am going wrong with?

[Please take a look](https://github.com/PalisadoesFoundation/talawa-api/compare/main...Atharva-Kanherkar:talawa-api:main)

**Comment by palisadoes** [comment]
@Atharva-Kanherkar 

1. Please ask the `#talawa-api` slack channel for assistance. We are reviewing 14 PRs in this repo alone.
2. Open a PR independently, without asking permission, when you are confident of having a viable solution.

**Comment by palisadoes** [comment]
@Atharva-Kanherkar Were you able to get assistance from the channel? There are other API GraphQL PRs that are currently open and others that are closed that you could use as examples. Contact the contributors associated with them on slack.

**Comment by Atharva-Kanherkar** [comment]
> @Atharva-Kanherkar Were you able to get assistance from the channel? There are other API GraphQL PRs that are currently open and others that are closed that you could use as examples. Contact the contributors associated with them on slack.

Yes, i reached out to many people on personal messages. Many of them helped out. Thank you for your suggestion, ill contact them too. I only have the work of testing the API and my work left, and will need small assistance for that. I will be contacting people for that. Thankyou!

**Comment by palisadoes** [comment]
How's progress on this?

**Comment by Atharva-Kanherkar** [comment]
> How's progress on this?

Hi, the work on this is almost done (can say 60%) all that is left is fixing errors, documentation and some more resolvers. I am thinking of drafting a PR of the done work tommorrow, if this is fine, as i am a little busy today travelling to my university.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes I had something to propose, can i post this as three PR's? I Know reviewers do not have that much time and so many PR's would actually take more of it, but this seems an easy way to contribute for me. I will be posting one PR every two days. So that i am sure my code works properly. Thankyou!

**Comment by Atharva-Kanherkar** [comment]
> @palisadoes I had something to propose, can i post this as three PR's? I Know reviewers do not have that much time and so many PR's would actually take more of it, but this seems an easy way to contribute for me. I will be posting one PR every two days. So that i am sure my code works properly. Thankyou!

The last PR can have all the documentation and test based stuff.

**Comment by palisadoes** [comment]
Whats the justification for this approach? You are right, it'll be more work for our limited team that already has a backlog.

**Comment by Atharva-Kanherkar** [comment]
> Whats the justification for this approach? You are right, it'll be more work for our limited team that already has a backlog.

Actually some of the stuff was taking a lot of time, and i thought that as almost two weeks have passed, i should draft a PR for more than half of the done work.

**Comment by palisadoes** [comment]
One PR

**Comment by Atharva-Kanherkar** [comment]
Alright! I'll draft a whole PR when i complete the work. Thank you

**Comment by Atharva-Kanherkar** [comment]
@palisadoes I had some doubts while writing the tests for the code i have written, kindly provide me with relevant information so that i can draft a PR as soon as possible. 1) Agenda Items can be created by a normal user, and only who created it, the super admin, admin can delete and update it? 2) Agenda categories will be universal to an organisation, so only admins and superadmins can create, update and delete the categories, right? 3) Agenda sections can be created by only super admins Or admins? I think we should give this only to superadmins, correct me if i am wrong.  4) If a user is creating a "Note" type of agenda item, will it be okay if i create another schema for it or it'll be better to merge it in the normal agenda item only, where it has reduced properties? 
These were some final doubts before wrapping up the issue. I would really thank palisadoes for being such a beautiful community!

**Comment by palisadoes** [comment]
1. Agenda item creation should be by the event organizer, Admins and Super Admins
2. Categories will be universal to the organization as you suggest. An Admin screen to do CRUD will need to be created
3. Sections are local to the Agenda itself to be created by the event organizer, Admins and Super Admins
4. The final result must be that all line items in an Agenda will need to be able to be easily listed in a Mobile or Admin screen when requested by queries. The line items will need to be easily edited with the order maintained. You are suggesting that Sections will either have:
     1. Lists of agenda items with the same object types or
     2. Lists of agenda items with variable object types.
    Which of these approaches do you feel will be best in the long term for readability and maintainability?

**Comment by Atharva-Kanherkar** [comment]
> 1. Agenda item creation should be by the event organizer, Admins and Super Admins
> 2. Categories will be universal to the organization as you suggest. An Admin screen to do CRUD will need to be created
> 3. Sections are local to the Agenda itself to be created by the event organizer, Admins and Super Admins
> 4. The final result must be that all line items in an Agenda will need to be able to be easily listed in a Mobile or Admin screen when requested by queries. The line items will need to be easily edited with the order maintained. You are suggesting that Sections will either have:
>    
>    1. Lists of agenda items with the same object types or
>    2. Lists of agenda items with variable object types.
>       Which of these approaches do you feel will be best in the long term for readability and maintainability?

Basically what i have done is made one schema (Agenda section) which has a list of items, (same object types) and we can create a new section by giving it title, description, sequence and the list of items (whereas items is an object type) And the schema AgendaItem has a property called sequence(Int type) which helps manage the sequencing of the items within a section.  It's easy and readable, too. (In the mobile app, or on the frontend, we can implement something using the sequencing so that the items show on a section in sorted order). Does this sound good? Or any new logic seems appropriate? I have implemented this logic right now.

**Comment by Atharva-Kanherkar** [comment]
Hello @palisadoes,

I hope this message finds you well. I wanted to share that I've successfully passed all tests locally, and the code coverage on the added files from my side is 100%. In the process of creating the upcoming PRs, I've encountered a scenario where some code elements might coincide among the three PRs.

Given the intrinsic nature of certain code sections, it would be challenging for me to temporarily remove and store them while making subsequent PRs, as i will have to curate some code and select them. While it will be easy for seperate files, but for intrinsic codes like types and inputs, it will be difficult.  I'm reaching out to inquire whether having coinciding elements across the PRs is acceptable. I believe this approach would streamline the process and ensure a smoother contribution. 

I appreciate your time and consideration on this matter. Looking forward to your guidance.
There is an image attached for your reference. 

Best regards, 
Atharva
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/142440039/832ef2ad-eb7e-44ba-8a50-7857abcb3354)

**Comment by palisadoes** [comment]
The expectation isn't to remove code between PRs. Each PR must be additive, building on the code of the previous one. These are the minimum expected PRs we'll need to see.

1. Category CRUD
1. Section CRUD
1. Agenda Item CRUD

We cannot have PRs with dozens of files to review. It causes too much delays with the reviewers.

**Comment by Atharva-Kanherkar** [comment]
> * Section CRUD

Hello @palisadoes , while i totally understand your concern for the availability and ease for the reviewers, i just wanted to shed some light upon that when i am playing with the code, while removing some files and not removing some, it is just simply messing the code up. It is getting a lot of errors because almost every piece of code is inter-related an inter-dependent. I, while totally ready and understand and value the reviewer's time, is there any other option or i must have to segregate the code in three PR's? 
Thank you for your time.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Hello, i wanted to update you on a situation. I was almost ready with the code, I even made a pr yesterday which mistakenly had a lot of other people's commit. I am very sorry for opening it and closing it, I should've been sure. I wanted to update you that my PC has experienced an unexpected shutdown and has stopped working. I am trying to get it opened as soon as possible. I sincerely apologise for the delay caused. I will get back to the code as soon as possible. 
Atharva

**Comment by palisadoes** [comment]
1. Are you still working on this? You have been focusing on the mongoose upgrade.
2. It would be good to give this to someone else to complete

**Comment by palisadoes** [comment]
We'll need to

**Comment by Atharva-Kanherkar** [comment]
> 1. Are you still working on this? You have been focusing on the mongoose upgrade.
> 2. It would be good to give this to someone else to complete

Hello, it is almost completed with one PR pending. There is one issue, the PR action file tells me that there are >600 (604) lines of code. And it is in the typedefs file. Removing the code will not make any sense because it will simply alter the functionality of the code. Also, i am sorry of solving this issue a bit late, actually the ES lint issue got me bugged for a couple of weeks. This seems to be completed in a day or two.

**Comment by palisadoes** [comment]
Thanks. Please work with the contributors listed in this issue to handle your technical questions. I have to focus on other areas.

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Atharva-Kanherkar** [comment]
> Thanks. Please work with the contributors listed in this issue to handle your technical questions. I have to focus on other areas.
> 
> * [Student Internship Programs talawa#359](https://github.com/PalisadoesFoundation/talawa/issues/359)

Hello, @palisadoes  I am sorry for pinging you when you are busy. I just wanted to ask one thing,  in the issue about the admin implementation of the agenda items, you have self assigned it to yourself. Is that issue still available to work? Or it is not open for contributors? I have written the API version of the code, so was willing to write the frontend too. Waiting for your reply. Thank you!

**Comment by palisadoes** [comment]
I have some questions about the current implementation:

1. Can categories be blank in an agenda item? This should be an option
2. Can sections be optional in an agenda? This should be an option
3. What happens when a section is deleted and there are items associated with it? Will they be assigned to the previous section, or will they be deleted?

**Comment by Atharva-Kanherkar** [comment]
> I have some questions about the current implementation:
> 
> 1. Can categories be blank in an agenda item? This should be an option
> 2. Can sections be optional in an agenda? This should be an option
> 3. What happens when a section is deleted and there are items associated with it? Will they be assigned to the previous section, or will they be deleted?

Hello, @palisadoes 
1. Yes, you can make an agenda item without entering a category, it is not mandatory.
2. I would like to tell you that agendas do not have sections, it would be futile if agendas would have sections, sections have agendas and yes, i have made sections this way that sections can exist without agendas in them (blank sections, where you can put agenda items later, and have only other details such as description, etc for starters).
3. If you delete an agenda section, the agenda items will not get deleted or get assigned to previous sections, if you want me to implement this that they get assigned to a previous section, i would be happy to draft a PR regarding this. Right now, the implementation is simple, you can just delete the section, but it will have no effect on the items associated with it, they exist independently.

**Comment by Atharva-Kanherkar** [comment]
Also, @palisadoes I would like to ask you about the implementation of this issue on the talawa-admin portal, is anyone working on it? If not, can i work on it as i would be happy to implement the thing on the frontend? Thank you!

**Comment by palisadoes** [comment]
There is a parent issue for admin that has a child issue that is already assigned. 

You can create issues for the follow up activities required.

We need to implement the ability to delete sections without affecting the utility of the action items.

**Comment by palisadoes** [comment]
If there are no sections then the items should still be visible.

Did you implement the ability to assign items to sections?

What happens when the first section is created? Do all the items get assigned to it?

**Comment by Atharva-Kanherkar** [comment]
> There is a parent issue for admin that has a child issue that is already assigned.
> 
> You can create issues for the follow up activities required.
> 
> We need to implement the ability to delete sections without affecting the utility of the action items.

Alright, works.

**Comment by Atharva-Kanherkar** [comment]
> If there are no sections then the items should still be visible.
> 
> Did you implement the ability to assign items to sections?
> 
> What happens when the first section is created? Do all the items get assigned to it?

1. Yes, if there are no sections the items will be visible. 
2. When creating a new section, the creator gets the option to enter the items and it gets stored in an array of agenda items. If the creator does not want to enter any items right now, he can use `updateAgendaSection.ts` to enter the items afterwards too. 
3. I do not understand your point, sir. When you will delete an agenda section, how will items get affected? They are independently existing as i have implemented them. If there is anything else or any new functionality you would like me to implement, happy to work on them! Thank you:)

**Comment by Atharva-Kanherkar** [comment]
@palisadoes I had an idea if we can implement this. I don't know why this did not come to my mind before hand. We can implement a sub sections in agenda sections named ```priorities``. This is highly needed as more and more people start creating agendas and inputting them into sections, it would a hotchpotch with so many items. While the sequencing is a great idea for people that first one will be the most prior, but we can implement a sub section with a different color type, and it can have the most important agendas for the event. The sequencing would not be this visually appealing, while a priority subsection would be visually appealing as will have a different color and a subsection, drawing admin's attention even more rather than a single number, which someone could miss. Thank you!

**Comment by palisadoes** [comment]
An interesting perspective. We need to keep it simple to ensure it is used.

1. Agendas are the equivalent of Meeting Agendas or an Event Program. 
2. It's just a simple sequential list of activities to guide the master of ceremonies or meeting chairperson.

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/aa702e94-a9b3-4f48-82d5-a549a9a2fbe4)

**Comment by Atharva-Kanherkar** [comment]
> An interesting perspective. We need to keep it simple to ensure it is used.
> 
> 1. Agendas are the equivalent of Meeting Agendas or an Event Program. 
> 2. It's just a simple sequential list of activities to guide the master of ceremonies or meeting chairperson.
> 
> ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/aa702e94-a9b3-4f48-82d5-a549a9a2fbe4)
> 

2. It is already implemented, but if we add the priorities sub section it would be easier for the admins to decide and prioritise the agenda items!
Should I move ahead with the ideation? Does it sound good?

**Comment by palisadoes** [comment]
Events will be created by Members and Admins alike. There is no need for priorities being listed on the equivalent of an online brochure for an event. Priorities are not a priority and must not be implemented.

**Comment by palisadoes** [comment]
1. Your Admin Event Agenda issue depends on this one.
2. Will you be submitting a PR soon?

**Comment by Atharva-Kanherkar** [comment]
> 1. Your Admin Event Agenda issue depends on this one.
> 2. Will you be submitting a PR soon?

Yes I have been working on this issue but it is taking some time. I will be submitting a PR very soon for talawa admin. I am also taking help from others for the issue so it's taking some time. Thank you

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Is there any significant changes made in the API? My docker container stops just right at this point and does not start anymore.
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/142440039/080556ac-212d-468b-a3ec-0c7cb3b54280)
This only happened when i fetched some fresh code from the repository.

**Comment by palisadoes** [comment]
Ask in the API slack channel

**Comment by varshith257** [comment]
@palisadoes I think you can be done it quickly. In docker-compose file uncomment the container code 😅

**Comment by palisadoes** [comment]
@Atharva-Kanherkar 

I've uncommented the dockerfile. Please merge with the latest upstream.

**Comment by Atharva-Kanherkar** [comment]
> @Atharva-Kanherkar
> 
> I've uncommented the dockerfile. Please merge with the latest upstream.

Alright! Thank you so much.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes I would like to update you with some information on this issue, repository wise : 

### Done:
- **Talawa - API:**
  1. Implemented all provided functions in the API.
  2. Some tests have low code coverage due to userTypeFix; working on fixing these soon.

### In Progress:
- **Talawa - Admin:**
  - Working on implementing event agendas in the admin. Currently facing login issues on my local machine but working fine on my friend's machine. Kindly reassign related issues to me to submit a PR soon.

### Documentation:
- I have added  documentation in the code whenever and wherever it is needed. My question is, do we need to add any documentation regarding this and `docs.talawa.io`? And if yes, i would like to work on it. This would be a new and challenging task to work on only if it is needed. 


### My suggestions : 
- I think in the implementation of the agenda items, there is a need for me to correct two things in the implementation of agenda items. First, that the `user` type in the agenda item is a `string`. Should it be though? It should be of type `User`? Correcting it and making respective resolvers for it would be a good issue.
- Secondly, i think that the note agenda item's functionality is a little bit skewed right now. We have two variables in the agenda item model, one is a boolean type `isNote` and another is an enum `ItemType`, which both work towards the same goal. Removing either of them whichever seems simpler and more functional would be a great nway to introduce simplicity. 

### Additional Suggestions/Questions:
- Are there any more suggestions or missing functionalities related to agendas that need implementation? I'm open to working on those if required.

Please let me know if any further information or updates are needed. Thank you!

**Comment by palisadoes** [comment]
1. You don't have to ask permission to open an issue
2. The more clarification documentation we have, the better
3. Follow best practice on the user type
4. We need a methodology of adding a note between agenda items so that they are easily visible. That is why it was created. Suggest an alternative if you have a better way of implementing the solution.

**Comment by Atharva-Kanherkar** [comment]
> 1. You don't have to ask permission to open an issue
> 2. The more clarification documentation we have, the better
> 3. Follow best practice on the user type
> 4. We need a methodology of adding a note between agenda items so that they are easily visible. That is why it was created. Suggest an alternative if you have a better way of implementing the solution.

Alright! I will make an issue right away, with the solutions and suggestions provided in the issue itself. Thankyou!
I would also like to tell you that i plan to work on the admin issue very soon after fixing these. The logging in works fine. on my freind's PC. Please re-assign me the issue. 
Thank you!

**Comment by palisadoes** [comment]
You are already assigned the issue

**Comment by palisadoes** [comment]
OK, closing
