### ISSUE TITLE
Upgrade to the latest Apollo Server and GraphQL packages

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1593]
**Describe the bug**
1. A major bug was discovered in `Apollo Server v4.9.3` which we currently use
    1. https://github.com/apollographql/apollo-server/blob/main/packages/server/CHANGELOG.md
1. We currently use `graphql` v16.6.0 which is susceptible too

**To Reproduce**
- Refer to the repository's `package.json`  file

**Expected behavior**
1. The bug is fixed due to the recommended upgrade
2. Upgrade to `Apollo v4.9.5`
3. Upgrade `GraphQL` to at least v16.7.0. 
    1.  The current latest version is `v16.8.1` which we should attempt to use as a completion criteria for this issue. 

**Actual behavior**
- Our packages are susceptible to the bug

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/fcdfe619-4f10-496d-a3e2-277b7dc13058)

**Additional details**
- Please work with @xoldyckk on any questions you may have or when reviewing your PR

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AdityaRaimec22** [comment]
@palisadoes can I get assigned to this issue.

**Comment by Sahil-Shadwal** [comment]
@palisadoes can i work on this

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 You have two issues across the repos, so I'm going to give some one else a chance.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by KshitijTodkar48** [comment]
@palisadoes I want to work on this. Can you assign me this issue?

**Comment by Veer0x1** [comment]
I would like to work on it.

**Comment by Sahil-Shadwal** [comment]
@palisadoes i didn't upgraded Graphql because it was already up to date . And sorry for the inactivity , i thought the issue was solved . It won't happen again.
![Screenshot 2024-01-07 180437](https://github.com/PalisadoesFoundation/talawa-api/assets/119167601/099834c7-92c0-4269-b5ca-9e53bf821ff4)

**Comment by palisadoes** [comment]
> @palisadoes i didn't upgraded Graphql because it was already up to date . And sorry for the inactivity , i thought the issue was solved . It won't happen again. ![Screenshot 2024-01-07 180437](https://private-user-images.githubusercontent.com/119167601/294758265-099834c7-92c0-4269-b5ca-9e53bf821ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDY5OTUsIm5iZiI6MTcwNDY0NjY5NSwicGF0aCI6Ii8xMTkxNjc2MDEvMjk0NzU4MjY1LTA5OTgzNGM3LTkyYzAtNDI2OS1iNWNhLTllNTNiZjgyMWZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNjU4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWE1YWFjYWYxMGJjMGNhY2UyZDgwM2FmMmQ3NmY3MmJhYmZiZWY5NTZmZjY3MzhjYjdhMDk2NmJjYWFhOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8xSco_DtgtbxuY3g2EeYf6ww7V4EyQAuGSzvtg2Z-98)

It's not up to date in the current `develop` branch in the repo.

**Comment by Sahil-Shadwal** [comment]
> > @palisadoes i didn't upgraded Graphql because it was already up to date . And sorry for the inactivity , i thought the issue was solved . It won't happen again. ![Screenshot 2024-01-07 180437](https://private-user-images.githubusercontent.com/119167601/294758265-099834c7-92c0-4269-b5ca-9e53bf821ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDY5OTUsIm5iZiI6MTcwNDY0NjY5NSwicGF0aCI6Ii8xMTkxNjc2MDEvMjk0NzU4MjY1LTA5OTgzNGM3LTkyYzAtNDI2OS1iNWNhLTllNTNiZjgyMWZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNjU4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWE1YWFjYWYxMGJjMGNhY2UyZDgwM2FmMmQ3NmY3MmJhYmZiZWY5NTZmZjY3MzhjYjdhMDk2NmJjYWFhOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8xSco_DtgtbxuY3g2EeYf6ww7V4EyQAuGSzvtg2Z-98)
> 
> It's not up to date in the current `develop` branch in the repo.

You mean develop_legacy right? cause develop is also up to date
![Screenshot 2024-01-08 004541](https://github.com/PalisadoesFoundation/talawa-api/assets/119167601/89ac1911-8246-4319-9d35-635e708258e3)

**Comment by palisadoes** [comment]
I was looking at the wrong section of the file. 
Closing
