### ISSUE TITLE
Create support for `Action Items`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1595]
**Is your feature request related to a problem? Please describe.**

We need the ability to assign people to Action Items that can be tied to: 

1. A person at an event
2. A person independent of an event
3. A person and a non-event

This would be used to create a simpler, more universal alternative to Event Project Tasks on which a wider range of services could be built.

**Describe the solution you'd like**

To implement this we’ll need an Action Item related collection with the following fields:

1. ID
2. Assigned To (UserID)
3. Assigned By (UserID)
4. Topic ID 
5. Notes Prior to Completion
6. Notes on Completion
7. Assignment Date
8. Due Date (Should default to a week upon creation)
9. Completion Date (Should default to a week upon creation)
10. Completed (True/False)
11. Event ID -  Null if not related to an event (Generic Checklist)
12. updatedBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
13. updatedAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
14. createdBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
15. createdAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542

You will need to create CRUD mutations and queries for these fields

The supporting Topic collection would have these fields:

1. ID
2. Topic - A subject area that would be of interest to the organization. (eg: Youth Group, Membership, Care etc.)
3. OrgID
4. Disabled/Enabled (True / False)
5. updatedBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
6. updatedAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
7. createdBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
8. createdAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542

You will need to create CRU (no deletions) mutations and queries for these fields. The organization may want to disable a Topic so that it is no longer selectable, but still visible for pre-existing Action Items.

It is very possible that Action Items could be used beyond Events, and Generic Checklists. For example, they could be used to track activities related to a venue. Designing some way to make an action item usable for other purposes would be very useful. This would mean that the EventID field would be replaced with something else. Think of ways that this could be implemented simply.

**Describe alternatives you've considered**

- Event Project Tasks (See above)

**Approach to be followed (optional)**
- See above

**Additional context**
1. This is a prerequisite for our menu of GSoC 2024 project ideas
1. This issue would be best handled by someone who already has experience with updating our schema, mutations etc or can prove it in other scenarios. 
1. Please work with @xoldyckk on the details of this issue and the subsequent PR

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
@palisadoes I would like to work on this.

**Comment by palisadoes** [comment]
> I'd love to try this... I haven't had experience with updating schemas and mutations for this project yet, but I'm familiar with mongoose and graphql, and I'd be eager to learn anything else that might be required.

How are you planning to link an Action item to the Event collection or any other type of future collection, or None?

**Comment by palisadoes** [comment]
@meetulr 

- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github%2Fworkflows%2Finspect.yml

There are two schema generators at the end of this GitHub action file. One of them exports markdown files that we commit to the Talawa Docs repo to create the Talawa website. It will have the information you require on how to document your schema code to make the markdown user friendly

**Comment by meetulr** [comment]
Thanks, let me get a better look at the schemas before proposing a solution.

**Comment by meetulr** [comment]
Ok, so here's my understanding of the issue:

We need more flexibility than the "Event Project Tasks", which are limited to a particular project of a particular event.
To address this, we create a "Topic", and an "ActionItem" collection.
Each organization could create different Topics they'd like to handle. Based on those, they could create different "Action Items", each action item could be assigned to a user.
Now the flexibility comes from the fact that an action item can be independent of an event. As mentioned in the issue:

1. A person at an event (a creator/admin/attendee of the event).
2. A person independent of an event (not a creator/admin/attendee of the event).
- In these two, the action item would be related to an event.

3. A person and a non-event (action not related to any event).
- This is for a more general topic.

Please tell me if I've misunderstood.
Thanks.

**Comment by palisadoes** [comment]
1. Yes, and we should assume there will quickly be multiple related collections. The design best needs to be flexible from the beginning. 
1. How will you most seamlessly ensure the two way relationship between any current or potential collection  and their related action items to facilitate bidirectional lookups?

**Comment by meetulr** [comment]
> 1. Yes, and we should assume there will quickly be multiple related collections. The design best needs to be flexible from the beginning.
> 2. How will you most seamlessly ensure the two way relationship between any current or potential collection  and their related action items to facilitate bidirectional lookups?

As I've mentioned, we could create two fields, one enum type for storing the name of the collection the action item refers to, which would initially just be "Event" (we could add more collection names to it later according to the requirement), and another would be the objectID of a document of that collection.

For querying the action items, the name of the collection and the id of the document(say, an event document) should be enough, but if we want a two way relationship, we could create an array of action items in those collection schemas, which would store the objectIDs of the action items associated to that collection document.

If it's an independent action item, both of those fields would just be null.

Please let me know if that'd be ok.

**Comment by palisadoes** [comment]
1. The array approach should be OK and should be implemented from the beginning.
1. @xoldyckk what do you think?

**Comment by palisadoes** [comment]
@meetulr 

1. I gave this some more thought. Assume only the events and non-events approach for the sake of simplicity and speed of implementation.
1. We can use the array approach if other necessary scenarios are discovered

**Comment by meetulr** [comment]
> @meetulr
> 
> 1. I gave this some more thought. Assume only the events and non-events approach for the sake of simplicity and speed of implementation.
> 2. We can use the array approach if other necessary scenarios are discovered

So, no two-way relationships?

**Comment by palisadoes** [comment]
> > @meetulr
> > 
> > 1. I gave this some more thought. Assume only the events and non-events approach for the sake of simplicity and speed of implementation.
> > 2. We can use the array approach if other necessary scenarios are discovered
> 
> So, no two-way relationships?

Two way relationships but just for events ("EventID" ) and non-events (where 2 way isn't required). The "concernedWith" approach can come later.

**Comment by meetulr** [comment]
Oh ok.

**Comment by palisadoes** [comment]
Action items access should be granted to org Admins, Super Admins, and whoever creates an event

**Comment by palisadoes** [comment]
If anything I've requested could be better handled from a sustainability, maintainability perspective, let me know.

I'm tracking lots of items this week and can get distracted

**Comment by meetulr** [comment]
Sorry about the delayed response. I have been familiarizing myself with the codebase and the established practices. I'll soon start with the schemas and database operations. I will not hesitate to raise any queries that arise and will share my insights on potential enhancements.

**Comment by meetulr** [comment]
So, I have a couple of doubts:
1. Would event creators have CRU access for Topic or just super admins and admins?
2. A topic can have multiple action items, right? (Like a task having multiple volunteers)
3. Could you provide more details about the purpose and usage of the ‘assignmentDate’ field? How does it differ from the ‘createdAt’ field? If there is a possibility of updating the ‘assignedTo’ field to a different user, then having an ‘assignmentDate’ field would make sense, as it would differ for the new assignee and would not be the same as the ‘createdAt’ date for that action item.

Please let me know.
Thanks.

**Comment by palisadoes** [comment]
1. Topics would only be managed by Admins and Super Admins
1. The initial assignment would match the creation date, but would change if the assignee were changed later.
1. Think of a topic as a category of action type.
1. Only one person per action item for ease of management for the Admin

**Comment by meetulr** [comment]
> 1. Topics would only be managed by Admins and Super Admins
> 2. The initial assignment would match the creation date, but would change if the assignee were changed later.
> 3. Think of a topic as a category of action type.
> 4. Only one person per action item for ease of management for the Admin

What I meant to ask about the Topic is that, since it would be unique to an Organization(the ordID field), while creating a new action item, we would have options of topics to choose from, right? And the "disabled" field here would make sense too, so that multiple action items can select the same topic (some collaborative work), like multiple volunteers for a task.
If there is to be a single action item for one topic, then having seperate models wouldn't make sense, we could just add the ordId field to the action item and the topic field could be just a string instead of a ref to a seperate model.

Let me know if I've misunderstood.

**Comment by meetulr** [comment]
> Correct to a point.
> 
> 1. Only one person assigned per action item
> 2. Multiple action items could be categorized with the same Topic. Topics would most likely be general categories of activity such as `Membership Drive`, `Youth Group` not a project, but ultimately that would be up to the organization. Rename `Topic` to `Category`. It'll be easier to explain to future contributors.
> 3. We should have at least one default Category to make Admins want to consider adding more or renaming it.

Regarding the 3rd point... by one default Category, do you mean on an organization creation?
If so, shall I add a category-organization two-way relationship too by making a new "categories" field in the organization? to store refs to different categories for that org, which would have one default(sample) category(say for "Membership Drive") added at the time of creation, and to which more could be added on later.

**Comment by meetulr** [comment]
How do we want to query the Categories? Individually, or by orgId, or both?

**Comment by palisadoes** [comment]
By both combined

**Comment by meetulr** [comment]
> > Correct to a point.
> > 
> > 1. Only one person assigned per action item
> > 2. Multiple action items could be categorized with the same Topic. Topics would most likely be general categories of activity such as `Membership Drive`, `Youth Group` not a project, but ultimately that would be up to the organization. Rename `Topic` to `Category`. It'll be easier to explain to future contributors.
> > 3. We should have at least one default Category to make Admins want to consider adding more or renaming it.
> 
> Regarding the 3rd point... by one default Category, do you mean on an organization creation? If so, shall I add a category-organization two-way relationship too by making a new "categories" field in the organization? to store refs to different categories for that org, which would have one default(sample) category(say for "Membership Drive") added at the time of creation, and to which more could be added on later.

What about this?

**Comment by palisadoes** [comment]
1. Yes, on organization creation we must add the default category. Make the default value "Default" as "Membership Drive" won't be universally relevant. 
2. The field name should reflect its relationship with Action Items or else people will think it's a categorization of the organization itself.
3. There may need to be bidirectional relationships depending on how the Admins may want to access the data for reporting purposes and editing. We should provide that from the beginning just in case.

**Comment by meetulr** [comment]
I'm done with all the queries and mutations. I'll move on to writing tests.
Shall I open a pr now or after everything's complete.

I know draft pr's are not allowed, but I'm just asking because there's much to review.
Please let me know.

**Comment by palisadoes** [comment]
Submit it all as a one. Tests usually don't get implemented if we split them as you suggest.

**Comment by palisadoes** [comment]
@meetulr

Be aware of this PR which will have a significant impact on yours. 

- https://github.com/PalisadoesFoundation/talawa-api/pull/1542

**Comment by meetulr** [comment]
> @meetulr
> 
> Be aware of this PR which will have a significant impact on yours.
> 
> * [Feature: Audit trail fields in Schema #1542](https://github.com/PalisadoesFoundation/talawa-api/pull/1542)

I see, so updatedBy is not required.
