### ISSUE TITLE
Organization doesn't have id of creator

### ISSUE THREAD

**Issue by Laurell876** [PalisadoesFoundation/talawa-api#160]
When created the company does not hold the _id of the creator which makes it inefficient to check whether the logged in user is the admin of organization or not

**Comment by Gautam-Arora24** [comment]
@Laurell876 I want to work on this issue. Can you please assign it to me?

**Comment by CyberWake** [comment]
@Laurell876 sir please assign this to me. I have taken the insights of the following issue. Remarked the same as well after making points on frontend requirement. I felt this as a issue while working on the same issue to fix the issue over there. Found that is requires some changes in talawa-api as well to have it a flawless one.

**Comment by CyberWake** [comment]
Would like to working on this one ☺️.

**Comment by Priyaraj17** [comment]
Is this issue still open? May I work on this?

**Comment by CyberWake** [comment]
the issue is resolved we may close this one @Laurell876 sir.

**Comment by CyberWake** [comment]
with the merge of the PR #162
