### ISSUE TITLE
Improve MongoDB configuration during setup

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1605]
**Is your feature request related to a problem? Please describe.**

The person installing Talawa API needs to know the MongoDB URL to use. This requires a manual process.

**Describe the solution you'd like**

1. The installation script should detect whether MongoDB is running on `localhost` and auto-populate the URL if one isn't already configured. The default database name would be `talawa-api`
2. This must work for both Docker and non-Docker installation methodologies

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship:
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RAGHAV-N5** [comment]
I want to work on this issue. Please assign me.

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by pateldivyesh1323** [comment]
Hello @Cioppolo14 I already have two issues assigned currently. Sorry I should have deleted the comment after I got assigned to reduce confusion.

**Comment by Cioppolo14** [comment]
@pateldivyesh1323 Thank you for your honesty! I try to check but missed this.

**Comment by Aaditya-G** [comment]
I would like to work on this

**Comment by vasujain275** [comment]
Hi @Aaditya-G,

I've implemented the Docker installation section. Please note that the validation of the MongoDB URL cannot be performed when the user selects the Docker installation option. In the setup.ts file, you should verify whether the user has opted for Docker installation. If so, you need to hardcode the MongoDB URL as follows: `mongodb://localhost:27017/talawa-api`, no need to ask user for it. Here is an example code snippet for this:


```ts
const { isDockerInstallation } = await inquirer.prompt({
    type: "confirm",
    name: "isDockerInstallation",
    message: "Are you setting up this project using Docker?",
    default: false,
  });

  
  if (isDockerInstallation) {
    const DB_URL = "mongodb://localhost:27017/talawa-api";
    const config = dotenv.parse(fs.readFileSync(".env"));
    
    config.MONGO_DB_URL = DB_URL;
    process.env.MONGO_DB_URL = DB_URL;
    fs.writeFileSync(".env", "");
    for (const key in config) {
      fs.appendFileSync(".env", `${key}=${config[key]}\n`);
    }
    console.log(`Your MongoDB URL is:\n${process.env.MONGO_DB_URL}`);
  }
```

**Comment by vasujain275** [comment]
@Aaditya-G are you still working on this? If not, @Cioppolo14 @noman2002 can I work on this as this feature is required for working of Docker Installation properly.

**Comment by Aaditya-G** [comment]
you can go ahead
