### ISSUE TITLE
Improving Code Coverage of the Project.

### ISSUE THREAD

**Issue by git-init-priyanshu** [PalisadoesFoundation/talawa-api#1609]
**Is your feature request related to a problem? Please describe.**
Improving code coverage of the project.

**Describe the solution you'd like**
Improving code coverage.

**Describe alternatives you've considered**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by git-init-priyanshu** [comment]
I would like to work on this issue. I have my PR ready.

**Comment by palisadoes** [comment]
We should already have issues created for these.
Closing

**Comment by palisadoes** [comment]
We should already have issues created for these.
Closing

PRs were created and merged for these files. Please check for duplicates before creating issues.
Please be aware of the overhead of checking dozens of issues each day. Please do better research.

**Comment by git-init-priyanshu** [comment]
You are right sir. PR has already been submitted for these files. But right now the code coverage of these files is not 100%. That's why I thought of making a PR.

**Comment by palisadoes** [comment]
- Please focus on the remainder of these files the next time. They will cause the greatest improvement in our overall coverage.
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/c4f77f34-efba-4c4d-a3dd-9a7cb68d4c51)

**Comment by git-init-priyanshu** [comment]
hey @palisadoes, should I create different PRs for each test file, or should I create a single PR?
