### ISSUE TITLE
Add support to change pre-login imagery

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1611]
**Is your feature request related to a problem? Please describe.**
1. Communities need the ability to change the social media icons and logo images upon login.
1. We don't want users thinking that they are always logging into Palisadoes

**Describe the solution you'd like**
1. `Talawa-API`
    1. You will need to create a new collection specifically meant to store the customizations listed below
    1. You will need to write valid tests for your code
    1. No other functionality must be affected
1. `Talawa-Admin`
    1. Our login screen is not specific to organizations, so we'll need to make this change at the Community level.
    1. This will require the creation of a Community Profile button at the Super Admin level which would lead to a Community Profile edit screen
    1. This screen must be designed in keeping with our Talawa Admin Figma design found here
        1. https://docs.talawa.io/docs/design/ux/ux-design-system
    1. The logo and social media icons to be edited are visible in the attached screen shots
    1. By default, when the Palisadoes Logo is changed, the Palisadoes specific social icons should disappear so that the Community can add theirs. If the Logo is left blank, then the Palisadoes imagery should return, but the database parameters must remain so that the Admin doesn't have to re-enter the information.
    1. This will require the creation of a new collection in the API
    1. Please work with @aashimawadhwa and @rishav-jha-mech on the design approval before submitting a PR

**Related Issues**
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1334
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1611

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1. Images that should be editable: 
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/0347a075-e9f5-4117-8816-a9aab27e99d5)
1. Location of the Community Profile
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/76b8b87b-87d0-4178-97c8-e6c82911a399)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
@palisadoes
Can I work on this issue?

**Comment by palisadoes** [comment]
You'll need to get the requirements from the person assigned this issue. It cannot be worked on in a vacuum
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1334

**Comment by gauravsingh94** [comment]
Please review this  `Community Profile Section` design.

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/99260988/8219ef07-d2b2-43b1-a959-e53b15f0aeb4)




Do i need to add anythings more?

Once the design is approved. I will instruct @chandel-aman to create the routes for storing the logo, description and social icons. 
Afterword, I will integrate these elements into the webpage.

**Comment by gauravsingh94** [comment]
video

[Screencast from 2024-01-01 22-45-54.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/99260988/ecef78a4-eb60-4010-91d4-90d6e9775fe7)

**Comment by chandel-aman** [comment]
> You'll need to get the requirements from the person assigned this issue. It cannot be worked on in a vacuum

Got it, thanks! I'll get the requirements from the person assigned the issue in talawa-admin. Once I have the details, I'll start working on the issue.
Please let me know if you have any specific points in mind.

**Comment by jayantpranjal0** [comment]
Can I work on this issue ??

**Comment by Cioppolo14** [comment]
@chandel-aman Are you working on this?

**Comment by chandel-aman** [comment]
@Cioppolo14 Yes, I'm working on it. I'll be making the PR sometime soon.

**Comment by Cioppolo14** [comment]
@chandel-aman When will a PR be ready?

**Comment by rohansx** [comment]
Hi @chandel-aman , @Cioppolo14 

I noticed that it's taking a bit longer than expected. I understand that challenges can arise in the course of development, and it's completely normal.

@chandel-aman, if you're encountering any difficulties or roadblocks with this task, I'd be more than happy to lend a hand or take over if needed. My goal is to contribute positively to the project and ensure timely progress.

Please feel free to let me know how I can assist. Thanks for your hard work on this!

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by rohansx** [comment]
@palisadoes @Cioppolo14 would love to take on this issue and complete within a week

**Comment by palisadoes** [comment]
1. Please create a PR when ready
2. Coordinate with the person assigned this issue
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1334

**Comment by chandel-aman** [comment]
@palisadoes @Cioppolo14 
I understand that I was unassigned from this issue due to inactivity, and I apologize for not being able to complete it earlier. I had some health issues that prevented me from working. However, I would like to take ownership of this issue again as I have already implemented it. Could you please reassign it to me? Thank you for your understanding.

**Comment by palisadoes** [comment]
@chandel-aman 

When do you plan to submit a PR? This issue has been open for two months with no resolution. We really need something submitted within the next day. We may have to unassign this again otherwise. It's holding up the PR from @git-init-priyanshu 

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1649

**Comment by chandel-aman** [comment]
@palisadoes
I apologize for the delay. I understand the urgency and will ensure to submit the PR by tomorrow. Thank you for your patience.
