### ISSUE TITLE
API - Deprecate the Project / Task Feature

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1617]
**Is your feature request related to a problem? Please describe.**

To simplify the UI/UX we have decided to deprecate the Project / Task feature for Events. This means that all support for this feature must be removed from:

1. Talawa Admin
1. Talawa API
1. Talawa Mobile

**Describe the solution you'd like**

This includes removing all of the following related `Talawa-API` items:

1. Underlying code related to the specific support of this feature
1. Any testing code specific to this feature

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**

1. This is a prerequisite for our menu of GSoC 2024 project ideas
1. All other features and testing methodologies must remain unchanged
1. Changes must be limited to this repository
1. You may have to coordinate with the assignees for these issues:
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1346
    2. https://github.com/PalisadoesFoundation/talawa/issues/2296
    3. https://github.com/PalisadoesFoundation/talawa-api/issues/1617

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359
https://github.com/PalisadoesFoundation/talawa/issues/2296

**Comment by NamitBhutani** [comment]
Could I please work on this issue?

**Comment by wingman47** [comment]
can i work on this issue?

**Comment by NamitBhutani** [comment]
I am done with the issue - but currently I have commented out all of the code related to Project/Task features; should I rather delete the code/files ?

**Comment by palisadoes** [comment]
1. We should have no reference to the code. Remove it completely.
2. Please open a PR when ready
