### ISSUE TITLE
Inconsistencies and Errors in Handling Commented or Removed Parameters in .env File

### ISSUE THREAD

**Issue by Doraemon012** [PalisadoesFoundation/talawa-api#1624]
**Describe the bug**

Unexpected behavior occurs in the setup when modifying or removing parameters in the `.env` file, resulting in setup failure and complications with the handling of commented and removed parameters and as well as with non-existent `.env` file.

**To Reproduce**

1. Comment out a parameter in the `.env` file using `#`.
2. Remove a parameter completely from the configuration.
3. Delete the `.env` file

**Expected behavior**

The `setup script` encounters issues when handling `commented` or `removed parameters`, leading to errors. Key points include:
- No errors when removing a parameter.
- Preservation of comments in the `.env` file.
- Automatic creation of the `.env` file if it doesn't exist.

**Actual behavior**

- The setup script dose not preserve comments.
- The setup fails when handling removed parameters in the `.env` file. 
- User is prompted to `copy the contents from .env.sample` if the `.env` file is missing or some of the parameters are missing from the file.

**Comment by Doraemon012** [comment]
@palisadoes, please assign this to me.

**Comment by Cioppolo14** [comment]
@Doraemon012 Thank you for documenting this issue. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Sauradip07** [comment]
Can i work on this issue?

**Comment by shreyashidabral** [comment]
@Doraemon012 please assign this issue to me, I would like to work on it

**Comment by Cioppolo14** [comment]
@Doraemon012 I am going to close this issue, but please include the fix to this issue in the issue #1625.  Please, when you make an issue and have similar items, include them in one issue. This method supports our volunteers' time and minimizes extra work.  Thank you!
