### ISSUE TITLE
Issues with RECAPTCHA Keys and Duplicate Congratulations Message

### ISSUE THREAD

**Issue by Doraemon012** [PalisadoesFoundation/talawa-api#1625]
**Describe the bug**
When entering a `RECAPTCHA_SECRET_KEY` value, the `RECAPTCHA_SITE_KEY` is not mandatory. Additionally, the `Congratulations message` is occasionally duplicated

**To Reproduce**

For `RECAPTCHA_SECRET_KEY`:
1. Enter a value for `RECAPTCHA_SECRET_KEY`.
2. Get a prompt to `Would you like to set up a reCAPTCHA site key?`

For `Congratulations message`:
1. Observe the behavior of the Congratulations message.

**Expected behavior**

- `RECAPTCHA_SITE_KEY` must be mandatory when `RECAPTCHA_SECRET_KEY` is provided.
- No duplication of the Congratulations message.

**Actual behavior**

- Failure to enforce the mandatory nature of `RECAPTCHA_SITE_KEY ` when `RECAPTCHA_SECRET_KEY` is present.
- Occasional duplication of the Congratulations message.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Doraemon012** [comment]
@palisadoes, Please assign this to me.

**Comment by Cioppolo14** [comment]
@Doraemon012 Thank you for documenting this issue. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by aabbi15** [comment]
Can you assign this to me?

**Comment by Doraemon012** [comment]
@Cioppolo14 @palisadoes I have only one issue assigned to me. Please assign this to me, I've already been working on this and the code is ready.

**Comment by aabbi15** [comment]
I had a question. If only one of the RECAPTCHA_SECRET_KEY or RECAPTCHA_SITE_KEY exists(which would be not really ideal) Should we give the option to setup both of them once again from scratch or only the one that is missing?
