### ISSUE TITLE
[Bug]: Post images not loading due to same-origin policy

### ISSUE THREAD

**Issue by wingman47** [PalisadoesFoundation/talawa-api#1626]
**Describe the bug**
Image inside the post doesn't render because same-origin policy in server blocks access to image stored inside the images folder on the server.

**To Reproduce**

1. Go to manage organization.
2. Create a post with an image.
3. Reload the page.

**Expected behavior**
Posts along with the image should render.

**Actual behavior**
Images are saved in the database and the backend server but they don't render on the frontend.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/49762303/11f4e3d7-9e11-416a-9bb5-e522d8b44d9d)

**Comment by wingman47** [comment]
Can i work on this issue?

**Comment by Sejal1411** [comment]
Would love to work on this issue!
please assign it to me
