### ISSUE TITLE
Enhance Clarity of Sample Data Import Instructions for Docker Setup in Talawa API Installation

### ISSUE THREAD

**Issue by harshpreet14** [PalisadoesFoundation/talawa-api#1639]
**Describe the issue**
Improve the instructions to import sample data via docker installation. 

**To Reproduce**
1.  Navigate to  ‘Importing Sample Database’ in Installation.md and notice that the instructions to import the sample database are not clear. 
<img width="681" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/114172812/cdbbf1a7-35cb-4b31-aa4c-e37d2b61d050">

<img width="679" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/114172812/d8822752-bd85-4967-b6cd-389bce93419a">

**Steps to solve the bug**
1. To run `npm run import:sample-data -- [args]`, you need to execute it within the container that has your Talawa API application and Node.js environment.
2. Run the command `docker ps` on your host terminal to list all running containers and find the correct container.
4. Run the docker exec command to access its shell - `docker exec -it <container_id> /bin/sh`. Here, the container id is that of 'talawa-api-talawa-api-container-1`.
5.Once you're inside the container, you should be in the root directory where the package.json file for the Talawa API is located. 
6. Now, run the import command: `npm run import:sample-data -- [args]`

**Screenshots**
<img width="827" alt="Screenshot 2024-01-05 224429" src="https://github.com/PalisadoesFoundation/talawa-api/assets/114172812/a22411b8-a816-425f-845b-345f960a3909">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by vasujain275** [comment]
@harshpreet14 This is a bug that can be simply fixed by adding the mongo url to .env during setup process. by adding something like this to setup.ts  - 

```ts
const { isDockerInstallation } = await inquirer.prompt({
    type: "confirm",
    name: "isDockerInstallation",
    message: "Are you setting up this project using Docker?",
    default: false,
  });

  
  if (isDockerInstallation) {
    const DB_URL = "mongodb://localhost:27017/talawa-api";
    const config = dotenv.parse(fs.readFileSync(".env"));
    
    config.MONGO_DB_URL = DB_URL;
    process.env.MONGO_DB_URL = DB_URL;
    fs.writeFileSync(".env", "");
    for (const key in config) {
      fs.appendFileSync(".env", `${key}=${config[key]}\n`);
    }
    console.log(`Your MongoDB URL is:\n${process.env.MONGO_DB_URL}`);
  }
```

I am currently working on this here - https://github.com/PalisadoesFoundation/talawa-api/issues/1605

**Comment by Cioppolo14** [comment]
@vasujain275 Are you saying that your issue resolves this one and I can close it as a duplicate?

**Comment by vasujain275** [comment]
> @vasujain275 Are you saying that your issue resolves this one and I can close it as a duplicate? 

No, this is a separate issue. I wasn't able to work on it for a few days because I was unwell. I will resolve this issue and raise pr for it in 1-2 days.

**Comment by vasujain275** [comment]
@Cioppolo14 Sorry for my miscommunication from my side, This issue is a **duplicate**  of issue https://github.com/PalisadoesFoundation/talawa-api/issues/1605. Please close it. Sorry again

**Comment by Cioppolo14** [comment]
Closing as a duplicate.
