### ISSUE TITLE
API - Add support for event venues

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1640]
**Is your feature request related to a problem? Please describe.**

We need the ability to add API functionality to assign a venue to an event. Currently you can assign geographic coordinates, but you cannot also provide one of a list of pre-defined venues (eg. "Conference Room", "Sports Field" or "Theater") This would be a useful capability to add.

**Describe the solution you'd like**

The aim would be for Admins to do CRU activities (no deletions, but disabling/enabling) for venues on an Org screen, and for these venues to appear as options whenever events are scheduled.

The API must be able to:

1. determine whether the venue is already allocated during all or some part of the proposed event timeslot when the event is being created and not make it appear as an option.
    1. if there are no venues configured, or no available venues, then the returned result be meaningful and the app must not crash
2. reject the creation of an event if the requested location is unavailable
3. return an availability status for a selected venue for a given timeslot that could be used whenever the event timing is adjusted.

Other

1. We will also need the ability to set the maximum capacity of the venue in terms of user checkins. This will help with events that require pre-registration
1. Venues can often be reconfigured to have less or more seating. This means that there will need to be the ability to override the checkin limit on a per event basis.

The schema must include support for:

1. Venue ID
2. Venue name
3. Venue description 

This issue should be split into multiple PRs for ease of review:

1. Venue CRUD
2. Adding a venue to a single Event
3. Verifying the venue isn't already used for a single event
4. Managing event checkins for venue capacity
5. Adding the venues to recurring events

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

Related issues:
- https://github.com/PalisadoesFoundation/talawa-api/issues/1640
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1390

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by wingman47** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
1. We will also need the ability to set the maximum capacity of the venue in terms of user checkins. This will help with events that require pre-registration
1. Venues can often be reconfigured to have less or more seating. This means that there will need to be the ability to override the checkin limit on a per event basis.

**Comment by wingman47** [comment]
@palisadoes ok, so i will create a new model for venue and include that in the events schema.

**Comment by meetulr** [comment]
@wingman47 please update me on the schemas you'll be making, as I would be working on the frontend for this [issue](https://github.com/PalisadoesFoundation/talawa-admin/issues/1390).

**Comment by wingman47** [comment]
> @wingman47 please update me on the schemas you'll be making, as I would be working on the frontend for this [issue](https://github.com/PalisadoesFoundation/talawa-admin/issues/1390).

I have done the following changes in the schemas for now -

Created a new venue schema which contains id, name, description and capacity of the venue. 

Added an array of venues as objects that are available in an organisation in Organisation schema.

Added venue property as an object in event schema.

**Comment by wingman47** [comment]
Hey @palisadoes, how to handle events that are recurring because the start and end dates can change based on whether it's a 'ONCE,' 'DAILY,' 'WEEKLY,' 'MONTHLY,' or 'YEARLY' thing. So, every time I want to check if the venue's free, I've got to recalculate the new start and end date while considering stuff like days in a month (which itself varies), leap years etc. for every recurrances.  Any suggestion to handle this situation?

**Comment by wingman47** [comment]
@palisadoes @Cioppolo14 are there any plans to implement recurring events? because right now events can only be set to once. There's no option to change it. If there would be recurring events then it would be very difficult to managing venue for multiple recurring events with same location.

**Comment by palisadoes** [comment]
Please refer to this PR. We will need to implement this in the Web UI soon after merging
- https://github.com/PalisadoesFoundation/talawa-api/pull/1658

**Comment by meetulr** [comment]
Do we currently a direct way to know the number of check-ins for an event, if not, we should add a field in the event schema that stores that, which could be incremented every time an attendee checks in.
This way we won't have to make a separate query to find the number of check-ins to check against the venue capacity.

**Comment by palisadoes** [comment]
Yes, that would be useful

**Comment by wingman47** [comment]
@palisadoes I am unassigning myself because the current implementation of event dates can vary too much. I am facing these problems for which I am unable to find any solutions:

**Comment by wingman47** [comment]
@palisadoes I am unassigning myself because current implementation for events have too many variables. I am facing these challenges which I am unable to solve:
Events start date and end date can have a difference of any number of days with any type of recurrance therefore it involves many different situations to handle venues availability. On top of that we also need to take care of start time and end time which makes the whole situation very complex to solve.

**Comment by meetulr** [comment]
Might I give it a try? It could take a couple days to understand the whole recurrence situation, and coming up with an effective strategy.

**Comment by palisadoes** [comment]
@wingman47

1. You don't need to incorporate recurring meetings.
2. That is the job of another contributor. 
3. Make this work for a single event and let the other contributors figure out how to incorporate your changes in a recurring event.
4. I'll reassign you

**Comment by wingman47** [comment]
> @wingman47
> 
> 1. You don't need to incorporate recurring meetings.
> 2. That is the job of another contributor. 
> 3. Make this work for a single event and let the other contributors figure out how to incorporate your changes in a recurring event.
> 4. I'll reassign you

Ok, so i will complete it for single events. Thank you.

**Comment by meetulr** [comment]
![Screenshot (10)](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/de67fbd5-528b-4b24-9169-01fac3440f42)
@wingman47 let me know when you're done with these.

**Comment by wingman47** [comment]
> ![Screenshot (10)](https://private-user-images.githubusercontent.com/55585268/295785619-de67fbd5-528b-4b24-9169-01fac3440f42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjQzMzEsIm5iZiI6MTcwNDk2NDAzMSwicGF0aCI6Ii81NTU4NTI2OC8yOTU3ODU2MTktZGU2N2ZiZDUtNTI4Yi00YjI0LTkxNjktMDFmYWMzNDQwZjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA5MDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2FiY2Q0NTFkZjA3NmVhNmI1ZTVlMjk4NWJkZWJhMjlhOTA2MGRkYWNjN2Q2ZDcxNDJmNTJjZmQ5OTQ4N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQ4NKDUgsZ7gyqdRvV2h8HRYCSZaE7bufcQYnhNwmY0) @wingman47 let me know when you're done with these.
> 
> Also, I think it'd be better if you keep pushing the incremental changes to your fork, so that I can add it as a remote and work with it on the frontend on the go. What do you think?

Will let you know. For now, I have pushed my changes to event-venue branch.

**Comment by meetulr** [comment]
@palisadoes Are we going to have images for venues?

**Comment by meetulr** [comment]
@wingman47 You've restricted the mutations to (role: ADMIN).
SUPERADMINs should be able to do anything, right?

Could you clear as to who would have the access?
I'm under the impression that SUPERADMINS and the current organization's ADMINs (not just any admin) should be allowed.

Let me know if I'm wrong😅.
Thanks.

**Comment by wingman47** [comment]
> @wingman47 You've restricted the mutations to (role: ADMIN). SUPERADMINs should be able to do anything, right?
> 
> Could you clarify who would have access? I'm under the impression that SUPERADMINs and the current organization's ADMINs (not just any admin) should be allowed.
> 
> Let me know if I'm wrong😅. Thanks.

My bad. You are correct. I have fixed it now. Thanks👍

**Comment by palisadoes** [comment]
@wingman47 

1. Adding support for a single venue image would be useful
2. Venues will often have addresses, so we should add that to the schema for venues

Open a PR when ready.

**Comment by wingman47** [comment]
> @wingman47
> 
> 1. Adding support for a single venue image would be useful
> 2. Venues will often have addresses, so we should add that to the schema for venues
> 
> Open a PR when ready.

Will add both of them to the schema. I was writing tests for the new features I have added as of now.

**Comment by palisadoes** [comment]
See the updated comment about venues being a limited list

**Comment by palisadoes** [comment]
An event's venue must be optional

**Comment by wingman47** [comment]
> See the updated comment about venues being a limited list

The maximum venues allowed in an organization should be defined by us (like 5 -6 venues) or will it be editable by the admin of the organization?

**Comment by palisadoes** [comment]
Admins will be able to add as many venues as they want. It's unlikely that there will be large numbers.

**Comment by wingman47** [comment]
> Admins will be able to add as many venues as they want. It's unlikely that there will be large numbers.

As of now, only admins of an organisation can create a new venue and a user can only select the venues added by the admins when creating an event. 
Should I open the ability to create a new venue for normal users of an organisation as well?

**Comment by palisadoes** [comment]
> > Admins will be able to add as many venues as they want. It's unlikely that there will be large numbers.
> 
> As of now, only admins of an organisation can create a new venue and a user can only select the venues added by the admins when creating an event. Should I open the ability to create a new venue for normal users of an organisation as well?

No. Then there could be be infinite entries.

**Comment by meetulr** [comment]
@wingman47 are the queries done yet?

**Comment by wingman47** [comment]
> @wingman47 are the queries done yet? Specifically the one that, given event start and end dates, start and end times, returns an array of available venues.

I will push it by tonight.

**Comment by meetulr** [comment]
> Do we currently have a direct way of knowing the number of check-ins for an event? If not, we should add a field in the event schema that represents that, which could be incremented every time an attendee checks in. This way we won't have to make a separate query to find the number of check-ins to check against the venue capacity.

@wingman47 please add this.

**Comment by palisadoes** [comment]
@meetulr @wingman47 

An event check-in count is not necessary. Check-in counts will be tracked here:

- https://github.com/PalisadoesFoundation/talawa-api/issues/1644

Please revert. You will be duplicating efforts. Talk to the person assigned this issue instead.

**Comment by wingman47** [comment]
> @meetulr @wingman47
> 
> An event check-in count is not necessary. Check-in counts will be tracked here:
> 
> * [Add Support for Event Invitees and Registrants #1644](https://github.com/PalisadoesFoundation/talawa-api/issues/1644)
> 
> Please revert. You will be duplicating efforts. Talk to the person assigned this issue instead.

Ok, I will revert the checkIn part. Should I keep the declination of any new request in addEventAttendee after the event's venue capacity is reached?

**Comment by palisadoes** [comment]
Yes, thanks
