### ISSUE TITLE
Add Support for Event Invitees and Registrants

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1644]
**Is your feature request related to a problem? Please describe.**

We need the ability to track users who:

1. Are invited to events
2. Register for events

This is important for venue management where there may be limited seating and registration is required.

**Describe the solution you'd like**

We need `[User!]` type fields added to the Event collection with the following names:

1. `invitedUsers`
2. `registeredUsers`

Other:

1. You will be required to write tests for the expected CRUD activities related to these new users being tracked.
1. The tests must include verification of the users added to the following lists:
    1. `attendees` (This testing may not have been done)
    1. `invitedUsers`
    1. `registeredUsers`

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

The current screen shot of the `develop` branch's schema

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/a1e36c95-e66e-4060-9612-42c4abf5bb98)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by shreyashidabral** [comment]
Please assign me this issue

**Comment by Dante291** [comment]
@palisadoes also how are we differentiating invitees from attendees? Users who are checked In are basically Invited Users right? If yes then there should be a proper logic implemented for this in backend side only. 

If no user is checked In by the admin of the Event then Invited Users should be zero. Similarly there should be a logic for attendees too.

**Comment by Dante291** [comment]
@palisadoes There should be a flag `hasAttended` for checked In users to identify whether they have attended the event or not.

**Comment by palisadoes** [comment]
1. You may invite people to register for an event
1. You may invite people to an event but registrations are not required
1. If you physically turn up for the event then you are an attendee. Attendees may or may not be invited or registered, such as a sports day.

**Comment by palisadoes** [comment]
Are you proposing a list of some objects that include:

1. User
1. Invited flag
1. Attended flag
1. Registered flag

**Comment by palisadoes** [comment]
@shreyashidabral What approach would you suggest?

**Comment by Dante291** [comment]
> Are you proposing a list of some objects that include:
> 
> 1. User
> 2. Invited flag
> 3. Attended flag
> 4. Registered flag

@palisadoes Could you please give more clarification on what does `checkIn` flag do? It differentiates users who have registered and who are invited to attend the event right? 

For an event where registration is not required then Registered and Invited fields wouldn't matter but only the attendees (This will also matter if Event creator have to record who attended the event) but in the case of Event where registration is required we do need these flags in order to identify users who have registered, who are invited, and who have attended. 

What are your views about it.

**Comment by shreyashidabral** [comment]
I think we can have flags
Invited Flag: This flag denotes users who have been formally invited to an event. This flag can be set when an invitation is extended to a user, irrespective of whether registration is required.
Registered Flag: For events that require registration, this flag indicates users who have completed the registration process.
Attended Flag: This flag signifies users who physically attended the event, regardless of whether they were invited or registered.

Users who physically attend can be marked as attendees, even if they weren't invited or registered. This can be the default behavior for events where attendance is open 

I need clarity on the check-in part though, does it have users who are invited only by the admin and do not require registration or we can mark the "Attended flag" for the respective users after check-in by the admin is done

**Comment by palisadoes** [comment]
1. The intention was for persons attending an event to be checked in using the app as a verification of user attendance with a timestamp. It also attempts to track whether the user left feedback using the app.
    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/7e16978d-10a8-48a4-bb3f-7064f058395e)
1. Now that we have an issue created for venues we can deprecate the `allottedRoom` and `allottedSeat`. 
1. Revisiting the schema we are effectively tracking attendance twice using the fields below. When we could just use `attendeesCheckInStatus`
    1. `attendance` and,
    2. `attendeesCheckInStatus`
    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/8b7157de-077c-4078-92ff-bfcb78db2687)

**Comment by palisadoes** [comment]
Thanks @shreyashidabral 

I've explained the check-in process above. The only way to update attendance is for the User to be checked-in. The expectation is that in these cases there will be:

1. Someone at the door of the event running Talawa on a tablet
2. Greeting people coming to the event
3. Doing check-ins via the tablet to note User attendance

**Comment by palisadoes** [comment]
We need to figure this out now as it will have an impact on follow up issues we will eventually create.

@noman2002 @rishav-jha-mech @aashimawadhwa This should interest you.

**Comment by palisadoes** [comment]
@shreyashidabral Is it clear now?

**Comment by shreyashidabral** [comment]
Yes, I understood that any user will be added as an attendee when the check-in is done by the Talawa app at the event.

So to track invitedUsers and registeredUsers, should we go with the approach defined above - by setting boundaries on who will be added to invited, registered and attendees.

**Comment by palisadoes** [comment]
@shreyashidabral 

Yes, as long as you can accommodate the following:

1. You may invite people to register for an `Event` as registrations are required
1. You may invite people to an `Event` but registrations are not required
1. If you physically turn up for the `Event` then you are an attendee. Attendees may or may not be invited or registered, such as a sports day.
1. You can only check-in to an `Event` requiring registration if you are registered

This means `Event` will also need a `registrationRequired` flag

Do you or @Dante291 have any further concerns with this approach?

Other:

- You will need to create issues in Talawa and Talawa Admin for Events to reflect this new approach as soon as you submit your PR so that work to reduce the risk of the crashes.

**Comment by Dante291** [comment]
> @shreyashidabral
> 
> Yes, as long as you can accommodate the following:
> 
> 1. You may invite people to register for an `Event` as registrations are required
> 2. You may invite people to an `Event` but registrations are not required
> 3. If you physically turn up for the `Event` then you are an attendee. Attendees may or may not be invited or registered, such as a sports day.
> 4. You can only check-in to an `Event` requiring registration if you are registered
> 
> This means `Event` will also need a `registrationRequired` flag
> 
> Do you or @Dante291 have any further concerns with this approach?
> 
> Other:
> 
> * You will need to create issues in Talawa and Talawa Admin for Events to reflect this new approach as soon as you submit your PR so that work to reduce the risk of the crashes.

@palisadoes Thanks for the clarification it really helped, about `registrationRequired` flag we already have `isRegistrable` flag in order to identify if event is registrable or not, so is there really any need for `registrationRequired` flag as it would be doing somewhat same task as `isRegistrable` flag?

@shreyashidabral You don't have to worry about Talawa-mobile as I have made issue for this in Talawa-mobile repo and I'm assigned to it, do update me when you'll be done with your PR and it gets merged to the codebase though, but you need to make issue in admin repo for this.

**Comment by palisadoes** [comment]
I didn't notice that, `isRegistrable` is OK

**Comment by Dante291** [comment]
https://github.com/PalisadoesFoundation/talawa/issues/2309

**Comment by palisadoes** [comment]
@shreyashidabral 

Please remove the alotted room and seat fields as part of this PR. I don't think they are used. Check the mobile and admin code bases first

**Comment by shreyashidabral** [comment]
Okay I'll remove them if they're not being used

**Comment by Dante291** [comment]
@shreyashidabral Currently  `registrantsByEvent(id: ID!): [User] ` this query is being used to fetch registrants in Talawa-mobile (There is no such query in Admin as we are basically displaying info of attendees as registrants there which need to be fixed when you will fix this issue). There will be no use of this query as you will modify Event model to fetch registrants' info by FetchOrgEvents query only, so you could remove this too.

**Comment by palisadoes** [comment]
Open a PR when ready

**Comment by shreyashidabral** [comment]
@Dante291 thankyou for letting me know 
@palisadoes I'm on it, I'll open the pr when ready

**Comment by shreyashidabral** [comment]
@palisadoes 

This is the mock schema that I am thinking of creating to track invited, registered, and checked-in users

type UserEventStatus {
  _id: ID!
  user: User!
  isInvited: Boolean!
  isRegistered: Boolean!
  isCheckedIn: Boolean!
  checkInInfo: CheckIn
}

with this we can remove `attendees` & `attendeesCheckInStatus` from event schema

and it would be like this 
<img width="232" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/97970381/b28e00de-23ac-485a-a2fe-1f5c72ec0312">

Please let me know your views if I'm proceeding in the right direction

**Comment by palisadoes** [comment]
1. Yes, this looks OK to me.
2. Please proceed and clean up any of the unused Checkin types

**Comment by palisadoes** [comment]
Open a PR when ready

**Comment by shreyashidabral** [comment]
@palisadoes 
I'll not be able to work on it due to some time constraints. Please unassign me from this issue, so someone else take take over this.

**Comment by aialok** [comment]
Can I work on this issue?

**Comment by meetulr** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
@aialok How is work progressing?

**Comment by aialok** [comment]
Hey @palisadoes,

While exploring the codebase, I came up with a slight alternative solution to our earlier discussion. Instead of introducing a new `userEventStatus` schema with boolean fields, I suggest enhancing the existing `EventAttendee` schema by adding a new field named `attendeeStatus`. This field will have an enum of `"INVITED"`, `"REGISTERED"` and `"ATTENDED".`
```js
attendeeStatus: {
    type: String,
    required: true,
    enum: ["INVITED", "REGISTERED", "ATTENDED"],
    default: "INVITED",
},
```

![Screenshot from 2024-01-20 23-16-37](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/0e71057c-ebb5-4924-b015-17529f0a19b6)

Why this approach?

Upon inspecting the talawa-admin codebase, I noticed that we were originally tracking event registrants using the `EventAttendee` schema alone. By introducing this new field, we can conveniently manage event registrants. How?

In the talawa-api, we have mutations within `eventAttendeeMutations`.

![Screenshot from 2024-01-20 23-51-52](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/2a86eb16-77be-43fb-96e9-080ee1508dcb)

With the added enum, we can seamlessly track `attendeeStatus` while creating the `EventAttendee` itself. If a user is initially invited and registers then for the event, we can easily update the `attendeeStatus` to "REGISTERED". If a user attends the event directly, we can set the attendeeStatus to "ATTENDED".

```js 
 await EventAttendee.create({
    userId: context.userId,
    eventId: args.id,
    attendeeStatus : "INVITED" // "REGISTRED" , "ATTENDED"
  });
```




And about the `checkIn` when user will checkIn to the event, we can update the `attendeeStatus` to `ATTENDED`.

This approach not only saves storage but also avoids the creation of unnecessary new Schema.

**Comment by palisadoes** [comment]
Will this allow us to easily add future capabilities such as:

1. Calculating historic invitation to attendance rates?
2. Calculating historic invitation to registration conversion rates?
2. Calculating historic registration to attendance conversion rates?

Administrators will want to know to see how effective their efforts are.

How can we create a solution that will satisfy these needs based on this most recent and past proposals?

**Comment by aialok** [comment]
> Will this allow us to easily add future capabilities such as:
> 
> 1. Calculating historic invitation to attendance rates?
> 2. Calculating historic invitation to registration conversion rates?
> 3. Calculating historic registration to attendance conversion rates?
> 
> Administrators will want to know to see how effective their efforts are.
> 
> How can we create a solution that will satisfy these needs based on this most recent and past proposals?


Well, if we want to incorporate the functionalities mentioned above, it's better to stick with the first approach. Creating a separate schema with flags will assist us in easily tracking the conversion rate. Here's how:

If a user is initially invited, we can set the isInvited boolean flag to true. When a user registers for the event, we can update the isRegistered flag to true. Since each of these fields is separate, we will eaisily calculate the conversion rate.

This approach simplifies the process of determining how many invited users eventually registered for the event, providing clarity in tracking user engagement.

**Comment by palisadoes** [comment]
1. OK let's go with the original plan.
2. Remember to include the checked-in flag because it will verify attendance

**Comment by aialok** [comment]
@palisadoes , only eventAdmin and SuperAdmin have right to invite, registered and do checkIn for event?

**Comment by palisadoes** [comment]
> @palisadoes ,  
> - Only eventAdmin and SuperAdmin have right to invite, registered and do checkIn for event?
> - Can invited user register for event by own?

1. All users should be able to register for events.
1. Admins should be able to invite too
1. Only the event admin, admins and super admins should be able to check in for now. We'll probably want to expand this later.
1. If it's an invitation only event then only invitees and the admins should be able to register. If this flag doesn't exist then we need to open an issue to create the functionality. This is separate from the isRegisterable flag. Sometimes you'll want people to register without being invited.

**Comment by aialok** [comment]
Hello @palisadoes,

I need few suggestion regarding implementation of this feature. 

- Currently, in the Talawa-admin codebase, we don't invite users; instead, we directly add them as registered users and mark them as checked in for the event. My current approach is to introduce new modals for inviting attendees to events, while leaving the Add-Registrant and check-in processes unchanged.

- In the case of inviting a user, We can create new document of `UserEventStatus` and set `isInvited` true.

- When a user is registered after being invited, I will update the `isRegistered` flag. If a user is not invited and is registered directly, I'll create a new document for that scenario.

- For registering using same modals
![Invitee](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/63fa1b24-b400-4ccd-90be-d44861a5c527)

- For the check-in process, if a user is registered, I'll update the `isCheckedIn` flag to true. If the user is not already registered, I'll create a new document and set the `isCheckedIn` flag to true.

- for checking using same model
![Screenshot from 2024-01-24 19-10-33](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/9061f3d3-8570-4887-b11d-d0cc6b97c3e6)


This approach would require minimal updates to the Talawa-admin code, and if needed, we can create separate mutations for inviting, registering, and checking in.


Your feedback on this approach would be greatly appreciated.

**Comment by palisadoes** [comment]
We are going to need a suite of PRs for this:

1. Please proceed with your approach.
2. We'll definitely need corrected mutations to handle the desired functionality. When would the PR for this be created?
3. We'll also need to update the User Portal side of the Admin code base to allow users to register for `open` and `invitee only` registration events. This will require another PR for this too.

**Comment by aialok** [comment]
> We are going to need a suite of PRs for this:
> 
> 1. Please proceed with your approach.
> 2. We'll definitely need corrected mutations to handle the desired functionality. When would the PR for this be created?
> 3. We'll also need to update the User Portal side of the Admin code base to allow users to register for `open` and `invitee only` registration events. This will require another PR for this too.

I have completed the implementation of basic mutations, queries, and business logic. The only remaining task is to write tests for these changes. Due to time constraints, I plan to submit the pull request this coming Sunday.

**Comment by aialok** [comment]
Hey @palisadoes,

I am in a little bit of a dilemma about choosing between two approaches: updating the existing `eventAttendee` models, mutations, and queries, or creating new `userEventStatus` models, mutations, and queries. I have already implemented the second option—`userEventStatus` models—and created the required mutations and queries.

However, I later realized that we are maintaining the same information in two places: `eventAttendee` and `userEventStatus`. In both cases, we are tracking user attendance. Instead, what we can do is make slight changes to the `eventAttendee` models:

```typescript
type EventAttendee{
    _id: ID!
    user: User!
    event: Event!
    checkIn: CheckIn
    isInvited: Boolean
    isRegistered: Boolean
    isCheckedIn: Boolean
    createdAt: DateTime!
    updatedAt: DateTime!
}
```

With these changes, we can easily track the user's event status regarding invitations, registration, and check-ins. This way, we won't require much effort in changing the existing mutations, queries and talawa-admin.

Let me know if you have any further questions or need additional clarification!
Should I go with this approach?

**Comment by palisadoes** [comment]
Yes. This should work. Please proceed

**Comment by palisadoes** [comment]
@aialok 

How is progress on this? It's been over a week without any updates or PRs.

**Comment by aialok** [comment]
> @aialok 
> 
> How is progress on this? It's been over a week without any updates or PRs.

@palisadoes , I have been busy for while due to very important family function.
I will be making PR in two days for sure.
Thank You !

**Comment by aialok** [comment]
> 1. The intention was for persons attending an event to be checked in using the app as a verification of user attendance with a timestamp. It also attempts to track whether the user left feedback using the app.
>    ![image](https://private-user-images.githubusercontent.com/16875803/294744301-7e16978d-10a8-48a4-bb3f-7064f058395e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzYwMTEsIm5iZiI6MTcwODIzNTcxMSwicGF0aCI6Ii8xNjg3NTgwMy8yOTQ3NDQzMDEtN2UxNjk3OGQtMTBhOC00OGE0LWJiM2YtNzA2NGYwNTgzOTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA1NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjBmZGU5YmFkMWU0YTUwOWJiMGE4NzhjMDMyMTBiZmVlMTExOTY4ZDZiNzc5YjQ3MGUzY2U4ODhkZmYwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.24mg6RVWjfV01DygOYa9UP4p2I5j4yIAf44vmyIizDg)
> 2. Now that we have an issue created for venues we can deprecate the `allottedRoom` and `allottedSeat`.
> 3. Revisiting the schema we are effectively tracking attendance twice using the fields below. When we could just use `attendeesCheckInStatus`
>    
>    1. `attendance` and,
>    2. `attendeesCheckInStatus`
>       ![image](https://private-user-images.githubusercontent.com/16875803/294744459-8b7157de-077c-4078-92ff-bfcb78db2687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzYwMTEsIm5iZiI6MTcwODIzNTcxMSwicGF0aCI6Ii8xNjg3NTgwMy8yOTQ3NDQ0NTktOGI3MTU3ZGUtMDc3Yy00MDc4LTkyZmYtYmZjYjc4ZGIyNjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA1NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZGY0YjY2NWZhZjExNGQyNTQ4YWI4OTgwYzMxZGQ0MDkxMzYwMjU5ZjI2NjY0ZTgyMzQ3MDM4NDI4Mjg2YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E_-G28hpo89OlGkTKHZEdTM7J_SQ2BAxAEvFQSlpffI)

@Palisadoes, can we deprecate the `attendeesCheckInStatus` and `attendees` fields? With the `eventAttendee` model in place, we can now easily track event attendees.

**Comment by palisadoes** [comment]
OK

**Comment by aialok** [comment]
Hi @palisadoes , May I create a new issue on talawa-admin for the frontend-required changes? If there's anything necessary to discuss, I will initiate the discussion there only.

Additionally, I also require some improvements in the backend along with the frontend, so please do not close this issue. If any extra PR is needed in backend, I will handle it within this issue.

**Comment by palisadoes** [comment]
1. Yes, and ask to be assigned.
2. However you'll need to create a design based on our design system by working with @rishav-jha-mech and @aashimawadhwa. We really need consistency on this.
    1. https://docs.talawa.io/docs/design/ux/ux-design-system

**Comment by aialok** [comment]
OK sir.

> 1. Yes, and ask to be assigned.
> 2. However you'll need to create a design based on our design system by working with @rishav-jha-mech and @aashimawadhwa. We really need consistency on this.
>    
>    1. https://docs.talawa.io/docs/design/ux/ux-design-system

OK Sir.

**Comment by palisadoes** [comment]
> @palisadoes I'll not be able to work on it due to some time constraints. Please unassign me from this issue, so someone else take take over this.

@shreyashidabral Have your time constraints improved?

**Comment by aialok** [comment]
> > @palisadoes I'll not be able to work on it due to some time constraints. Please unassign me from this issue, so someone else take take over this.
> 
> @shreyashidabral Have your time constraints improved? 

The issue has already been resolved, and the PR has been merged.

**Comment by Cioppolo14** [comment]
@aialok Can we close this issue?

**Comment by aialok** [comment]
> @aialok Can we close this issue?

Yes : )

**Comment by gautam-divyanshu** [comment]
closing this issue because the getEventAttendeeByEventId &userare two separate queries. The user query requires authentication.
