### ISSUE TITLE
Add Support for Event Images

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1645]
**Is your feature request related to a problem? Please describe.**

We need the ability to apply images to events. This could be useful in making the event more interesting because of an added flyer.

**Describe the solution you'd like**

1. We need an `image`  field added to the Event collection
1. You will be required to write tests for the expected CRUD activities related to the image.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

The current screen shot of the `develop` branch's schema

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/a1e36c95-e66e-4060-9612-42c4abf5bb98)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by shreyashidabral** [comment]
Can I work on this

**Comment by varunsh17** [comment]
Can I start working on this issue?

**Comment by Dante291** [comment]
https://github.com/PalisadoesFoundation/talawa/issues/2309

**Comment by Azad99-9** [comment]
@palisadoes I propose,

-  It will be more sensible, If we create a field `images (list of images)` instead of `image (single image)`.
- This change would allow us to incorporate a `carousel` on the `event page`, enhancing the `user experience` with a more sophisticated and engaging display of multiple images.
- Also Having only a single image gives a limited context to the user regarding the event and also its a bit outdated.

I would like to know your thoughts on this.

**Comment by palisadoes** [comment]
1. Yes that would be a good addition
2. @shreyashidabral please incorporate that. Limit it to 5 images. No video.
3. We need to freeze all other modifications at this time to facilitate the implementation of the feature

**Comment by shreyashidabral** [comment]
@palisadoes 
I'll not be able to work on it due to some time constraints. Please unassign me from this issue, so someone else take take over this.

**Comment by duplixx** [comment]
@palisadoes @shreyashidabral, I have a few queries while implementing this feature.

Is an image a required field?
Are images a collection of images?

**Comment by palisadoes** [comment]
1. Images are not required
1. Up to 5 images per event

**Comment by palisadoes** [comment]
> @palisadoes I'll not be able to work on it due to some time constraints. Please unassign me from this issue, so someone else take take over this.

@shreyashidabral Have your time constraints improved?

**Comment by AspireSsp** [comment]
if this issue is still open ?  i want to work on it

**Comment by duplixx** [comment]
@AspireSsp  the pr is already raised for this #1675
