### ISSUE TITLE
API: Deprecate Organization `Location`. Replace with `Address` 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1650]
**Is your feature request related to a problem? Please describe.**

Organizations only have a `location`  field to describe their physical location

**Describe the solution you'd like**

1. Replace the `location` field with the existing `address` type
    1. `Location` is deprecated and must not be supported  
1. Repo actions required
    1. _Talawa API_
        1. Verify whether your repo is using `location` for organizations and remove support and replace it with `address` 
        1. Update the appropriate mutations and queries
    1. _Talawa Mobile_
        1. Verify whether your repo is using `location` for organizations and remove support and replace it with `address` 
        1. Update the appropriate mutations and queries used to interact with the API
    1. _Talawa Admin_
        1. Verify whether your repo is using `location` for organizations and remove support and replace it with `address` 
        1. Update the appropriate mutations and queries used to interact with the API
1. Create and update the appropriate tests to have valid test criteria
1. No other features must be affected by this change

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1. Address Type
    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/26c1390a-a302-4917-98c3-74069fe2176f)
1. Organization Type
    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/d9be1764-1979-4110-8a51-6de4eb334b20)

**Related Issues**

- https://github.com/PalisadoesFoundation/talawa-api/issues/1650
- https://github.com/PalisadoesFoundation/talawa/issues/2354
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1502

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Anubhav-2003** [comment]
@palisadoes I would like to work on this issue sir.

**Comment by Sejal1411** [comment]
Would like to work in this issue...pls assign!

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, I wanted to tell that I have made most of the changes in the Talawa-api regarding the switch from location to address, but in order to verify if the changes are working properly or not, I was using Talawa-admin portal. And from What I observed that there are quite a few places where the changes must be made in the front-end to ensure that the Talawa admin portal works properly, like updating forms, mutations, and queries after the changes in the API. 

Should I make those changes in the admin portal as well? Because without those changes, it would be hard to tell if the admin portal would work properly after my changes.

Thank You.

**Comment by Anubhav-2003** [comment]
@palisadoes ok sir. But I think we should not merge this PR until all the changes are made in the front-end. Otherwise people working in the talawa-admin will face issues. I think We can fix them parallelly, test and then merge the PR’s, only after ensuring that the organisations are being handled properly by both ends.

**Comment by palisadoes** [comment]
OK, let's try that approach, but you should still get approvals for this PR so that we can merge without delay when necessary

**Comment by vinayakjaas** [comment]
Can I work this issue

**Comment by palisadoes** [comment]
@Anubhav-2003 

Our `push` GitHub action is failing after merging your PR.

- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7681704624
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7681704624


This issue needs to be reopened until it's fixed.

**Comment by Anubhav-2003** [comment]
@palisadoes ok sir, let me see the bug and fix it. Thank you.

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, 

I just pulled the latest changes from the develop branch of the API, and the admin portal after my PR got merged, and tested. All features seem to be working as expected. 

Sir, in my last API PR, there were significant changes to the schema.graphql of the TALAWA API, and the above error is also related to inspection. Is it just possible sir that the PR from the specified reference ('refs/pull/24/merge'), does not have the updates schema. 

Also sir, I would advice everyone to pull the latest changes from the develop branch before making any PR'S else all of their tests related to GraphQL schema would fail, if they would not have the current one. 

Thank You.

**Comment by palisadoes** [comment]
Run the schema test command against your local repos to see if the error persists.

**Comment by Anubhav-2003** [comment]
@palisadoes ok sir. Let me do that.

**Comment by Anubhav-2003** [comment]
@palisadoes Repscted sir, 

Please close this issue as I have completed it, and the PR has been successfully merged with the feature implemented. The push workflow fail you refered to was actually failing from before my PR got merged, and has nothing to do with my PR, as you can see from this workflow link: https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7670722935/job/20907525959 , this check ran before my PR #1740 was merged.

This issue has been succesfully solved. Thank You. 

But one suggestion I would like to make is please create an issue that address the fact that the push workflow from inspect.yml is failing.
