### ISSUE TITLE
Verify `organizationUserBelongsTo` in the User Collection

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1651]
**Is your feature request related to a problem? Please describe.**

1. The `organizationUserBelongsTo` field in the User collection may not be used by any other app.
2. It is reference in the `MemberDetail.tsx` screen of Talawa Admin but isn't modified
3. It does not seem to be used in Talawa Mobile
4. Field `joinedOrganizations` seems to be used instead.

**Describe the solution you'd like**

1. Verify whether the field is used and remove it from the Schema
2. If removed, create an appropriate issues in Talawa Admin and Talawa Mobile where applicable to not use it.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/9e421655-3cad-4a66-901b-c475c995710c)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue. Please assign me.

**Comment by Sejal1411** [comment]
would like to work on this issue ...pls assifgn

**Comment by Veer0x1** [comment]
I would like to work on it.

**Comment by akhilender-bongirwar** [comment]
Since the field `joinedOrganizations` is used instead of `organizationUserBelongsTo` field in the memberDetail screen, I have raised an issue to remove this in talawa-admin repository. Please check and assign me this [issue](https://github.com/PalisadoesFoundation/talawa-admin/issues/1426)
