### ISSUE TITLE
Fundraising - Parent Issue

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1661]
**Is your feature request related to a problem? Please describe.**

We are creating a series of issues to add a fundraising feature to Talawa-Admin for use by Org Admins.

**Describe the solution you'd like**
- Sequentially complete the issues listed below

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

Related issues:
- https://github.com/PalisadoesFoundation/talawa-api/issues/1663

**Comment by AkashMundari** [comment]
Can i be assigned this task ??
