### ISSUE TITLE
Bug Report: Dependencies upgrade.

### ISSUE THREAD

**Issue by varunsh17** [PalisadoesFoundation/talawa-api#1662]
Since the @graphql-codegen/typescript @typescript-eslint/eslint-plugin vitest uuid are marked for UPGRADE, 
Some major like,

@graphql-codegen/cli                                  `2.16.5 ->   5.0.0`  
@types/express-rate-limit                          ` 5.1.3 ->  6.0.0`
mongoose                                                  ` 5.13.21 ->   8.0.3`
tsx                                                               `3.14.0 ->  4.7.0`

also requires upgrade 

There are many good features provided by the new updated dependencies with better TS support.
We can use many great features this way and enhance the site security with will overall improve performance to great extend.

**Comment by varunsh17** [comment]
If there's need to upgrade any of the package, I would like to work upon one or two (not all) and leave other for fellow contributor friends.

**Comment by palisadoes** [comment]
1. There is no need for this. Our repo is automatically upgraded using dependabot. We create manual issues when dependabot fails
2. Closing
