### ISSUE TITLE
Add Support of Fundraising Campaigns

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1663]
### Introduction
This issue requires someone with:

1. provable GraphQL coding experience **_OR_**,
2. significant activity in their GitHub profile

It is the first in a series of issues and we want to make sure that it will be completed quickly so that others can use it as a guide

### Funds
We need the ability to create **_Organization specific_** fundraising funds these will have:

1. GraphQL Fundraising Fund ID
2. GraphQL Org ID
3. A fund name
4. An optional alphanumeric Reference Number ID (Not GraphQL) for internal tracking purposes within the organization, possibly by an accounting department.
5. A flag to track whether or not the fund is tax deductible
6. A flag to track whether the fund should be the default fund for the organization.
7. An archive flag 
8. Our standard update and creation fields as outlined in these pull requests
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1603
    2. https://github.com/PalisadoesFoundation/talawa-api/pull/1542

Other:

1. CRUD capability will be required with cascading deletions to any campaigns
2. Funds must be able to be archived as well as deleted
3. Create the necessary mutations, queries and valid tests for your work on this feature

### Fundraising Campaigns

There will be the need to create fundraising campaigns. These campaigns will need a:

1. GraphQL Fundraising Campaign ID
2. GraphQL Fundraising Fund ID (Parent)
4. Campaign name
5. Start date
6. End date
7. A funding goal in local currency
9. The GraphQL ID of the fund to which the campaign will belong. There can be a many to one relationship between the campaign and its parent fund
7. Our standard update and creation fields as outlined in these pull requests
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1603
    3. https://github.com/PalisadoesFoundation/talawa-api/pull/1542

Other:

1. CRUD capability will be required for campaigns
2. Create the necessary mutations, queries and valid tests for your work on this feature

### Fundraising Campaign Pledges
Fundraising campaigns will need the ability to accept pledges from Users. Each pledge would record a:

1. GraphQL Fundraising Pledge ID
2. GraphQL Fundraising Campaign IDs - A list of campaigns that the total pledge amount will be spread across
4. GraphQL User IDs - A list of user IDs that are committing to fulfilling the pledge. This could be a list of family members for example. 
5. Start date for when the User would be expected to start their pledge drive - Default as the start of the campaign
6. End date date for the User’s pledge drive - Default as the end of the campaign
7. The amount of the pledge
8. Our standard update and creation fields as outlined in these pull requests
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1603
    2. https://github.com/PalisadoesFoundation/talawa-api/pull/1542

Other:

1. CRUD capability will be required for pledges
2. reate the necessary mutations, queries and valid tests for your work on this feature
3. **_NOTE:_** Each campaign must only have one pledge per person or family

### Approach

Create 3 successive PRs based on this issue. One each for:

1. Funds
2. Fundraising Campaigns
3. Fundraising Campaign Pledges

This will make progress tracking and troubleshooting easier

#### Preparation

- The assigned person will be required to discuss their proposed schema in this issue's comments before submitting a PR

#### Related Issues
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1661

**Comment by Tarunmeena0901** [comment]
@palisadoes  @nishnatadebnath @Ayush0Chaudhary  i would like to work on this issue

**Comment by palisadoes** [comment]
@Tarunmeena0901 As stated in the issue "This issue requires someone with provable GraphQL coding experience." Do you have that?

**Comment by Tarunmeena0901** [comment]
@palisadoes  i do have knowledge about graphql even though i havent work on it much , even so one week should be enough

**Comment by Tarunmeena0901** [comment]
i do understand the importance of this issue so it'll be fine if you like to assign someone else

**Comment by meetulr** [comment]
I'd be happy to work on this.

**Comment by saswat10** [comment]
I would like to work on this issue if it is unassigned yet, I do have some experience with GraphQL

**Comment by palisadoes** [comment]
@saswat10 

Please read the `Approach` and `Preparation` sections above to guide your activities.

**Comment by varshith257** [comment]
I have read the requirements, Can I work on this issue @palisadoes

**Comment by varshith257** [comment]
I have read the requirements, Can I work on this issue @palisadoes 
 I've finished with the proposed Schema according to the requirements for Funds, Fundraising Campaigns and Fundraising Campaign Pledges.
I would like to proceed further and discuss the proposed schema and promise you a faster solution. As per requirement, I have experience in GraphQL, eager to discuss the schemas and contribute to this feature.

**Comment by Cioppolo14** [comment]
@varshith257 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by saswat10** [comment]
My proposed schema for the above models is 

#### Organization Specifc Funds

```graphql
type Funds {
	_id: ID!
	organizationId: ID!
	name: String!
	taxDeductible: Boolean!
	defaultFund: Boolean!
	archived: Boolean!
}
```

#### Fundraising Campaign

```graphql
type FundCampaigns {
	_id: ID!
	name: String!
	startDate: Date!
	endDate: Date!
	goalAmount: Int!
	currency: String!
	fundIds: [fundId]!
}
```

#### Fundraising Campaign Pledges

```graphql
type CampaignPledge {
	_id: ID!
	campaignID: [FundCampaigns]!
	members: [User]
	startDate: Date!
	endDate: Date!
	amount: Int!
	currency: String!
}
```
@palisadoes 

Kindly suggest any changes if required. Otherwise I would proceed further.

**Comment by palisadoes** [comment]
Thanks,

1. Funds can have many associated campaigns and not vice versa
2. You'll need to add the other fields as mentioned in the reference PRs. Your code will have to comply with the logging methodology of that PR.
3. Consider collection or enum type with currency codes that can support multilingual translations. `String!` won't be sufficient.

Other:

1. After implementing these changes, you should submit your PR
2. Remember, it needs to be close to final as we want to commit our volunteer time in the most efficient way.

**Comment by saswat10** [comment]
Ok, I will make the necessary changes and create the additional fields as mentioned in the referenced PR.
I just wanted to confirm the basic schema for the above.

**Comment by varshith257** [comment]
@palisadoes  If this issue is still open, I'd be more than happy to contribute actively to this issue. I have no other commitments at the moment, so I can dedicate my full attention to this issue.  
As I mentioned earlier, I am eagerly waiting for the series of issues related to this parent issue."

**Comment by palisadoes** [comment]
Unassigning due to inactivity.

**Comment by varshith257** [comment]
@palisadoes Please assign me this issue. I would like to contribute to this

**Comment by AVtheking** [comment]
I would like to work on this issue sir

**Comment by palisadoes** [comment]
@varshith257 You already have 2 issues

**Comment by varshith257** [comment]
@palisadoes I am eagerly waiting to work on this issue for a while if it is not resolved. Please assign me this issue I am eagerly waiting to contribute to this feature.

**Comment by varshith257** [comment]
> @varshith257 You already have 2 issues

 I didn't known the another issue here in talawa-api assigned to me. In thought of I have only one issue and due to inactivity in this issue I commented to express my interest to work on this issue.

**Comment by varshith257** [comment]
@palisadoes Sorry for the inconvenience, but I have been waiting for the update on the assignment of the issue for quite a long time
Looking forward to contributing to this issue

**Comment by AVtheking** [comment]
@varshith257  what plan did you made so far for this issue ?

**Comment by varshith257** [comment]
> @varshith257 what plan did you made so far for this issue ?

My plan to address the issue, which includes the following:

1. Propose a schema for the `Funds`, `Fundraising Campaigns` and `Fundraising Campaign Pledges`
2. Divide the work into three separate PRs for easier management and faster review by the reviewers.

For the `Funds` section, the plan is as follows:

1. Define typeDefs for the Funds.
2. Implement CRUD operations for Funds using mutations and resolvers.
3. Write tests to ensure their functionality.

The same approach will be followed for the `Fundraising Campaigns` and `Fundraising Campaign Pledges` sections.

I also remember that @EshaanAgg suggested making multiple PRs for every 2-3 resolver changes made to make it easier for reviewers to review the code quickly and I plan to incorporate this suggestion into my approach to address this issue.

**Comment by AVtheking** [comment]
ya that approach is already stated in the issue itself, what else did you planed like how would you define relation between these models ?

**Comment by AVtheking** [comment]
As I am already assigned for this issue this would be not good approach from my side to unassign myself if @palisadoes  sir want to assign this issue to you then it is okay 

I would suggest we should work together on this issue as this is an important feature and should be completed as soon as possible for more issues to come

**Comment by varshith257** [comment]
@AVtheking Let's go!! It required working with three features to be implemented let's collaborate and work together, we can build on the progress for this feature and make it complete ASAP  :)

I noticed that you have worked with user-specific issues, so I suggest you focus on the `Fundraising Campaign Pledges`. Where `Funds` and `Fundraising Campaigns` require close coordination, I'll take care of those.

**Comment by palisadoes** [comment]
1. Our policies are clearly stated in our documentation and YouTube channel videos. 
1. Though we sometimes make mistakes, and have rare exceptions, we try to abide by them

No further action is required in this case

**Comment by varshith257** [comment]
> @palisadoes If this issue is still open, I'd be more than happy to contribute actively to this issue. I have no other commitments at the moment, so I can dedicate my full attention to this issue. As I mentioned earlier, I am eagerly waiting for the series of issues related to this parent issue."

@palisadoes I respect your decision and agree with it and I am the one first who expressed to work on this issue.

**Comment by varshith257** [comment]
> > @AVtheking Let's go!! It required working with three features to be implemented let's collaborate and work together, we can build on the progress for this feature and make it complete ASAP  :)
> > I noticed that you have worked with user-specific issues, so I suggest you focus on the `Fundraising Campaign Pledges`. Where `Funds` and `Fundraising Campaigns` require close coordination, I'll take care of those.
> 
> Only one person per issue as stated in our policies

Can make a another small issue and we work together as it also helps to complete this issue quickly as it is important feature and related issues are waiting based on this as you stated

**Comment by palisadoes** [comment]
> > @palisadoes If this issue is still open, I'd be more than happy to contribute actively to this issue. I have no other commitments at the moment, so I can dedicate my full attention to this issue. As I mentioned earlier, I am eagerly waiting for the series of issues related to this parent issue."
> 
> @palisadoes I respect your decision and agree with it but I am the one first who expressed interest to work on this issue. 

At the time you had two issues assigned, one with the API and another in Admin. The correct decision was made.

**Comment by palisadoes** [comment]
> > > @AVtheking Let's go!! It required working with three features to be implemented let's collaborate and work together, we can build on the progress for this feature and make it complete ASAP  :)
> > > I noticed that you have worked with user-specific issues, so I suggest you focus on the `Fundraising Campaign Pledges`. Where `Funds` and `Fundraising Campaigns` require close coordination, I'll take care of those.
> > 
> > Only one person per issue as stated in our policies
> 
> Can make a another small issue and  get it assigned we work together as it also helps to complete this issue quickly as it is important feature and related issues are waiting based on this as you stated

No. Please desist from this behavior

**Comment by varshith257** [comment]
> ya that approach is already stated in the issue itself, what else did you planed like how would you define relation between these models ?

@AVtheking These are definitions for `Funds`, `Fundrsiaing Campaigns` and `Fundraising Pledges` and relationship between them will be as  follows: 

**Funds**

```
type Fund {
  id: ID!
  orgId: ID!
  name: String!
  referenceNumber: String
  taxDeductible: Boolean!
  isDefault: Boolean!
  isArchived: Boolean!
  campaigns: [FundraisingCampaign!]!
  currency: CurrencyCode!     # Use the enum type for currency codes
}
```

**Fundraising Campaigns**
```
type FundraisingCampaign {
  id: ID!
  fundId: ID!
  name: String!
  startDate: Date!
  endDate: Date!
  fundingGoal: Float!
  fund: Fund!
  pledges: [FundraisingPledge!]!
  currency: CurrencyCode!  # Use the enum type for currency codes
}
```

**Fundraising Pledges**

```
type FundraisingPledge {
  id: ID!
  campaignIds: [ID!]!
  members: [Users]!
  startDate: String!
  endDate: String!
  amount: Float!
  campaigns: [FundraisingCampaign!]!
  currency: CurrencyCode!  # Use the enum type for currency codes
}
```
**Relationships:**

1. **Fund to FundraisingCampaigns:**
The Fund type has a one-to-many relationship with FundraisingCampaign through the campaigns field. One organization specific fund can be associated with multiple fundraising campaigns.

2. **FundraisingCampaign to Fund:**
The FundraisingCampaign type has a many-to-one relationship with the Fund through the fund field. Each fundraising campaign is associated with a specific fund.

3. **FundraisingCampaign to FundraisingPledges:**
The FundraisingCampaign type has a one-to-many relationship with FundraisingPledge through the pledges field. One campaign can have multiple pledges.

4. **FundraisingPledge to FundraisingCampaigns:**
The FundraisingPledge type has a many-to-many relationship with FundraisingCampaign through the campaigns field. One pledge can be associated with multiple campaigns, and one campaign can have multiple pledges.


Hope this will clarify these for you ;)

**Comment by varshith257** [comment]
My bad! As a CS student, just explaining these using DB terms 😅. If any help required, ping me

**Comment by AVtheking** [comment]
@palisadoes sir does fund model need to refrence to the FundCampaigns model as in the issue you have not stated that refrence ?

**Comment by palisadoes** [comment]
> @palisadoes sir does fund model need to refrence to the FundCampaigns model as in the issue you have not stated that refrence ?

Yes, that would be useful. There will need to be a bidirectional relationship for this reason:

1. An Admin will want to create a fund, for example `Building Fund`
2. There may be different `campaigns` related to the fund that they may want to click through to:
    1. `Build the Auditorium` Campaign
    1. `Fix the Kitchen` Campaign
    1. `Pave the Parking Lot` Campaign

For this issue:

1. Create a PR for Funds and Campaigns first. That will be easier to review.
3. Then create one for pledges. The schema for that may need to change soon.

**Comment by varshith257** [comment]
@palisadoes Can also suggest the list of currency codes to be used in the model. Is it could be USD, INR etc.. i.e..language regions supported by talawa as of  now ? 
OR
Standard currency codes that are widely used in financial transactions:

1. United States Dollar: USD
2. Euro: EUR
3. British Pound Sterling: GBP
4. Japanese Yen: JPY
5. Canadian Dollar: CAD
6. Australian Dollar: AUD
7. Swiss Franc: CHF
8. Chinese Yuan: CNY
9. Indian Rupee: INR

**Comment by AVtheking** [comment]
> > ya that approach is already stated in the issue itself, what else did you planed like how would you define relation between these models ?
> 
> @AVtheking These are definitions for `Funds`, `Fundrsiaing Campaigns` and `Fundraising Pledges` and relationship between them will be as follows:

> **Fundraising Campaigns**
> 
> ```
> type FundraisingCampaign {
>   id: ID!
>   fundId: ID!
>   name: String!
>   startDate: Date!
>   endDate: Date!
>   fundingGoal: Float!
>   fund: Fund!
>   pledges: [FundraisingPledge!]!
>   currency: CurrencyCode!  
> ```
> 
why you have refrence to parent fund two times in the campaign it can be used only one time with have id of parent fund as refrenced and with that we  can also populate the parent fund

**Comment by varshith257** [comment]
1. As I referenced it provides direct access to the `Fund` object when querying a `FundraisingCampaign`. This can be useful for more complex queries where you want to retrieve detailed information about the associated fund.
2. If detailed information about the parent `fund` is not often needed when querying a `campaign`, you might consider having just the `fundId` reference and avoid the direct fund reference.

**Comment by AVtheking** [comment]
Yes but in mongoose directly reference using id of model and it stores id in db only

**Comment by AVtheking** [comment]
@palisadoes  sir would the name of the fund for organization is unique ?

**Comment by palisadoes** [comment]
Yes

**Comment by palisadoes** [comment]
What's left to complete with this issue? It looks like pledges, correct?

**Comment by AVtheking** [comment]
Yes sir pledges and some mutation of campaign

**Comment by AVtheking** [comment]
@palisadoes  sir more clarity on fundraising pledges would be helpful ,like what it is all about ,what is the need of it and  one campaign can have multiple pledges ?

**Comment by AVtheking** [comment]
Thank you sir for the clarification

**Comment by AVtheking** [comment]
> Should I create a single PR for these two ?

What about this sir ? If I include pledges with it then the no of files changed would increase

**Comment by palisadoes** [comment]
Go ahead. The number needs to be adjusted.

**Comment by AVtheking** [comment]
> 1. Admins create a fund:
>        
>        1. Eg. The Building Fund
> 
>     2. Admins then create campaigns for the funds:
>        
>        1. New Parking Lot campaign
>        2. Fix Concert Hall campaign
> 
>     3. Members who are interested may want to make a pledge of money (a commitment) towards one or more campaigns.
> 
>     4. The admins will then be able to track who makes pledges and then follow up with them to make a donation matching their pledged amount
> 
>     5. At some later stage we'll need to integrate a donation plugin with a payment gateway.

so multiple users can create pledges to the campaigns ?
how will add the list of members for the pledge ,user who created it or there would be the options for the other user to join this pledge ?

**Comment by palisadoes** [comment]
1. Yes, multiple members can create pledges to the same campaign. Adjust the schema accordingly if required
2. Multiple pledges per member per campaign should be possible
3. Members should be able to edit previous pledges

**Comment by AVtheking** [comment]
And can user directly join pledge or the creator of the pledge can only add more members ?

**Comment by palisadoes** [comment]
The user can directly make a pledge. The creator shouldn't be a requirement

**Comment by AVtheking** [comment]
But there is a thing like list of userId in the pledge

**Comment by palisadoes** [comment]
Yes, family members could be added to the pledge

**Comment by palisadoes** [comment]
I meant that users can create a pledge to a campaign on their own, the campaign creator doesn't necessarily have to be the one adding users to make the pledge

Yes, others can join in on an existing pledge. They could be family members.

**Comment by AVtheking** [comment]
ok sir

**Comment by palisadoes** [comment]
Is anything else outstanding on this?

**Comment by AVtheking** [comment]
No sir

**Comment by AVtheking** [comment]
Can I work on the frontend part of this issue as I have made backend it would be easier for me to implement it from frontend also

**Comment by palisadoes** [comment]
1. Create an issue and ask to be assigned
2. @aashimawadhwa and/or @rishav-jha-mech will soon have a design for you to use for this.

**Comment by AVtheking** [comment]
ok sir
