### ISSUE TITLE
Bug Report: Images Exceeding Size Limits are Being Uploaded

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa-api#1667]
*Describe the bug*
Currently, images exceeding size limits for display are being uploaded, even when an error is given. 

*Expected behavior*
If an image is too large, an error should be given AND the image should NOT be uploaded. 

*Actual behavior*
The image is being uploaded and stored even though an error is seen. 

*Additional details*
PLEASE TAKE NOTE: Please limit the size of all image related mutations to 3 MB. This limit should be included as a parameter in the .env file.  Please also make the setup.ts file prompt for it too when the API setup is done.

Please also note that this is being worked on in Talawa-Admin: https://github.com/PalisadoesFoundation/talawa-admin/issues/1405

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?
