### ISSUE TITLE
`userType` incorrectly set to `string` in DB schema

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1669]
**Describe the bug**
- `userType` incorrectly set to `string` in sections of the schema

**To Reproduce**

Search the develop branch DB schema
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/schema.graphql

**Expected behavior**

- `userType` references should not be type `string` as it is an Enum

**Actual behavior**
- `userType` is consistently set to  type `string` 

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/f97ba963-21a3-4552-b48f-6707238b70c6)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/b89220f6-bf60-49a3-a31c-1f3c2ea5694b)

**Additional details**
1. Make the necessary changes if required
1. Ensure all tests are valid and pass
1. No other functionality must be affected

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@palisadoes can I work on this issue?

**Comment by MahendraDani** [comment]
I would like to work on this

**Comment by Veer0x1** [comment]
Can I take up this issue?

**Comment by LakshyaSatpal** [comment]
@palisadoes This issue was addressed in the review of [this PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1542) by @xoldyckk. I've done the changes for this.
