### ISSUE TITLE
Use `let` or `const` instead of `var`

### ISSUE THREAD

**Issue by gauravdas014** [PalisadoesFoundation/talawa-api#167]
Currently, in some files, `var` is being used and in some others, `let/constant` has been used. `let` is block-scoped, it's kind of a standard and more readable. Moreover, block-scoped code is easy to debug as compared to function scoped. So, it's a good idea to change the `var` to `let/constant`. 

@Sagar2366 @Laurell876 Can you assign me this issue?

**Comment by somya339** [comment]
This issue needs a better understanding of variable hoisting and scope assignment .  I would like take up this issue .
@Sagar2366  @Laurell876  can you assign it to me.

**Comment by iamsaumya** [comment]
Apologies everyone, this issue is already addresses in the #125. I encourage you all to review the changes made there and help me find If I have left anything.
