### ISSUE TITLE
Add Support for Event Volunteers

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1670]
## Introduction
This issue requires someone with:

1. provable GraphQL coding experience **_OR_**,
2. significant activity in their GitHub profile

It is the first in a series of issues and we want to make sure that it will be completed quickly so that others can use it as a guide

## Problem Description

1. We will need the _**OPTIONAL**_ ability to assign volunteer groups to events. 
2. This will help event organizers have greater success.

## Preferred Solution

1. We will need DB schema updates to facilitate this.
1. Queries and mutations will need to be created to satisfy CRUD operations for volunteers
1. Valid tests must be created for the code added for this issue
1. No other functionality must be affected

### Event Volunteer Groups Collection

At a minimum this will need to record:

1. Event ID
2. Group Name
3. Volunteer Group Leader User ID
4. Number of volunteers required
5. List of Event Volunteer Types
8. Our standard update and creation fields as outlined in these pull requests
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1603
    2. https://github.com/PalisadoesFoundation/talawa-api/pull/1542

### Event Volunteer Collection

At a minimum collection of Event Volunteer Types will need to record:

1. Event ID
2. User ID
3. Response [No, Yes, None]
4. Invited - T/F
5. Assigned - T/F
8. Our standard update and creation fields as outlined in these pull requests
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1603
    2. https://github.com/PalisadoesFoundation/talawa-api/pull/1542

## Other

It is best for our reviewers to verify smaller PRs. Therefore you will need to create one PR per collection created.

1. Event Volunteer Collection CRUD
2. Event Volunteer Groups Collection CRUD

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

1. Multiple PRs
1. See above for details

**Additional context**
1. When recurring meetings are correctly implemented, Admins will want event volunteers to be part of the recurring event up to some end date. Volunteers may also only want to participate in the role every N events. 
    1. Supporting recurring events is beyond the scope of this issue, but your work must not make support for this at a later date be more difficult. See this issue for details.
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1583
    1. Explain how you think this could best be achieved when eventually implemented to show that you have considered your impact on this long term goal.
1. Reminders will eventually need to be sent to volunteers prior to the event. 
    1. This is beyond the scope of this issue, but your work must not make support for this at a later date be more difficult. 
    1. Explain how you think this could best be achieved when eventually implemented to show that you have considered your impact on this long term goal.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@palisadoes Interested to work on this issue. As mentioned I have experience in GraphQL

**Comment by Veer0x1** [comment]
I would like to work on it.

**Comment by AVtheking** [comment]
@palisadoes I  would like to work on this issue

**Comment by LakshyaSatpal** [comment]
@palisadoes I would like to work on this.

**Comment by Cioppolo14** [comment]
@Veer0x1 I am going to assign this to you.  Please note, you have a history of closing PRs before merging, and we do not want this to continue with this issue.  Also, notify us if you are no longer interested in an issue you are assigned.  Thank you.

**Comment by varshith257** [comment]
> @Veer0x1 I am going to assign this to you. Please note, you have a history of closing PRs before merging, and we do not want this to continue with this issue. Also, notify us if you are no longer interested in an issue you are assigned. Thank you.
@Cioppolo May I know the reason for not assigning me?

**Comment by Veer0x1** [comment]
> @Veer0x1 I am going to assign this to you. Please note, you have a history of closing PRs before merging, and we do not want this to continue with this issue. Also, notify us if you are no longer interested in an issue you are assigned. Thank you.

Yes I'll make sure I won't repeat that mistake again.

**Comment by xoldyckk** [comment]
> > @Veer0x1 I am going to assign this to you. Please note, you have a history of closing PRs before merging, and we do not want this to continue with this issue. Also, notify us if you are no longer interested in an issue you are assigned. Thank you.
> 
> @palisadoes @xoldyckk @Cioppolo14 May I know the reason for not assigning me?

idk wasn't me

**Comment by palisadoes** [comment]
> > @Veer0x1 I am going to assign this to you. Please note, you have a history of closing PRs before merging, and we do not want this to continue with this issue. Also, notify us if you are no longer interested in an issue you are assigned. Thank you.
> 
> @palisadoes @xoldyckk @Cioppolo14  May I know the reason for not assigning me?

The rationale for not assigning was that we wanted someone with provable GraphQL experience or an active GitHub profile. This is clearly stated in the beginning of the issue.

We could not find evidence of either based on your profile.

This unfortunately this was not conveyed to you at the time.

We have a published system for assignments. Overriding assignments without consultation is not advised.

I will reassign.

**Comment by palisadoes** [comment]
Also as stated in the issue description, this is both an important feature and one with planned dependencies. 

We wanted a reasonable assurance of success for these reasons, which is why we had the provable experience threshold.

**Comment by varshith257** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/f9ab8b27-755a-4e06-bda4-494d6e9d2b3f)
@palisadoes  @xoldyckk I started working on it after assigned to me and am done with DB Schema for both  Event Volunteer Group and Event Volunteer. 
Just now came to get any suggestions or reviews about this DB schema and planned to start with Queries and mutations. But came to know this issue is unassigned. For a GraphQL coding experience have done a collaborated project in a hackathon. Due to its deployment issues haven't been pushed to my GitHub profile.

**Comment by palisadoes** [comment]
Thanks for the explanation, though unfortunate, the decision stands for the reasons stated previously.

There will be other follow up GraphQL issues in the near future.

**Comment by varshith257** [comment]
Eagerly waiting for the series of the issues 😀

**Comment by Veer0x1** [comment]
@palisadoes that recurring meeting part for this issue isn't clear to me. Can you please elaborate more on it. Do we want the same volunteer group to assigned for every instance of that recurring event?

**Comment by palisadoes** [comment]
Get in contact with the person working on recurring meetings to make sure they are aware of your work.

Coordinate with them to make sure your design will eventually work with minor modifications with recurring meetings.

The scope of this issue is to make this work for a single instance of an event

**Comment by Veer0x1** [comment]
@palisadoes what does `List of Event Volunteer Types` mean in EventVolunteerGroups Schema.

**Comment by palisadoes** [comment]
Documents in the `Event Volunteer Collection`

**Comment by Community-Programmer** [comment]
@palisadoes 

When creating a volunteer, we need one more field the ` groupId` parameter that will ref to `create volunteer group` to associate the volunteer with a specific volunteer group......as we can have multiple groups for same event for different task

For Example:
One group for performing Task A and Other B for the same event

This approach allows each volunteer to be associated with a specific group within the same event.

Also we can query volunteers based on the `groupId` to get a list of volunteers for a specific group.

**Comment by Community-Programmer** [comment]
@Veer0x1 

You continue with this issue, creating models, mutations, and queries for the same. 
Only ensure one thing: when editing `event.ts` model, just make sure none of the fields are touched. Just add the required field, for example, one named `volunteerGroups` that will refer to the volunteer group model, etc. 
Also, make this field optional; by default, no groups are assigned, and it will be managed while creating the event. 

Since you have to add this feature for single recurring events only, ensure that your created mutation adds only volunteer groups to those events whose recurring is set to `False` and have a recurrence of any type, such as `"ONCE," "DAILY," "WEEKLY," "MONTHLY," "YEARLY"`. 

Also, ensure flexibility so that it can be extended for recurring events with minimal changes, as mentioned in the issue we later have to extend it for recurring events also.

Thank You

**Comment by palisadoes** [comment]
> @palisadoes
> 
> When creating a volunteer, we need one more field the ` groupId` parameter that will ref to `create volunteer group` to associate the volunteer with a specific volunteer group......as we can have multiple groups for same event for different task
> 
> For Example: One group for performing Task A and Other B for the same event
> 
> This approach allows each volunteer to be associated with a specific group within the same event.
> 
> Also we can query volunteers based on the `groupId` to get a list of volunteers for a specific group.

Yes a group ID would be required

**Comment by palisadoes** [comment]
@Veer0x1

How's progress on this? It's been almost 2 weeks.

**Comment by Veer0x1** [comment]
> @Veer0x1
> 
> How's progress on this? It's been almost 2 weeks.

I'm working on it. Actually I'm parallerly working on upgrading mongoose to v8, so I'm trying to first complete that task, so that I can use the mongoose 8 in my resolvers for this PR.

**Comment by palisadoes** [comment]
@Veer0x1 

1. We cannot wait on the mongoose upgrade to implement this feature.
2. The mongoose issue has been inactive for 10 days so far.
3. I have to unassign you.

Please focus on mongoose and/or other issues that are not blocked by the mongoose upgrade.

**Comment by LakshyaSatpal** [comment]
I would like to take this. Please assign

**Comment by LakshyaSatpal** [comment]
@palisadoes Need some context of the `invited` and `assigned` field for EventVolunteer collection. 
1. EventVolunteer will be `invited` to EventVolunteerGroup or Event?
2. same for `assigned`.

Also, since the EventVolunteer and EventVolunteerGroup collections are very related, can I just do them in a single PR?

**Comment by palisadoes** [comment]
1. Invited / assigned to the EventVolunteerGroup
2. CRUD will be required for the above
3. `response` tracks whether the User has confirmed their participation

We've been having difficulties with really large PRs with many dozens of files to review. Splitting the work into the two PRs mentioned will help to speed things up.

**Comment by LakshyaSatpal** [comment]
@palisadoes Can you give some context about the `Number of volunteers required` field for EventVolunteerGroup?

**Comment by palisadoes** [comment]
It helps in helping the organizers whether any more volunteers need to be added

**Comment by lakshz** [comment]
@palisadoes EventVolunteer should be connected to an EventVolunteerGroup, necessarily? 
Or, `groupId` must be non-null?

**Comment by palisadoes** [comment]
The group ID is mandatory. Someone related to an event is going to want volunteers to handle catering. That would be the role/group the volunteers would be a part of. 

Volunteers without a grouping won't easily know what they generally have been assigned to do.

**Comment by palisadoes** [comment]
Can this issue be closed?

**Comment by lakshz** [comment]
@palisadoes Yes. 2 pull requests were merged for this issue.

**Comment by palisadoes** [comment]
Are there any issues in Admin to create screens? I don't see any.
