### ISSUE TITLE
Feature Request: Building an OTP verification system for the users registering on the talawa website.

### ISSUE THREAD

**Issue by adi790uu** [PalisadoesFoundation/talawa-api#1676]
**Is your feature request related to a problem? Please describe.**
The users registering on the talawa website can give any random email and an account is created based on that, an otp system will help in verification of the user as well as user email id.

**Describe the solution you'd like**
Building an OTP system such that when user is signing up an OTP is sent to the email id provided, the user enters the OTP sent for verification and for the signup to be successfull.

**Additional context**

https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/c2fc8ba9-aec0-46d2-892c-c6d16546d86e

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship

**Comment by adi790uu** [comment]
I would like to take this up if this is valid!

**Comment by palisadoes** [comment]
1. We had this before and decided to remove it to focus on post login features.
2. We will return to this at a later point
3. @Cioppolo14 take note
