### ISSUE TITLE
eslint Error on existing codebase

### ISSUE THREAD

**Issue by wingman47** [PalisadoesFoundation/talawa-api#1693]
**Describe the bug**
Getting eslint error when trying to git commit after upstreaming my fork yesterday which added stricter eslint rules. There are linting errors for already existing code.

**To Reproduce**

1. Perform git commit.

**Expected behavior**
There shouldnt be any linting error for the existing codebase.

**Actual behavior**
There arelinting error for the existing codebase.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/49762303/48613c3b-be9b-4594-8dc2-d35886884433)

**Comment by varshith257** [comment]
When performing git commit the files in the test folder are majorly performing this eslint error behavior because of using any, non-null assertions and unused variables. We can fix it by explicitly mentioning the type or unknown instead of any and Avoid using the non-null assertion operator (!) Instead, ensuing the variables are properly initialized.
 for ex : 
C:\Users\91970\Desktop\talawa\talawa-api\tests\utilities\uploadImage.spec.ts
   58:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  116:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 953 problems (1 error, 952 warnings)
Before using specific type:
![WhatsApp Image 2024-01-15 at 17 26 33_eb78f802](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/9d083089-1994-4b5e-a0b8-33f105485644)

After using InterfacePngImage:
![WhatsApp Image 2024-01-15 at 17 24 45_ab7f4f83](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/84c7d949-c49d-455c-8048-57f00613b3dd)

if it is valid way, I would like to work on this issue.

**Comment by wingman47** [comment]
> When performing git commit the files in the test folder are majorly performing this eslint error behavior because of using any, non-null assertions and unused variables. We can fix it by explicitly mentioning the type or unknown instead of any and Avoid using the non-null assertion operator (!) Instead, ensuing the variables are properly initialized.
>  for ex : 
> C:\Users\91970\Desktop\talawa\talawa-api\tests\utilities\uploadImage.spec.ts
>    58:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
>   116:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
> 
> ✖ 953 problems (1 error, 952 warnings)
> 
> Before using specific type:
> ![WhatsApp Image 2024-01-15 at 17 26 33_eb78f802](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/9d083089-1994-4b5e-a0b8-33f105485644)
> 
> After using InterfacePngImage instead any:
> ![WhatsApp Image 2024-01-15 at 17 24 45_ab7f4f83](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/84c7d949-c49d-455c-8048-57f00613b3dd)
> 
> if it is valid way, I would like to work on this issue.

Did you get any error in the above files in the image I have attached above?

**Comment by NamitBhutani** [comment]
The errors only come up for the files that are modified and added to the staging area. This is a part of our efforts to slowly improve the linting of the codebase. So please resolve the issues and commit! :D

**Comment by wingman47** [comment]
> The errors only come up for the files that are modified and added to the staging area. This is a part of our efforts to slowly improve the linting of the codebase. So please resolve the issues and commit! :D

Ok... So I just want to confirm that I will need to solve the linting issues for the existing codebase that I haven't changed? (I did git pull yesterday)

**Comment by NamitBhutani** [comment]
> > The errors only come up for the files that are modified and added to the staging area. This is a part of our efforts to slowly improve the linting of the codebase. So please resolve the issues and commit! :D
> 
> Ok... So I just want to confirm that I will need to solve the linting issues for the existing codebase that I haven't changed? (I did git pull yesterday)

No! only for the files you are editing, i.e all the files that are in staged area should be free of linting errors.

**Comment by wingman47** [comment]
> > > The errors only come up for the files that are modified and added to the staging area. This is a part of our efforts to slowly improve the linting of the codebase. So please resolve the issues and commit! :D
> > 
> > Ok... So I just want to confirm that I will need to solve the linting issues for the existing codebase that I haven't changed? (I did git pull yesterday)
> 
> No! only for the files you are editing, i.e all the files that are in staged area should be free of linting errors. For example in the screenshot you have attached only the errors in Event.ts have been mentioned, so fix them and you should be good to go.

But I didn't change anything in the Event.ts file. There are linting issues in other files as well that I haven't touched which isn't shown in the screenshot I have attached. 
Now the error is asking me to solve these linting issues which already exists in the develop branch right now.
Sorry if I am missing something.. 😅

**Comment by palisadoes** [comment]
@NamitBhutani 

Wasn't this fixed with your PR? Is the messaging in the script not sufficiently instructive?
- https://github.com/PalisadoesFoundation/talawa-api/pull/1677

@wingman47 

Have you merged with the latest upstream?

**Comment by NamitBhutani** [comment]
> @NamitBhutani 
> 
> Wasn't this fixed with your PR? Is the messaging in the script not sufficiently instructive?
> - https://github.com/PalisadoesFoundation/talawa-api/pull/1677
> 
> @wingman47 
> 
> Have you merged with the latest upstream?

Yes, it was fixed, I have tried to replicate it locally and it works as expected, probably their local is out of sync.

**Comment by palisadoes** [comment]
@NamitBhutani You are correct. It is fixed, I just tested it on the same file mentioned by @wingman47 


![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/1139378a-3bb0-4563-83d5-569157170698)

**Comment by palisadoes** [comment]
@wingman47 

1. Please lint your code and submit. It will fail the PR tests too if not fixed.
2. Merge with the latest upstream
3. Closing

**Comment by palisadoes** [comment]
@wingman47 

1. Please lint your code and submit. It will fail the PR tests too if not fixed.
2. Merge with the latest upstream
3. Closing
