### ISSUE TITLE
API: GitHub Action - Failure when PRs made against the main branch

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1694]
**Is your feature request related to a problem? Please describe.**

We are having an increasing number of PRs made against the `main` branch when they should be made against the `develop` branch.

**Describe the solution you'd like**
1. We need a separate job added to the end of this GitHub action file that has no `needs: ` statement that tests to make sure that the target branch of the PR is `develop`. It must fail without affecting any of the other jobs in the file. The aim of this is to alert contributors of their likely mistake as in most cases we will be merging against `develop`
    - https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml
1. There must be messaging that explains that the job is testing whether the `develop` branch is being used.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

Sample PR made against `main`
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1363

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by meetulr** [comment]
I'd like to work on this.

**Comment by LakshyaSatpal** [comment]
I can take this issue.

**Comment by Cioppolo14** [comment]
@meetulr Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.
