### ISSUE TITLE
[Bug report] Update Profile Mutation not found

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#170]
**Describe the bug**
Missing Update Profile Mutation to let the user update there profile description after the account creation.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open GraphQL Playground 
2. Check mutation section
3. Mutation doesn't exist

**Expected behaviour**
A mutation should exist which let the user update the profile.

**Actual behaviour**
Mutation doesn't exist

**Additional details**
This needs urgent attention as it is affecting the frontend UI and I am working on it.

**Comment by palisadoes** [comment]
@sumitra19jha please close this if you are no longer working on it.
