### ISSUE TITLE
Command `npm run import:sample-data -- [args]` not working

### ISSUE THREAD

**Issue by git-init-priyanshu** [PalisadoesFoundation/talawa-api#1705]
**Describe the bug**
When executing the command npm run import:sample-data -- [args], it results in a series of errors.

**To Reproduce**

1. Navigate to "talawa-api" directory
2. Run the command `npm run import:sample-data -- [args]`

**Expected behavior**
The command should execute without errors, and the sample data should be successfully imported into the database.

**Actual behavior**
The command fails to import sample data to the database and also throws a bunch of errors.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/110045644/913f12de-0067-4d19-9e76-249d6d52fa28)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@git-init-priyanshu  It already has been solved by #1679 
Just sync your fork for updated PR's and run it. It's working fine.

**Comment by git-init-priyanshu** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
Closing. This works on the latest upstream running the recommended node v20
