### ISSUE TITLE
Address npm Audit Warnings: glob-parent and minimist vulnerabilities

### ISSUE THREAD

**Issue by shivang-16** [PalisadoesFoundation/talawa-api#1706]
### Issue Summary:
I encountered npm audit warnings related to vulnerabilities in the dependencies of this project. The affected packages are `glob-parent` and `minimist`. 

### Vulnerabilities:
1. **glob-parent:** [GHSA-ww39-953v-wcq6](https://github.com/advisories/GHSA-ww39-953v-wcq6)
   - Severity: High
   - Fix: `npm install pm2@5.3.0` (breaking change)

2. **minimist:** [GHSA-xvch-5gv4-984h](https://github.com/advisories/GHSA-xvch-5gv4-984h)
   - Severity: Critical
   - Fix: `npm audit fix --force` (will install pm2@5.3.0, breaking change)
  

### Proposed Solution:
1. Upgrade `pm2` to version `5.3.0` using `npm install pm2@5.3.0`.
2. Run `npm audit fix --force` to address remaining vulnerabilities.

<img width="980" alt="Screenshot 2024-01-17 at 12 55 50 AM" src="https://github.com/PalisadoesFoundation/talawa-api/assets/125182653/33c74657-2f64-4f12-9ffb-e756996b4021">

**Comment by varshith257** [comment]
Would like to work on this

**Comment by palisadoes** [comment]
Closing. We get regular automated vulnerability updates via dependabot that also create PRs with the fixes.
