### ISSUE TITLE
Enhancement  -  /codecov/patch and /codecov/project

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#1709]
**Is your feature request related to a problem? Please describe.**

While I am spectating the PRS most of them failing  /codecov/patch and /codecov/project tests before merging. We can fix it by solving conflicts.

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/249f1144-aee8-45be-b8d6-cfdd56fb3ef5)

Here some of the files have no tests with 0.00% and in some files, a few lines did not include tests.

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/d6c8239c-981e-451d-a71d-34902d3d7b5e)

**Describe the solution you'd like**

1) Write tests for the lines missing in tests of conflicting files to pass codecov/patch test.
2) The files in the **src/utilities/PII/**  folder ( isAuthorized.ts, encryption.ts, decrytion.ts ) aren't used in the entire code base which is verified through VS Code Shortcut (Ctrl + Shift + F ) and also manually verified.

![WhatsApp Image 2024-01-17 at 03 19 45_1761afd0](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/af531b2c-d70f-43c8-9971-317f4f6fbf17)

![WhatsApp Image 2024-01-17 at 03 20 49_3894ba80](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/7a8cba1f-65c4-4230-8c20-3fd2f7522c5c)

![WhatsApp Image 2024-01-17 at 03 22 04_f0c4715b](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/e2db4e53-eb45-4e03-908d-f291805de3e8)

i) Maybe these files should be deleted, if any part of the code in the code base is not using these functions.  
ii) If they are used, writing tests for these files can fix this issue.

**Approach to be followed (optional)**
  NA

**Additional context**
This issue can be checked at any PR's that are closed or still open.
https://github.com/PalisadoesFoundation/talawa-api/pull/1702
https://github.com/PalisadoesFoundation/talawa-api/pull/1687

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
If it is valid, would like to work on this issue.

**Comment by palisadoes** [comment]
1. Closing our code coverage target is 95% and we are at 97%.
2. There will soon be issues to utilize these orphaned libraries
