### ISSUE TITLE
API: Fix the usage of userType

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1711]
**Describe the bug**

1. The schema doesn't apply a person's `userType` by organization. 
1. The `userType` is currently a part of the `User` definition not part of a `userOrganization` definition or something similar. 
    1. This means that an `Admin` is an `Admin` for all organizations which grants the same rights as a `SuperAdmin`. This is not the intention.
    2. This has created historical confusion in the `Admin` and `SuperAdmin` roles.

This needs to be resolved as it is a showstopper bug.

**Expected behavior**

These conditions must apply:

1. The `userType` must be applied per person per organization.
2. Each `SuperAdmin` must be a `SuperAdmin` for all organizations
3. All other `userType`s would be on a per organization basis

This means that all code logic referencing the `userType` will need to be updated accordingly.

_TALAWA API_

Additional considerations include:

1. New user registrations will need to default to the `userType` `USER` if not done so already
1. The Schema will need to be updated to reflect this requirement
1. Mutations and queries will need to be updated and in some cases new ones added.

_TALAWA ADMIN_

Additional considerations include:

1. The current screen that edits a person's userType will need to be updated. A design is being created for this and will be reflected in the Figma file on our Design Guide page:
    1. https://docs.talawa.io/docs/design/ux/ux-design-system

_TALAWA MOBILE_

No expected changes as userType isn't referenced in the code base

**Actual behavior**

- The schema doesn't apply a person's `userType` by organization. 

**Screenshots**

The current schema:

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/cbd791b2-3ff7-44b9-b936-023c9d979b01)

**Additional details**

Related issues:

1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
Would like to work on this issue.

**Comment by NayOoLwin5** [comment]
Would like to work on this issue.

**Comment by AVtheking** [comment]
I would like to work on this issue

**Comment by Pranavx1** [comment]
Can i work on this?

**Comment by Cioppolo14** [comment]
@KoraboinaSankeerth You requested this in both the api & admin repos. Since you had no issues, I did give you both. These are both noted as urgent issues, so if having both will slow down the resolution, please unassign yourself from one, so we can make sure this gets addressed as fast as possible.  Thank you!

**Comment by AVtheking** [comment]
Hey @palisadoes if the admin is going to per organisation then I think there is no purpose of user type field as we already have adminfor field in the user schema which contain the list of organisation in which user is admin ,we can directly check from it . Instead of user type field we can have Is_Super_Admin field

**Comment by palisadoes** [comment]
1. The super admin flag would solve part of the workflow
1. We need the user type of USER and NON_USER because the app will need to distinguish between people in the database who do, and do not, use the app. 
    1. This will be required for the check-in process to record attendance of Members who cannot, do not want or have yet to use the app. 
    1. The current registration process assumes email address and Internet access, but older or incapacitated people may not have access. 

Other challenges to consider:

1. Ways to uniquely identify people. (We have an issue to create an `identifier` auto incrementing field which could help)
1. How to assign Admin rights only to `USER`s in a clean way as suggested by @xoldyckk 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1633#issuecomment-1880168423

How would can we best achieve all these goals?

**Comment by AVtheking** [comment]
How will the user would get userType =Non_user as the user registering through mobile app and web portal will get userType=user by default?

**Comment by palisadoes** [comment]
In at least these circumstances:

1. An administrator decides to add them manually. This will allow the person to be checked-in to future events even though they don't use the app.
1. During the event check-in process where anyone who attends an event may need to be added to the system. 

Both these features are planned to be added soon.

**Comment by xoldyckk** [comment]
> 1. The super admin flag would solve part of the workflow
> 2. We need the user type of USER and NON_USER because the app will need to distinguish between people in the database who do, and do not, use the app.
>    
>    1. This will be required for the check-in process to record attendance of Members who cannot, do not want or have yet to use the app.
>    2. The current registration process assumes email address and Internet access, but older or incapacitated people may not have access.
> 
> Other challenges to consider:
> 
> 1. Ways to uniquely identify people. (We have an issue to create an `identifier` auto incrementing field which could help)
> 2. How to assign Admin rights only to `USER`s in a clean way as suggested by @xoldyckk
>    
>    1. [feat: Created an User Type Flag Field - AppUserType #1633 (comment)](https://github.com/PalisadoesFoundation/talawa-api/pull/1633#issuecomment-1880168423)
> 
> How would can we best achieve all these goals?

I should remind that this suggestion was made considering the approach used in that PR, it's not a bulletproof suggestion.

**Comment by palisadoes** [comment]
@xoldyckk Even so, the points need to be considered in the PR for this issue for their applicability.
@AVtheking Let us know your updated final proposed solution would be.

**Comment by AVtheking** [comment]
ok then we can go with the userType field but I think we can have separate model for the non-users as temp user with basic fields of the user and as we already have the field adminFor which contain the list of organization for which the user is admin so I think there is no need to specify user as admin in a different field

**Comment by AVtheking** [comment]
when the non user would become user then we can migrate data to user model

**Comment by AVtheking** [comment]
with this we can easily provide admin right only to user as we would querying on User model only and Non User would be stored in different model

**Comment by palisadoes** [comment]
1. It makes more sense to make User be the default with the minimum required fields with additional data added for app users. 
    1. For example, an `AppUser` object / class would inherit `User` object / class characteristics to have expanded access to fields. This is what @xoldyckk was suggesting. 
    1. It's going to require more coordination with the other repos and the earlier we start the better before we have too much legacy code.
    1. `adminFor` would be under `AppUser`
    1. A `superAdmin` flag would be a part of `AppUser`, and when set, there would be no need for `adminFor`. This would make the logic easier because when a new organization is added, you wouldn't have to add the `superAdmin`s to it because the flag was already set.
1. Having temporary users and migrating data back and forth is going to be very cumbersome. We are trying to move towards greater simplicity.

**Comment by palisadoes** [comment]
@KoraboinaSankeerth 

Are you still working on this? It's a key feature on which many others rely.

**Comment by palisadoes** [comment]
Unassigning due to no PR activity or assignee comments in the past 10 days

**Comment by AVtheking** [comment]
Can I work on this issue ,although I am already assigned with two issues but the one in mobile repo is ready to be merged

**Comment by manishjha-04** [comment]
Hey can I work on this ?

**Comment by NayOoLwin5** [comment]
I would like to work on this

**Comment by git-init-priyanshu** [comment]
I would love to work on this issue. Thanks.

**Comment by Cioppolo14** [comment]
I assigned this to the first person on the list with less than 2 issues.  I appreciate that sometimes issues have PRs close to merging, but it becomes too much for us to manage and track without strictly following the 2 issues rules. Thank you for understanding this policy.

**Comment by palisadoes** [comment]
1. Unassigning @NayOoLwin5 
2. You already have two issues in Admin with active PRs. Please give others a chance.

**Comment by varshith257** [comment]
I would like to work on it

**Comment by palisadoes** [comment]
@AVtheking Let us know immediately if you have the time to complete this in about a week. If not, we'll need to assign it to someone else.

1. Assigning to the first person who wasn't unassigned with less than 2 issues and a successful merge history
2. This is really needs to be resolved quickly. There are many dependent issues and PRs.

**Comment by AVtheking** [comment]
Yes I can complete this in a week

**Comment by AVtheking** [comment]
@palisadoes  sir should I go with appUser model for this issue ?

**Comment by palisadoes** [comment]
Yes

**Comment by AVtheking** [comment]
more clarity on this approach would be helpful sir

**Comment by palisadoes** [comment]
It was explained in the link. 

What specific clarification do you need? That would help with the answer. Please be specific with your concerns so that we can figure out a good long term solution

**Comment by AVtheking** [comment]
Like which fields would be move to the appUser model  apart from adminFor and isSuperAdmin field

**Comment by AVtheking** [comment]
thanks ,I guess we need to move more fields to the appUser than suggested by you in the link,

**Comment by palisadoes** [comment]
You could start with posting a sample schema  of what you're thinking of doing here. That would help with the review prior to creating a PR

**Comment by AVtheking** [comment]
ok sur

**Comment by palisadoes** [comment]
1. We may have situations where someone attends an event and wants to join the organization, but doesn't wan to use the app. This is will help the Admin keep in contact with them somehow. They will need to be added to the DB and made a member of an organization at the door of the event. This means that they will have a membership request, but just not submitted by them. This will need to be moved to User.
2. Similarly, they may register for events at the door too, or ask an admin to do it for them. This will need to be moved to User.

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/89a1b84c-dcec-4b90-8c43-8e808352764e)

Rename `AppUser` to `AppUserProfile` for clarity.

**Comment by palisadoes** [comment]
FYI - We'll soon be creating issues to convert this from `Boolean` to `[Organization]`. This may create conflicts with your PR if it is merged before. Approvals will be per organization, not per API instance (all organizations)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/b667ff7d-cead-4739-898f-5be946b0f34c)

**Comment by palisadoes** [comment]
@AVtheking Please proceed. The solution was mostly agreed upon in that referenced issue. The fields with the suggested modifications will meet our needs.

**Comment by AVtheking** [comment]
Ok sir

**Comment by AVtheking** [comment]
@palisadoes  sir I want to ask that whether a super admin(if he is not admin of that org), can change organization related things or not ?

**Comment by AVtheking** [comment]
@palisadoes  sir should I deprecate the updateUserType mutation as there will be no userType field in the User model ,or modify it to make  the user superUser?

**Comment by AVtheking** [comment]
One more thing @palisadoes  sir in organization model should I change the admin field refrence to  AppUserProfile or it is okay to be refrenced to the User ?

**Comment by palisadoes** [comment]
User

**Comment by palisadoes** [comment]
> @palisadoes sir should I deprecate the updateUserType mutation as there will be no userType field in the User model ,or modify it to make the user superUser?

Yes

**Comment by AVtheking** [comment]
Ok sir
