### ISSUE TITLE
Docker not auto-reloading on code changes

### ISSUE THREAD

**Issue by harmanbatheja15** [PalisadoesFoundation/talawa-api#1728]
#### Is your feature request related to a problem? Please describe.
I am encountering an issue with the automatic reloading of my Node.js application when changes are made to the code within the Docker container. Currently, I have to manually restart the server every time I make modifications to my code.

#### Describe the solution you'd like
I would like the Docker container to automatically reload my Node.js application whenever changes are made to the source code. This would significantly improve the development workflow by eliminating the need for manual server restarts.

#### Approach to be followed
I've ensured proper setup of the project using Docker, and adjusted volumes in the Docker Compose file for seamless automatic code reloading.

**Comment by harmanbatheja15** [comment]
I want to work on this issue.

**Comment by AbhishekCS3459** [comment]
@EshaanAgg @harmanbatheja15 is there any problem regarding this issue, it can be easily solved by mounting volumes.
Can work on this issue?
