### ISSUE TITLE
Modifying createdAt field inside the models

### ISSUE THREAD

**Issue by KunalAnkur** [PalisadoesFoundation/talawa-api#173]
In `GroupChatMessage` and `DirectChatMessage` model, `type` of `createdAt` property is `String`, unlike another model it's `Date`. It should be changed from `String` to `Date` for sake of consistency and it also makes more sense.

The functionality of the code remains the same. It's just improving the quality of code.

![Screenshot from 2021-03-20 17-02-21](https://user-images.githubusercontent.com/57923976/111882795-83fb6300-89dd-11eb-8a33-755d4691b49c.png)

**Comment by Priyaraj17** [comment]
Is this issue still open? May I work on it?

**Comment by KunalAnkur** [comment]
@Priyaraj17  I am already working on it. You can check other issues  🙂.

**Comment by Priyaraj17** [comment]
> @Priyaraj17  I am already working on it. You can check another issues  🙂.

Sure brother 😊
