### ISSUE TITLE
API: Deprecate Titles for Non-Pinned Posts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1739]
**Is your feature request related to a problem? Please describe.**

Our post feature has never worked as expected. The original idea was for only pinned posts created by Admins requiring titles to attract greater attention, all other posts would not have them.

Social media platforms do not require titles for news feed posts, this is because it adds a step that increases the risk of low interaction rates. We need to implement this as per the original design.

**Describe the solution you'd like**

_API_
1. The API must only require titles for pinned posts. All other post types must generate an appropriate error if a title is provided. 
1. Pinned posts can only be created by Super Admins or Admins for the organization where the post was created

_Admin_
1. Only pinned posts must require titles. 
1. Non Pinned Posts
    1. Post screens not related to pinned posts must not display titles (As they won’t exist)
1. There must be no CRUD activity related the titles of regular post
1. Pinned posts can only be created by Super Admins or Admins for the organization where the post was created

_Mobile_
1. The mobile app must not allow the creation of pinned posts as this is an Admin function
1. There must be no CRUD activity related the titles of regular post
1. Pinned posts can only be created by Super Admins or Admins for the organization where the post was created

_Other_ 
1. All tests for this functionality update must be valid
1. No other functionality must be altered

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

Related issues:

- https://github.com/PalisadoesFoundation/talawa/issues/2351
- https://github.com/PalisadoesFoundation/talawa-api/issues/1739
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1486

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
I would like to work on this.
