### ISSUE TITLE
Inspection GitHub Action Fails on Push 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1745]
**Describe the bug**

Our current GitHub action that inspects the schema is only implemented on pushes. This means that schema errors may not be detected until after the PR has been merged 
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/inspect.yml

**To Reproduce**

1. Have a schema error.
1. It is not detected by the pull request action
1. The PR is merged
1. Schema error is detected
    1. https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7673337932/job/20915758114

**Expected behavior**

1. The `Check Schema` job in the  `inspect.yml` file must be moved to the `pull-request.yml` file
   1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/inspect.yml
   2. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml
1. The  `inspect.yml` file must be removed
1. The `Check Schema` job must:
    1. automatically detect the target branch of the PR and do its testing against the equivalent branch in Talawa Admin (if required)
    1. run independently of any other jobs in the `pull-request.yml` file

**Actual behavior**

- See above

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue.

**Comment by aialok** [comment]
#1696 in this issue, we are already merging the inspect.yml to push.yml.

**Comment by palisadoes** [comment]
For the reasons stated here we need this in pull requests instead.

It's causing hardship. Sorry about not finding this one. I remember creating it but didn't find it in my search.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1745

**Comment by palisadoes** [comment]
Please work on this for pulls

**Comment by palisadoes** [comment]
Closing for the other o issue
