### ISSUE TITLE
Docker volume (for talawa-api-container) for live-updates

### ISSUE THREAD

**Issue by NamitBhutani** [PalisadoesFoundation/talawa-api#1747]
**Is your feature request related to a problem? Please describe.**
Currently whenever we edit the source code, the docker image has to be rebuilt to have the changes reflect while using Docker.

**Describe the solution you'd like**
Mount the source code as a volume in the container and a separate named volume for node_modules so that they are not affected by the source code mount as both of them are in the same parent directory.

**Describe alternatives you've considered**
Only alternative is to build the docker image again whenever we make any changes to the code.

**Comment by Cioppolo14** [comment]
Thank you for this idea. This is not planned for now, so I am going to close it.
