### ISSUE TITLE
Implementing multi stage builds to Dockerfile

### ISSUE THREAD

**Issue by vasujain275** [PalisadoesFoundation/talawa-api#1751]
**Is your feature request related to a problem? Please describe.**
Currently, our Dockerfile lacks the implementation of multi-stage builds, leading to larger image sizes. This not only affects the efficiency of our deployment process but also contributes to increased resource consumption on cloud instances. Large Docker images can negatively impact both performance and security in cloud environments.

**Describe the solution you'd like**
Implement multi-stage builds in the Dockerfile to optimize image size, improve deployment speed, and enhance the overall efficiency of our containerized applications. Multi-stage builds allow us to use separate stages in the Dockerfile, enabling us to build and compile code in one stage and then copy only the necessary artifacts to the final image. This will result in smaller image sizes without compromising the functionality of the application.

**Describe alternatives you've considered**
One alternative is to manually clean up unnecessary files and dependencies after building the application, but this can be error-prone and time-consuming. Multi-stage builds offer a more automated and standardized solution to achieve smaller and more optimized images.

**Approach to be followed (optional)**
1.   Identify the different stages required for building and running the application.
2.   Implement the necessary build and compile steps in the first stage.
3.   Copy only the essential artifacts from the first stage to the final image in the second stage.
4.   Ensure that the final image contains only the dependencies and files required for runtime.
5.   Test the multi-stage build locally to verify its effectiveness and correctness.
6.   Update the documentation to reflect the changes made to the Dockerfile.

**Additional context**
Implementing multi-stage builds is crucial for optimizing our Docker images, especially in cloud instances where image size directly impacts resource utilization and deployment speed. Smaller images not only contribute to faster deployment but also improve the security and performance of our cloud API instances. The reduction in image size leads to decreased network transfer times, lower storage costs, and a minimized attack surface, ultimately enhancing the overall efficiency of our containerized applications in cloud environments.

**Comment by Shubh152** [comment]
Please assign this issue to me.

**Comment by NayOoLwin5** [comment]
I would like to work on this issue

**Comment by vasujain275** [comment]
Hi @Shubh152 @NayOoLwin5, appreciate your sentiments to contribute to talawa-api, but this issue is linked with the Issue #1428 which I am working on. That's why I raised this issue because I am already working on it.

**Comment by Cioppolo14** [comment]
@vasujain275 I am assigning this to you, because as you said, because it is related to the other issue you are working on.  In the future, please comment right away, it will help me track the moving pieces. Thank you!

**Comment by vasujain275** [comment]
@Cioppolo14 Thank you for understanding, I will remember to comment first next time.

**Comment by vasujain275** [comment]
Update on this - 
1. There is a bug in the build process that is taking time to debug.
2. Dockerfile is ready as its reduced size of docker images from 2GB to 180MB.
3. Will try to figure out build error and raise a PR.

**Comment by vasujain275** [comment]
Update - 
1. Still not able to find the bug in build process.
2. @Cioppolo14 It is taking a lot of time to debug and I think some other person should try it with a fresh perspective.
3. So I am unassigning myself and let others try, sorry for the delay on my end. Here is the Dockerfile for anyone to refrence  - 
```Dockerfile
FROM node:lts AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run prebuild
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=build /usr/src/app/build /app/build
EXPOSE 4000
CMD ["npm", "run", "start"]
```
4. If I solve this issue in the future, I will update the assigned person with the information. Sorry again for the delay

**Comment by varshith257** [comment]
@vasujain275 Can I know the error what you facing? Currently I am working in talwa-admin to implement docker-support. I do have bit experience in deploying applications using docker

**Comment by varshith257** [comment]
@palisadoes Can I make improvements of docker installation as we discussed in `talawa-admin` by  this issue ?

**Comment by palisadoes** [comment]
@varshith257 

1. Please discuss your plans with the group here. We need coordination of the activities.
2. If the use of Docker Hub requires the creation of an account for that service, it will need to be in the name of The Palisadoes Foundation

**Comment by varshith257** [comment]
@palisadoes we need creation of account for Docker Hub to publish the image of talawa-api and need a credentials for it and same have to be used for docker. Need your review for this

**Comment by vasujain275** [comment]
@varshith257 sorry for late reply, 
1. There is an error in npm install command during docker image build process, It is getting stuck there.
2. I need to modify the Deploy to Cloud VPS CI/CD GitHub action according to the changes you implement in the Dockerfile
3. The Multi-Stage Docker File is almost ready as I commented above, you need to just debug the “Stuck on npm install process error”.
4. The upload of the talawa-api docker image will be handled by the deployment to cloud VPS only. So, no need to implement it separately. 

@palisadoes 
1. As @varshith257 said, we need a Docker Hub Account to upload docker images of talawa api to it. Issue #1428 also require one to make improve the cloud api deploy process.

**Comment by varshith257** [comment]
1.  I noticed that the current talawa-api docker support has no volumes related to code changes. This means that rebuilding has to be done again and again whenever changes are made locally and need to be reflected in the image.
2.  To avoid this, we should use volumes and done building the docker image  with the multi-stage build, as it significantly reduced the image size from 1.8GB to 500MB.

**Comment by varshith257** [comment]
@palisadoes Waiting for your approval for credentials to publish to Docker-Hub

**Comment by varshith257** [comment]
> @palisadoes Waiting for your approval for credentials to publish to Docker-Hub

@Cioppolo14 I have completed all the necessary work and am now waiting for Docker-Hub credentials to upload the image. With continuous support, I believe we can efficiently resolve this issue within a day. I have completed all the work; however, I need assistance with obtaining the necessary credentials. Can you please help me with this matter? I have done all the work waiting for credentials for docker. Can I get your assistance in resolving this matter?

**Comment by vasujain275** [comment]
@varshith257

1. I think the Docker-Hub Image Workflow should not be implemented here.
2. We should upload the new Docker image during the Cloud Deploy Process, which we are implementing in #1428.
3. Go ahead and make a PR with an updated multi-stage Dockerfile.
4. Then I will make changes to the Cloud Deploy CI/CD accordingly and raise the PR in that issue itself.
5. This way, we can have separation of concerns in both the issues.

**Comment by kb-0311** [comment]
@varshith257 @vasujain275 I think if we implement docker volumes for code related changes we can also use volumes for object storage as well in the future especially file uploads.

**Comment by vasujain275** [comment]
@kb-0311 

1. I agree that volumes can be immensely helpful, especially with file uploads.
2. I noticed discussions on #952 and the associated pull request #1168, indicating the need for a better solution for file uploads.
3. In my opinion, Docker volumes could serve as an excellent solution for this issue.
4. However, I believe that updating code within a Docker container is not advisable as a best practice.
5. Nonetheless, utilizing Docker volumes for file uploads would streamline many complexities.

**Comment by kb-0311** [comment]
@vasujain275 Yes I am aware that volumes are generally used for data storage and not for storing code.

I think @varshith257 can explain how he would go about using volumes for code-related changes and how it will reduce the size of the codebase on the VPS.

**Comment by varshith257** [comment]
> @vasujain275 Yes I am aware that volumes are generally used for data storage and not for storing code.
> 
> I think @varshith257 can explain how he would go about using volumes for code-related changes and how it will reduce the size of the codebase on the VPS.

1. Using volumes in Docker in a development environment allows for real-time reflection of code modifications inside the running container without the need to rebuild the entire image
2. . Without volumes, rebuilding the image each time a code change is made can be time-consuming. 
3. If VPS Development is mainly concerned with the Production environment, we might want to create new Docker images every time to ensure that all dependencies are properly encapsulated. But for local development and testing, volumes are a powerful tool.
4. However, storing the entire codebase directly on the VPS can lead to increased storage usage, and updating the code may involve transferring large amounts of data over the network.

@EshaanAgg Your opinion here could be more valuable as discussed in Talawa-Admin

**Comment by kb-0311** [comment]
@varshith257 I wanted to know how the CI/CD pipeline will work on a low level, like basically the control flow of getting changes reflected in the codebase. Please don't copy-paste theoretical AI answers directly, if you are doing that, and try to explain using control flows and nuances instead, that would be very helpful.

@vasujain275 Correct me if I am wrong but the approach you had come up with was that every code change would result in a new talawa-api image being deployed on docker hub -> VPS pulls the latest image from docker hub -> build the image and run the app. 


Let's say you @varshith257, mount the code base to a location on the machine, what will be the end-to-end control flow of the CI/CD pipeline in the repo?

**Comment by vasujain275** [comment]
@varshith257 @kb-0311

1. I think both approaches, one mounting the code as a volume for local development and the other not mounting code and creating a Talawa API image at each new commit, have their advantages. So why not keep both? 
2. We can have a Makefile and two Dockerfiles: Dockerfile.dev and Dockerfile.prod. 
3. We can use both for their use cases. For cloud instances, we will use my suggested method: every code change would result in a new Talawa API image being deployed on Docker Hub. Then, the VPS pulls the latest image from Docker Hub, builds the image, and runs the app. 
4. For local development, we can use the Dockerfile.dev that has the code mounted as a volume for a hot module-like refreshing feature.
5. This way it will reduce the image size significantly for cloud instance and will be for a lot efficient and secure and will also have good local development too.

Example Makefile in my mind -
```make
# Makefile

# Targets for local development
.PHONY: dev
dev:
    docker-compose -f docker-compose.dev.yml up --build

# Targets for production
.PHONY: prod
prod:
    docker-compose -f docker-compose.prod.yml up --build -d

# Clean up
.PHONY: clean
clean:
    docker-compose down -v

```

**Comment by vasujain275** [comment]
@varshith257 What is the progress on new Dockerfile PR? We need the new Dockerfile so that we can continue with our cloud instance testing.

**Comment by varshith257** [comment]
@Cioppolo14  Please assign me this issue. So that I will raise PR

**Comment by kb-0311** [comment]
@vasujain275 @varshith257 Sorry for the confusion guys, I kind of jumbled up between another discussion related to docker, and I did not realize that volumes was being suggested for LOCAL not PROD environment.

**Comment by kb-0311** [comment]
So we will be creating 2 docker files and depending on the environment build image, accordingly after @varshith257 gets officially assigned to the issue?

**Comment by palisadoes** [comment]
1. @noman2002 Is going to be working with you guys on this.
2. We have created a Docker Hub account, and are trying to figure out how to minimize the expected monthly cost for an organization.

**Comment by varshith257** [comment]
@palisadoes  Please assign me this issue. So that I will raise PR

**Comment by varshith257** [comment]
> 1. @noman2002 Is going to be working with you guys on this.
> 2. We have created a Docker Hub account, and are trying to figure out how to minimize the expected monthly cost for an organization.

@palisadoes @Cioppolo14 I Hope this may help to minimize the cost for an organization by applying to DSOS program :
https://www.docker.com/community/open-source/application/

**Comment by vasujain275** [comment]
> > 1. @noman2002 Is going to be working with you guys on this.
> > 2. We have created a Docker Hub account, and are trying to figure out how to minimize the expected monthly cost for an organization.
> 
> @palisadoes @Cioppolo14 I Hope this may help to minimize the cost for an organization by applying to DSOS program : https://www.docker.com/community/open-source/application/

@varshith257 I think this is not what he meant, we want to minimize the monthly cost for an organization that will be using talawa applications. By avoiding for example third party paid services, low server etc.

**Comment by varshith257** [comment]
> Thanks, this is what we needed. However we'll see what other options we can use to keep our docker hub costs down
> 
> * https://www.docker.com/community/open-source/application/

@palisadoes IMO, implementing a registry mirror is also an effective solution to keep docker hub costs down. This means:

1. The first time the user requests the image, the Docker Daemon pulls it from the Docker Hub and cache it and store them locally
2. Then the local registry responds to the user's Docker pull requests, which means subsequent requests for the same image are fetched directly from the local cache
3. It reduces the number of pulls to the organization on Docker Hub and significantly reduces the costs.

For detailed information:
https://docs.docker.com/docker-hub/mirror/#how-does-it-work

**Comment by kb-0311** [comment]
@varshith257 Yes we should use local Registry as cache to minimize network calls , will you be using filesystem as storage driver for the registry>

**Comment by varshith257** [comment]
> @varshith257 Yes we should use local Registry as cache to minimize network calls , will you be using filesystem as storage driver for the registry?
> 
> @vasujain275 What do you two guys think about using local registry only instead of docker hub all together for the talawa-api image, since it is an inhouse image with just two services that can be pulled and stored locally with their image tags? IIRC the use of a remote docker hub deployment of talawa-api image was only suggested because of the race condition of remote SSH commands which could be prevented using some predefined time delays, What are your thoughts?

1. Yes, we are going to use filesystem as a storage driver for the registry.
2. IMO it is a viable approach. But the main concerns that start when we shift to the local registry as you mentioned are its maintenance, backup and security.
3. If we can overcome them we can effectively implement it

**Comment by vasujain275** [comment]
@kb-0311 @varshith257 @noman2002 Correct me if I am wrong, but -

1. Doesn't a local registry add a lot of complexity and maintenance?
2. I think the Docker Hub free tier is very generous for our use case. It has a limit of 200 public images pulls/pushes per 6 hour. I don't think we will exceed it anyway. Here is a screenshot of what I found on their pricing page -
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/69643310/2c82113f-7bfe-4a0f-80c2-39e053312790)

**Comment by kb-0311** [comment]
@vasujain275 Ah okay I got my answer. Using the Docker Hub free tier is the obvious choice for now. Thanks for the clarification

**Comment by varshith257** [comment]
@noman2002 @kb-0311 @vasujain275 Done with all setup to support multi-stage build Docker setup of Talawa Api for both development and production environments.

I like to add that I need to create an issue regarding Add support for production for Talawa-Api as we discussed in PR #1885
