### ISSUE TITLE
Adding a Message Broker/Queue between API and MongoDB

### ISSUE THREAD

**Issue by Manik2708** [PalisadoesFoundation/talawa-api#1753]
**Is your feature request related to a problem? Please describe.**

The current setup involves APIs directly interacting with the database, leading to occasional delays in the project. As data volume increases, queries to MongoDB are anticipated to slow down, and the reliability of MongoDB's availability is questionable. 

**Describe the solution you'd like**

The solution is all about adding a Message Broker/ Queue between the API and DB. The message can be kept in a queue for processing and then can be consumed later. See the image:

![IMG-20240128-WA0004](https://github.com/PalisadoesFoundation/talawa-api/assets/65224535/bef2f767-ba3e-4365-8427-40780312c0ad)

**Pros:**
1) Very fast response to the user, as Queue services are faster than DB.
2) If Mongo is not available for sometime, still server will work smoothly due to this message broker.
3) When messages will be consumed from queue to save data in DB, operations can be performed in batches. This will reduce the number of read and writes in DB.
4) Implementation of chats will become easy as these Queues can be used for saving chat messages when the user is offline. 

**Cons:**
1) A new service has to be added, maintained and scaled.
2) We also need to consider message persistence; if a message is lost from the queue, it should be saved elsewhere to ensure retrieval in case of loss. This may lead to addition of a new service.

**Approach to be followed (optional)**
1) Choosing the service; there are many services available: RabbitMQ, Amazon SQS, BullMQ, Apache Kafka etc.
2) Classifying all the GraphQL queries and mutations on the basis of urgency and non urgency.
3) If user expects urgent response then the server, then this message broker approach has to be skipped.
4) If user expects some delay in the process, a queue has to be added between the API and DB.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Manik2708** [comment]
Before asking for assignment I request @xoldyckk @EshaanAgg to see the need of this issue. @palisadoes said to firstly discuss it with you.

**Comment by Manik2708** [comment]
@xoldyckk @EshaanAgg, Can we discuss over this issue?

**Comment by EshaanAgg** [comment]
It's a cool initaitive, but un-necessary IMO. Right now, we should focus on developing the basic functionality and making the same robust. When that is stable and we start getting the level of traffic that the application that generally use there message brokers get, then we can look into it. Hopefully we will get there soon, but in my strong opinion, we are not there yet.

**Comment by Manik2708** [comment]
Oh! Thanks for your reply. Then I think we can close this issue!
