### ISSUE TITLE
User passwords are not encrypted with a random salt

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1755]
**Describe the bug**

1. User passwords are not encrypted with a random salt. A fixed value of `10` or `12` are used
2. This is a serious security risk

**To Reproduce**

- See screen shots below

**Expected behavior**

1. Our code needs to hash passwords with random salts
2. All password tests must pass and be valid
3. All other functionality must be maintained

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/b5e9a1de-be16-4875-a6d4-e5dba1e65200)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
I would love to work on this issue.

**Comment by Anubhav-2003** [comment]
Respected sir, I can work in this issue, I am comfortable with our graphql schema, after the last two issues got merged. Thank You.

**Comment by AVtheking** [comment]
I would like to work on this issue please assign me

**Comment by devsargam** [comment]
Can I work on this??

**Comment by aialok** [comment]
@palisadoes, 
I want to know what do you mean by random salt ? Is it randomly selecting salt round from specific range like 10-12. Because in present we are randomly generating salt for each user with fixed salt round and this approach is still very safe.

**Comment by palisadoes** [comment]
You are mistaken. Please do your research.

1. https://en.m.wikipedia.org/w/index.php?title=Salt_(cryptography)&action=edit&section=3
1. https://gist.github.com/AndiDittrich/4629e7db04819244e843

Both links describe in great detail the challenges of reusing a salt

**Comment by aialok** [comment]
> You are mistaken. Please do your research.
> 
> 1. https://en.m.wikipedia.org/w/index.php?title=Salt_(cryptography)&action=edit&section=3
> 1. https://gist.github.com/AndiDittrich/4629e7db04819244e843
> 
> Both links describe in great detail the challenges of reusing a salt 

Thank you, will look into this : )

**Comment by AVtheking** [comment]
Respected @palisadoes sir I think we do need to generate random salt as library bcrypt always generate random salt when password is being hashed ,this means that result would never be same even for same passwords.The numeric value 10 and 12 used in the bcrypt function is the salt round which means cost factor.The cost factor is how much time is needed to calculate a single hash.

**Comment by palisadoes** [comment]
Once again, a random salt is recommended

https://en.m.wikipedia.org/w/index.php?title=Bcrypt&action=edit&section=2

**Comment by AVtheking** [comment]
Yes the bcrypt function everytime generates random salt for the password,do you mean to give random value of salt round ?

**Comment by palisadoes** [comment]
Thanks. In that case we can close this issue

**Comment by AVtheking** [comment]
I guess there is no  need to give random value to salt round as bcrypt always generate random salt regardless of what is the value salt round (which is 10 and 12 in our case )
