### ISSUE TITLE
No encryption of user email addresses in the database

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1756]
**Describe the bug**

1. User email addresses are not encrypted in the database
2. This means a bad actor could SPAM Talawa users if they got access to the database

**To Reproduce**

1. Dump the database
2. View unencrypted email data in the User table

**Expected behavior**

A solution where:

1. Email addresses are:
    1. encrypted for storage in the database
    1. decrypted for retrieval from the database
1. The encryption key is not stored in the database
1. Uses a random salt in addition to the encryption key
1. The encryption key is configured with `setup.ts`
    1. If a value is found, then the default for changing the value must be `No`
    2. If a value is not found, then the encryption key must be randomly generated
1. Uses a strong encryption algorithm
1. The User email address data in the `sample_data/users.json` file must be updated with the encrypted addresses during the data importation process.
1. The encryption / decryption key(s) are not stored in the:
    1. code base
    1. database

**Actual behavior**

1. Email addresses are not encrypted

**Screenshots**

- N/A

**Additional details**

1. This is the first of many issues to encrypt PII stored in the database
1. All tests must pass and be valid
1. No other functionality must be affected

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Anubhav-2003** [comment]
Respected sir, I can work in this issue, I am comfortable with our graphql schema, after the last two issues got merged. Thank You.

**Comment by AVtheking** [comment]
I would like to work on this issue

**Comment by devsargam** [comment]
Can I work on this?

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, 

I wanted to clarify one question. Do you want a single encryption key with a random salt for every user email. Or a user specific unique encryption key for each email. The latter option would involve creating an in-house KMS for handling the keys.

Thank You.

**Comment by palisadoes** [comment]
A single encryption key, encrypting the field using a random salt

**Comment by Anubhav-2003** [comment]
@palisadoes Ok sir, Thank You.

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, 

There was a recent revert of a PR in the API  that was causing error related to user signup. I had started my feature branch before the revert. So i had to merge the latest upstream to my feature branch. But as a result a lot of files were changed.

One thing I noticed is that for every file changed, eslint throws multiple linting errors that are already present in the code base. At the moment around a hundred linting errors are showing while I try to commit my changes. How can I disable those errors. Otherwise I am unable to commit. Every new line of code I write is passed through linting checks, but the errors shown are for hundreds of lines of code already present.

Thank You.

**Comment by Anubhav-2003** [comment]
@palisadoes  Respected sir, 

The issue is almost done. But I am using an opensource key management service by HashIcorp, for an  in-house secret management. As storing the encryption key as plaintext in the .env file is not secure, and industry standard.  But this would require all future users of Talawa-api to install 'Vault' from 'HashICorp' , into their local systems and configure it before they can start contributing. Also when pushed to the main repo, the actual cloud instance that runs the API in production must also be updated with the latest software.

Should I proceed with this major addition of software. Or store the key in the .env file only. I feel that if we make the migration, then all current secrets in the .env file could be migrated to the service as well for better security.

Thank You.

**Comment by palisadoes** [comment]
At this time use the `.env` file for the simplicity of implementation.

**Comment by Anubhav-2003** [comment]
@palisadoes ok sir. Thank You.

**Comment by Anubhav-2003** [comment]
This issue is active. I have already raised a PR, it is awaited approval. Thank you.

**Comment by Anubhav-2003** [comment]
I have already raised PR for this issue, but due to the merge of my recent PR #1896 and a few others there has been drasti changes in the setup. I will be updating the PR as soon as the new implementations are done. Thank You.

**Comment by jyotiv737** [comment]
@Anubhav-2003 Are you working on this?

**Comment by Anubhav-2003** [comment]
> @Anubhav-2003 Are you working on this?

Actually, I have already raised a PR for this,  the feature is completely implemented, but due to recent pull request merges. Some tests are failing. Thank you.

**Comment by Anubhav-2003** [comment]
Update: working on the latest new PR for this issue after the userType-fix branch merge.

**Comment by Suyash878** [comment]
I would like to work on this issue. I will proceed with the preferred **AES-256-GCM** encryption/decryption algorithm.

**Comment by palisadoes** [comment]
You will need to ensure that all the encryption / decryption will work:

1. maintaining existing functionality
2. across the entire test suite 
3. with the setup script where sample data is imported.

**Comment by Suyash878** [comment]
I was planning on implementing function for the encryption key variable in the `setup.ts`, So my question was is there a specific preference for where exactly should this function be implemented as in for instance after the mongodb URL function and or before the recaptcha function.  
Or should I just proceed with what I think would be the most suitable place.

**Comment by Suyash878** [comment]
According to this error, we must switch to `eslint.config.js` from `.eslintrc.json`, and moreover `.eslintignore` is no longer supported either. This could be a potential issue in my opinion. 
![image](https://github.com/user-attachments/assets/82613218-664e-46ee-9e7e-4e9e7a768d95)

**Comment by AnshulKahar2729** [comment]
Suyash are you working on this.

**Comment by Suyash878** [comment]
Yes, I am working on this.

**Comment by palisadoes** [comment]
unassigning, inactivity

**Comment by prayanshchh** [comment]
Steps to encrypt the email

1) Create Encryption Key in setup.ts and store it in env using crypto package
2) Generate random salt again using in crypto 
3) Encrypt email using AES-256-GCM algorithim
4) Decrypt email

is this all i need to do (except writing tests)

**Comment by prayanshchh** [comment]
I am using the previous PR as reference, if there was some changes needed in the previous PR do tell me..will be opening a PR in a week.

**Comment by PurnenduMIshra129th** [comment]
can  i work on this issue? i would love to work on this issue

**Comment by prayanshchh** [comment]
the work for encryption is almost done, but it was done in relation with develop branch, we will have to wait unit the new develop-postgres gets to the same working state as develop or we can implement revolvers in the new branch with email encryption..whatever the maintainers decide

**Comment by prayanshchh** [comment]
> can i work on this issue? i would love to work on this issue

 working on it

**Comment by bandhan-majumder** [comment]
Hi. Is this issue still valid?

**Comment by prayanshchh** [comment]
I was but as the migration to postgres is not fully completed for the api, hence I will resume my work when postgres branch reaches the appropriate state

**Comment by palisadoes** [comment]
I'm going to close this. We can reopen it when the Postgres merge is complete
