### ISSUE TITLE
Fix setup.ts Image Size Prompt

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1764]
**Describe the bug**

1. The image size prompt occurs after loading sample data
2. This is not desirable. All configuration parameters must be set before this is done

**To Reproduce**

1. Run the setup script
2. The image size prompt occurs after the data import

**Expected behavior**

- The prompt for image size must occur before the `Would you like to setup the mail username and password?` prompt

**Actual behavior**

- See screen shot

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/fe4f61dd-3e56-46e4-b2be-c983cfe6d7f2)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment]
Would like to solve this issue!

**Comment by manishjha-04** [comment]
Hey @palisadoes i have already included this in the issue [#1715](https://github.com/PalisadoesFoundation/talawa-api/issues/1715) should i consider this ! or exclude in my upcoming pr?

**Comment by Cioppolo14** [comment]
@adi790uu @manishjha-04 This is a duplicate, I am going to close it.
