### ISSUE TITLE
Bug : Admin Panel Infinite Loading Issue: 400 Bad Request Error on GraphQL Fetch After Latest Changes

### ISSUE THREAD

**Issue by aialok** [PalisadoesFoundation/talawa-api#1765]
**Describe the bug**
After fetching latest changes both in the admin and API, the admin panel encounters infinite loading. The console displays a '400 Bad Request' error for `http://localhost:4000/graphql/` , despite the API operating correctly. The user portal is functioning properly.

**To Reproduce**

1. Fetch the latest changes in both Talawa Admin and Talawa API.
2. Run Talawa Admin and Talawa API.
3. Log in to the admin panel.
4. Observe infinite loading on the dashboard screen.

**Expected behavior**

Upon completing the specified steps, the admin panel's dashboard should load seamlessly without encountering any infinite loading issues. Users should be able to access and interact with the dashboard content after logging in.

**Actual behavior**
After following the provided steps, the admin panel's dashboard exhibits an issue with infinite loading, preventing the expected display of content. Users are unable to access the dashboard as intended.

**Screenshots**

![Screenshot from 2024-01-30 22-00-56](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/3b62792e-105e-4b8c-9632-d42e5eda2663)

[cinnamon-2024-01-31T020929+0530.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/d008fa4b-1fa5-4cf4-ae66-6aa0fe96afd7)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@aialok @NayOoLwin5 

This is probably related to this PR
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1497/files

Reverting

**Comment by palisadoes** [comment]
FYI
- Reverting didn't solve the problem. It's something else

**Comment by aialok** [comment]
> FYI
> - Reverting didn't solve the problem. It's something else
> 

I am trying to find the problem. Will report you back once I get the cause.

**Comment by palisadoes** [comment]
I'm having difficulties registering too. 

@Manik2708 Could this be related to your PR?
- https://github.com/PalisadoesFoundation/talawa-api/pull/1741

**Comment by palisadoes** [comment]
I restored the PR that I reverted as that didn't solve the issue

**Comment by aialok** [comment]
> I'm having difficulties registering too.
> 
> @Manik2708 Could this be related to your PR?
> 
> * [Signup route changed #1741](https://github.com/PalisadoesFoundation/talawa-api/pull/1741)

I attempted to investigate the bug. Essentially, I have one Talawa API folder with commits up to January 28 before commit #1741. When I run the server on this folder, it works. However, when I attempt to run the server with another folder containing the latest changes, I encounter an issue with infinite loading. In my opinion, the problem may be arising due to issues related to sample data.

[cinnamon-2024-01-31T032908+0530.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/0620390a-efad-4634-9fe8-25139f21d1b4)

@Manik2708 @palisadoes   what you say about this?

**Comment by palisadoes** [comment]
I'm reverting the @Manik2708 PR
- https://github.com/PalisadoesFoundation/talawa-api/pull/1741

**Comment by palisadoes** [comment]
1. Reverted
2. Fixed
3. Closing

**Comment by aialok** [comment]
> 1. Reverted
> 2. Fixed
> 3. Closing

Thank you : )

**Comment by Manik2708** [comment]
> I'm reverting the @Manik2708 PR
> 
> * [Signup route changed #1741](https://github.com/PalisadoesFoundation/talawa-api/pull/1741)

Will raise a new PR after fixing the issue!
