### ISSUE TITLE
Implementing Rate Limiter through Redis

### ISSUE THREAD

**Issue by Manik2708** [PalisadoesFoundation/talawa-api#1782]
**Is your feature request related to a problem? Please describe.**
Currently `express Rate Limiter` is being used, which is a bad way specially when API will be going to cloud in future. So use Redis for rate limiting of APIs

**Describe the solution you'd like**
As proposed by @vasujain275 we can store IPs in Redis to limit the API calls

**Approach to be followed (optional)**
See this video for a possible approach: https://youtu.be/_DqfiW08HkA?si=SzS8NGVucoJTgVKG
**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Manik2708** [comment]
If this is relevant then I can work on this @palisadoes

**Comment by palisadoes** [comment]
Attacks can be inventive. You'll need a solution that will also answer this question in the YouTube comments.

```
So, in a interview they ask me what if user IP is changing on every request then how will you rate limit this? 
```

**Comment by Manik2708** [comment]
Yes, will try to cover all the possible edge cases

**Comment by Manik2708** [comment]
I am thinking of IP Address+API Key approach for rate limiting. This API Key will be like a token which should be passed in headers for every API call. Another note is that this API Key would be unique for a device not for user. See the Logout API also. API Key can only be removed from Mobile only when app is uninstalled (same with browser, only when browser's data is cleared)

![Screenshot from 2024-02-05 13-20-31](https://github.com/PalisadoesFoundation/talawa-api/assets/65224535/79288d98-2bcf-4e69-966a-70c7c1858f8f)

This approach tries to cover these two edge cases:
1) If multiple requests are sent from same browser/device but from different IP Addresses.
2) If multiple requests are sent from same IP Address but from different browsers/devices

**Comment by palisadoes** [comment]
OK

**Comment by Manik2708** [comment]
> OK

Another question which I want to ask, will all the APIs be using the same rate Limiter? Or some APIs can demand different constraints? For later one we have to think of a different approach!

**Comment by palisadoes** [comment]
Do you mean rate limiting per organization versus per API instance?

**Comment by Manik2708** [comment]
No, let's assume there are 100 APIs, and if 20 requests per minute are allowed, so will all the 100 APIs will follow same constraint? Or there can be division that 40 specific APIs will be allowing 30 requests per minute and rest 20 per minute?

**Comment by palisadoes** [comment]
There is only one API end point per Talawa API instance. You are implying a cloud service. There is none. The solution may be per API instance

**Comment by Manik2708** [comment]
Ok, then a single rate Limiting service per API instance will be fine!

**Comment by palisadoes** [comment]
However if there is a shared Redis server, there must be a way to distinguish between instances.

**Comment by Manik2708** [comment]
That means multiple API instances with a single instance of Redis?

**Comment by palisadoes** [comment]
Yes, that is a possible situation.

**Comment by Manik2708** [comment]
> Yes, that is a possible situation.

Then probably solution lies in Single instance of Redis. All the keys and counters will be in that single Redis Instance, so all API instances will contact to that single instance. Even if in future, more Redis instances are created, data is replicated, so that will also be taken care of.

**Comment by Manik2708** [comment]
This can be done by maintaining a bucket of trusted proxy servers. We have to get a proxy server provider service (Please tell me if we are already using it!) and then we can validate! Are we using this service? Or we can do another thing, validation of API Keys before IP Address. Please suggest me what approach should I follow?

**Comment by Manik2708** [comment]
> This can be done by maintaining a bucket of trusted proxy servers. We have to get a proxy server provider service (Please tell me if we are already using it!) and then we can validate! Are we using this service? Or we can do another thing, validation of API Keys before IP Address. Please suggest me what approach should I follow?

@palisadoes @krishna619

**Comment by palisadoes** [comment]
Once again. There is no cloud service. 

Most organization communities will be very small. There is no guarantee that proxy services will be used.

If proxy server farm street used then the protection would be configured on the load balancers.

You may be over engineering the problem

**Comment by Manik2708** [comment]
> Once again. There is no cloud service.
> 
> Most organization communities will be very small. There is no guarantee that proxy services will be used.
> 
> If proxy server farm street used then the protection would be configured on the load balancers.
> 
> You may be over engineering the problem

No, as @krishna619 suggested we have to take care trusted address also. I researched about it and got to know that it requires proxy servers. I think for now we can skip this and once we have cloud instance, this issue can be addressed!

**Comment by EshaanAgg** [comment]
> Currently `express Rate Limiter` is being used, which is a bad way specially when API will be going to cloud in future.

Why is it bad? Instead of reinventing the wheel completely ourselves, why aren't we searching for alternatives that handle this for us? Handing this level of fine-grained manipulation of headers and IP addresses is bound to break things, as I don't presume that any of us are any networking experts.

**Comment by Manik2708** [comment]
> > Currently `express Rate Limiter` is being used, which is a bad way specially when API will be going to cloud in future.
> 
> Why is it bad? Instead of reinventing the wheel completely ourselves, why aren't we searching for alternatives that handle this for us? Handing this level of fine-grained manipulation of headers and IP addresses is bound to break things, as I don't presume that any of us are any networking experts.

Actually the main issue was testing Redis Cache Services, but @vasujain275 suggested that before this we have to implement a rate limiter using Redis and then the services can be tested. It is indeed tough to take care of all the security related to IP but I was trying my best since last week to research about it and implement. If mentors think that this is not required for now, we can close this and work on testing Redis Services!

**Comment by EshaanAgg** [comment]
Thanks for your efforts and I appreciate the research. But it currently feels like a solution in search for a problem, so it would be more beneficial for you to direct your efforts to some other issues. Thanks again for the work. Hopefully we can come back to this later.

**Comment by Manik2708** [comment]
> Thanks for your efforts and I appreciate the research. But it currently feels like a solution in search for a problem, so it would be more beneficial for you to direct your efforts to some other issues. Thanks again for the work. Hopefully we can come back to this later.

No problem, I learnt a lot in the last week. Please see for my idea regarding writing unit tests for Redis Services, as for now no tests are written for them.
