### ISSUE TITLE
Fix: Requirement of pinned post for post title

### ISSUE THREAD

**Issue by wingman47** [PalisadoesFoundation/talawa-api#1800]
**Describe the bug**
Currently if we want to create or update a post they need to be pinned in order to add a title which effectively means every new post needs to be pinned. Adding post title and pinned post doesn't need to have any relation.

**To Reproduce**

1. Go to organization.
2. Go to posts.
3. Create a post.
4.  Add a title, description and create the post.

**Expected behavior**
A new post should be created.

**Actual behavior**
We get error: Post needs to be pinned in order to add a title.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/49762303/33b9f42a-bfc2-40f8-9667-4351bda5999a)

**Comment by wingman47** [comment]
Can i work on this issue?

**Comment by palisadoes** [comment]
1. This is the correct behavior. 
2. However, only admins and super admins can create pinned posts
