### ISSUE TITLE
Backend support for registration and check-in of non-members of the organization for an event

### ISSUE THREAD

**Issue by Anvita0305** [PalisadoesFoundation/talawa-api#1805]
**Is your feature request related to a problem? Please describe.**
Currently, only the admin is able to add and register only the people who are the part of an organization. Outsiders are not able to register for that event.

**Describe the solution you'd like**
Admin and superadmin must be able to accommodate the outsiders if they wish to attend a particular event inspite of them not being the member of the org.

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
1. Create a new schema for outsider attendees which will have id, eventid as its fields.
2. Alternative for new schema can be: Currently, eventattendees is present. So, one additional field isMemberOfOrg: boolean can be used to distinguish between members and non-members.

**Additional context**
This is the screenshot from frontend. In the dropdown, only the current members of the org are visible.
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/78889572/9d8a1b2c-85a0-45f0-b8e5-4ac17f648072)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
Thank you for this suggestion. Right now, we only want those inside the organization to be able to register for an event. I am going to close this as unplanned.
