### ISSUE TITLE
Tests: src/resolvers/Mutation/addUserToUserFamily.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1817]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

1. Tests need to be written for file `src/resolvers/Mutation/addUserToUserFamily.ts`
1. We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
1. When complete, all all methods, classes and/or functions in the refactored file will need to be tested. 
1. These tests must be placed in a single file with the same path as the tested file, but under the `tests/` with a `.spec.ts` suffix.
1. You may need to create the appropriate directory structure to do this.

### IMPORTANT:

Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### Other

Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NayOoLwin5** [comment]
I would like to work on this

**Comment by Cioppolo14** [comment]
@NayOoLwin5 Are you working on this?

**Comment by NayOoLwin5** [comment]
Yes, I will be submitting PR soon.

**Comment by palisadoes** [comment]
Unassigning as abandoned

**Comment by pranshugupta54** [comment]
Please assign this, I've fixed it.

**Comment by pranshugupta54** [comment]
@palisadoes, please assign this. I'll create a PR rn.

**Comment by pranshugupta54** [comment]
@Cioppolo14, please assign. I've fixed this already

**Comment by Cioppolo14** [comment]
@pranshugupta54 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by pranshugupta54** [comment]
@Cioppolo14, I know I'm assigned to 2 issues but 
1) Requests screen is in review
2) userType issue -> already merged one PR and now it's waiting for other related PRs to fix (So technically I'm assigned without my work)

**Comment by pranshugupta54** [comment]
@Cioppolo14, PR got merged. Please assign.
