### ISSUE TITLE
Test: src/resolvers/middleware/currentUserExists.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1818]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

1. Tests need to be written for file `src/resolvers/middleware/currentUserExists.ts`
1. We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
1. When complete, all all methods, classes and/or functions in the refactored file will need to be tested. 
1. These tests must be placed in a single file with the same path as the tested file, but under the `tests/` with a `.spec.ts` suffix.
1. You may need to create the appropriate directory structure to do this.

### IMPORTANT:

Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### Other

Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NayOoLwin5** [comment]
I would like to work on this issue

**Comment by Cioppolo14** [comment]
@NayOoLwin5 You now have two issues. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by MahendraDani** [comment]
@Cioppolo14 I would like to work on this issue

**Comment by MahendraDani** [comment]
Is there a command to run test on specified only instead of all the files?

**Comment by MahendraDani** [comment]
I could not write the tests, my apologies.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by Sivam2313** [comment]
I would like to work on this issue

**Comment by Cioppolo14** [comment]
@aarishshahmohsin I am going to assign you this issue, I only see that you have one issue.  I think we had some confusion, you are allowed a maximum of 2 issues across all repositories with a few exceptions. Thank you for your understanding, we are working hard to keep the flow going!
