### ISSUE TITLE
Test: src/resolvers/Mutation/createOrganization.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1827]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

1. Tests need to be written for file
    1. src/resolvers/Mutation/createOrganization.ts
1. We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
1. When complete, all all methods, classes and/or functions in the refactored file will need to be tested. 
1. These tests must be placed in a single file with the same path as the tested file, but under the `tests/` with a `.spec.ts` suffix.
1. You may need to create the appropriate directory structure to do this.

### IMPORTANT:

Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### Other

Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by antriksh-9** [comment]
Hey @palisadoes I would like to take this.

**Comment by NayOoLwin5** [comment]
I would like to work on this

**Comment by Cioppolo14** [comment]
@antriksh-9 Are you working on this?

**Comment by antriksh-9** [comment]
Yeah! I am trying to solve the issue...will take some time.

**Comment by antriksh-9** [comment]
Hey @noman2002 ,
I need some help of you in solving this issue.
I wanted to know what things I have to do, or what changes need to be done in createOrganization.spec.ts file to successfully write tests.
What approach or steps do I need to follow for writing tests.
Would be a great help,
Thanks.

**Comment by antriksh-9** [comment]
Hey @Cioppolo14, I just wanted to inform that I am working on this issue, but it will take some time to be solved as I have my college exams running.
Thanks.

**Comment by samiali12** [comment]
@Cioppolo14, Do you assign me this issue.

**Comment by Cioppolo14** [comment]
@samiali12 I do assign issues, but please request ones that don't already have an assignee.  Feel free to tag me in those requests.

**Comment by samiali12** [comment]
I understand the importance of this. I bring your attention to this issue because already 2 weeks ago on this issue without any response.

**Comment by jyotiv737** [comment]
@antriksh-9 Are you still working on this?

**Comment by palisadoes** [comment]
Unassigning as abandoned

**Comment by pranshugupta54** [comment]
The test is not covering 
```ts
if (!address) {
    return { isAddressValid: false };
  }

```

I've removed that part from the function.

<img width="1110" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/c3d18235-2b60-4765-a3f4-873056073d57">


**Will this affect the functionality?**

`validateAddress` is being called inside an `if` condition, so there is no way to send an empty address.
<img width="539" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/8b379d47-7fa0-45b2-9171-1807205ae4b6">


If this looks good, I'll make a PR.

**Comment by pranshugupta54** [comment]
@Cioppolo14, please assign
