### ISSUE TITLE
Database Logging for all models 

### ISSUE THREAD

**Issue by lakshz** [PalisadoesFoundation/talawa-api#1829]
- Recently logging middleware was introduced in the PR #1716. 
- The logging middleware can be found in `src/libraries/dbLogger.ts`. Currently, it is only applied to `User` model. 
- We should add it for all models.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by LakshyaSatpal** [comment]
I can do this.
