### ISSUE TITLE
bug: Few files are following the old way of auth checking

### ISSUE THREAD

**Issue by iamsaumya** [PalisadoesFoundation/talawa-api#183]
**Describe the bug**
A few files are following the old way of auth checking

```js
if (!context.isAuth) throw new Error("User is not authenticated"); // old way
  
authCheck(context); // new way
```
**To Reproduce**
Make a request with an expired token to resolvers using the old way of auth checking. You will get a ` User is not authenticated` error.

**Expected behaviour**
Request with expired token should return `Access token has expired` error. 

**Actual behaviour**
The old method only checks for `isAuth` field and leaves the `expired` field. Resulting in returning `User is not authenticated` instead of `Access Token has expired. Please refresh session`

**Comment by iamsaumya** [comment]
I have taken permission in the slack channel and a PR is incoming. @Sagar2366 Could you please assign this to me? Thanks!

**Comment by iamsaumya** [comment]
Hey @Laurell876 and @Sagar2366, `reject_membership_request` mutation does not check for authentication. Is this a bug or a feature? 

https://github.com/PalisadoesFoundation/talawa-api/blob/a062c7fb70d08bab874e25d380effb77d9d44e25/resolvers/membership_request_mutations/reject_membership_request.js#L5-L10

**Comment by Laurell876** [comment]
it's a bug

**Comment by iamsaumya** [comment]
Alright, I will add `authCheck` for this resolver.

**Comment by iamsaumya** [comment]
Closing the issue as the PR is merged.
