### ISSUE TITLE
API issue for "Profile Update Not Working on Admin Portal #1508"

### ISSUE THREAD

**Issue by Shubh152** [PalisadoesFoundation/talawa-api#1831]
**Describe the bug**
corresponding to Admin portal Fixes https://github.com/PalisadoesFoundation/talawa-admin/issues/1508

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional details**
The issue is solved and only a PR needs to be created  in the API repo

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Shubh152** [comment]
Please assign it to  me so that I can create the PR and resolve the issue

**Comment by palisadoes** [comment]
There isn't an adequate description of the problem. Closing
