### ISSUE TITLE
 Bearer Token Exposure on Login Admin/User

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#1838]
**Describe the bug**
 Bearer Token Exposure on Login Admin/User

**To Reproduce**

1. Enter a valid user/admin email and password on the user/admin login.
2. Press Ctrl + V (paste).

**Expected behavior**
No sensitive information should be exposed.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Closing. There is insufficient explanation of the steps to reliably reproduce this issue.
