### ISSUE TITLE
It is very difficult to setup the project locally for talawa-api

### ISSUE THREAD

**Issue by pankaj-2503** [PalisadoesFoundation/talawa-api#1848]
**Is your feature request related to a problem? Please describe.**
---
A clear and concise description of what the problem is.

Add short and consice readme file so that any beginner can set up the project locally . I recently setup the project which was too confusing by following the readme provided and took lot's of time to understand.
---
**Describe the solution you'd like**
I want to add readme fiel with crips and conscise solution to setup the project locally.I think this is the reason why this project has not much contributor.
---
**Describe alternatives you've considered**
I would like to update if it is assigned to me .
---
**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Closing. Repo already has a README.md file in the root directory
