### ISSUE TITLE
Merge the `develop` branch into `develop-userTypeFix` for #1830

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1851]
**Is your feature request related to a problem? Please describe.**
1. We recently fixed the usage of `userType` with this PR.
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
1. A new `develop-userTypeFix` branch was created to add this feature
1. We need to make sure that the  `develop-userTypeFix` branch is up to date with the latest merges to `develop`

**Describe the solution you'd like**
1. Merge `develop` into the `develop-userTypeFix` branch
2. Make sure all newly added features to the `develop` branch are included in the  `develop-userTypeFix` branch.
3. The new functionality of `userType` must be unchanged.
4. No other features must be affected
5. All tests must be valid and pass

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

1. Research these issues for context with the new `userType` functionality
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@AVtheking 

1. You should work on this to make sure the process works correctly.
2. We can then create new issues for others as new PRs are merged into `develop`

**Comment by AVtheking** [comment]
Ok sir

**Comment by AVtheking** [comment]
ok sir

**Comment by palisadoes** [comment]
How is the work going on this?

**Comment by AVtheking** [comment]
As latest PR are merging in develop branch I am merging and making change accordingly in develop-usertypeFix branch

**Comment by palisadoes** [comment]
1. Create a PR and get it merged. 
1. We can then open another PR to repeat the process and possibly assign separate issues to do that so others can get a turn and you can work other things

**Comment by AVtheking** [comment]
Ok sir will create a pr
