### ISSUE TITLE
Add Filter and Sort for Action Items

### ISSUE THREAD

**Issue by meetulr** [PalisadoesFoundation/talawa-api#1854]
**What is this feature request about?**
It's about adding the functionality to filter the action items (i.e. action items belonging to a particular action item category, that are active or completed). And also, the functionality to sort the action items (latest or earliest).

**Additional context**
This is a companion issue for PalisadoesFoundation/talawa-admin#1462

**Demo**
It would look something like this:

https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/3fa86b1d-6d05-4da8-8845-c88f1e0c4e5d

**Comment by palisadoes** [comment]
@rishav-jha-mech @aashimawadhwa Please take a look at this design to see whether is meets your requirements

**Comment by meetulr** [comment]
> @rishav-jha-mech @aashimawadhwa Please take a look at this design to see whether is meets your requirements

Yes, Please advise me on this. This is just a quick mock design.
