### ISSUE TITLE
Support for user to join organizations

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-api#1859]
**Is your feature request related to a problem? Please describe.**
Current version of API does not have any support for user to join organizations. 

**Describe the solution you'd like**
Update the [joinPublicOrganization](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/resolvers/Mutation/joinPublicOrganization.ts) mutation to create membershipRequest if the organization requires user registration instead of throwing user not authorised error. 

Also rename it to `joinOrganization`

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
Refer to [this](https://github.com/PalisadoesFoundation/talawa-admin/issues/1511#issuecomment-1921527633) comment

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
@palisadoes 
Please take a look and let me know if I am missing something.

**Comment by disha1202** [comment]
Also please feel free to assign this issue to any willing contributor. 
I already have multiple issues assigned.

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by disha1202** [comment]
Also should a user who has been rejected from joining an organization be allowed to request to join again?

**Comment by takshakmudgal** [comment]
I'd like to work on this issue.

**Comment by palisadoes** [comment]
> @palisadoes Please take a look at the issue and let me know if I am missing something or if the information in the issue description is inadequate.

If a request is rejected, we should block the user.

**Comment by palisadoes** [comment]
This may be a duplicate. Please discuss in the PR

- https://github.com/PalisadoesFoundation/talawa-api/pull/1770

**Comment by pateldivyesh1323** [comment]
@palisadoes Please give an update about what is going to happen to this issue after related PR and issues reaches to conclusion.

**Comment by palisadoes** [comment]
Based on the discussions in that other PR, this is a duplicate issue and should be closed
