### ISSUE TITLE
Create INSTALLATION.md File

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#186]
The installation section in the README.md file is insufficient. This needs to be resolved. We need the following steps to be completed.

1. Move the **Installation** section of the README.md file to a separate INSTALLATION.md file.
2. Create a link to INSTALLATION.md in the README.md file
3. Improve the quality of the INSTALLATION.md steps.

The INSTALLATION.md needs to be much better written.

1. Have an introductory paragraph under each section heading
2. Explain the steps in much greater detail. 
    1. For example saying "To run this api five environment variables need to be set in a .env file in the root of the api" is insufficient. Better wording would be: "You will need to configure five environmental variables as a precursor to installation. This can be done automatically by placing these commands (or settings, or whatever) in an `.env` file in the root directory. For the purposes of this guide we will work with a file called `filename.env` 
    2. For example saying "Docker Development Steps: `docker-compose build;docker-compose up`" is insufficient. Better wording would be: "Talawa API works best in a docker environment. To install docker on your system, follow these steps.... When docker is installed, run these commands to activate it..."
    3. For example saying "Docker Development Steps: `docker-compose build;docker-compose up`" is insufficient. Better wording would be: "Talawa API works best in a docker environment. To install docker on your system, follow these steps.... When docker is installed, run these commands to activate it..."

A new user following the installation steps word for word on a brand new system must be able to install talawa-api. That is not the case now, and it is a significant barrier to adoption.

**Comment by iamsaumya** [comment]
Here @palisadoes  👋🏻

**Comment by palisadoes** [comment]
> Here @palisadoes 👋🏻

Assigned to you.

**Comment by iamsaumya** [comment]
Thanks!

**Comment by palisadoes** [comment]
The current documentation has many lists of items written as if the person already knows what to do. We need a single document referenced from README.md for people to use.

Someone with only a basic understanding of the Linux CLI must be able to follow the steps, line by line with reasonable explanations to get the job done. That is not the case now.

**Comment by iamsaumya** [comment]
Indeed @palisadoes, I will keep this in mind while writing the new instructions.

**Comment by iamsaumya** [comment]
I am bit busy with my mid-term exams and I am also relocating. Will work on the issue in a few days. I hope you understand!

**Comment by XshubhamX** [comment]
@palisadoes  please assign it to me I will make it today and will attach a pr

**Comment by iamsaumya** [comment]
Hey @XshubhamX, I have already worked on this. The PR will be coming tomorrow.

Thanks!

**Comment by Sagar2366** [comment]
@iamsaumya push changes to the PR to track progress.
