### ISSUE TITLE
Update `adminApproved` to expected functionality in the  `develop-userTypeFix` branch

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1862]
**Is your feature request related to a problem? Please describe.**

1. We will be merging our `develop-userTypeFix` branch into `develop`. This feature branch was created for the reasons stated in this issue and PR
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
1. The `adminApproved` is better suited to be located in the `AppUserProfile` collection
    1. Use this schema for reference:    
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql

**Describe the solution you'd like**
1. The `adminApproved` is must be located in the `AppUserProfile` collection
2. The Schema will need to be updated to reflect this requirement
3. Mutations and queries will need to be updated and in some cases new ones added.
4. All tests must pass and be valid
5. No other functionality must be affected
6. The changes must only be applied to the `develop-userTypeFix` branch

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**
1. This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile
1. This need was identified here:
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1770
1. Type User
    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/d9499b3d-a0eb-45db-97fe-97b824f2eaf0)

1. Type AppUserProfile
  ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/9ad6e881-6c0c-47cc-96f6-1ced936a0604)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chintu-777** [comment]
Please assign me this issue. I would like to contribute to this
a

**Comment by palisadoes** [comment]
Thanks @chintu-777

This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and graphQL in their GitHub profile. Do you have that?

**Comment by varshith257** [comment]
I would like to work on this

**Comment by AVtheking** [comment]
I would like to work on this issue

**Comment by i-m-Paras** [comment]
@palisadoes I've successfully merged a PR in your repo, showcasing my hands-on experience. My GitHub history reflects my proficiency in MERN, and I invite you to check out a full-stack project on my [Linkedin](https://www.linkedin.com/in/parasawasthi/). I learned about GraphQL too.

Looking forward to contributing to this.

**Comment by palisadoes** [comment]
@varshith257 

You should be aware of this issue.

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1445

**Comment by varshith257** [comment]
@palisadoes Unassigning myself due to I would love to contribute to the issue of Fund-Raise Campaign. I had done a lot of research about it earlier it opened. And following the updates of fundraising campaign issue from starting of the issue. 

Let other's can work on this issue.

**Comment by Shubh152** [comment]
Please assign this issue to me

**Comment by Olatade** [comment]
Thanks @Shubh152,

This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and graphQL in their GitHub profile. Do you have that?

**Comment by Shubh152** [comment]
I have learned about GraphQL. I have solved issues related to TypeScript and worked out changes in GraphQL queries and mutations in talawa's repositories. Looking forward to contribute.

**Comment by palisadoes** [comment]
@Shubh152 Though you have merged PRs in Talawa-Admin, you have a history of closing PRs after we have assigned reviewers and they have started their work. This makes us hesitant to assign this to you. 
- https://github.com/PalisadoesFoundation/talawa-admin/pulls?q=is%3Apr+is%3Aclosed+author%3AShubh152+

What assurances can you provide that this won't continue?

**Comment by Shubh152** [comment]
I used to make errors in the PRs due to incorrect merging and had to close them unexpectedly. There was no other reason to do that. But now I have learned the right way to make a PR. I apologise for all the inconvenience that the reviewers had to face. You can trust me with this. The recent PR I made does not have this error.
 
https://github.com/PalisadoesFoundation/talawa-admin/pull/1573

**Comment by Shubh152** [comment]
Following discussions from - 
https://github.com/PalisadoesFoundation/talawa-api/pull/1770

I have come up with this solution - 

A spam user is a user rejected by or blocked by a some number of organisations. For every user, there should be a `isSpamUser` flag that is `false` by default for every new app user both on web and mobile apps but is set to `true` for the spam user after he spams requests to multiple organisations. 
 
The `isSpamUser` flag will be present in `AppUserProfile` in place of the `adminApproved` flag and the latter will be removed. 

The rest of the authentication flow can be handled by using `membershipRequests` and `joinedOrganizations` in the `User` schema and I making changes in the mutation and query resolvers accordingly.

Am I on the right track @palisadoes?

**Comment by Shubh152** [comment]
@palisadoes Relevant changes in queries need to be made in admin repo as well. Should I open an issue there and solve it?

**Comment by palisadoes** [comment]
Yes, specifically for this branch

**Comment by palisadoes** [comment]
When are you going to submit a PR for this?

**Comment by Shubh152** [comment]
Just resolving some tests, will be done in a day or two.
