### ISSUE TITLE
Integrate Action Item Assignment in Direct Chat Messages

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#1872]
**Description**
I would like to request the addition of a new feature  The feature is related to the sendMessageToDirectChat mutation and involves the ability to assign action items to a user when sending a message to a direct chat.

**Use Case**
As an administrator of the Talawa application, I want the capability to seamlessly assign action items to members when communicating through direct chat messages. This feature would streamline collaboration, making it easier to delegate tasks and manage action items within the organization.

`mutation SendMessageToDirectChat(
  $chatId: ID!,
  $messageContent: String!,
  $data: CreateActionItemInput,
  $actionItemCategoryId: ID
) {
  sendMessageToDirectChat(
    chatId: $chatId,
    messageContent: $messageContent,
    data: $data,
    actionItemCategoryId: $actionItemCategoryId
  ) {
    sender {
      firstName
    }
    receiver {
      firstName
    }
  }
}
`

`{
  "chatId": "65d07e4637e7d62f18d1b5d3",
  "messageContent": "Hello, this is a test message! from krishna super admin",
  "actionItemCategoryId": "65cf00d92a54e2458c79ee46",
  "data": {
    "assigneeId": "65378abd85008f171cf2990d"
  }
}
`
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/9fd9d713-9976-4bec-984a-e560c4107323)
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/01fd36ad-bbb0-44a6-bf6e-94a2d6a7bc17)

**Comment by krishna619** [comment]
@palisadoes
We can extend this feature to support additional functionalities such as attaching files, setting due dates, and creating inline polls, enhancing the versatility of Direct Chat for seamless communication and coordination within organizations.

**Comment by palisadoes** [comment]
Chat functionality doesn't work.

We are evaluating replacement options.

Closing
