### ISSUE TITLE
Replace deprecated package `shortid`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1899]
**Describe the bug**

1. shortid is no longer supported

**To Reproduce**

- Run `npm install`. You'll see this messag

```
npm WARN deprecated shortid@2.2.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

```

**Expected behavior**

1. No error because a currently maintained equivalent package is used
2. All functionality is maintained
3. All tests are valid and code coverage is maintained

**Actual behavior**

- See above

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sahi1l-Kumar** [comment]
Please assign this issue to me.

**Comment by its-VinayKumar** [comment]
@palisadoes Please assign this issue to me.
