### ISSUE TITLE
Event End time can be earlier than Start time

### ISSUE THREAD

**Issue by wasifkareem** [PalisadoesFoundation/talawa-api#1901]
**Describe the bug**
user can create event with end time earlier than start time.

**To Reproduce**

1.Go to /orgevents/id={id} in talawa-admin
2.Click on Add Event
3.Turn off the all day option
4.now you can create event with end time before the start time

**Expected behavior**
API should throw an error message saying "end time shouldn't be earler than start time"

**Actual behavior**
user can set the time backwards  and the api registers it  

**Screenshots**

![Screenshot from 2024-02-27 19-58-48](https://github.com/PalisadoesFoundation/talawa-api/assets/119349657/bf5a5afe-3aa3-4765-8209-8d43dc70898a)

**Additional details**
related to [#1618](https://github.com/PalisadoesFoundation/talawa-admin/issues/1618)
@Cioppolo14  Please assign me this as I'm working on this on the admin side already.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AspireSsp** [comment]
if no one is working on this issue, can you pls assign it to me? I would like to work on it.
