### ISSUE TITLE
Update the Sample Data With Recurring Events

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1903]
We need to have more realistic data in the Talawa-API sample data importation process. The data also needs to be more secular so that the application will more likely appeal to a wider range of Admins testing Talawa for their communities.

## Possible Approach

You will need to investigate whether this approach is viable and suggest modifications where applicable.

1. Load the current sample data into Talawa Admin
2. Use Talawa Admin to make the modifications below
3. Save the resulting database as the new sample data that `setup.ts` uses

## Events

We need recurring events created so that the calendar is populated no matter when the data is loaded.

### Weekly Recurring Events – Non Registration

Add the following public events to each organization. Registration is not required:

1. Monday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Yoga Class for Seniors": 10:00am – 11:00am, Location: Studio B
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
    1. "Book of the Week Club": 2:00pm – 3:00pm, Location: Atlantic Conference Room
1. Tuesday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Travel Club": 6:00pm – 7:00pm, Location: Atlantic Conference Room
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
1. Wednesday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Travel Club": 6:00pm – 7:00pm, Location: Atlantic Conference Room
    1. "Art Class - Advanced": 10:00am – 11:00am, Location:
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
1. Thursday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Kids Karate": 6:00pm – 7:00pm, Location: Studio B
    1. "Art Class - Beginners": 3:00pm – 4:00pm, Location: Studio A
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
1. Friday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Neighborhood Watch Meeting": 6:00pm – 7:00pm, Location: Atlantic Conference Room
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
1. Saturday:
    1. "So Bad They’re Good Movie Night": 7:00pm – 9:00pm, Location: Main Theatre
1. Sunday:
    1. "Travel Club": 6:00pm – 7:00pm, Location: Atlantic Conference Room

### Weekly Recurring Events – With Registration

Add the following public events to each organization. Registration is required. Make at least 4 of the newly added users be pre-registered in each of the events with no timing conflicts.

1. Monday:
    1. "Youth Swimming Lessons": 3:00pm – 5:00pm, Location: Pool
    1. "Finance Committee Meeting": 5:00pm – 6:30pm, Location: Pacific Conference Room
    1. "Risk Committee Meeting": 6:00pm – 7:30pm, Location: Arctic Conference Room
1. Tuesday:
    1. "Adult Swimming Lessons": 3:00pm – 5:00pm, Location: Pool
    1. "Conference Planning Committee": 5:00pm – 6:30pm, Location: Pacific Conference Room
    1. "Organization Strategy Workshop": 6:00pm – 7:30pm, Location: Arctic Conference Room
1. Wednesday:
    1. "Youth Swimming Lessons": 3:00pm – 5:00pm, Location: Pool
    1. "Families With Addiction": 5:00pm – 6:30pm, Location: Pacific Conference Room
    1. "Investment Strategy Committee": 6:00pm – 7:30pm, Location: Arctic Conference Room
1. Thursday:
    1. "Adult Swimming Lessons": 3:00pm – 5:00pm, Location: Pool
    1. "Programming for Everyone": 3:00pm – 5:00pm, Location: Computer Lab
    1. "University Preparation Tips": 5:00pm – 8:00pm, Location: Arctic Conference Room
1. Friday:
    1. "Career Counseling": 3:00pm – 5:00pm, Location: Pacific Conference Room
1. Saturday:
    1. "Saturday Serenade Concert": 5:00pm – 7:00pm, Location: Garden Patio
    1. "Youth Soccer Lessons": 9:00am – 10:00am, Location: Sports Field
1. Sunday:
    1. "Travel Club": 6:00pm – 7:00pm, Location:

## Other
1. All tests must pass
1. No functionality of the app must be affected
1. The suggested entries above may have errors. Wherever possible there must not be scheduling conflicts for:
    1. Locations
    1. Users 
 1. The sample data must be importable by the setup script without error and fully functional no matter how many times the setup script is run.

**Comment by its-VinayKumar** [comment]
@palisadoes Plz assign me this issue.

**Comment by palisadoes** [comment]
It's already assigned

**Comment by Girishbari** [comment]
@palisadoes  are you still working on this ?
