### ISSUE TITLE
Update the`develop-userTypeFix` branch with the latest features from `develop` - Fundraising / Recurring Events

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1904]
**Is your feature request related to a problem? Please describe.**
1. We recently fixed the usage of `userType` with this PR.
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
1. A new `develop-userTypeFix` branch was created to add this feature
1. We need to make sure that the  `develop-userTypeFix` branch:
    1. Maintains its current functionality
    1. Includes any new features in the `develop` branch and adjusts them to the new `userType` functionality. 
     1. Has all valid and passing tests that maintain our current test code coverage levels

This is required to support new Fundraising and Recurring events features added to `develop`:

1. https://github.com/PalisadoesFoundation/talawa-api/pulls?q=is%3Apr+is%3Amerged+funds
2. https://github.com/PalisadoesFoundation/talawa-api/pulls?q=is%3Apr+is%3Amerged+recurring

**Describe the solution you'd like**
1. Merge `develop` into the `develop-userTypeFix` branch
3. Make sure all newly added features to the `develop` branch are included in the  `develop-userTypeFix` branch.
4. **The new functionality of `userType` must be unchanged.**
5. No other features must be affected
6. All tests must be valid and pass

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**
1. This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile

Research these issues for context with the new `userType` functionality:

1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
1. https://github.com/PalisadoesFoundation/talawa/issues/2373
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1451
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1452
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1862
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1904

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by its-VinayKumar** [comment]
@palisadoes Plz assign me this issue.

**Comment by palisadoes** [comment]
@its-VinayKumar 

As described in the issue, this is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile. Do you have that?

**Comment by AdityaRaimec22** [comment]
@palisadoes Can I get assigned to the issue.

**Comment by NamitBhutani** [comment]
@palisadoes Can I work on this?

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 I am going to assign you because of your profile experience/skills and history with our repos.

**Comment by palisadoes** [comment]
@AdityaRaimec22 

Have the newly merged PRs been a challenge for this work?

**Comment by AdityaRaimec22** [comment]
When I started the work of merging the `develop` branch into `develop-userTypeFix` branch I got merge conflicts in nearly `191 files` after solving them the count has reduced to `48 files` I will solve all the conflicts then run tests and will check the functionality as well. Till now the only challenge was that the number of files having merge conflict was quite high.

**Comment by palisadoes** [comment]
Thanks. I was concerned that it would be too challenging. 

I hope the last set will be manageable.

Let us know if there are any unexpected delays

**Comment by palisadoes** [comment]
Reopening. This was not fixed

**Comment by palisadoes** [comment]
@AdityaRaimec22 Are you still working on this?

**Comment by AdityaRaimec22** [comment]
> @AdityaRaimec22 Are you still working on this?

Yes @palisadoes I am still working on this will commit changes ASAP.
