### ISSUE TITLE
Error when running "npm run dev"

### ISSUE THREAD

**Issue by NamitBhutani** [PalisadoesFoundation/talawa-api#1906]
**Describe the bug**
`npm run dev` throws error 

**To Reproduce**

1. Update to the latest upstream/develop branch
2. Run npm run dev

**Expected behavior**
The api should generate code and start in watch mode

**Actual behavior**
It is throwing error, expecting a package `@parcel/watcher`

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/26519624/d4fa2f43-4acd-4075-88f8-c1187625d27c)

**Comment by NamitBhutani** [comment]
Can I work on this issue?

**Comment by skbhagat0502** [comment]
@NamitBhutani I dont think that this is an issue. You should first fetch upstream and run npm install for any new packages if there. 
I had the same problem but after running doing this the issue resolved.
firt sync your fork with upstream then run
`git pull`
`npm install`
`npm run dev'

The issue will be resolved.

**Comment by NamitBhutani** [comment]
> @NamitBhutani I dont think that this is an issue. You should first fetch upstream and run npm install for any new packages if there. I had the same problem but after running doing this the issue resolved. firt sync your fork with upstream then run `git pull` `npm install` `npm run dev'
> 
> The issue will be resolved.

The issue is still there on the develop branch, I just checked , I ran npm install
