### ISSUE TITLE
ImageUrl not getting fetched for posts

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-api#1915]
**Describe the bug**
when fetching post data with imageUrl it is showing Internal server error
**To Reproduce**

1.Go to apollo sandbox
2.Run posts query.

**Expected behavior**
It should correctly return the imageUrl of the post even when it is null

**Actual behavior**
showing internal server error

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/132201033/955327a8-f6ed-4863-9546-e55a27fcf26b)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tushar-c23** [comment]
Hi @AVtheking , i understand the bug and i would like to work on the same kindly point me towards the module i should mostly focus on in the codebase
