### ISSUE TITLE
Add Support for Production Build of Talawa Api

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#1916]
**Describe the bug**
In the repo `src/server.js` is a stale file and in package.json we are still using the server.js to run the production build files 

```
    "start": "cross-env pm2-runtime start ./build/server.js --watch",
    "prod": "cross-env NODE_ENV=production pm2-runtime start ./build/server.js",
```

We have an old  ts-config-build.json and most of the packages only support the ES modules compatible but our ts-config.build .json emits commonjs and it doesn't support them, leading to new errors for the build environment.

**To Reproduce**

1. npm run build
2. npm run start

**Expected behavior**

1. It has to be pointed to `index.js` instead server.js which is a commented file.
2. The npm run build command should be emitted without any errors. 
3. The server should be accessed at localhost:4000 in a production environment.

**Screenshots**

```
C:\Users\91970\Desktop\talawa\talawa-api>npm run start

> talawa-api@1.0.0 start
> cross-env pm2-runtime start ./build/index.js --watch

2024-02-28T00:17:02: PM2 log: Launching in no daemon mode
2024-02-28T00:17:02: PM2 log: [Watch] Start watching index
2024-02-28T00:17:02: PM2 log: App [index:0] starting in -fork mode-
2024-02-28T00:17:02: PM2 log: App [index:0] online
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\91970\Desktop\talawa\talawa-api\node_modules\nanoid\index.js from C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js not supported.
Instead change the require of index.js in C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js to a dynamic import() which is available in all CommonJS modules.
    at Hook._require.Module.require (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\require-in-the-middle\index.js:101:39)
    at Object.<anonymous> (C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js:18:18)
    at Hook._require.Module.require 
```

**Additional details**
This has to be addressed in order to support the production setup of talawa-api and started working on it as discussed in #1885 .
This issue require multiple PRs to support Production environment build

**Comment by varshith257** [comment]
Please assign me this issue.

**Comment by varshith257** [comment]
Working on it 😅

**Comment by varshith257** [comment]
Workiy

**Comment by varshith257** [comment]
😅

**Comment by palisadoes** [comment]
Can this be closed now? Is there a part 3?

**Comment by varshith257** [comment]
Yes, we can close this now. There needed more changes in our codebase to add Production Support. It will be reopened after our codebase gets stability with the required features. It is also a type of migration work.
