### ISSUE TITLE
Chat-Based Analytics 

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#1918]
Hello Talawa community! 👋

I'm thrilled to share an exciting idea I've been working on to enhance the Talawa Admin platform: Chat-Based Analytics. This feature aims to empower administrators with an intuitive and accessible way to interact with data through natural language queries.

**Idea Overview**:
Imagine administrators asking questions like “How many events were there in last month?” and the system would generate and execute the corresponding MongoDB query and return the answer in a chat format. This way, administrators can get insights from their data without needing to know specific database queries or syntax.

To implement this idea, I have created a basic NLP model using the spacy library, regex and the en_web_core_sm package. The model can understand simple queries and convert them into MongoDB queries.

**Challenges and Alternatives**:
I've identified some challenges and explored alternative solutions:

1. **[MongoDB Translator](https://github.com/codeSTACKr/mongodb-translator)**: This is a free and open-source tool that uses a pre-trained GPT-3 model to convert natural language queries into MongoDB queries. 

2. **[nl2query](https://github.com/Chirayu-Tripathi/nl2query)**: This is a framework for converting natural language text inputs to corresponding Pandas, MongoDB, Kusto and Neo4j (Cypher) queries.It uses a pre-trained CodeT5+ 220m model and fine-tunes it on a dataset of SQL queries and their natural language equivalents. It also provides a Python library that lets you use the framework in your code.

**Your thoughts** : 
I would appreciate your opinions and advice on these options, or any other suggestions that you might have. I am also open to collaborating with other developers who are interested in working on this idea. I think this feature could be a valuable addition to the Talawa platform, as it can make it more accessible and user-friendly for administrators who may not be comfortable with traditional data analysis tools.

**Demo**:
To demonstrate the potential of Chat-Based Analytics, I've created a working demo using a event collection. The NLP model has been integrated to handle queries related to this dataset. I could have also used Faker.js to generate diverse and extensive mock datasets for comprehensive testing and refinement.

@palisadoes @DMills27 @bonnie-23 @Ayush0Chaudhary 

https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/1e9e1404-edf3-4f65-91dd-8d9db2afe2dc

**Comment by krishna619** [comment]
@palisadoes 
Cool.
But will it be fine to mention such AI related ideas while submitting proposal for Gsoc?

**Comment by palisadoes** [comment]
Please read the project idea list for context

**Comment by krishna619** [comment]
> Please read the project idea list for context

Sure sir
Let me go through it once.
