### ISSUE TITLE
Upgrade node-notifier package to > version 8.0.1 in package-lock.json

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#192]
We need to remedy the following known vulnerability: https://github.com/advisories/GHSA-5fw9-fq32-wv5p

GitHub cannot automatically do the required update to > 8.0.1 because:

```
The latest possible version that can be installed is 7.0.2 because of the following conflicting dependency:

jest@26.0.1 requires node-notifier@^7.0.0 via a transitive dependency on @jest/reporters@26.0.1
The earliest fixed version is 8.0.1.
```

This update needs to be implemented and tested.

**Comment by palisadoes** [comment]
Assigned to @Hrishikesh-Bhagwat

**Comment by somya339** [comment]
I want to work on this issue.
