### ISSUE TITLE
Change eslint's `no-explicit-any` rule from `error` to `warn`

### ISSUE THREAD

**Issue by xoldyckk** [PalisadoesFoundation/talawa-api#1944]
Eslint's `no-explicit-any` rule was prematurely enabled without the codebase already being in a state free of implicit or explicit usage of `any` keyword. This creates problems because new PRs would have to resolve issues that are unrelated to them because of minor changes in files that contain issues regarding the `any` keyword.

The attribute for the lint rule should be changed to `warn` for now. New issues must be created to resolve the warnings related to `no-explicit-any` rule, once all the warnings are resolved, the rule's attribute would be changed back to `error` and any further contributions must be free of the implicit or explicit usage of `any` keyword.

**Comment by varshith257** [comment]
@xoldyckk  I think we can use it as a parent issue to track the related issues until it turn back from warn to erroe

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?
