### ISSUE TITLE
Schedule Reminders for Action Items (CRON)

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#1947]
**Description**
Schedule reminders for action items. 

**Key Features:**

**Toggle for Set Reminder:**
Introduce a toggle option when creating or editing an action item to enable or disable reminders.

**Reminder Settings:**
Allow users to set the timing for reminders (e.g., 12 hours before the due date).

**Notification Type**
in-app notifications, email notifications, or both.

**Cron Job Integration**

**Comment by palisadoes** [comment]
1. Though this is a good idea, we need to focus on the core functionality and bug fixes at this time.
2. Not all operating systems use cron, so some other universal solution would need to be considered. Possibly a second process just for notifications in general.
3. Closing

**Comment by krishna619** [comment]
> 1. Though this is a good idea, we need to focus on the core functionality and bug fixes at this time.
> 2. Not all operating systems use cron, so some other universal solution would need to be considered. Possibly a second process just for notifications in general.
> 3. Closing

Cool. we can look upon this in future.
