### ISSUE TITLE
Documentation Issue: Missing Steps for Generating App Password

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [PalisadoesFoundation/talawa-api#1950]
**Describe the bug**
The instructions provided in the documentation do not align with the current interface on the Google Account page when attempting to generate an app password for Setting up .env MAIL_USERNAME and MAIL_PASSWORD. There is no "Select app" section and no "Generate" button.

**To Reproduce**

1. Open INSTALLATION.md file.
2. Go to Setting up .env MAIL_USERNAME and MAIL_PASSWORD ReCAPTCHA Parameters.
3. Check option 4 There is  selecting an app and generating a password, but the expected options are not present.

**Expected behavior**
The documentation should accurately guide users on how to generate an app password by providing steps that match the current interface of the Google Account page.

**Actual behavior**
The provided documentation instructions do not correspond to the interface of the Google Account page, leaving users unable to generate an app password as intended.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/94298791/f04795f7-a936-483b-9ba2-e7b1edd2898a)

**Additional details**

https://github.com/PalisadoesFoundation/talawa-api/assets/94298791/5f109472-4422-453c-8533-6447719dec58

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by takshakmudgal** [comment]
I'd like to work on this issue.
