### ISSUE TITLE
Join date for Organization

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#1951]
**Describe the bug**
User model should have field for `joinDate` for every organization which should be automatically added on join org mutation.
Every User is individually a part of the Organization and shouldn't have 1 common createdAt date only.

**Additional details**
Linked Issue #1711 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sourabh-awasthy** [comment]
please assign this issue to me

**Comment by palisadoes** [comment]
@pranshugupta54 

1. Is there an immediate need for this?
2. Is the need sufficiently important for us to add this feature?

If so, then

1. If this were to be done it would mean we'd need to create a new object type list for `joinedOrganizations` that included a Joined date and the `Organization` object.
2. This would need to be coordinated with Mobile and Admin too as separate issues

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/8248f379-a529-42ff-848e-4cd85c65a5f3)

**Comment by Sourabh-awasthy** [comment]
@palisadoes 
i have seen the schema and the required changes in schema and other files for this issue. it can be incorporated easily like this but will need to implement in App and admin but its not that immediate
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/116659744/4dd48f60-e8bd-48fc-94de-055cb60e305a)

**Comment by palisadoes** [comment]
1. Why do you use an interface and not a new collection for this?
2. The name should be `JoinedOrganization`

**Comment by Sourabh-awasthy** [comment]
Yes JoinedOrganization will be more apt name .
In my opinion we can use collection too but using an interface instead for this purpose ensuring consistency across different parts of the codebase and retrieving it will be simplified through 'User' as it is not needed to queried, updated, or deleted independently.

**Comment by palisadoes** [comment]
Will this work in cases where Users are removed from Organization membership such that all other functionality is maintained?

**Comment by palisadoes** [comment]
1. You are not interpreting the schema correctly.
2. I'm going to close this. We have other more pressing issues to address.
