### ISSUE TITLE
[Bug]: GraphQL Queries Lack Authentication Controls

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#1967]
**Describe the bug**
Some GraphQL queries, such as`directChatsByUserID`, `joinedOrganizations`, `organizations` etc, do not currently enforce authentication controls. This presents a security risk as sensitive information could be accessed by unauthorized users. Without proper authentication mechanisms in place, anyone can execute these queries and retrieve data that should be restricted to authenticated users.

**Impact:**
- **Security Risk**: Lack of authentication controls exposes sensitive user data to unauthorized access.
- **Compliance Concerns**: Failure to enforce authentication measures may violate data protection regulations and compliance standards.
- **User Privacy**: Users' private conversations and information could be accessed by unauthorized parties, leading to privacy breaches.

**Extra**:
- [ ] I'm interested in working on this issue

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@pranshugupta54 What changes need to be done to mobile and admin to make them compliant? Please verify you are working in the develop branch.

**Comment by pranshugupta54** [comment]
@Cioppolo14, we don't need changes on mobile/admin directly for now but users can access the API via other methods too. 
For example, 

I can see direct chats of any user using query,
_Status:200, though no chats found_
<img width="995" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/f89107e4-0952-4bdb-acfc-8725f133210d">

I can view all organisations (even private)

<img width="989" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/51182a0d-a72c-49cd-a919-f5547c5f76fb">

**Comment by Shubh152** [comment]
@Cioppolo14 Please assign this issue to me if available.

**Comment by Olatade** [comment]
@Shubh152 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Shubh152** [comment]
I have now unassigned from one issue, please assign me this issue.

**Comment by palisadoes** [comment]
Closing. This discussion is covering a long term auth solution for the API. You can comment there.
- https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1991995509

**Comment by varshith257** [comment]
> Closing. This discussion is covering a long term auth solution for the API. You can comment there.
> - https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1991995509

Our current ongoing discussion about authentication can be covered this all as goal of implementing  strict authentication and authorization mechanisms to Talawa.

**Comment by pranshugupta54** [comment]
Sounds good to use Casl or Casbin etc for fixing Auth 👍

**Comment by palisadoes** [comment]
What is the simplest way to implement this as an immediate fix without the longer term goal of considering installing new packages?
