### ISSUE TITLE
[Bug]:Update Campaign mutation showing bug 

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-api#1969]
**Describe the bug**
while mutating update fund campaign mutation it is showing  this bug

**To Reproduce**
1.Go to apollo sandbox
2.Run update Fundraising mutation.

**Expected behavior**
It should return updated Fund campaign.

**Actual behavior**
showing internal server error.

**ScreenShot**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/132201033/596126db-6d24-479a-bbe1-1e4d0a712ce4)

**Comment by Cioppolo14** [comment]
@AVtheking I am going to close this issue, if you believe it needs to be fixed, please complete the issue template in detail.

**Comment by AVtheking** [comment]
ok  I will complete the issue template.

**Comment by Manik2708** [comment]
If this is aproved, then can I work on this issue?

**Comment by AVtheking** [comment]
yes @Manik2708 go for it you need to specify this mutation in index.ts file of the mutation .

**Comment by AVtheking** [comment]
also lookout for some other mutations which are not mentioned in index.ts file

**Comment by Manik2708** [comment]
> If this is aproved, then can I work on this issue?

@Cioppolo14

**Comment by AVtheking** [comment]
@Manik2708 are you working on this issue ?
