### ISSUE TITLE
Add tagColor in OrganizationUserTag 

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-api#1970]
**Is your feature request related to a problem? Please describe.**

The current structure of User tags lacks an essential attribute, `tagColor`, which would facilitate easier differentiation between tag
The addition of the `tagColor` attribute will contribute to a more robust and user-friendly tagging system.

**Describe the solution you'd like**
To address this issue, we propose adding the `tagColor` attribute to the schema for User tags.

**Describe alternatives you've considered**
Without the `tagColor` attribute, users may rely on other visual cues such as text formatting or icons to distinguish between tags.

**Approach to be followed (optional)**
We need to modify the existing schema for User tags by adding tagColor attribute.

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/90516956/0ad6eafd-dd27-431c-8513-e8a8ca55dc41)
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/90516956/6034fabf-d2df-4a0b-b5f7-0c4aa3ddfcf0)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
@duplixx, I had a similar idea for the implementation of `user tag management`. However, in my opinion, storing the tag color in the database may not be necessary. The color handling could be managed on the Talawa-Admin frontend part.

**Comment by duplixx** [comment]
@akhilender-bongirwar I agree that storing tags in the front end is an immediate solution. However, storing tag colors in the backend would be preferable for a more **robust**, **scalable** and **compatible** solution.

**Comment by duplixx** [comment]
@Cioppolo14 i wanna work on this issue
