### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by XshubhamX** [PalisadoesFoundation/talawa-api#198]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Currently the whole code is in older javascript syntax of const vaiable = require(path/module),It would be better if the syntax is in ES6 javascript where we use import and export keywords.

**Describe alternatives you've considered**
In import export syntax its easy to determine which import is default import and which is named one. 

**Approach to be followed (optional)**
there will be a little bit change in pakage.json and then i will implement latest syntax into the mix 

**Additional context**
If you think that my Idea is reliable then Please assign it to me

**Comment by XshubhamX** [comment]
Can i work on this feature.

**Comment by palisadoes** [comment]
@XshubhamX are you available to work on this issue?

**Comment by XshubhamX** [comment]
@palisadoes sir I will solve this issue after solving previous ones
