### ISSUE TITLE
Update the`develop-userTypeFix` branch with the latest features from `develop` - Deleting Recurring Events

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#1987]
**Is your feature request related to a problem? Please describe.**
1. We recently fixed the usage of `userType` with this PR.
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
1. A new `develop-userTypeFix` branch was created to add this feature
1. We need to make sure that the `develop-userTypeFix` branch:
    1. Maintains its current functionality
    1. Includes any new features in the `develop` branch and adjusts them to the new `userType` functionality. 
     1. Has all valid and passing tests that maintain our current test code coverage levels

This is required to support these new features added to `develop`:

1. https://github.com/PalisadoesFoundation/talawa-api/pull/1890
1. https://github.com/PalisadoesFoundation/talawa-api/pull/1952
1. https://github.com/PalisadoesFoundation/talawa-api/pull/1917
1. https://github.com/PalisadoesFoundation/talawa-api/pull/1960

**Describe the solution you'd like**
1. Merge `develop` into the `develop-userTypeFix` branch
3. Make sure all newly added features to the `develop` branch are included in the  `develop-userTypeFix` branch.
4. The new functionality of `userType` must be unchanged.
5. No other features must be affected
6. All tests must be valid and pass

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**
1. This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile

Research these issues for context with the new `userType` functionality:

1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Atharva-Kanherkar** [comment]
I would like to work on this issue! I have been working on the event agenda issue, so I might as well be knowing a little more on how to implement this. I would be happy to work on this one.

**Comment by palisadoes** [comment]
You'll also need to integrate the changes in the latest PR
- https://github.com/PalisadoesFoundation/talawa-api/pull/1960

**Comment by Atharva-Kanherkar** [comment]
> You'll also need to integrate the changes in the latest PR
> 
> * [feat : Creating support for event agendas : Agenda Section CRUD #1960](https://github.com/PalisadoesFoundation/talawa-api/pull/1960)

Yes, surely. I have started to work on this.

**Comment by Atharva-Kanherkar** [comment]
Hello, @palisadoes
I have a minor query: Should I focus on integrating all changes from the develop branch that haven't yet been incorporated into the userTypeFix branch? Or are we specifically targeting the four mentioned PRs?

**Comment by palisadoes** [comment]
1. Ideally all `develop` changes. I'm willing freeze future API `develop` merges to accommodate this work.
2. Is this too much of a hardship, or should I adjust this expectation?

**Comment by Atharva-Kanherkar** [comment]
> 1. Ideally all `develop` changes. I'm willing freeze future API `develop` merges to accommodate this work.
> 2. Is this too much of a hardship, or should I adjust this expectation?

1. Alright...
2. It is hard, as there are almost 100+ conflicts. But i am working as much as i can according to my capabilities. Some of the files i do not understand, so i have left them. Many of the files i do understand, so i am focusing on them first. Then i will ask the people involed with the PRs to help me with the left files...
I am trying my best, and i hope i can solve this issue.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes, This issue here telling me that objectId is deprecated, is there any relevant information or updates on our codebase that i am missing? Or are we still using the objectId everywhere? Because it is most probably deprecated everywhere.
<img width="563" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/142440039/d53ed799-4858-448d-b47f-c08c8017937e">

**Comment by varshith257** [comment]
@Atharva-Kanherkar The Same issue occurred while making changes in #1916 . This needs to be addressed, I have solved them and will make a PR soon about this error.

**Comment by palisadoes** [comment]
@Atharva-Kanherkar If it's deprecated and still functional proceed with the error. 

@varshith257 can fix it after we go live with the new branch to reduce the risk of more merge conflicts now.

**Comment by palisadoes** [comment]
Only 2 issues to go before we are ready to merge back into develop. This is one of them.

I just merged this PR into `develop-fixUserType`, which may cause some additional conflicts:

- https://github.com/PalisadoesFoundation/talawa-api/issues/1862

**Comment by palisadoes** [comment]
This is now the last issue left. 

This issue will be completed after the merge back into `develop`.
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1452

**Comment by Atharva-Kanherkar** [comment]
@palisadoes  i am fixing the merge conflicts and the merge conflicts in the /tests directory are left. i will try to make a PR by tonight or tommorrow morning IST.

**Comment by palisadoes** [comment]
Remember to verify that the data importation works correctly with roles assigned appropriately. It should from previous PRs, but you'll need to make sure.

**Comment by palisadoes** [comment]
> @palisadoes  i am fixing the merge conflicts and the merge conflicts in the /tests directory are left. i will try to make a PR by tonight or tommorrow morning IST.

How's progress? Our queues have many approved PRs waiting on this to get merged

**Comment by Atharva-Kanherkar** [comment]
> > @palisadoes  i am fixing the merge conflicts and the merge conflicts in the /tests directory are left. i will try to make a PR by tonight or tommorrow morning IST.
> 
> How's progress? Our queues have many approved PRs waiting on this to get merged

Hello, i am working day and night to get the issue resolved. The test code coverage has become really low so i will be making the PR very soon.
