### ISSUE TITLE
UpdateUserProfile -  Insecure Image Upload Handling and Content type tampering (DoS)

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#1988]
**Describe the bug**

When intercepting the **UpdateUserProfile** GraphQL mutation and attempting to upload a large text file with a modified file type (e.g., changing from text to PNG), the server becomes unresponsive. This behavior indicates a potential vulnerability to a Denial of Service (DoS) attack. Furthermore, it seems that the mutation allows the unauthorized modification of the content type, posing a security concern related to unauthorized photo uploading.

**To Reproduce**
1. Intercept the UpdateUserProfile mutation.
2. Attempt to upload a large text file.
3. Modify the content type to "image/png."

Please ensure that the content type of the uploaded file is verified on the server-side, not just by checking the file extension.

P.S- use this payload for reference
https://easyupload.io/6lyizt

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@Cioppolo14 @krishna619   This functionality will be restored in GSOC Project Improved Files Upload and Security.

**Comment by krishna619** [comment]
@varshith257 Cool.

@Cioppolo14 For the time being, can I move forward to close this ticket?
