### ISSUE TITLE
Feature Request: Implement Filtering Capabilities and Fixing Infinite Scrolling in Search Requests

### ISSUE THREAD

**Issue by Sahi1l-Kumar** [PalisadoesFoundation/talawa-api#1989]
**Is your feature request related to a problem? Please describe.**
The current GraphQL schema lacks support for filtering `membershipRequests` based on specific parameters like `firstName`.
It also do not support `skip` and `first` arguments which are needed for Pagination.

**Describe the solution you'd like**

1. Extend the existing GraphQL schema to include a `where`, `first`, `skip` argument for the `membershipRequests` field in the `Organization` type. 
2. This `where` argument would accept input parameters corresponding to the desired filters, allowing the server to process and return filtered membership requests efficiently.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**

1. This need was identified here:
https://github.com/PalisadoesFoundation/talawa-admin/issues/1631

2. Screen shot of the `Organization` collection
![Screenshot 2024-03-12 170144](https://github.com/PalisadoesFoundation/talawa-admin/assets/135227614/8fcc1ddf-d17d-459c-8d11-7c5728d0da30)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Shubh152** [comment]
Please assign me this issue

**Comment by Sahi1l-Kumar** [comment]
Can I get this assigned since I am doing the parent issue in talawa-admin

**Comment by Cioppolo14** [comment]
@Sahi1l-Kumar I will assign you since you created it based on the talawa-admin issue you are assigned.  In the future, you can mention at the bottom of the issue or comment on it right away that you want to work on it.

**Comment by Sahi1l-Kumar** [comment]
> @Sahi1l-Kumar I will assign you since you created it based on the talawa-admin issue you are assigned.  In the future, you can mention at the bottom of the issue or comment on it right away that you want to work on it. 

Okay. I won't forget to mention that next time.
