### ISSUE TITLE
Add Support for Fastify instead Express for Backend Framework

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#1991]
**Is your feature request related to a problem? Please describe.**

 Fastify is known for its LTS for the Typescript community Fastify has LTS and has shown to be significantly faster than Express and has the same features as Express support. Fastify is a modern web framework highly focused on providing the best developer experience with the least overhead and a powerful plugin architecture. It is one of the fastest modern web frameworks and also can be a good alternative to Express because it can process requests 20% faster than ExpressJS. Fastify is also faster than Express in terms of response time and request throughput. 

**Describe the solution you'd like**

Migrate current backend framework support of express to fastify without affecting any other functionalities 

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

1. Migrate the current backend framework i.e.. express to support fastify in `develop-userTypeFix` branch
2. Remove all packages related to express and if needed,  restore with the modern alternative packages.

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@palisadoes This is the first feature we are going to implement as we discussed and please assign this issue to me

**Comment by palisadoes** [comment]
Closing temporarily until we get agreement on the desired path.

**Comment by palisadoes** [comment]
Reference

- https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1991809622

**Comment by palisadoes** [comment]
We need to stop this and figure out what exactly we want to achieve. @DMills27 has a point. We have a history of changing things without meaningful improvements.
- https://github.com/PalisadoesFoundation/talawa-api/discussions/1997

We can reopen it when we have clarity

**Comment by varshith257** [comment]
@palisadoes I think we have agreement on this. Can we reopen this ?

**Comment by varshith257** [comment]
@palisadoes Could I start this work with the support of the develop-userTypeFix branch or develop? I think the merging work of these branches has started. Can I go with develop branch?

**Comment by palisadoes** [comment]
It would be best to work on the `develop-userTypeFix` branch and then apply the PR against `develop`. There would be fewer merge conflicts

**Comment by varshith257** [comment]
@palisadoes It's quite a challenge finding Fastify-compatible middlewares equivalent to those supported by Express. However, I'm investing my time and effort into this process to ensure we make progress  besides working on my GSOC proposals. Rest assured, I'll be working thoroughly to prepare and submit a PR soon.

**Comment by palisadoes** [comment]
Is the migration to `fastify` still justified? `express` just came out with a new release
- https://github.com/expressjs/express/releases

Many of the `any` linting issues in the API stem from the use of Mongoose. If we replace that with a more Typescript compliant package would the fixing of the `express`  `any`  issues be manageable?

**Comment by varshith257** [comment]
@palisadoes Sorry to get you confused. I intended that we use express middlewares for express and to replace the same for Fastify we had to use their ecosystem supported [refer this](https://fastify.dev/docs/latest/Guides/Ecosystem/). All fastify middlewares related to the backend framework are maintained as its core and community so we don't need to worry about it.

>**Is the migration to Fastify still justified? Express just came out with a new release.**

While the recent release of Express is noteworthy, our decision to migrate to Fastify was based on several factors, including its performance benefits, strong LTS for TypeScript ( what express lacks) and potential for improved scalability. I believe that Fastify offers advantages that align with our project's requirements and long-term goals as @xoldyckk  discussed [here](https://github.com/PalisadoesFoundation/talawa-api/discussions/1997#discussioncomment-8776302) well

>**Many of the any linting issues mentioned in the discussion in the API stem from the use of Mongoose. If we replace that with a more Typescript compliant package would the fixing of the express any issues be manageable?**

Yes, we can make use of Prisma which is a strong candidate for a ts-compliant package instead mongoose to eliminate the long-living issue in our codebase, Also we have a discussion regarding db migration. If we proceed towards Postgresql, drizzle orm should be used. To update on this migration part we can safely migrate to PostgreSQL without making much effect on clients admin and mobile [refer this](https://hevodata.com/blog/mongodb-to-postgresql/) and [this](https://estuary.dev/mongodb-to-postgresql/)

>**One of the selling points for Fastify was that Express required middleware whereas Fastify did not. Hearing that you are looking for middleware is unexpected. The irony would be to use Express for middleware as stated in the discussion. Is this really the right approach?**

You raised a valid point regarding the differences in middleware handling between Express and Fastify. The decision to explore middleware solutions is driven by the need to ensure compatibility with existing Express-based middleware while migrating to Fastify. We can make use of existing middleware of express using  [@fastify/express](https://github.com/fastify/fastify-express) plugin is the quickest way to get existing Express working with Fastify. But may lack compatibility and integration so I am trying toremove all express instances from our codebase to replace with the fastify plugins 

To better understand here's a simple migration of **cors package** of express to fastify:

Express:

```
const corsOptions: cors.CorsOptions = {
  origin: (origin, next) => {
    if (process.env.NODE_ENV === "development") {
      next(null, true);
      return;
    } else if (process.env.NODE_ENV === "production") {
      const talawaAdmin = process.env.TALAWA_ADMIN_URL;
      if (origin === talawaAdmin) {
        next(null, true);
        return;
      }
    }

    next(new Error("Unauthorized"));
  },
};
```

Same use of cors using **@fastify/cors** in Fastify:

```
fastifyApp.register(cors, {
    origin: (origin, cb) => {
    if (process.env.NODE_ENV === "development") {
    //  Request from localhost will pass
      cb(null, true);
      return;
    } else if (process.env.NODE_ENV === "production") {
      const talawaAdmin = process.env.TALAWA_ADMIN_URL;
      if (origin === talawaAdmin) {
        cb(null, true);
        return;
      }
    }
    // Generate an error on other origins, disabling access
    cb(new Error("Unauthorized"), false);
  },
});
```
Just I am trying to replace all existing middleware with the fastify supported in it's ecosystem as core or community.

**Comment by varshith257** [comment]
Almost done with the work except few. Will complete it by this weekend. I really have to focus on my proposal for AI-Powered Community Health Improvements. There is a lot to discover for the technical implementation of this project adhering the given constraints and supports integration with our Talawa ecosystem and project goals. Though I have experience in AI/ML and web/mobile dev, the challenge is to leverage this two domains effectively for this project. I have explored many projects for a case study but none resulted. It's totally require a innovative solution for this project and actively working towards it that how best we can achieve this

**Comment by xoldd** [comment]
@varshith257 I would say instead of replicating everything 1:1, focus should also be on removing useless stuff from the express implementation and incorporating things the correct way. Otherwise there would be a certain wasted effort.

**Comment by varshith257** [comment]
Yeah, I am doing that what fastify supports instead express packages I am incorporating them . Due to working on proposal I didn't made a PR. Almost done with work to raise a PR with a minor adjustments.

**Comment by varshith257** [comment]
@xoldd I had DM you in a slack . Can you please look at it?

**Comment by Cioppolo14** [comment]
@varshith257

**Comment by varshith257** [comment]
Thanks @Cioppolo14 for alerting me. Will make a PR by EOD.

**Comment by palisadoes** [comment]
We need to wait for feedback from the GSoC awardees.
Closing. We can reopen depending on the final decision
