### ISSUE TITLE
[Bug]: Incorrect Organization Membership Check in addEventAttendee Mutation

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#1992]
**Describe the bug**
In the `addEventAttendee` mutation, the function incorrectly checks for organization membership by comparing the `joinedOrganizations` arrays of the `currentUser` and `requestUser`. This approach is not accurate as it does not consider the organization associated with the event.

**Proposed Solution:**
Instead of comparing the `joinedOrganizations` arrays, the function should retrieve the organization associated with the event using its ID (`eventId`). Then, it should check if both the `currentUser` and `requestUser` are members of that organization.

**To Reproduce**

1) Call the `addEventAttendee` mutation with `currentUser` and `requestUser` who are members of different organizations but are attending an event associated with one of the organizations.
2) Observe that the mutation incorrectly permits attendance due to the flawed organization membership check.

_Easy Explanation:_
- Suppose `currentUser` (Admin of Event) and `requestUser` both are part of `Org X`.
- Event happens in `Org Y`
- Current code checks if they have common Org ✅ - YES
- Adds the user to event

**But the requestUser was not even in Org Y**
_(Do not confuse this with AppUser and Non-AppUser)_

**Expected behavior**
The `addEventAttendee` mutation should only allow attendance if both the `currentUser` and `requestUser` are members of the organization associated with the event.

**Screenshots**
<img width="618" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/6fa69135-f0da-46fd-a875-0da18fe494d2">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by krishna619** [comment]
@pranshugupta54
1) if the current user is the admin of say Org X, he anyways cannot add eventAttendee for event in Org Y unless he is also the admin of Org Y.
2) And, if the current user is also the admin of Org Y, then how are you extracting eventId , take a case where we have events both in Org X and Org Y.

**Comment by pranshugupta54** [comment]
@krishna619, take 2nd case.

currentUser (Admin) -> OrgX and OrgY
requestUser -> OrgX

Event happens in OrgY, now admin tries to add the user to event which follows:

- check if they have common Org - YES (OrgX is common)

**Comment by pranshugupta54** [comment]
Probably casl will be used for Auth soon, but these functions will still have issues bcuz that won't check the function

**Comment by pranshugupta54** [comment]
There exists mapping for Events and Orgs. Events have a field for OrgId

**Comment by krishna619** [comment]
Okay. I'll fix this then.
Assign this to me.
