### ISSUE TITLE
The updateUserProfile mutation should incorporate the appLanguageCode field to modify the language preference in develop-userTypeFix.

### ISSUE THREAD

**Issue by adi790uu** [PalisadoesFoundation/talawa-api#1998]
**Is your feature request related to a problem? Please describe.**

Currently, in develop-userTypeFix branch the updateUserProfile mutation does not contain logic to modify the appLanguageCode field which is necessary to update language preference.

**Describe the solution you'd like**

Adding the logic to change the language preference in the updateUserProfile mutation.

**Additional context**
![Screenshot 2024-03-12 at 11 13 19 PM](https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/10a703db-be43-4fda-8f07-361e90b92a69)

![Screenshot 2024-03-12 at 11 21 22 PM](https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/caafa181-cbd4-4916-94f7-2eec0590d2ce)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment]
@Cioppolo14 @palisadoes  I know I am assigned three issues currently but this needs to be fixed quickly for resolving  Member Details screen in admin repo develop-userTypeFix branch.

Could you assign me this?

**Comment by adi790uu** [comment]
@Cioppolo14 I have made the changes and will create a PR as soon as I am assigned this.

**Comment by Cioppolo14** [comment]
@adi790uu I will make an exception here, because it seems part of the other issue you are assigned, but we need to get some issues off your list soon.
