### ISSUE TITLE
Unauthorized access to organizations in GraphQL query

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#2009]
**Describe the bug**
Currently, the GraphQL endpoint allows users to query for organizations regardless of whether they are members of those organizations or not.
`{"operationName":"Organizations","variables":{"firstName_contains":"","lastName_contains":"","orgId":"<ID>"},`

I can change the `orgId` and it would return the list of members about the organization even though I am not the part of it.

**To Reproduce**

1. Access the GraphQL endpoint.
2. Use the provided GraphQL query to retrieve organization data.
3. Note that users can retrieve data for organizations they are not members of.

**Expected behavior**
Members should only be able to query organizations that they are members of. Unauthorized users should not be able to access organization data.

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
Similar to #1967, will be covered in coming Authorization soon.

**Comment by krishna619** [comment]
Thanks
closing this for now.
