### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by XshubhamX** [PalisadoesFoundation/talawa-api#203]
**Is your feature request related to a problem? Please describe.**
Related to Optimization.

In Mongoose comment model If we have a closer look at its attributes we will see that we are storing array of users in LikedBy field of  comment. If we are just using the no. of likes on a comment then we can optimize system by not storing the data of user.

if a user want to remove his like from a comment, Then we can just decrement the like on it and will show the same in next render.

![Screenshot 2021-04-02 093252](https://user-images.githubusercontent.com/63532716/113379541-6cd25300-9397-11eb-98c1-518284042175.png)

@Laurell876  If you feel this optimization is Good ,So please assign this to me

**Comment by palisadoes** [comment]
@XshubhamX Are you still available to work on this?

**Comment by XshubhamX** [comment]
@palisadoes Sir previously this field was not being used but now I think there is a need to store likedBy data to reflect who liked the post in frontend.

**Comment by palisadoes** [comment]
This could be a useful feature. Please work with @rutvik11062000 as he will soon be creating `talawa` screens that may require this and similar features

**Comment by XshubhamX** [comment]
Ok sir I will contact him.
