### ISSUE TITLE
:bug: [BUG] : Upgrade juliangruber/sleep-action from v1 to v2

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#2030]
**Describe the bug**

 juliangruber/sleep-action@v1 is supported with node 16 and is deprecated 

**Expected behavior**

Currently, we using node 20 in `pull-request.yml `workflow file for Testing with node 20. The  juliangruber/sleep-action@v2 is supported action with node 20

 ```
 - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
```

**Screenshots**

![Screenshot 2024-03-17 150220](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/03c20866-ef8f-4de1-931d-206ec75ba924)

**Additional details**

Upgrade [pull-request.yml](https://github.com/PalisadoesFoundation/talawa-api/blob/f67030ea62988e89330e1fabaa7238fe0b82a28f/.github/workflows/pull-request.yml) workflow with  juliangruber/sleep-action@v1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
1. Closing this will be done for all files in all repos later today
2. Thanks for alerting us to this. We were waiting for the update but didn't realize it was completed.
