### ISSUE TITLE
Feature: Check-out registrants

### ISSUE THREAD

**Issue by git-init-priyanshu** [PalisadoesFoundation/talawa-api#2042]
**Is your feature request related to a problem? Please describe.**
Currently, Talawa has the feature to check in registrants but lacks a check-out feature. This feature is also important for visualizing data through charts, as it will help us see when members are checking in and when they are checking out of the event. This will assist admins in understanding whether event retention is good or not.

**Describe the solution you'd like**
I would like a feature to check-out the members who have previously checked in to the event.

**Additional context**
There is already a field called `isCheckedOut` in the `EventAttende` schema but it is not used anywhere.
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/110045644/94c033db-1b1e-4281-b16c-1d10e8abaa87)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by git-init-priyanshu** [comment]
I would like to work on this. Thanks.

**Comment by palisadoes** [comment]
@git-init-priyanshu 

1. This will need to be an optional feature 
2. It cannot be a toggle of check in. Check outs must be tracked separately
