### ISSUE TITLE
[userTypeFix] Continuous loading observed in 'Users' tab, no user data displayed when accessed as super admin.

### ISSUE THREAD

**Issue by Sahi1l-Kumar** [PalisadoesFoundation/talawa-api#2047]
**Describe the bug**
Upon logging in as a super admin and accessing the 'Users' tab from the left panel, continuous loading is observed with no user data displayed.

**To Reproduce**

1. Log in as a super admin.
2. Navigate to the 'Users' tab from the left panel.

**Expected behavior**
The 'Users' tab should display a table with user data, including usernames, roles, and other relevant information.

**Actual behavior**
Upon accessing the 'Users' tab, the table continues to load indefinitely without displaying any user data.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/135227614/0d6f9b45-c0b7-437c-9c96-4f293480a1da)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
The bug isn't there for SuperAdmins directly but `LAST_RESORT_SUPERADMIN_EMAIL`.

**Comment by pranshugupta54** [comment]
#2048

**Comment by Sahi1l-Kumar** [comment]
@pranshugupta54 This issue is happening only for sample data I believe. Can you check?

**Comment by pranshugupta54** [comment]
@Sahi1l-Kumar, I think it's an issue with adminApproved field being changed

**Comment by Sahi1l-Kumar** [comment]
@pranshugupta54  I saw some missconnection between users and appuserprofiles collection. Fixing those got this issue resolved.

**Comment by palisadoes** [comment]
Should this be closed?

**Comment by Sahi1l-Kumar** [comment]
Yes this can be fixed in talawa-api

**Comment by varshith257** [comment]
@Sahi1l-Kumar This is `talawa-api`  only :)

**Comment by varshith257** [comment]
@palisadoes I think he got confused about this is a Talawa-admin issue. It has to be fixed. Reopen it

**Comment by Sahi1l-Kumar** [comment]
Oh sorry  I made that comment on phone thinking that this current repo was talawa-admin. Please reopen this
