### ISSUE TITLE
[userTypeFix] Improve Tests for MongoDB Connection

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#2049]
**Is your feature request related to a problem? Please describe.**

Current tests of `setup.ts` can't  catch the mongo db basic connection issue

**Describe the solution you'd like**

- The tests have to catch the connection fails of MongoDB 

**Describe alternatives you've considered**

- N/A

 **Approach to be followed (optional)**

Create tests for different scenarios to connect of database to catch the issues of  MongoDB connection

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by gautam-divyanshu** [comment]
@palisadoes @Cioppolo14  Please assign me this issue

**Comment by palisadoes** [comment]
@gautam-divyanshu 

1. The setup script doesn't seem to verify that the test data has been loaded
2. It should make sure all the collections have all the data

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by gautam-divyanshu** [comment]
@palisadoes  @varshith257  **Is this problem are we talking about?**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/0244a4ef-e041-45a0-a818-2f6a3a59a557)

**Is this what we're after?**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/3414fbd6-cf48-457f-a7f1-a49395ee3a3d)

**Comment by Doraemon012** [comment]
@gautam-divyanshu I have opened an issue (#2099)  for the same.


> @palisadoes @varshith257 **Is this problem are we talking about?**
> 
> ![image](https://private-user-images.githubusercontent.com/137816099/316752053-0244a4ef-e041-45a0-a818-2f6a3a59a557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzU5NzIsIm5iZiI6MTcxMTQzNTY3MiwicGF0aCI6Ii8xMzc4MTYwOTkvMzE2NzUyMDUzLTAyNDRhNGVmLWUwNDEtNDVhMC1hODE4LTJmNmEzYTU5YTU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNjQ3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGY2YjI1NWM5MzA4MWM0ZjEzNzE3Y2VhMjE3ZTA0OWNmNjFlYTg0N2U5YmY5Y2E0MTk4OGU3ZjMyYWVkYmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v3pIdsJVMVXViashiQlnIfOmnkRntM-y4chiRJ9GfwI)
> 
> **Is this what we're after?**
> 
> ![image](https://private-user-images.githubusercontent.com/137816099/316751720-3414fbd6-cf48-457f-a7f1-a49395ee3a3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzU5NzIsIm5iZiI6MTcxMTQzNTY3MiwicGF0aCI6Ii8xMzc4MTYwOTkvMzE2NzUxNzIwLTM0MTRmYmQ2LWNmNDgtNDU3Zi1hN2YxLWE0OTM5NWVlM2EzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNjQ3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzIzMzI1NzY1ZjBmYmNhZjUxYTE3NWI4YjE5MTEzNmQzM2VmNzdkMmNhZWRlZWEwMjkyMGFlNTQ2YzM2YWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hOY9UndJZoqPsOqjGymQUkhF8-4KIk4YC20V320e5Nk)

**Comment by gautam-divyanshu** [comment]
> @gautam-divyanshu I have opened an issue (#2099) for the same.
> 
> > @palisadoes @varshith257 **Is this problem are we talking about?**
> > ![image](https://private-user-images.githubusercontent.com/137816099/316752053-0244a4ef-e041-45a0-a818-2f6a3a59a557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzU5NzIsIm5iZiI6MTcxMTQzNTY3MiwicGF0aCI6Ii8xMzc4MTYwOTkvMzE2NzUyMDUzLTAyNDRhNGVmLWUwNDEtNDVhMC1hODE4LTJmNmEzYTU5YTU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNjQ3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGY2YjI1NWM5MzA4MWM0ZjEzNzE3Y2VhMjE3ZTA0OWNmNjFlYTg0N2U5YmY5Y2E0MTk4OGU3ZjMyYWVkYmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v3pIdsJVMVXViashiQlnIfOmnkRntM-y4chiRJ9GfwI)
> > **Is this what we're after?**
> > ![image](https://private-user-images.githubusercontent.com/137816099/316751720-3414fbd6-cf48-457f-a7f1-a49395ee3a3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzU5NzIsIm5iZiI6MTcxMTQzNTY3MiwicGF0aCI6Ii8xMzc4MTYwOTkvMzE2NzUxNzIwLTM0MTRmYmQ2LWNmNDgtNDU3Zi1hN2YxLWE0OTM5NWVlM2EzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNjQ3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzIzMzI1NzY1ZjBmYmNhZjUxYTE3NWI4YjE5MTEzNmQzM2VmNzdkMmNhZWRlZWEwMjkyMGFlNTQ2YzM2YWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hOY9UndJZoqPsOqjGymQUkhF8-4KIk4YC20V320e5Nk)

Ok, I will raise a pr soon.
