### ISSUE TITLE
Test: Create tests for src/resolvers/Mutation/updateAgendaCategory.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2061]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by krishna619** [comment]
@Cioppolo14 Hey, I can work on this.
Please assign this to me.

**Comment by pranshugupta54** [comment]
Can i work on this instead? I added tests for deleteAgendaCategory today itself and this is very similar to it.

_(It's totally okay if Krishna wants to work on this)_

**Comment by Cioppolo14** [comment]
I assigned the first person who requested it with less than 2 issues assigned.  If you all work it out differently, let me know and I can change it.

**Comment by krishna619** [comment]
@Cioppolo14 
I don't have any issues @pranshugupta54 working on this.

**Comment by Cioppolo14** [comment]
@krishna619  @pranshugupta54 now currently has 2 issues already. You can keep it, or unassign yourself and then @pranshugupta54 can tag me again when one of the issues is merged.

**Comment by krishna619** [comment]
@palisadoes we can close this now.
