### ISSUE TITLE
Test: Create tests for src/resolvers/Mutation/removeFund.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2064]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14 , this issue can be closed since it was covered in my recent PR #2097

**Comment by pranshugupta54** [comment]
This has issue with 70th line, I think simply removing `|| ""` should work 🤔 bcuz if Fund exists then OrgId won't be null
<img width="582" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/5e58ff07-c5d3-44c1-abfa-377f6942864c">

**Comment by krishna619** [comment]
yes @pranshugupta54
this is how it should be.
