### ISSUE TITLE
Test: Create tests for src/resolvers/Mutation/addEventAttendee.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2074]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### Screenshot of GitHub Automated Error

- This will need to be resolved too:
    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/564848a0-85ae-417c-a82f-5a644f3743cb)

**Comment by varshith257** [comment]
@palisadoes I think it is better to track this test issues in a parent issue

**Comment by palisadoes** [comment]
- https://github.com/orgs/PalisadoesFoundation/projects/29/views/1

**Comment by krishna619** [comment]
@palisadoes assign this to me.

**Comment by Cioppolo14** [comment]
@krishna619 I just assigned you another issue so now you have 2 issues.  Feel free to tag me again when one of them is merged.

**Comment by krishna619** [comment]
> @krishna619 I just assigned you another issue so now you have 2 issues. Feel free to tag me again when one of them is merged.

sure.

**Comment by krishna619** [comment]
@Cioppolo14 please assign this to me.
The other issue has been marked as completed.
