### ISSUE TITLE
GraphQL validation failed errors

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-api#2083]
**Describe the bug**

**To Reproduce**

1.Sign in as superadmin
2.Click on the user profile on leftsidebar

**Expected behavior**
On clicking the user profile card it should redirect to userprofile

**Actual behavior**
It shows an BAD_REQUEST_ERROR

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/90516956/275e3e61-e847-45e2-a1e1-872133cb5f3b)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/90516956/6a091506-c58e-4bd1-b1aa-d0cdcfd7776d)
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/90516956/c661eb8d-f2ea-4674-bb13-17d483e31d6e)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/90516956/4dfec51b-7b0b-4a61-bf01-d238ae9ff6b4)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
Reference: 

-  https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/8407216776/job/23021925968?pr=1787

**Comment by AVtheking** [comment]
@palisadoes I would like to fix this.

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by AVtheking** [comment]
This issue require some changes in admin repo too .

**Comment by varshith257** [comment]
@AVtheking Create an issue there and work on it. Most of people's failing their admin testing application workflow due to this error. We need to fix this ASAP

**Comment by AVtheking** [comment]
yeah creating it bro.
