### ISSUE TITLE
[userTypeFix] Fix  type AdverstidmentConnection Graphql Queries

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#2084]
**Is your feature request related to a problem? Please describe.**

- Modify the queries to fix the bugs fetched due to the merge of the userType fix branch

**Describe the solution you'd like**

Every query has to work as intended. Most errors are currently due to not fetching the fields  in the type AvertismentsConnection

**Describe alternatives you've considered**

- N/A

 **Approach to be followed (optional)**

- N/A

**Additional context**

```
 - Cannot query field name on type AdvertisementsConnection.
 - Cannot query field type on type AdvertisementsConnection.
 - Cannot query field organization on type AdvertisementsConnection.
 - Cannot query field mediaUrl on type AdvertisementsConnection.
 - Cannot query field endDate on type AdvertisementsConnection.
 - Cannot query field startDate on type AdvertisementsConnection.
```

Reference:
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/8407216776/job/23021925968?pr=1787

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by varshith257** [comment]
@palisadoes Please assign this issue to me. I thought someone can tackle meanwhile I had focused on my proposal. This needs to be fixed ASAP. The Introspection tests in most of Admin PRs are failing due to this.

**Comment by Anubhav-2003** [comment]
I can work on this issue. I may have 2 issues assigned but one of them is complete with PR  raised, another one cannot be done until People's page bug is fixed. So assign it to me. Thanks.

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir,  I have fixed the error, please assign me so that I can raise a PR. Thank You.

**Comment by Anubhav-2003** [comment]
@palisadoes I have created the following issue https://github.com/PalisadoesFoundation/talawa-admin/issues/1807 because I have fixed all the errors related to the introspection. And the tests are passing for me. So I think we can close this issue. Thank You.

**Comment by varshith257** [comment]
@Anubhav-2003 Get the Admin issue assigned and make a PR to fix it. So that we can close this issue.

**Comment by Anubhav-2003** [comment]
@varshith257 Yes, I have asked to be assigned. Thank You.
