### ISSUE TITLE
Windows isn't Starting Server

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#2091]
**Describe the bug**

- When we start Talawa-API in other OS such as Linux, WSL, MAC, etc.. It's working fine. But when we start in WIndows it's struck at **Waiting for changes**

**To Reproduce**

1. Setup API locally in Windows
2.  Start the server  - `npm run dev`

**Expected behavior**

- The Talawa-API should start the server without any struck while starting server and has access to the Apollo Server.

**Actual behavior**

- It's getting struck as attached  below SCR

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/9ed711f5-3255-4ec7-b368-554b01327e6f)

**Additional details**

- The Windows setup is waiting to make a change in the current setup of the server

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@xoldyckk Any insights on it?

**Comment by varshith257** [comment]
I suscept the current API setup is Watching for changes ...as in the above SCR.

**Comment by varshith257** [comment]
@palisadoes I have fixed this issue and is starting in WIndows. Please assign me this issue so that i will make a PR

**Comment by meetulr** [comment]
really what was it?
