### ISSUE TITLE
Adding support for updating color of a tag in updateUserTag resolver.

### ISSUE THREAD

**Issue by chandel-aman** [PalisadoesFoundation/talawa-api#2094]
**Is your feature request related to a problem? Please describe.**
We have tagColor for every OrganizationTagUser for which the updation is not provided.

Organization Tag schema
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/97614113/21fb3ecd-4d08-403d-91ee-586cf08bedbb)

updateUserTag
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/97614113/421fa465-901a-4ee3-a6a7-51e705ba847d)

**Describe the solution you'd like**
Providing updation of tag color for organization tag.

**Approach to be followed (optional)**
Taking tagColor input and updating it in updateUserTag mutation for the given tag id.

**Comment by varshith257** [comment]
@duplix

**Comment by chandel-aman** [comment]
> @duplixx I think you have raised a similiar issue and got merged PR?

Indeed a similar issue was raised, but it only added tagColor in the model, it did not include updating of tag color in updateUserTag resolver.

**Comment by duplixx** [comment]
@chandel-aman, yeah, I have not added CRUD operations in tags because it's part of the user tag idea expected outcome. Maybe we can work on this after announcing the mentee.

**Comment by varshith257** [comment]
@chandel-aman I think we may close this issue as not planned for now

**Comment by chandel-aman** [comment]
Closing this issue as this feature will be added later on during GSoC period.
