### ISSUE TITLE
Bug: Error in connecting to mongodb

### ISSUE THREAD

**Issue by Doraemon012** [PalisadoesFoundation/talawa-api#2099]
**Describe the bug**
The script fails to connect to MongoDB, even when provided with a correct connection string.

**To Reproduce**

1. Execute the setup command for talawa-api.
2. Input your MongoDB URL.
3. Notice the occurrence of connection error.

**Expected behavior**
Upon providing a correct MongoDB URL, the setup should successfully connect to it.

**Actual behavior**
Regardless of the accuracy of the provided connection string, the script fails to establish a connection to MongoDB during setup. However if the connection string is correct, it is possible to connect to MongoDB when running the API.

**Screenshots**

1. When MongoDB URL does not already exist in the `env`

[mongo_problem.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/0712b391-9c67-43f3-8abe-cc5675ff1d9f)

2. When MongoDB URL already exists in the `env`

[change_env_mongo_issue.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/f4edba54-7e01-4cae-9a86-dc9835d2365a)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
Closing as a duplicate.
