### ISSUE TITLE
[userTypeFix]: Privilege Escalation through login mutation Response Interception

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#2103]
**Describe the bug**
In the Talawa Admin dashboard where intercepting and modifying the response to the login mutation can escalate privileges. Specifically, changing the `isSuperAdmin` value to `true` in the intercepted response grants super admin privileges to the user. This issue poses a significant security risk, allowing unauthorized access to super admin functionalities.

**To Reproduce**

1. Log in to the Talawa Admin dashboard as an admin.
2. Intercept the network response to the login mutation.
3. Modify the isSuperAdmin field value from false to true.
4. Observe that the user session now has super admin privileges.

**Expected behavior**
The application should securely validate user privileges on the server side, preventing the escalation of privileges through client-side manipulation.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/5af3208f-0250-44c9-9ec8-3e6c33d3d154)

https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/98bcc2bf-1f0d-448d-bc5c-64ca02c89302

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by krishna619** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/4b651a5d-4f75-4e2e-adbd-2e517772ce19)

@palisadoes please add the userTypeFix tag.

**Comment by palisadoes** [comment]
Is this opened in the correct repo?

**Comment by krishna619** [comment]
@palisadoes hey I feel that this should come under admin repo, closing this and creating one in the admin repo.
I have fixed it, please assign this to me

**Comment by Cioppolo14** [comment]
Closed this as the issue was moved to admin.
