### ISSUE TITLE
Make setup create a default organization 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2109]
**Is your feature request related to a problem? Please describe.**

1. With a brand new installation of the API we don't create an organization.
2. It would be best to create one so that the user isn't faced with a blank screen on login
3. We also want users to select an organization upon registration. This will be impossible without at least one organization being pre-populated.

**Describe the solution you'd like**

1. Update the setup script to import a default organization with default values for fields if test data isn't imported.
    1. When in doubt about values, use the word `Default`
3. Use the flow chart below for guidance. There is one modification:
    1. If a person wants to import data, they must be given the option of:
        1. Importing sample data. This would remove all prior data from the database beforehand.
        2. Importing the default organization data. This would remove all prior data from the database beforehand.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See flow chart

**Additional context**
1. Use this PR for reference:
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1770
1. Use this issue for reference:
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1703
1. You'll need to write tests for this. All tests must pass and be valid. No other functionality must be affected.
1. Flow chart

    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/2f11d05c-8ecc-43d1-a2ea-8ce7ae316ff7)

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@AVtheking 

As menitoned in:
- #1703

**Comment by AVtheking** [comment]
Please assign me this issue.

**Comment by pranshugupta54** [comment]
To fix:

**Comment by palisadoes** [comment]
@AVtheking 

1. This is caused by not populating the Community collection. 
2. When you login as SuperAdmin and reset the community values the screen is OK

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/eb2d7d82-e557-40c6-837d-391c18ef7f8c)

**Comment by AVtheking** [comment]
@palisadoes  I got this basically it should be fixed from the frontend as in sample data we are not providing the logoUrl that's why it is showing the alternative text which should be displayed if there is no url.

**Comment by palisadoes** [comment]
Thanks, however:

1. This was working before.
2. All the social media icons and the Palisadoes logo were present.
3. Something changed recently. 
4. Please investigate further as to what the possible cause could be

**Comment by AVtheking** [comment]
I think earlier either we are not populating the sample data of community or in frontend we were checking that if the logoUrl is present or not ,which got changes now.

**Comment by AVtheking** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/132201033/1a9ea323-2fde-4188-8a30-07d5ed4b4427)
Here we are checking that if the data has communtiy data and if it has then we are using it's logoUrl ,if it doesn't then we are using Palisadoes Logo.
