### ISSUE TITLE
Add a payment gateway integration 

### ISSUE THREAD

**Issue by Laurell876** [PalisadoesFoundation/talawa-api#211]
**Describe the solution you'd like**
Implement a payment gateway system that will allow the organization to receive donations from users of the app

**Comment by yasharth291** [comment]
Sir i would love to work on it

**Comment by yasharth291** [comment]
Please @Laurell876 Can you assign me this

**Comment by yasharth291** [comment]
thanks sir i am working on it

**Comment by yasharth291** [comment]
@Laurell876  hello sir i think this issue is related to the gsoc so can you please label it as gsoc parallel

**Comment by PavanHosmani** [comment]
i can solve this issue sir

**Comment by yasharth291** [comment]
@PavanHosmani Hello i am really sorry but i am already working on this issue you can checkout any other  issue

**Comment by palisadoes** [comment]
@yasharth291  can this be closed?

**Comment by yasharth291** [comment]
@palisadoes yeah sir it ritik will work on this so he will take care of this

**Comment by yasharth291** [comment]
@palisadoes or you can assign ritik on it
