### ISSUE TITLE
[userTypeFix]:  Add Support for Create Sample Organization with new AppUserProfile

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#2112]
**Describe the bug**

The current ` src/utilities/createSampleOrganizationUtil.ts` file has no support with the new AppUserProfile to create a Sample Organization.

**To Reproduce**

Some culprit PRs introduced many changes in this file, reflecting the whole codebase change.

**N/A**

**Expected behavior**

The file has to support creating Sample Organization without any errors and to support new userTypeFix 

**Actual behavior**

It has to be supported for the creation of a Sample Organization

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/fec0abb9-a1d0-454f-8baf-75ce0d7840be)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@palisadoes It is the roadblock to my PR work to support the Production environment to Talawa which has been the roadmap of Talawa MVP:

- #1938

**Comment by varshith257** [comment]
I am fixing it as part of #1938 PR work which is a roadblock to commit my changes in that PR. Please assign this issue to me

**Comment by palisadoes** [comment]
Closing. This is a duplicate issue
- https://github.com/PalisadoesFoundation/talawa-api/issues/2109
