### ISSUE TITLE
Email Address Case Sensitivity Leads to Potential Privilege Escalation

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#2118]
**Describe the bug**
The case sensitivity of email addresses is not properly handled. This issue allows a user with an email address (e.g., `abc@example.com`) to update their profile email to another user's email using a different case (e.g., `TESTSUPERADMIN@example.com`). Consequently, the system treats these email addresses as distinct, potentially allowing unauthorized access or notifications to be sent to the impersonated user.

It creates two different users with email `TESTSUPERADMIN@example.com` and `testsuperadmin@example.com`, so if someone sends a password reset request to TESTADMIN (Upper Case), the system would sent it to lower case one.

**To Reproduce**

1. Update the second user's email address to TESTSUPERADMIN@example.com through the profile update feature.
2. Observe that the system accepts the update leading to potential security issues such as unauthorized access to notifications or account takeovers.

**Expected behavior**
The application should normalize email addresses to a standard case (e.g., lowercase) before processing them. This normalization should occur at all points where email addresses are entered or processed, including account creation, login, and profile updates. The system should recognize abc@example.com and ABC@example.com as the same email address, preventing case-based impersonation or duplication.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/95904273-a1b8-4f90-954f-c0c062fdcfc1)
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/ca31b72c-80b5-44ca-84fb-b89bac77c35d)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Anubhav-2003** [comment]
@Cioppolo14 I would like to work on this issue thank you.
