### ISSUE TITLE
loadSampleData isn't working

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#2119]
**Describe the bug**

When we try to import sample data from ` npm run import:sample-data --format` it throwing mongo connection error.

**To Reproduce**

1.  npm run import:sample-data --format

**Expected behavior**

The sample data has to be imported successfully without any errors when formatted.

**Actual behavior**

The code isn't checking for them mongo client connection which maybe an issue with this.

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/c34454ad-5d6a-4a24-8f9e-21a477c3dda6)

**Additional details**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by meetulr** [comment]
@nikhil-pandey-digital, are you not going to take it?

**Comment by nikhil-pandey-digital** [comment]
I want to take this, @Cioppolo14 please assign this issue to me

**Comment by palisadoes** [comment]
1. Closing. This is covered in the documentation

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/22fdc3d9-2a28-472f-8862-7b6a9ccf0b2e)

**Comment by pranshugupta54** [comment]
@palisadoes, it's throwing error on `npm run import:sample-data -- --format` and `npm run import:sample-data --format` both
