### ISSUE TITLE
[userTypeFix] Removal of adminApproved field

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#2122]
**Describe the bug**
- `adminApproved` field is not being used anymore after the change in userType.
- Remove all the code using it.

**Actual behavior**
Every feature should be working, tests and code coverage.

**Screenshots**
NA

**Additional details**

1. We are using `userRegistrationRequired` bool for checking approval in Org. 
2. `membershipRequests` array for list of pending users in Org.
3. `adminApproved` was earlier used for orgs but it's global.
4. All tests must pass and be valid
5. No other functionality must be affected

**References:**

1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1845
2. https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1711717178931399

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by meetulr** [comment]
I'd like to work on this.

**Comment by meetulr** [comment]
@palisadoes These are the required changes:

1) Earlier with `userType`, we were setting `userType: SUPERADMIN` along with `adminApproved: true`. Now that the `isSuperAdmin` field is moved to the `AppUserProfile`, we need to update this in the [INSTALLATION.md](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#using-mongodb-compass).

- current:
![mongodb_compass_user_edit](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/e68b334f-9c6e-4249-9704-4ede4da37e68)

- updated:
![elevateUserStatus](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/7dd6c2c2-9cd6-4973-98d0-d4416b64b897)

Might be a little inconvenient going to the `AppUserProfile` and updating the `isSuperAdmin` field😅... hope this diagram is enough. I'll also update the steps required.

2) What about the [acceptAdmin](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/resolvers/Mutation/acceptAdmin.ts) and [rejectAdmin](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/resolvers/Mutation/rejectAdmin.ts) mutations? Shall I just remove them? They are the ones involving the `adminApproved` status, and they are not being used in the frontend.

**Comment by palisadoes** [comment]
The aim is to remove all legacy code and documentation related to `userType`

**Comment by meetulr** [comment]
What I meant to say is:

1) This issue is about the removal of `adminApproved`, and since the mutations `acceptAdmin` & `rejectAdmin` aren't used anywhere and they're just updating the `adminApproved` field, shall I just remove them?

2) The `INSTALLATION.md` was not updated to reflect the changes after `userTypeFix`, I'll do that with this issue since the changes required are involving `adminApproved` field.

**Comment by palisadoes** [comment]
Yes the mutations and related queries should be removed
