### ISSUE TITLE
Any url accepted as a valid url.

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa-api#213]
**Describe the bug**
Suppose an organisation does not use talawa, a get request on their website also yeilds a status code 200 then it is considered to be a valid organisation.

**To Reproduce**

1. In the set url page of the app, enter any random organisation url. If it returns a status code of 200 then it is accepted as a valid organisation in the app.

**Expected behavior**
There must be some messsage, like some check endpoint in the backend. If that yeilds some talawa specific message then we can say that that organisation uses talawa and the url is valid.

**Actual behavior**
Any organisation is accepted as long as a get request yeilds a 200 status code.

**Comment by rutvik11062000** [comment]
@palisadoes Please assign it to me.
