### ISSUE TITLE
Security Vulnerability: IDOR (Insecure Direct Object Reference) allows Unauthorized Profile Editing  

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#2131]
**Describe the bug**
In the Talawa admin portal, an admin can edit other users' profiles, including those of super admins, by intercepting and manipulating the edit profile request.

**To Reproduce**

1. log in as an admin to the Talawa admin portal.
2. Navigate to the profile edit page (/member/<id>).
3. Intercept the profile edit request using a proxy tool.
4. Change the ID in the request payload to that of a super admin (e.g., from `66378abd85008f171cf2990d` to `64378abd85008f171cf2990d`).
5. Modify the email address in the request payload and submit the request.

**Key Points**
1) If I change the email address to `testhacked@example.com` and log in via that, It still shows the unchanged email address `testsuperadmin@example.com` but allows me to log in via the changed one.

2) Now even if I try to change the email to some random `abc@example.com` it shows a success status on the front end but it does not allow me to log in with the new one (User not found).

https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/f583e4fc-d8b8-4adf-a619-69ae2fc44df5

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by krishna619** [comment]
@palisadoes I believe this issue is to be addressed from the front end as well.
What are your thoughts?

**Comment by palisadoes** [comment]
Admins in a specific role should be able to edit the profiles of people at or below their level. Therefore:

1. SuperAdmins can edit other SuperAdmin and Admin profiles. User/Member profiles too
2. Admins can edit other Admin profiles. User/Member profiles too. They cannot edit SuperAdmin profiles.
3. Users/Members must only be able to edit their own profiles

This needs to be enforced in the API first

**Comment by krishna619** [comment]
@palisadoes 
I see, apart from it

1. we need to handle **concurrent sessions** what if Super Admin is editing let's say admin A's profile and admin A is editing his/her profile at that point of time?
2. Should we also focus on a fallback or recovery mechanism for users who lose access to their accounts due to unauthorized profile changes? 
3. can we also maintain an audit log that records when a user's profile is edited, by whom, and what changes were made?

**Comment by palisadoes** [comment]
Create issues as required

**Comment by krishna619** [comment]
@palisadoes https://github.com/PalisadoesFoundation/talawa-api/issues/2147 done

**Comment by hg6658** [comment]
Can we encrypt the URL parameters also using strong cryptographically tokens which references models?

**Comment by krishna619** [comment]
Encrypting won't help, anyone with the encrypted payload (visible in the request param) can still make edits. 
This needs auth implementation.

**Comment by pranshugupta54** [comment]
@krishna619, you logged in the SuperAdmin account by changing their email id but how do u password for that superadmin account ?🤔

**Comment by krishna619** [comment]
@pranshugupta54 once i changed the email address to `testhacked@example.com` I can anyways get a new password by forgetting the password, where the password would be sent to `testhacked@example.com` and hence i can login as super admin.

**Comment by pranshugupta54** [comment]
@krishna619, did it change the email in database? I don't think so? It's just frontend part interceptor doing it.

**Comment by krishna619** [comment]
How did it make him log in if it didn't save in the backend?
Will look into it more thoroughly.

**Comment by pranshugupta54** [comment]
Most probably the interceptor is just saving it on the frontend
