### ISSUE TITLE
[userTypeFix] Remove `updateUserType` mutation

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#2139]
**Describe the bug**
`updateUserType` mutation (takes only user id and role) does not work after the new userType update.

**Additional details**
We're using `updateUserRoleInOrganization` now which takes org id, user id and role. `updateUserType` only depends on userId and not OrgId, though with new implementation we have admin role according to Orgs and not globally.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
How's progress? It's one of the last remaining tasks for fixing `userType`
