### ISSUE TITLE
Update Githooks and our PR workflows for updated `eslint`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2146]
**Is your feature request related to a problem? Please describe.**

1. We recently updated the `eslint` package.
2. The PR passed the relevant tests 
3. New PRs are now failing

**Describe the solution you'd like**

1. Update our GitHooks and PR workflows to accommodate the upgrade
2. All tests must pass and be valid
3. All functionality must be maintained

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

1. https://github.com/PalisadoesFoundation/talawa-api/pull/2136
1. Failed GitHub action
    1. https://github.com/PalisadoesFoundation/talawa-api/actions/runs/8523533854/job/23346007795?pr=2143

    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/474fea0e-3f12-4ea9-9b97-c45ace180b19)

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by lakshz** [comment]
I can fix that.

**Comment by NamitBhutani** [comment]
I am interested to work on this issue! As I implemented this feature I might be able to fix it quickly!
