### ISSUE TITLE
"Member Not Found" Error When Re-Blocking a Previously Unblocked Member

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#2149]
**Describe the bug**
There seems to be an issue with the API regarding the block/unblock functionality. After blocking a member of an organization, unblocking them, and then attempting to block them again, the API returns a "member not found" error. This issue occurs despite the member being listed and previously blocked/unblocked through the admin portal.

**To Reproduce**

1. Go to the Talawa Admin Portal.
2. Navigate to the 'Block/Unblock User' section.
3. Block a member of an organization.
4. Unblock the same member.
5. Attempt to block the same member again.

**Expected behavior**
The member should be blocked again successfully, without any errors.

**Additional details**

https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/605da26e-2183-421d-91b7-85dba97ce24b

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
Are you sure it's an issue with API? I think that should be fixed on admin panel.

Also, once we block the user then that user automatically disappears from the list. Currently I can see an issue where blocked users are not getting rendered.

**Comment by pranshugupta54** [comment]
Doesn't look like an issue on API. (Admin page is being re-designed so it's fine)
