### ISSUE TITLE
Bug Report: userRegistrationRequired and appUserProfile

### ISSUE THREAD

**Issue by ArinNigam** [PalisadoesFoundation/talawa-api#2154]
**Describe the bug**

`userRegistrationRequired` 

`appUserProfile`

These 2 fields have not been defined or deleted in the _`types.ts`_ file which are likely causing the error in mobile and needs to be fixed so that further client issues can be solved since login and signup are causing errors.

**To Reproduce**
https://github.com/PalisadoesFoundation/talawa/issues/2454

**Expected behavior**
Run client successfully without any errors.

**Actual behavior**
Error because of the following two fields.

**Additional details**
I have made an issue on Talawa-Mobile: https://github.com/PalisadoesFoundation/talawa/issues/2454

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ArinNigam** [comment]
I would like to work on this issue

**Comment by palisadoes** [comment]
Please make sure you are referencing the `develop` branch. The references are in the file there.

**Comment by ArinNigam** [comment]
> Please make sure you are referencing the `develop` branch. The references are in the file there.

I am sorry for the confusion my branch got switched from `develop` to `main` and I wasn't aware of it.
Though I am still facing issue at the client side.

I'll close this issue here for now and explain it on talawa-mobile repository.
