### ISSUE TITLE
Cannot Start Server through Docker Setup

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-api#2166]
**Describe the bug**

The docker-compose isn't starting to setup the API Server
 
**To Reproduce**

1. docker-compose up

**Expected behavior**

The docker service of API has to start without any errors.

**Actual behavior**

The docker build container has been commented on. It results in build errors for the docker-compose service.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/c20795aa-a28d-4df1-92e2-d5653b260a93)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@karthxk07 Ask here to get it assigned and uncomment the code above in scr in `docker-compose.yaml`

**Comment by karthxk07** [comment]
@palisadoes can i get this assigned to me?

**Comment by Cioppolo14** [comment]
@karthxk07 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by karthxk07** [comment]
@Cioppolo14 👍

**Comment by palisadoes** [comment]
Closing. I've uncommented the code

**Comment by karthxk07** [comment]
@palisadoes Ok sir, Didn't see the comment, so made the pull request by mistake. I'll close the PR. :+1:
