### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by karthxk07** [PalisadoesFoundation/talawa-api#2167]
**Describe the bug**
While setting up the repo locally using docker, the api is not working 

**To Reproduce**

1. Clone the repo
2. Switch to develop branch
3. Try running `docker compose build`
4. Go to localhost:4000/graphql, (It returns 'The site can't be reached right now error').

**Expected behavior**
`docker compose build` should build the containers for the api to work properly. 

**Actual behavior**
`docker compose build` is not printing any output to the console , and also the Apollo server is not loading.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/109301536/1ce38c61-d652-4489-b2ea-761f5b461b09)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/109301536/16bec03a-8ce7-45db-a730-c95236d7b1bf)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
Duplicate #2166

**Comment by karthxk07** [comment]
@varshith257 Ok, sorry , didnt knew the issue already existed. Closing with comment :+1:
