### ISSUE TITLE
Add Query Venues Resolver with Sorting & Filtering support

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-api#2169]
**Is your feature request related to a problem? Please describe.**
Currently, there is no support for searching and sorting (on basis of capacity) for Organization Venues.  The lack of server-side sorting and searching for venues based on capacity and name respectively is a limitation that needs addressing.

**Describe the solution you'd like**
To address this, a query resolver getVenueByOrgID will be introduced which will add support for sorting and filtering. 

**Approach to be followed (optional)**

```
getVenueByOrgId(
    first: Int
    orderBy: VenueOrderByInput
    orgId: ID!
    skip: Int
    where: VenueWhereInput
): [Venue]
```

```
enum VenueOrderByInput {
    capacity_ASC
    capacity_DESC
}
```

```
input VenueWhereInput {
    name_contains: String
    name_starts_with: String
    description_starts_with: String
    description_contains: String
 }
```

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by GlenDsza** [comment]
Would like to work on this as am working on the Admin (client) part to add searching & sorting feature for Venues

https://github.com/PalisadoesFoundation/talawa-admin/pull/1886

**Comment by dhanagopu** [comment]
@GlenDsza   Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. . You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by GlenDsza** [comment]
@dhanagopu existing issues have been closed, pls assign
