### ISSUE TITLE
Invalid URL error while fetching advertisements

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-api#2198]
**Describe the bug**
Invalid URL error while fetching advertisements
**To Reproduce**

1. login to admin portal
2. Select an org
3. navigate to advertisements section
4. Blank screen along with Invalid URL error while fetching advertisements in the network tab

**Expected behavior**
List of advertisements should be displayed
**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.
Blank screen along with Invalid URL error while fetching advertisements in the network tab
**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
I would like to work on this.

**Comment by pranshugupta54** [comment]
@disha1202, are you sure it's API issue? 
The error I see is about variables not being passed, so it should be fixed on Talawa-Admin Query 
<img width="498" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/30f0f053-2748-4597-a3d2-bd863d31ebaf">

**Comment by pranshugupta54** [comment]
API works fine 
<img width="1124" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/f218c463-f877-4052-a789-632246784ef2">

**Comment by disha1202** [comment]
> @disha1202, are you sure it's API issue? The error I see is about variables not being passed, so it should be fixed on Talawa-Admin Query <img alt="image" width="498" src="https://private-user-images.githubusercontent.com/76090263/322089599-30f0f053-2748-4597-a3d2-bd863d31ebaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTAxMjksIm5iZiI6MTcxMjk0OTgyOSwicGF0aCI6Ii83NjA5MDI2My8zMjIwODk1OTktMzBmMGYwNTMtMjc0OC00NTk3LWEzZDItYmQ4NjNkMzFlYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE5MjM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZmY4ZGI1N2QyNDFiZjIwNWNlNzk4NjcyMTlkMzg1MmZmOTdiMmFiNzUzMTI0YzAzMjFhNGY5ODc0YWQ5ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TaoLk3bpbYix4be2JwL1dtY-6FPnEuFWW3vAjpM_gJo">

@pranshugupta54 
We are no longer using the `getAdvertisements` API because it returns list of all the APIs which has to be filtered by organizationId. 

Instead we have exposed advertisements in the organization schema itself. The implementation to that and the reason why we still have `getAdvertisements` can be found in this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1585)

**Comment by pranshugupta54** [comment]
@disha1202, I'm unable to find why we still have `getAdvertisements`? Can you link some comment for the same.

Can reproduce the issue with mediaUrl ✅ 
<img width="1000" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/33c9bd94-3233-4bc1-8c1a-32365ec378ae">

Also should create an issue on admin repo for not displaying them properly.

**Comment by disha1202** [comment]
>> Do you have any doc or reference on how exactly these ads work?

Works similar to `getAdvertisements`, the issue here is while returning the ads we need to prepend the baseUrl to mediaUrl.
https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/resolvers/Query/advertisementsConnection.ts#L62

This needs to be fixed in the advertisements resolver over here https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/resolvers/Organization/advertisements.ts

**Comment by disha1202** [comment]
@Cioppolo14 

Can you please assign this issue to me?
