### ISSUE TITLE
Migrate documentation to Talawa-Docs

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#221]
**NOTE:** [This issue is linked to one in the Talawa-Docs repo](https://github.com/PalisadoesFoundation/talawa-docs/issues/65)

The [Legacy Talawa-API documentation website](https://talawa-api.readthedocs.io/en/latest/) needs to be migrated to the new [Talawa Docs website](https://palisadoesfoundation.github.io/talawa-docs/)

The steps to do this would be:

1. Create a major heading for Talawa-API in the Talawa-Docs repo
2. Migrate the existing [Talawa-API documents in the talawa-api repo](https://github.com/PalisadoesFoundation/talawa-api/tree/master/docs) to the Talawa-Docs repo. Note: The source documents are in RST format and will need to be converted to .MD format.
3. Inform @palisadoes when the pull request for this documentation is completed so that the legacy ReadTheDocs site can be removed.

Copy / pasting the documentation will not be enough. The documentation has changed. You will need to update the documentation so that it matches the current master branch functionality.

**Comment by XshubhamX** [comment]
Sir can i work on this

**Comment by palisadoes** [comment]
Work with mentor Xavier Bryson on this

**Comment by palisadoes** [comment]
You need to also be assigned to https://github.com/PalisadoesFoundation/talawa-docs/issues/65. Please comment on the issue, so you can be assigned formally.

**Comment by XshubhamX** [comment]
@palisadoes Sir this issue can be closed now.
