### ISSUE TITLE
 Unrestricted Exposure of User Data Through the User Query

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#2214]
**Describe the bug**
The affected query is `User($id: ID!)`  which fetches detailed information about a user based on the user ID provided. The current implementation **does not restrict users** from querying information about others, which violates common privacy principles and data access controls.

```
query User($id: ID!) {
    user(id: $id) {
        user {
            _id
            joinedOrganizations {
                _id
            }
            phone {
                mobile
            }
            address {
                line1
                countryCode
                city
                state
            }
        }
        appUserProfile {
            _id
            adminFor {
                _id
            }
        }
    }
}
```

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AdityaRaimec22** [comment]
I want to work on this issue

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by rohansen856** [comment]
@palisadoes i would like to work on this issue. please assign me this issue. thank you.

**Comment by nitintwt** [comment]
@palisadoes @Cioppolo14  Can you please assign this issue to me. Already resolved the issue locally and wanted to make a PR. Thank you

**Comment by palisadoes** [comment]
@nitintwt I've assigned it to you

**Comment by palisadoes** [comment]
unassigning. Inactivity

**Comment by Suyash878** [comment]
I would like to work on this.

**Comment by Cioppolo14** [comment]
@Suyash878 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Suyash878** [comment]
@Cioppolo14 I have unassigned myself from this [issue](https://github.com/PalisadoesFoundation/talawa-admin/issues/2484).

**Comment by NishantSinghhhhh** [comment]
@Cioppolo14 , @palisadoes  , Can you please assign this issue to me

**Comment by Cioppolo14** [comment]
@NishantSinghhhhh Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by NishantSinghhhhh** [comment]
@Cioppolo14 , both my existing PRs have been merged , now can you assign this issue to me , I am higly motivated to do so

**Comment by NishantSinghhhhh** [comment]
@Cioppolo14 , I am highly motivated to work on this issue can you assign this issue to me
