### ISSUE TITLE
[Bug report] update the backend url

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa-api#222]
**Describe the bug**
 The back end is pointing to an old organization url

**To Reproduce**

1.Try to login to the mobile application
2.
3.
4.

**Expected behavior**
Successfully login or create a user account

**Actual behavior**
the user cannot login or create an account  from the mobile app

**Screenshots**
None

**Additional details**

**Comment by palisadoes** [comment]
There must be a way to manually update the URL that the backend points to. There should be no default at this time. The installation process and documentation must reflect this.

**Comment by OnyemaAnthony** [comment]
@palisadoes  so after updating the url in constant.js file what do you suggest i do next?

**Comment by OnyemaAnthony** [comment]
am asking because i did not understand clearly what you meant

**Comment by XshubhamX** [comment]
Got the issue please assign it to me @palisadoes sir

**Comment by XshubhamX** [comment]
@OnyemaAnthony  are you working on this issue?

**Comment by OnyemaAnthony** [comment]
@XshubhamX you can work on it,i have been busy with processing my proposal

**Comment by XshubhamX** [comment]
Sure @OnyemaAnthony
