### ISSUE TITLE
Rectify the ExperimentalWarning: Watch mode on starting the API app

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2227]
**Describe the bug**

When you run the API app, the following message is shown on the CLI that recommends that `watch mode` is deprecated.

```
$ npm run dev

> talawa-api@1.0.0 dev
> concurrently  "tsx --watch ./src/index.ts" "graphql-codegen --watch"

[0] (node:127742) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
[0] (Use `node --trace-warnings ...` to show where the warning was created)

```

**To Reproduce**

- Run the app

**Expected behavior**

- No message because the issue has been has been resolved using coding best practices

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/22853626-59c7-4435-a76c-c33ba3fff4a1)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship: 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
Watch mode is still experimental for `v20.10.0` node version. We can suppress the warning to just turn off the warning but it won't change anything else.

Do you want to turn the warning off? 
**It's not recommended to turn off any warnings, we might miss out important updates about `watch` in future.**

**Comment by ARYANSHAH1567** [comment]
When i run the API i dont get any such warning, so i guess this issue should be closed[
![Screenshot 2024-09-12 193842](https://github.com/user-attachments/assets/7fbd9e66-cb76-4dba-926b-01cb56c71a62)
]

**Comment by palisadoes** [comment]
@ARYANSHAH1567 Please check to see whether the messages have been suppressed, versus fixed. We have a history of people taking short cuts to create apparent best practice behavior.

**Comment by ARYANSHAH1567** [comment]
> @ARYANSHAH1567 Please check to see whether the messages have been suppressed, versus fixed. We have a history of people taking short cuts to create apparent best practice behavior.

I looked into the thing and found out that to suppress the warning we have to write the 
 "dev": "NODE_NO_WARNINGS=1 concurrently \"tsx --watch ./src/index.ts\" \"graphql-codegen --watch\"" in package.json
 but in the current package.json the command is 
 "dev": "concurrently  \"tsx --watch ./src/index.ts\" \"graphql-codegen --watch\""
which does not suppress the warning. So mostly i guess the issue is fixed

**Comment by Suyash878** [comment]
I would like to work on this.

**Comment by Suyash878** [comment]
I am unassigning myself, since this issue has been resolved.
