### ISSUE TITLE
`LAST_RESORT_SUPERADMIN_EMAIL` usage message not displayed on startup

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2228]
**Describe the bug**

1. We used to have an error that would warn when the `LAST_RESORT_SUPERADMIN_EMAIL` parameter was set.
2. The use of `LAST_RESORT_SUPERADMIN_EMAIL` is a security risk

**To Reproduce**

1. Set the `LAST_RESORT_SUPERADMIN_EMAIL` environment variable
2. No message is visible when the API starts

**Expected behavior**

1.  The following message must be displayed:
    ```
    The LAST_RESORT_SUPERADMIN_EMAIL variable configured in your .env file poses a security risk. We strongly recommend that you remove it if not required. Please refer to the documentation in the INSTALLATION.md file.You have created super admin, please remove the LAST_RESORT_SUPERADMIN_EMAIL variable from .env file if you don't require it
    ```
1. Tests must be written to ensure that the message is displayed

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/2555488d-ade3-4096-a75a-d95ba2e13fd1)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship:
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
I can work on this
