### ISSUE TITLE
Event agendas - Minor improvements and fixes

### ISSUE THREAD

**Issue by Atharva-Kanherkar** [PalisadoesFoundation/talawa-api#2230]
**Is your feature request related to a problem? Please describe.**
 - Currently, in the implementation of the agenda items, there is a need to correct two things in the implementation of agenda 
  items. First, that the user type in the agenda item is a string. This does not seem like a bad practice. Plus the user type is 
  conflicting, it should be of `User` type. 
- Secondly, i think that the note agenda item's functionality is a little bit skewed right now. We have two variables in the agenda 
item model, one is a boolean type isNote and another is an enum ItemType, which both work towards the same goal. Removing either of them whichever seems simpler and more functional would be a great nway to introduce simplicity.

**Describe the solution you'd like**

 - The solution for the user type would be to use the `User` model and not the `string` type. 
 - We will have to make a field level resolver for finding out the user (Main speakers or people in the event)
 - Optionally, it can be an array of `User` type if we want more than one main speakers in an event agendas. 
 - The solution for note type is to implement a different schema for a note type agenda item. Right now it is really confusing on how to create a note type agenda item.
 - Implementing one or more resolvers for a note type agenda item seems like the best option to me.

**Describe alternatives you've considered**

  Implementation of the above. Also removing redundant and useless functionalities in the code. 

 
**Additional context**

Refers isssue #1588  

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Kindly assign the issue to me.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Sir, in the current implementation attributes like `title` , `duration`  are compulsary fields. But if we want to incorporate making a note agenda item, we would have to make these optional. In my Point of view, when creating a regular agenda item, we should be making these compulsary. What do you suggest? Making a new schema for a note item type or making these fields optional? Making a new schema for a note item type would make the process a little bit complex, but in my view it would be a more functional way. I would love to get your inputs on this!

**Comment by palisadoes** [comment]
How would you handle interspersed agenda items and notes for an event?

**Comment by Atharva-Kanherkar** [comment]
> How would you handle interspersed agenda items and notes for an event?

I will have to add a new field in agenda sections. That wont be too difficult to make, some more resolvers will be needed to make for note items. As per as regular agenda items, entering the title and duration should not be optional and incorporating notes withing regular items will make them optional.

**Comment by palisadoes** [comment]
1. How will you be able to have any sequence of notes and agenda items in a section? The notes must be able to be moved around in the listing sequence visible in the UI
2. The intention is for the user to create any number of notes before or after each agenda item to help with their event management

**Comment by Atharva-Kanherkar** [comment]
> 1. How will you be able to have any sequence of notes and agenda items in a section? The notes must be able to be moved around in the listing sequence visible in the UI
> 2. The intention is for the user to create any number of notes before or after each agenda item to help with their event management

1. This seems like a challenge. We currently have items array in the sections, we can add another array called notes. This can help. Do you want a note to be associated with each agenda item? That means each agenda item can have n number of notes? If that is the case, It would be really easy to implement. 
2. So every note is bind to an agenda item, that means it is dependent? If that is so, I will use a different approach. The current approach does not work the way we want it to.

**Comment by palisadoes** [comment]
That is why the issue was worded the original way. 

Can you implement that?

**Comment by Atharva-Kanherkar** [comment]
Alright! I will implement it right away. Thak you.
