### ISSUE TITLE
Fix intermittent failing tests

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2235]
**Describe the bug**

GitHub actions testing the application are intermittently failing. 

We need to fix the cause. A link to an example is below

**To Reproduce**

1. https://github.com/PalisadoesFoundation/talawa-api/actions/runs/8730773419/job/23955167950

This was discussed in this pull request. You can investigate another failed run there

1. https://github.com/PalisadoesFoundation/talawa-api/pull/2229

**Expected behavior**

1. Consistency in test passing 
1. All tests valid and comprehensive

**Actual behavior**

See above
 
**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I would like to try solving this issue. As per my understanding, the error states:
```
Error: ENOENT: no such file or directory, open '/home/runner/work/talawa-api/talawa-api/videos/RXqbTEmCp504mtCeblYwwvideo.mp4'
```
There is no such file or directory for the videos, which is true. However, the catch here is that we are just mocking a test video file (it doesn't actually exist) to check if the functionality is working correctly or not. My approach will be to create a separate function that generates the test video file, which might solve this unexpected test failure, but I am not completely sure.

**Comment by palisadoes** [comment]
Check other failed actions to see whether the cause is the same.

**Comment by akhilender-bongirwar** [comment]
> Check other failed actions to see whether the cause is the same.

I've verified the other failed actions as well and it seems the cause is the same. I've also found a fix! But first I would like to demonstrate a video to show the cause of the error.

**Comment by akhilender-bongirwar** [comment]
@palisadoes sir please check the above explanation.

**Comment by palisadoes** [comment]
Thanks. Please proceed
