### ISSUE TITLE
Bug: `UnblockUser` mutation always returns `UnauthorizedError`

### ISSUE THREAD

**Issue by Doraemon012** [PalisadoesFoundation/talawa-api#2238]
**Issue Description:**

**Bug:**  
The `UnblockUser` mutation always triggers an `UnauthorizedError`, making it impossible to unblock a blocked user.

**Steps to Reproduce:**  
1. Open GraphQL.
2. Execute the mutation to block a user (`BlockUser`) within an organization.
3. Confirm that the operation completes successfully.
4. Execute the mutation to unblock the previously blocked user (`UnblockUser`) within the organization.
5. Observe the return of `UnauthorizedError`.

**Expected Behavior:**  
The `UnblockUser` mutation should not result in an `unauthorized error`. After blocking a user, unblocking should be possible without encountering this error.

**Actual Behavior:**  
The `UnblockUser` mutation always returns `UnauthorizedError`.

**Screenshots:**  

[Screencast from 2024-04-20 23-14-58.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/b46ca0b4-10bb-4f26-9b7b-44807671fb51)

**Additional Note:**  
For potential internship candidates: Please review this issue if you are considering applying for a Palisadoes Foundation internship: [Link to internship issue](https://github.com/PalisadoesFoundation/talawa/issues/359)

**Comment by Doraemon012** [comment]
@palisadoes This is a blocking issue for the issue [talawa-admin/issues/1885](https://github.com/PalisadoesFoundation/talawa-admin/issues/1885) in Talawa-admin. Please assing this to me.

**Comment by pranshugupta54** [comment]
@Doraemon012, did you feel any changes recently? Like API getting very slow? Pages keep loading? CORS error in API randomly? 

Bcuz i got this `UnauthorizedError` on other mutation too, restarting everything multiple times fixed it back

**Comment by Doraemon012** [comment]
> @Doraemon012, did you feel any changes recently? Like API getting very slow? Pages keep loading? CORS error in API randomly?
> 
> Bcuz i got this `UnauthorizedError` on other mutation too, restarting everything multiple times fixed it back.
> 
> If you're facing this only for one mutation then please check if you find any flaw in the API code or not.

@pranshugupta54, I agree that the API seems slower, but that's not why we're getting the UnauthorizedError in the UnblockUser mutation. The real issue is a mistake in the code.

**Comment by pranshugupta54** [comment]
I got this similar for fund raising campaigning randomly then it got resolved automatically. Let's see if you could find some issue with code
