### ISSUE TITLE
[BUG] Event Image not encoded

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#2246]
**Describe the bug**
`createEvent` got the feature of image addition but saves directly with 64base and not encoded into a URL. 

**To Reproduce**

1. Login
2. Create new event and pass a file

**Expected behavior**
Should encode and save like other resolvers.

Organizations are saving like:
<img width="375" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/b890c409-fae5-4c8e-bcda-3774e49a7c1f">
Users:
<img width="486" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/2fd010f4-4795-428f-9589-7607529399e4">
Events:
<img width="747" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/1c58e876-60cf-4cb4-a739-b8669366e349">

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
Can be taken under GSoC Project - `Improved File Uploads and Security`

**Comment by asimdelvi** [comment]
can you assign me this issue

**Comment by Cioppolo14** [comment]
@asimdelvi Are you working on this?

**Comment by Cioppolo14** [comment]
Unassigning due to no open activity or PR.

**Comment by pranshugupta54** [comment]
@chandel-aman, are you working on this under `Improved File Uploads and Security` - GSoC Project?

**Comment by chandel-aman** [comment]
@Cioppolo14  @pranshugupta54 We could close this issue for now, I'll be working on this in upcoming weeks.
