### ISSUE TITLE
Improve Setup: Better prompts for loading data

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2258]
**Is your feature request related to a problem? Please describe.**

The current setup process could be confusing for new users.

**Describe the solution you'd like**

1. When data is detected in the database it prompts to overwrite it. This is OK, however the next prompt should be:
    1. `Are you installing this software make open source contributions to the Talawa community ?` or something that more clearly signals the intention.
        1. If `No`, it should prompt to import starting `data for production purposes`, instead of `default data`, which could be confusing, or something that more clearly signals the intention.
        2. If `Yes` it should prompt to import the sample data as before

**Describe alternatives you've considered**

- See above

**Approach to be followed (optional)**

- See above

**Additional context**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/21fc1846-c7c5-4fd4-92ea-fb0ce6e3db9f)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, please assign it to me.
