### ISSUE TITLE
API Setup should prompt for the TCP listening port

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2259]
**Is your feature request related to a problem? Please describe.**

API Setup should prompt for the TCP listening port. 

**Describe the solution you'd like**

1. The API Setup should prompt for the TCP listening port and:
    1. store the value in the `.env` file
    2. make the API instance listen on this port for Admin and Mobile connections
    3. operate as designed in all situations on this TCP port
1. It must work in standalone mode or as a Docker container
1. This will allow us to run multiple instances of the API on any server
1. Tests must be created for this feature
1. When complete we'll then to evaluate possible changes to the Mobile and Admin client apps

**Describe alternatives you've considered**

- See above

**Approach to be followed (optional)**

- See above

**Additional context**

- See above

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NamitBhutani** [comment]
i'd like to work on this issue!
