### ISSUE TITLE
Query returns null for the image field of the likedBy object of the post.

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-api#2262]
**Describe the bug**
The following query returns null for the image field of the `likedBy` object, despite there being an existing image of the user who has liked the post.

Query
```
query ExampleQuery($organizationsId: ID, $first: PositiveInt) {
  organizations(id: $organizationsId) {
    posts(first: $first) {
      totalCount
      edges {
        node {
          _id
          likedBy {
            image
          }
        }
      }
    }
  }
}
```

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by lokeshsingh3721** [comment]
I would like to work on this issue.

**Comment by prayanshchh** [comment]
can u assign this issue to me?

**Comment by prayanshchh** [comment]
![Screenshot from 2024-08-30 19-11-04](https://github.com/user-attachments/assets/467600fd-d799-4b5d-ae70-22e8fa439219)

**Comment by prayanshchh** [comment]
Query: 
query ExampleQuery($organizationsId: ID, $first: PositiveInt) {
  organizations(id: $organizationsId) {
    posts(first: $first) {
      totalCount
      edges {
        node {
          _id
          likedBy {
            _id,
            image
          }
        }
      }
    }
  }
}

Response:
{
  "data": {
    "organizations": [
      {
        "posts": {
          "totalCount": 9,
          "edges": [
            {
              "node": {
                "_id": "6589bdce2caa9d8d69087514",
                "likedBy": [
                  {
                    "_id": "64378abd85008f171cf2990d",
                    "image": "https://plus.unsplash.com/premium_photo-1683121366070-5ceb7e007a97?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                  },
                  {
                    "_id": "66378abd85008f171cf2990d",
                    "image": "hhh"
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  }
}


I have manually populated likedby array as it was not populated in the sample database, as you can see now the graphql query is able to return the image url of each user.

I have also manually updated the value of image of user as there were no sample values.

User image getting updated manually (null value was there in sample database so I had to update the value for testing my updates and check if my solution was working or not)
![image](https://github.com/user-attachments/assets/6b0d01cf-63bc-4830-837a-3797e7d5459e)
![image](https://github.com/user-attachments/assets/f82fea2e-9420-4d6d-bd3b-a9ed4a004c45)

GraphQl query and response:
![image](https://github.com/user-attachments/assets/a5416ace-e1af-4358-89ab-5ef5f23e3e19)

Do i need to do something more or this is good to go?

**Comment by palisadoes** [comment]
@prayanshchh 

Please ask the `#talawa-api` slack channel and @krishna619 for guidance.

**Comment by prayanshchh** [comment]
done

**Comment by prayanshchh** [comment]
@krishna619 didn't reply on the api channel, can I create the PR and move forward from there?@palisadoes

**Comment by palisadoes** [comment]
You don't need to ask permission to open a PR
