### ISSUE TITLE
Fix `ExperimentalWarning` on starting API

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2264]
**Describe the bug**

1. When the app is started this error is displayed indicating that the app is using an undesirable configuration or code snippet.
2. This must be fixed to reduce the risk of future instability

```
[0] (node:626775) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
[0] (Use `node --trace-warnings ...` to show where the warning was created)
```

**To Reproduce**

- Start the app

**Expected behavior**

1. The error message is not displayed because
     1.  the correct fix has been applied
     1. it has not been otherwise suppressed
1. The fix must be added to our test suite
1. All test must be valid and pass.

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/4ebdd5b4-c229-4e7a-a805-1e762a119c37)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
duplicate #2227
