### ISSUE TITLE
Remove docs/ directory to complete documentation migration

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#228]
@XshubhamX [you need to complete your Talawa-Docs pull request](https://github.com/PalisadoesFoundation/talawa-docs/commit/10381655ea2e2b76528b01428757428aa6f9316a)

I have removed the readthedocs.org pages, you will now need to remove the `docs/` directory in this repo

**Comment by XshubhamX** [comment]
Ok sir. Should I make a PR directly in master branch @palisadoes sir.
