### ISSUE TITLE
Migration to fastify and graphql-yoga

### ISSUE THREAD

**Issue by xoldd** [PalisadoesFoundation/talawa-api#2283]
**Is your feature request related to a problem? Please describe.**
Talawa-api is making use of many legacy packages that are either not maintained anymore or do not have the best modern features for providing best developer experience.

**Describe the solution you'd like**
The primary server for talawa-api is to be migrated to fastify and the graphql apollo server is to be migrated to graphql-yoga. Fastify is a well maintained and trusted node.js framework with a big community. It's core maintainer Matteo Collina is one of the core contributers to node.js itself. Graphql-yoga is a modern spec-compliant graphql server that works on almost all javascript server runtimes.

**Describe alternatives you've considered**
- 

**Approach to be followed (optional)**
It will be done in parts in a non breaking way so that it is easier to review the changes and also can be incrementally migrated instead of a sudden disruption.

**Additional context**
This is a pre-requisite to a lot of work that is to be done during GSOC 2024. 

**Potential internship candidates**
-

**Comment by nilaygit-10721** [comment]
Hello @palisadoes, could you please assign this issue to me? Thank you!
