### ISSUE TITLE
API fails if the `SERVER_PORT` variable is not in the `.env` file

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2285]
**Describe the bug**

API fails if the `SERVER_PORT` variable is not in the `.env` file

**To Reproduce**

1. Remove the SERVER_PORT variable from the `.env` file
2. Start the API
3. Errors are seen

**Expected behavior**

1. The API should default to a SERVER_PORT if the variable is not in the `.env` file
2. We need valid passing tests created to make sure that this is not repeated

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/eab64eac-de5b-4d2f-a2a1-29b0114fbaf8)

**Additional details**

The feature was added in this PR, but this edge case was not considered

- https://github.com/PalisadoesFoundation/talawa-api/issues/2259

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@NamitBhutani If you have the time, you may want to take a look at this.

**Comment by NamitBhutani** [comment]
> @NamitBhutani If you have the time, you may want to take a look at this.
Although I tested this case, I'll take a look again.

**Comment by TARishabh** [comment]
Hey @palisadoes, I am thinking of fixing this issue, can you please assign it to me?

**Comment by Cioppolo14** [comment]
@TARishabh If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by palisadoes** [comment]
1. Inactive, unassigning
2. Are you still working on this?

**Comment by Suyash878** [comment]
@palisadoes I have come up with a solution, can you please assign the issue to me?

**Comment by Suyash878** [comment]
@Cioppolo14  I would really like to work on this issue.

**Comment by varshith257** [comment]
@Suyash878 How are you planning to solve this issue?
If we have a clear plan then we are ready to go solve this issue easily

**Comment by Suyash878** [comment]
@varshith257  I was planning on running one final check in the src/index.ts file using the isNaN() function to get to know about the nature of the port if in case it is undefined, and if it returns undefined then switching the port to 4000.
