### ISSUE TITLE
Setup doesn't detect a pre-existing `SERVER_PORT` value in the `.env` file

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2286]
**Describe the bug**

1. Setup doesn't detect a pre-existing `SERVER_PORT` value in the `.env` file
2. If a value, say `4006`, is configured the setup process prompts for port 4000.
3. Other variables detect preexisting values and prepopulate the values in the prompts as the desired value. 
4. See the mongodb example in the screenshot below
5. This reduces ensures that the parameters are not overwritten

**To Reproduce**

1. Run setup with a non `4000` value in the `.env` file
2. The value is not detected and used as the prompt default.

**Expected behavior**

1. Run setup with a non `4000` value in the `.env` file
2. The value is detected and used as the prompt default.
3. If no value is present, then `4000` should be the prompted default .

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/45a28d7e-88c1-4cf3-aa7e-510918c5cd91)

**Additional details**

- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@NamitBhutani If you have the time, you may want to take a look at this.

**Comment by lokeshsingh3721** [comment]
can you please assign me this issue ?

**Comment by lokeshsingh3721** [comment]
putting port no is not getting configured while running npm run setup , it is only running on 4000 right ? if yes then i have a doubt , when i am running npm run setup there is no command asking me for entering server port ..can you please clarify a little bit . Thanks.

**Comment by palisadoes** [comment]
Merge your local branch with the latest upstream of the code. You will see it there.

**Comment by lokeshsingh3721** [comment]
ohkay....
