### ISSUE TITLE
Error populating pledges & user details in getFundraisingCampaignById Resolver

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-api#2296]
**Describe the bug**
- Issue 1. Unable to populate pledges in result of `getFundraisingCampaignById` resolver as a result no pledges are displayed at admin side.

- Issue 2. Once solving Issue 1, error in using firstname of user part of pledge, as users are not populated.
Error Log:
`error 2024-05-10 14:34:17 swhwmog23z Cannot return null for non-nullable field User.firstName. {"locations":[{"line":11,"column":9}],"path":["getFundraisingCampaignById","pledges",1,"users",0,"firstName"],"extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["Error: Cannot return null for non-nullable field User.firstName.","    at completeValue`

**To Reproduce**

1. Test the behavior of `getFundraisingCampaignById` Resolver via Apollo Server   
2. Unable to view pledges and thereby user details involved in pledges as these are not populated.

**Expected behavior**
In the result of `getFundraisingCampaignById` resolver, pledges should be populated and afterwards user details involved in pledges should be populated.

**Actual behavior**
In the result of `getFundraisingCampaignById` resolver, pledges and user details are not populated (accessible).

**Screenshots**
- Issue 1: Unable to populate pledges
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/109027247/55b16c41-571f-4fc6-adfd-562d5a387b87)

- Issue 2: After solving Issue 1, error populating user details

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/109027247/fcfae330-bf46-4c0d-87cd-d04c5fc5be94)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/109027247/189dae88-b8e7-49dc-8a1e-4ba6d3aae619)

**Comment by GlenDsza** [comment]
Would like to work on this

**Comment by Cioppolo14** [comment]
@GlenDsza You currently have 2 issues assigned to you.  When one is complete, let me know and I can assign it to you.

**Comment by GlenDsza** [comment]
@Cioppolo14 one of the issue has been resolved, pls assign
