### ISSUE TITLE
Add Search/Sort & Refac for Fund, Campaigns & Pledge resolvers 

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-api#2305]
**Is your feature request related to a problem? Please describe.**

Query resolvers: `getFundById` `getFundraisingCampaignById` `getFundraisingCampaignPledgeById`

- Add search by & sort functionality to query resolvers for Funds, Fundraising campaigns and associated pledges.
- Bug: Admin can create multiple pledges on behalf of single user for a fundraising campaign (NOTE: Each campaign must only have one pledge per person or family [Reference](https://github.com/PalisadoesFoundation/talawa-api/issues/1663#issue-2071259746)). 
- The current structure of nested resolvers could be improvised by refactoring as they perform unnecessary operations to populate documents from database per request

**Describe the solution you'd like**
- Add sort (ascending/descending) by amount, startDate, endDate, etc for funds, fundraising campaigns and pledges.
- Add search by name, creator (for fund) and pledge volunteer name, etc.

**Comment by Cioppolo14** [comment]
@GlenDsza Are you working on this?

**Comment by GlenDsza** [comment]
@Cioppolo14  yes
Delayed due to exams, will submit PR soon

**Comment by GlenDsza** [comment]
> @GlenDsza Just checking to see if you're still able to work on this

Yes, just adding few test cases remain
