### ISSUE TITLE
Superadmin Access Issue in Organizations with User-Posted Media

### ISSUE THREAD

**Issue by lokeshsingh3721** [PalisadoesFoundation/talawa-api#2307]
**Describe the bug**
Superadmin encounters access issues in organizations containing user-posted media, possibly due to a malfunction or disruption caused by the presence of such content.

**To Reproduce**

1. sign in as the user and visit any org 
2. post the content containing media 
3. then sign in as a superAdmin and try to access the same org 
4. you wont be able to do it 

**Expected behavior**
super admin should be able to  open the org and see all the post . 

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/71646466/3169e53b-74e5-4296-9e3e-384b5d5cc560

**Comment by varshith257** [comment]
@lokeshsingh3721 Here's your issue

**Comment by lokeshsingh3721** [comment]
> @lokeshsingh3721 Here's your issue

I didn't know this was possible! Thanks!
