### ISSUE TITLE
Adding logging in the whole api section

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa-api#231]
Adding logging to whole api to know where the error is coming from

**Comment by yasharth291** [comment]
@Laurell876  sir can you please assign me this

**Comment by impiyush83** [comment]
@yasharth291  Some suggestions before working on this. 

1. Replace all console.log statements with logger library  
2. Use logger.info in the try block and. logger.error in a catch. block

**Comment by yasharth291** [comment]
@impiyush83  could you take this issue

**Comment by SiddheshKukade** [comment]
Hello @yasharth291 Sir, Is the issue still valid?
