### ISSUE TITLE
Error while checking if creator id is equal to the logged in userId

### ISSUE THREAD

**Issue by XshubhamX** [PalisadoesFoundation/talawa-api#233]
**Describe the bug**
While making a new admin of an organization .There is a creatorCheck which checks if the userId from token is equal to the creator id in Organization. But there is a bug in approch where the check is being made, We are comparing creator with userId but initially the creator id is of type object and userId is of type string so even if there values are same ,they will not pass the test because there datatypes are different.

![image](https://user-images.githubusercontent.com/63532716/115440958-f1452280-a22d-11eb-8f08-39da75a7e032.png)
Console log shows the datatypes are different

![image](https://user-images.githubusercontent.com/63532716/115441115-1f2a6700-a22e-11eb-80a8-154c3659ae18.png)

There is also a need to change some console log messages , at some places they are not giving relevant information.

**Steps to resolve**

If we change the data type of creator to staring the problem can be resolved.

Can i work on this issue @Sagar2366 Sir.

**Comment by ssaumyaa7** [comment]
Hello, can I work on this issue ?

Solution:
The datatype of creatorid and userid should be the same.

**Comment by ssaumyaa7** [comment]
@palisadoes 

bugfix done.... created pull request #240

**Comment by XshubhamX** [comment]
@palisadoes sir this issue can be closed now
