### ISSUE TITLE
API URL to use for Talawa app not included in INSTALLATION.md

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#234]
The INSTALLATION.md document does not provide a URL to use for your Talawa mobile app if you have just installed the API on your local machine. 

1. Users have no means of knowing how to test their mobile app in their local environment.
1. The local URL needs to be listed in the INSTALLATION.md document in a separate section

**Comment by XshubhamX** [comment]
Can i work on this issue Sir

**Comment by palisadoes** [comment]
Test comment

**Comment by yasharth291** [comment]
can i do this sir ? @palisadoes
