### ISSUE TITLE
Add and test GitHub action to lint all PRs before submission

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#235]
We need to lint all code as part of the pull request process. 

1. The commands for the actions file can be found at the beginning of the documentation of this [outdated GitHub action](https://github.com/marketplace/actions/run-eslint)
1. We will need the action to be activated only on a pull request. [We have an example of how to do that in the Talawa repo](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/linter.yml)
1. Make the action be defined in a file named `linter.yml`

Test and make sure it doesn't break the code. Try running the linter on the code base as proof.

**Comment by XshubhamX** [comment]
Can i work on this issue sir

**Comment by palisadoes** [comment]
@XshubhamX Look at the examples in [Talawa](https://github.com/PalisadoesFoundation/talawa/tree/master/.github/workflows) There is an action for issues, and another for pull requests.

**Comment by XshubhamX** [comment]
Ok Sir @palisadoes i will have a look at it.

**Comment by Sagar2366** [comment]
@XshubhamX what's the progress on this issue ? 
This is one of priority item for us. If you are not available please let us know, someone else can take over on this issue.

**Comment by XshubhamX** [comment]
@Sagar2366 sir I'm currently working on talawa-admin as the whole code of that needs to be converted from vuejs to reactjs sorry sir I won't be able to work on this issue I would have informed earlier.

**Comment by yasharth291** [comment]
@Sagar2366 sir

**Comment by yasharth291** [comment]
@Sagar2366  sir amul dhungel has asked to fix it please assign this to him

**Comment by mihdas** [comment]
Can I try working on this? @palisadoes @Sagar2366.

**Comment by mihdas** [comment]
Added action to lint, however unable to merge as many files contain errors

**Comment by palisadoes** [comment]
@mihdas you will need to lint the entire code base as part of the PR. We had to do the same with Talawa and now things are much better with conflicts.
