### ISSUE TITLE
Migrate from Nginx to Caddy for Reverse Proxy in Cloud API Demo

### ISSUE THREAD

**Issue by vasujain275** [PalisadoesFoundation/talawa-api#2360]
**Is your feature request related to a problem? Please describe.**
Currently we are using Nginx to do reverse proxy for our cloud instance with cerbot for ssl certificate. But Caddy is much more simple effectice and more maintaible solution to this. So, thats why it will be good for us to migrate to Caddy

**Describe the solution you'd like**
As the Cloud API Demo Instance is WIP currently(issue - #1428 )  , it will be easy to implement Caddy and change the documentation of cloud instance setup accordingly. 

**Describe alternatives you've considered**
There are mainly these two reverse proxy most popular and used while hosting and I think Cady is better suited for our purpose.

**Approach to be followed (optional)**
1. Create a Caddyfile in the Repo.
2. Setup Caddy on the Demo VPS.
3. Document the Steps.

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by vasujain275** [comment]
Can I work on this?

**Comment by palisadoes** [comment]
Is this really necessary? Doesn't it work already, why change?

**Comment by Cioppolo14** [comment]
@vasujain275 Can you explain in more detail why we need this change?

**Comment by vasujain275** [comment]
1. Caddy requires only a simple Caddyfile, making setup easier than Nginx with Certbot.
2. It automatically handles HTTPS, including acquiring and renewing certificates, with no extra cron jobs.
3. It works seamlessly with Docker, allowing for straightforward configuration within Docker Compose.
4. It supports on-the-fly configuration changes without needing to reload the server, ensuring continuous availability.

**Comment by palisadoes** [comment]
OK
