### ISSUE TITLE
To add the functionality to add the option to report post ,organization ,user and comment 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa-api#237]
**Is your feature request related to a problem? Please describe.**
No, It is an Enhancement regarding the feature to add the option to report the inappropriate post, comment, organization, and user. 

**Describe the solution you'd like**
Adding one more key to every schema in the following by the name "reported by" and to maintain it a key with name "report count"

**Comment by yasharth291** [comment]
@Laurell876  @DMills27  @palisadoes  please sir assign me this

**Comment by palisadoes** [comment]
@yasharth291  

1. Where would the report go? Who would see it?
1. What actions would the person seeing the report be able to do? 
1. Is there a mechanism for sending a warning to people?

**Comment by yasharth291** [comment]
@palisadoes Hello sir There is no report there is just report button and if the report count is higher than the post or the organisation will be sent to admin and admin can send warning mail or block that.

**Comment by SiddheshKukade** [comment]
Hello @yasharth291 Please let me know if this issue is still valid so that I can update its status. Thanks
