### ISSUE TITLE
Create `Talawa-API` Installer

### ISSUE THREAD

**Issue by bonnie-23** [PalisadoesFoundation/talawa-api#241]
# Introduction

1. We need a single CLI script or program to install Talawa API.
1. It must be 100% intuitive and worry free.
1. Must be able to run on Linux or Windows

# General Requirements

1. The only pre-requisite that should be installed for the script to run is the interpreter the script uses (if any)
1. If a script interpreter is used, it must be `python 3`
    1. Do not use the `os.system` call, use [subprocess.Popen](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) call. [This link has an example of how to use it with STDIO and STDERR](https://pymotw.com/3/subprocess/)
1. Any failing OS commands must be logged to STDIO, STDERR and .
1. The script must fail gracefully if any underlying OS command fails. 

The script must:

1. Not require the installation of any prerequisite packages for the script itself to run.
    1. This could be achieved by it installing any missing prerequisite packages for itself to run as part of its operation.
1. Install all required prerequisite packages for `Talawa-API` to operate
1. Activate `Talawa-API` upon completion of the script
1. Be a part of the `Talawa-API` code base
1. Be documented as part of the `Talawa-API` installation guide

# Installer Operation
The installation process must:

1. Prompt for:
    1.  Organization name.
    1. *Super Administrator* Name and Username.
    1. Password. The password information will need to be securely encrypted.
1. Insert the API keys to be used between `Talawa API` and `Talawa Admin` in a configuration file.
1. Insert all information prompts in a configuration file.
1. Display the URL to use to access the API for use with `Talawa Admin` installation.

# Post Installer Operation
1. The script (or a second script) must be able to be run to show the status of `Talawa-API`.
    1. This must display whether `Talawa-API` is correctly operational
    1. This must display `Talawa-Admin` instances communicating with `Talawa-API`
    1. It must also display the URL that `Talawa-Admin` should use to contact `Talawa-API`

# Related Issues
- https://github.com/PalisadoesFoundation/talawa-admin/issues/18

**Comment by kailash360** [comment]
@palisadoes ,can I work on this issue?

**Comment by palisadoes** [comment]
@kailash360 It may be easiest to:
- Have the script run in a python venv environment
- Use `pip3 install -r requirements.txt` for installing the required packages, with `requirements.txt` being a part of the repo.

**Comment by kailash360** [comment]
Alright, 
I was wondering about 2 things:
1. How can we find the ```Talawa-Admin``` instances that are communicating with ```Talawa-API```?
2. How do we display the URL that ```Talawa-Admin``` should use to contact ```Talawa-API```?

Rest of the codebase is ready, and it is starting successfully within a virtual environment.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by kailash360** [comment]
> Are you still working on this?

Yes, I have refactored the code in JavaScript. Just need to write the comments for readability.

**Comment by sumitra19jha** [comment]
Please assign this issue to me.
Few checks are failing in existing PR by Kailash, those needs to be fixed
