### ISSUE TITLE
Add support to reply to messages in direct chat and group chat

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-api#2416]
**Is your feature request related to a problem? Please describe.**
Add support to reply to messages in direct chat and group chat

**Describe the solution you'd like**
Users should be able to reply to messages in direct chat and group chat.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
Related to https://github.com/PalisadoesFoundation/talawa-admin/issues/2103

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign

**Comment by AryanSwaroop** [comment]
Can I work on this feature ?

**Comment by Cioppolo14** [comment]
@disha1202 Are you working on this?

**Comment by palisadoes** [comment]
Yes.

**Comment by Cioppolo14** [comment]
@disha1202 Closing this as the PR is merged.  Please let me know if it needs to be reopened.
