### ISSUE TITLE
Refactor PR #216

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#242]
**Is your feature request related to a problem? Please describe.**
The code in this pull #216 needs to be refactored according to the suggestions by @impiyush83

**Describe the solution you'd like**
@impiyush83 explains it clearly in his suggestions.

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
See #216 

**Additional context**

**Comment by impiyush83** [comment]
@palisadoes  I have raised a PR,  can you assign it to me.

**Comment by palisadoes** [comment]
> @palisadoes I have raised a PR, can you assign it to me.

In future please get the issue assigned first. It's outlined in our contributing.md file. Good luck!

**Comment by impiyush83** [comment]
#244 changes are also in this branch as both are related to refactoring and fixing eslint issues.

**Comment by impiyush83** [comment]
@palisadoes  We can close this issue also.
