### ISSUE TITLE
Create query to fetch all volunteer groups of an event

### ISSUE THREAD

**Issue by Dante291** [PalisadoesFoundation/talawa-api#2442]
**Is your feature request related to a problem? Please describe.**
There is no query to fetch volunteer groups of an event

**Describe the solution you'd like**
Query to fetch all groups for an event

**Describe alternatives you've considered**

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by GlenDsza** [comment]
Pls Assign

**Comment by kennethnrk** [comment]
This could be closed now
