### ISSUE TITLE
Bug Report: Development server is not starting properly

### ISSUE THREAD

**Issue by MikiPAUL** [PalisadoesFoundation/talawa-api#2445]
**Describe the bug**
Development server is not starting properly 

**To Reproduce**

1. clone the repo
2. install dependencies
3. run 'npm run dev'

**Expected behavior**
On running npm run dev, the server is not starting properly and it is restarting in a endless loop

**Actual behavior**
Server should start properly and backend port should be accessible

**Screenshots**
![Screenshot 2024-08-07 223756](https://github.com/user-attachments/assets/595e6ee5-ef08-44e9-b120-573af40692dc)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by MikiPAUL** [comment]
I would like to take on this issue

**Comment by MikiPAUL** [comment]
I'm getting an error during redis initialization when the maxmemory-policy to allkeys-lfu but working fine when the maxmemory-policy is set to allkeys-lru
![image](https://github.com/user-attachments/assets/ad655d53-dd49-4d01-9a5e-f0fe340e1e95)

**Comment by AnshulKahar2729** [comment]
Before starting the main server, you have to run the prerequisite service as well

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by ARYANSHAH1567** [comment]
Did you run setup and started the redis or directly started npm run dev? cause its working fine for me

**Comment by palisadoes** [comment]
The app starts
