### ISSUE TITLE
OTP feature while signing up

### ISSUE THREAD

**Issue by XshubhamX** [PalisadoesFoundation/talawa-api#245]
**Is your feature request related to a problem? Please describe.**
It will be great if an OTP can verify the user's email ID whether it is legit or not. This can be done by using some libraries like Sendmail(for sending OTP), OTP generator(for generation different OTP).

When the user will send signup data, the mutation that will be called should be generatOTP which will send OTP to the user's email and if this OTP is correct, the signup mutation will be called and user data get saved.

This task requires work with a frontend contributor.

@palisadoes sir can I work on this enhancement.

**Comment by palisadoes** [comment]
Please work with @yasharth291 on this. 

1. We will need to enable the feature using Talawa-Admin. The configuration parameters for the mail server will need to be updated there. 
2. This will need to be an optional feature activated by the administrator.

**Comment by XshubhamX** [comment]
@palisadoes Sir can you assign a frontend contributor with me for this task

**Comment by XshubhamX** [comment]
@palisadoes sir Ok I will contact him and will explain him my approach.

**Comment by XshubhamX** [comment]
@palisadoes sir when the user will signup they will use talawa app so the otp need to be verified there only so i think there is some work which needs to be done in frontend also

**Comment by palisadoes** [comment]
Please create all the necessary child issues for each of the subsystems that will need to be updated. Others will be able to assist you.

**Comment by XshubhamX** [comment]
Ok Sir sure

**Comment by palisadoes** [comment]
@XshubhamX  As I haven't heard back from you. I'm going to close PR #248 and #245. We prefer to go with an email service for the reasons stated previously.
