### ISSUE TITLE
Feature Request: Mdx file need 

### ISSUE THREAD

**Issue by gautam-divyanshu** [PalisadoesFoundation/talawa-api#2456]
**Is your feature request related to a problem? Please describe.**
include the mdx file here not in docs repo.

Error:
![image](https://github.com/user-attachments/assets/bc187b9b-4409-4632-980e-5d8db9198601)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
You need to add the script to the YAML file for it to operate

**Comment by palisadoes** [comment]
Should this be closed?

**Comment by gautam-divyanshu** [comment]
@palisadoes yes
