### ISSUE TITLE
Pagination query creation for posts by organisation 

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#246]
**Is your feature request related to a problem? Please describe.**
Creation of new `postsByOrganization` query for pagination of posts by organization.

**Describe the solution you'd like**
A new query needs to be created with the input parameter of `first` and `skip`. first will define the number of data points to fetch while the skip will define the number of data points to skip from the top entry in the database. Apart from that `where` parameter also needs to be added to allow the filter capability within the list. This entire query creation will be done for posts by organizations.

**Why Needed?**
This is needed to perform pagination in news feed page for the issue [#721](https://github.com/PalisadoesFoundation/talawa/issues/168)

**Approach to be followed (optional)**
Similar to the `organiationsConnection` query.

**Comment by sumitra19jha** [comment]
@palisadoes @Sagar2366 This issue is important to be resolved first in order to deal with issue [#721](https://github.com/PalisadoesFoundation/talawa/issues/168). Can you please assign me this issue?

**Comment by impiyush83** [comment]
@sumitra19jha  @palisadoes  @Sagar2366    

The pagination approach mentioned above will take O(N) as skip requires to scan through N entries and take out the next batch. 

Please explore cursor-based pagination which takes O(1) to fetch the next batch of data.

Links for cursor-based pagination: https://slack.engineering/evolving-api-pagination-at-slack/ 

Expectations: 

To create a library for cursor-based pagination which can be reusable for other paginated api's

Features in the library: 
1. Sort - ['ASC, 'DESC']
2. Filter - To filter with attribute

**Comment by sumitra19jha** [comment]
Will look into this for Sure @impiyush83

**Comment by SiddheshKukade** [comment]
Closing this as associated PRs are merged.
