### ISSUE TITLE
Update Chat schema (GSOC)

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-api#2465]
**Is your feature request related to a problem? Please describe.**
Update the Chat Schema

**Describe the solution you'd like**
Currently we have DirectChat and GroupChat, need to combine both in single Chat entity.

**Describe alternatives you've considered**

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign

**Comment by akshayw1** [comment]
Please assign

**Comment by Cioppolo14** [comment]
@akshayw1 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance

**Comment by nilaygit-10721** [comment]
Has this issue been resolved?

**Comment by Cioppolo14** [comment]
@disha1202 I am closing this as the PR was merged, please let me know if I should reopen.
