### ISSUE TITLE
Switching from eslintrc.json to eslint.config.json

### ISSUE THREAD

**Issue by Suyash878** [PalisadoesFoundation/talawa-api#2472]
**Describe the bug**
We need to switch from `eslintrc.json` to `eslint.config.js` as the former is considered deprecated now.

**To Reproduce**

1. Make changes in any file in the code base. 
2. Add all the changes using `git add .` command
3. Try and commit the changes using `git commit -m "<Your commit message>"`
4. Examine the error, The process fails after the initial few tests.

**Expected behavior**
The changes should have been committed without any such error messages.

**Actual behavior**
After the initial few tasks the commit action fails. Since "`.eslintrc.json`" file is no longer supported. And it asks to switch over to `eslint.config.js` file.
More over the property `.eslintignore` is also not supported rather user is supposed to use the "ignores" property in `eslint.config.js`.

**Screenshots**
![image](https://github.com/user-attachments/assets/fc8d3485-884f-418d-acfc-2ceedb565283)

**Additional details**
None.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Suyash878** [comment]
In accordance with the issue #1756 and my current awareness about this issue, I would like to work on this.

**Comment by palisadoes** [comment]
When this is resolved, please open one in Admin as we'll face the same issue.

**Comment by Suyash878** [comment]
@palisadoes Sure
