### ISSUE TITLE
Fix minor text issues with the Setup Script

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2493]
**Describe the bug**

1. The some of the setup script prompts need better clarification 

**To Reproduce**

1. Run the setup script
2. Note the requested changes below
3. The test code coverage must be maintained.
4. All tests must be valid and pass 

**Expected behavior**

- The suggested changes are applied

**Actual behavior**

- See below

**Screenshots**

1. Change to `Enter the Talawa-API server port (4000)`
    ![image](https://github.com/user-attachments/assets/ecdaad50-6c06-427b-8d87-423c3de5aa39)
1. Change `Do you want to import sample data? (y/N)` to `Do you want to import Talawa sample data for testing and evaluation purposes? (y/N)`  
![image](https://github.com/user-attachments/assets/69a8cc79-7304-447b-8d3d-e8fd1fb7e2ef)
1. Change `Do you want to import default data?` to `Do you want to import the required default data to start using Talawa in a production environment?`
1. In both cases below change `Would you like to generate ` to `Would you like to us to auto-generate ... for you`.
    ![image](https://github.com/user-attachments/assets/4b1cfe84-1249-4255-9dba-f6f4c1f82aec)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ARYANSHAH1567** [comment]
I would like to work on this issue can you assign it to me?

**Comment by ARYANSHAH1567** [comment]
The issue I'm facing is due to the updation of ES-Lint config because the file i cloned from latest repo of develop has linting error such as unused vars and many others so i had to change so many files.
Is there any solution for it?
