### ISSUE TITLE
Update ESLint Configuration to Address Deprecations

### ISSUE THREAD

**Issue by chandel-aman** [PalisadoesFoundation/talawa-api#2496]
The ESLint configuration needs to be updated to align with the deprecations introduced in TypeScript ESLint v8. Specifically, the deprecated @typescript-eslint/ban-types rule has been removed and replaced with newer, more granular rules.

**Changes Made:**

   - **Removed:**
        @typescript-eslint/ban-types: This rule has been deprecated and removed in TypeScript ESLint v8.

   - **Added:**
        @typescript-eslint/no-empty-object-type: Enforces banning the built-in {} type in confusing locations.
        @typescript-eslint/no-unsafe-function-type: Enforces banning the built-in Function type.
        @typescript-eslint/no-wrapper-object-types: Enforces banning built-in class wrappers such as Number.
        
**Additional Notes:**
Please refer to the [TypeScript ESLint documentation](https://typescript-eslint.io/rules/) for more details.

**Comment by GlenDsza** [comment]
@palisadoes @tasneemkoushar Pls assign
This is a blocker for submitting PR for #2492 as this deprecation raises following error for every push
![image](https://github.com/user-attachments/assets/4f198f38-5801-4fe2-aebc-52b39c7c9e78)
