### ISSUE TITLE
Configure the API to upload posts (images/videos).

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa-api#251]
**Is your feature request related to a problem? Please describe.**

- While adding posts from the app, only the Title and Description of posts are taken as input, while a dummy image is added from the assets to give the feel of the post item (image). We need to configure the API to take in images and videos as well. 

- There is a Textfield that takes in the title of the post, but it has been replaced to take in hashtags as per the new design. To avoid confusion, the `title` in the [schema](https://github.com/PalisadoesFoundation/talawa-api/blob/2ad0700a0e04efd7ed9b54eaa62842827660a274/schema/newsfeed/newsfeed.graphql#L19) should be changed to something relevant like` hashtags`.

**Additional context**
Please note that every post doesn't need to have an image or video associated with it, this means that if a user wishes to have post without an image he/she should be able to do that. We are trying to achieve something similar to LinkedIn.
Figma design: [Here](https://www.figma.com/file/GdvI0NPxsIAwQwZ7txfuTF/Talwa-case-study?node-id=0%3A1)

**Comment by palisadoes** [comment]
@sumitra19jha  This is GSoC related.

**Comment by sumitra19jha** [comment]
@palisadoes Ok
Please assign it to me

**Comment by sumitra19jha** [comment]
@utkarshshendge The current API is already capable to handle both image and video. The data model for the post is this:
```
Post {
  id
  text
  title
  createdAt
  imageUrl
  videoUrl
  creator
  organization
  likedBy
  comments
}
``` 

Please use file parameter in createPost Mutation to add image.

**Comment by sumitra19jha** [comment]
@palisadoes We can close this issue as of now.
