### ISSUE TITLE
Standardize GitHub Actions  File Layout

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#255]
**Is your feature request related to a problem? Please describe.**

We need to have a standardized way of adding GitHub actions to the repository. [The preferred methodology is that done with the Talawa repo.](https://github.com/PalisadoesFoundation/talawa/tree/master/.github/workflows)

**Describe the solution you'd like**
1. Place all actions related to issues in the issues.yml file.
1. Place all actions related to pull requests in the pull-requests.yml file.
1. Have a greeting for first issue created
1. Have a greeting for first PR created
1. Force the manual running of GitHub actions by the PR approvers if it is the submitters first pull request. This is already done with Talawa.
1. [Add a README.md file that states these requirements](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/README.md) Use this as a guide.

**Describe alternatives you've considered**

1. When the actions are in a single file GitHub gives status messages for each section. This makes it easier for both the PR approver and submitter to troubleshoot the source of the error.
1. The current method gives only a single status. You have to click through to see the results.

**Approach to be followed (optional)**

See guidelines above

**Additional context**

Parent Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/287

If we have a standardized approach, both troubleshooting and the addition of new actions will be easier

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by muskan399** [comment]
Assign this issue to me.
I'm a GitHub Extern candidate 28-04_Mus695_tfa_262.
