### ISSUE TITLE
[Security Bug] User has access to delete others events (API)

### ISSUE THREAD

**Issue by AdityaBirangal** [PalisadoesFoundation/talawa-api#261]
**Describe the bug**
Normal user can delete events created by other user/admin by calling API

**To Reproduce**

1. Switch to Events Screen
2. Tap on Event (which is created by other user)
3. Click on menu (3 dot) & Tap delete.
Or 
Call Delete Event API from any user

**Expected behavior**
Delete event API call should be Denied if call it not from original Creator/Admin

**Actual behavior**
Normal User has access to delete others events

**Screenshots**

**Additional details**
1) Front-end part will be fixed in PalisadoesFoundation/talawa#832
2) Backend API part need to address in this issue. So, non-creators will not able to delete event by using services like Postman.
(This might get fixed by doing some updates in `talawa-api/resolvers/event_mutations/removeEvent.js`) 

Server Side Logic :
![119254871-68c3f400-bbd6-11eb-9b38-066932057ea6](https://user-images.githubusercontent.com/43909309/119338897-2d94f400-bcae-11eb-9ae4-509bb37cf367.png)

**Comment by palisadoes** [comment]
@AdityaBirangal who did you identify to work on this issue?

**Comment by AdityaBirangal** [comment]
No-one yet.
Waiting for some volunteers to come forword.
Can I post it on slack for better reach ?

**Comment by palisadoes** [comment]
Yes

**Comment by akshatgarg12** [comment]
@palisadoes @AdityaBirangal I would like to work on the backend part.

**Comment by palisadoes** [comment]
@akshatgarg12 please coordinate with @sumitra19jha who is overseeing a wide range of API features

**Comment by akshatgarg12** [comment]
@sumitra19jha  I need to check **if the user is the creator of the event** or **if the user is an organisation creator to which the event belongs to**. Any other checks I'm missing?
