### ISSUE TITLE
Add feature to view unread messages and mark messages as read in chat (GSoC)

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-api#2610]
**Is your feature request related to a problem? Please describe.**
Add feature to view unread messages and mark messages as read in chat

**Describe the solution you'd like**
View unread messages

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign

**Comment by haresahani** [comment]
I’d like to work on this issue. Could you assign it to me?

**Comment by nilaygit-10721** [comment]
Could you please assign this issue to me? I would like to work on it.

**Comment by dhanagopu** [comment]
@disha1202  Are you still working on this?

**Comment by abbi4code** [comment]
Can you please assign this issue to me?

**Comment by BhaumikKhandela** [comment]
@palisadoes Could you assign this issue to me?

**Comment by palisadoes** [comment]
> @palisadoes Could you assign this issue to me?

This is part of a GSoC project

**Comment by palisadoes** [comment]
> Can you please assign this issue to me?

This is part of a GSoC project
