### ISSUE TITLE
Improve the Code Coverage 

### ISSUE THREAD

**Issue by Manik2708** [PalisadoesFoundation/talawa-api#2613]
**Describe the bug**
Make the code coverage of file `src/resolvers/Mutation/unblockUser` to 100%

To see the current code coverage of this file, please visit: https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/blob/develop/src%2Fresolvers%2FMutation%2FunblockUser.ts

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sumitsh28** [comment]
I would like to write tests for uncovered code. Please assign

**Comment by palisadoes** [comment]
We are going to migrate away from mongoose. this is not necessary
