### ISSUE TITLE
API: Create PR GitHub Actions logic for the `ignore-protected-files-pr` label 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2617]
**Is your feature request related to a problem? Please describe.**

1. The `pull-request.yml` workflow file has a section called `Check-Sensitive-Files`
1. This GitHub action:
    1. was created to flag PRs that edited sensitive files that we want to protect from unauthorized changes
    1. is run on all PRs except those submitted by `dependabot`
1. There are cases where community members need to edit sensitive files. When this is done, the `Check-Sensitive-Files` test fails. Our formal GitHub contributors can only merge PRs where all tests pass. This means the Repository owners have to merge the PRs. This creates a bottleneck in PR reviews

**Describe the solution you'd like**

1. There is a `ignore-sensitive-files-pr` label in this repository
1. We want only the `Check-Sensitive-Files` GitHub action to be ignored if this label is applied to the PR by any of our GitHub contributors
1. No other functionality must be altered, especially the logic where the  `Check-Sensitive-Files` GitHub action is also not run when the PR author is the `dependabot` user.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sumitsh28** [comment]
I'd like to give this a try. Could you please assign it to me?

**Comment by palisadoes** [comment]
> I'd like to give this a try. Could you please assign it to me?

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by govindsingh3477** [comment]
can i work on this ?
