### ISSUE TITLE
Add mutations to mark chat messages as read, update message, update group chat info, add user to group chat, share images in chats, and create dedicated group chats for events.

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-api#2624]
**Is your feature request related to a problem? Please describe.**
Add mutations to mark chat messages as read, update message, update group chat info, add user to group chat, share images in chats, and create dedicated group chats for events.

**Describe the solution you'd like**
Add mutations to mark chat messages as read, update message, update group chat info, add user to group chat, share images in chats, and create dedicated group chats for events.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign

**Comment by Studycode001** [comment]
please assign me

**Comment by Cioppolo14** [comment]
@Studycode001 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by Cioppolo14** [comment]
Unassigning due to inactivity.

**Comment by palisadoes** [comment]
Reassigning GSoC

**Comment by Pratz2005** [comment]
is this issue open?

**Comment by Cioppolo14** [comment]
No it is not, I shouldn't have unassigned them.
