### ISSUE TITLE
Create standardized classes to throw meaningful HTTP error responses

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#263]
**Is your feature request related to a problem? Please describe.**

1. [The API must give HTTP compliant error codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).
2. This is not being done, creating issues with the mobile app

**Describe the solution you'd like**

The API must give HTTP compliant error codes

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

Discuss in the comments below

**Additional context**

Parent issue #259

**Comment by impiyush83** [comment]
@palisadoes  Assign this to me. 

As per my comment in #264, we will introduce internationalization for throwing error messages.

**Comment by impiyush83** [comment]
@palisadoes  We can close this issue.
