### ISSUE TITLE
Use the logger library for proper logging

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#264]
**Is your feature request related to a problem? Please describe.**

1. Consistently use a logger library for proper logging with proper log levels like logger.info, logger. error
1. Console.log is being used all over the place which is a bad idea as console.log prints the message in the console. 
1. We need to have a request tracing key-id attaching to every log message.
1. Messages must be multilingual compliant. We are working on an mulitlingual app, the devops teams managing the backend will need to see messages in their language of choice.

**Describe the solution you'd like**

See above

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

Discuss in the comments below

**Additional context**

Parent issue #259

**Comment by impiyush83** [comment]
@palisadoes  Assign this to me

**Comment by palisadoes** [comment]
@impiyush83 we'll need to figure out a way to do multilingual log messages. The app has multilingual support. Logging must not crash if the language translation isn't found.

**Comment by impiyush83** [comment]
@palisadoes  

As per my idea, logging is majorly for debugging which is developer-specific. Hence, I think multilingual support is not required here. 

But I agree, we should have multilingual support in error handlers which sends an error message based on language.

**Comment by palisadoes** [comment]
@impiyush83 Yes, I was thinking of the messaging. The end user, be they on the app or using the results of the API should expect text in their native spoken language.

**Comment by palisadoes** [comment]
@impiyush83  can this be closed?

**Comment by impiyush83** [comment]
@palisadoes  Yes, we can close this.
