### ISSUE TITLE
Consistently use the `async-await` pattern

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#265]
**Is your feature request related to a problem? Please describe.**

Most of the code uses `async-await` functions, but some some functions are returning `Promise`.

**Describe the solution you'd like**

1. Use the Async await paradigm instead of Promise - https://itnext.io/javascripts-async-await-versus-promise-the-great-debate-6308cb2e10b3
2. Use either the `lodash` or `ramda` library which has beautiful functions to write concise code

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

Discuss in the comments below

**Additional context**

Parent issue #259

**Comment by akshatgarg12** [comment]
I would like to work on this, Can you point me to the functions in code which needs to be changed?

**Comment by palisadoes** [comment]
@impiyush83 will have details for you @akshatgarg12

**Comment by impiyush83** [comment]
@akshatgarg12  

You can check Promise functions with .then and .catch.

eg: 

new Promise((resolve) => { 
})
.then()


Replace them with async-await with try-catch

**Comment by akshatgarg12** [comment]
@impiyush83 Can you point me to the files that needs change?
