### ISSUE TITLE
Use MVVM to Separate Business Logic

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#266]
**Is your feature request related to a problem? Please describe.**

1. We need to separating out db methods, and business logic from mutations, handlers and controllers 
1. All of the business logic let it be controllers, core-service logic, DB calls logic are currently all in one function in resolvers

**Describe the solution you'd like**

1.  Controllers / Resolvers  currently this is called as mutation resolvers in **talawa-API** can be reused folder, which will do marshaling, unmarshalling, schema validation of data
2. Services folder, which will mainly deal will business logic
3.  Repositories folder, which will deal with DB calls
4. Having a core folder that will keep track of all the helper, constants, utils, lib files.

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

Discuss in the comments below

**Additional context**

Parent issue #259

**Comment by SiddheshKukade** [comment]
@palisadoes Should we close this as the parent issue is also closed ?

**Comment by palisadoes** [comment]
Closed. Thanks
