### ISSUE TITLE
Validate Talawa API with PostgreSQL (No Docker)

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#2666]
### Objective: 
Ensure that the setup and installation process for the Talawa API, including PostgreSQL integration without docker, works as expected by following the provided documentation. Identify any gaps, inaccuracies, or areas where instructions could be clearer. Follow each step in the setup documentation carefully, starting from environment setup to running the API with PostgreSQL.

**Branch:** `develop-postgres`

**Tasks:**
1. **Install PostgreSQL:** Install and setup PostgreSQL on your local machine.
2. **Configure Database:** Update environment variables in the Talawa project to connect to your PostgreSQL instance.
3. **Import Sample Data:** Import the sample data into the database to test functionality.
4. **Run the API:** Start the Talawa API and verify that it connects successfully to PostgreSQL.
5. **Test Endpoints:** Access key endpoints to ensure they are running as expected.

**Acceptance Criteria:**  
- The setup process works as described in the documentation.
- The API runs without errors, sample data is loaded, and key endpoints return expected responses.
- Attach a short video demonstrating that the API runs smoothly, showcasing major endpoints.
- Attach a brief summary of findings and recommendations for documentation updates if needed.

**Comment by bandhan-majumder** [comment]
Hey @pranshugupta54 . I need a bit more clarification. Do I have to write tests for them or just have to test endpoints with following instructions and make a proof of test video that shows  everything is working fine?

**Comment by pranshugupta54** [comment]
No need to write tests, just a video and also to check if documents are accurate.

**Comment by bandhan-majumder** [comment]
Thank you.

**Comment by bandhan-majumder** [comment]
Hi @pranshugupta54 . I have questions related to `sample_data`. As there is no sample data in `develop-postgres` branch. So I copied it from the `main` branch. But `events.json` has more than `4490821` lines, so a lot of entries Should I take only a few of them or the whole as sample ?

**Comment by palisadoes** [comment]
Please work with @meetulr who will be able to provide some guidance on what to do.

**Comment by bandhan-majumder** [comment]
Thank you @palisadoes. I have messaged him and waiting for his response. I also messaged @pranshugupta54 my query about routes which are not defined ( I think ).

**Comment by palisadoes** [comment]
Don't let that delay the work. Try with a just few event entries. We need the installation script.

**Comment by palisadoes** [comment]
We can add the rest later

**Comment by TharunYetti** [comment]
Can I have chance to work on this issue if there is no progress, as I already have talawa-api and talawa-admin setup and also the docker

**Comment by pranshugupta54** [comment]
@TharunYetti, this is on the new branch Postgres. Are you able to run on it?

**Comment by bandhan-majumder** [comment]
Hey @TharunYetti. I am already working. Things are working except the routers. Having some env type problems that I will fix soon.

**Comment by TharunYetti** [comment]
> @TharunYetti, this is on the new branch Postgres. Are you able to run on it?

I was dealing with develop branch only, might take some time for setting up with postgres branch

**Comment by bandhan-majumder** [comment]
Please let me know if I need to change anything. As this branch is not same like the develop branch, there are less functionalities(mentioned by @xoldd). So I was not able to test the endpoints further. But I hope this script will help to setup the project locally without docker. Thanks @pranshugupta54 @palisadoes. I have added the working proof after setup.

**Comment by bandhan-majumder** [comment]
Working on this. Will raise a PR with script and the test (based on recent merge) soon.

**Comment by bandhan-majumder** [comment]
My script is ready with signin, signup query and mutation testing proof. Should I raise a PR, or wait for all other queries to test?

**Comment by palisadoes** [comment]
1. @xoldd said that work should stop on this issue until further notice in slack.
2. Please open separate issues and PRs for testing queries
