### ISSUE TITLE
Validate Talawa API with PostgreSQL (Using Docker)

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-api#2667]
### Objective:
Ensure that the setup and installation process for the Talawa API, including PostgreSQL integration in a Docker environment, works as expected by following the provided documentation. Identify any gaps, inaccuracies, or areas where instructions could be clearer. Follow each step in the setup documentation carefully, starting from environment setup to running the API with PostgreSQL.

**Branch:** `develop-postgres`

**Tasks:**
1. **Ensure Docker Setup:** Confirm that Docker is installed and configured on your machine.
2. **Docker Compose Configuration:** Use the `docker-compose.yml` file to set up PostgreSQL and the Talawa API.
3. **Configure Environment Variables:** Adjust Docker environment variables to ensure the API connects to PostgreSQL.
4. **Import Sample Data:** Load the sample data into the PostgreSQL instance within Docker.
5. **Run and Verify the API:** Start the API container and test that it runs correctly with the imported data.

**Acceptance Criteria:**  
- The setup process works as described in the documentation.
- The API is running in Docker, sample data is successfully loaded, and endpoints are accessible and responsive.
- Attach a short video demonstrating smooth API operation for major endpoints.
- Attach a brief summary of findings and recommendations for documentation updates if needed.

**Comment by bandhan-majumder** [comment]
I would like to do this test too. Please provide me some clarification on this one as well as I asked the same on "without docker" issue at #2666. Do I have to write tests for them or create a fully working video with docker setup.Thank you :)

**Comment by PurnenduMIshra129th** [comment]
@pranshugupta54  can u provide more details on it . Is it the updated branch means all endpoint present that were  in devlopment branch . And what exact do means upon running the script npm run setup and upon selection of using docker it should automettically build the image and load the sample database and start the server ? need some clarification

**Comment by palisadoes** [comment]
Closing until the postgres branch is live
