### ISSUE TITLE
Bug Report: Docker installation failed in ubuntu

### ISSUE THREAD

**Issue by Shriya-Chauhan** [PalisadoesFoundation/talawa-api#2718]
**Describe the bug**

**To Reproduce**

1.Follow installation guide mentioned in installation.md (ubuntu)
2. While installing using docker- command` bash sudo /usr/libexec/docker/cli-plugins/docker-compose -f docker-compose.dev.yaml up --build`
3.Error

![Screenshot from 2024-11-25 18-30-24](https://github.com/user-attachments/assets/fe51f471-7c35-4639-a45c-d127234a0727)

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Shriya-Chauhan** [comment]
@palisadoes @pranshugupta54 PTAL

**Comment by varshith257** [comment]
Related work is going here
https://github.com/PalisadoesFoundation/talawa-api/pull/2647

**Comment by palisadoes** [comment]
@Shriya-Chauhan  Please ask to be assigned to this issue if you have a solution. It was mentioned in the #talawa-api slack channel with a fix.
- https://github.com/PalisadoesFoundation/talawa-api/issues/2598

**Comment by abhayymishraa** [comment]
@palisadoes  i already fixed that issue i think so why unassigneed me i added the container it was just a small problem
