### ISSUE TITLE
Incorrect Command , Syntax and Path for talawa-api setup for Ubuntu using docker.

### ISSUE THREAD

**Issue by DevyanshuNegi** [PalisadoesFoundation/talawa-api#2719]
**The documentation for setting up development containers on Ubuntu contains multiple incorrect command syntax and invalid paths for Docker Compose, leading to errors during setup.**

1. The command uses bash sudo which is invalid.
2. The path /usr/libexec/docker/cli-plugins/docker-compose may not exist, causing "file not found" errors.
3. The inconsistency between Docker Compose v1 and v2 commands isn't addressed, potentially confusing users.

**Steps to reproduce the behavior:**

1.Follow the Talawa API Docker Setup Documentation for Ubuntu development setup.
2.Run the following command as instructed in the documentation :
`bash sudo /usr/libexec/docker/cli-plugins/docker-compose -f docker-compose.dev.yaml up --build
`

3.Observe the errors, including invalid command usage and path issues.

**Expected behavior**
The command should correctly start the development environment using Docker Compose without errors, ensuring compatibility with Ubuntu and both Docker Compose v1 and v2.

**Actual behavior**
The command fails with errors like:
![image](https://github.com/user-attachments/assets/628593f4-2cf8-4ed1-94f2-5b5b2ca9a673)

- sudo: /usr/bin/sudo: cannot execute binary file
-bash: /usr/libexec/docker/cli-plugins/docker-compose: No such file or directory

**Recommended fixes**

1. Replace bash sudo /usr/libexec/docker/cli-plugins/docker-compose with:
`sudo docker compose -f docker-compose.dev.yaml up --build  # For v2
` 
or
`sudo docker-compose -f docker-compose.dev.yaml up --build  # For v1
`
3. Add instructions to verify which version of Docker Compose is installed and guide users to use the appropriate command.
4. Include a note on how to install Docker Compose if it's missing.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Duplicate issue
- https://github.com/PalisadoesFoundation/talawa-api/issues/2598
