### ISSUE TITLE
Fix CodeQL GitHub Action `develop-postgres` branch

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#2731]
**Describe the bug**

The CodeQL GitHub Action `develop-postgres` branch fails

**To Reproduce**

1. Submit a PR to the branch
2. Test fails

**Expected behavior**

1. The test must pass
1. The test must be valid in detecting poor code quality

**Actual behavior**

See this PR as an example:

- https://github.com/PalisadoesFoundation/talawa-api/pull/2728

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by IITI-tushar** [comment]
Hi @palisadoes ,Can you assign this issue to me? I would like to work on it..

**Comment by IITI-tushar** [comment]
![image](https://github.com/user-attachments/assets/8e4c49f7-6fc0-4d3f-980c-c9fa11bb953b)
I checked the Actions and found that codeql-scan is working in develop-postgres branch...
Also i couldn't reproduce the error in my forked repo.
Well if I'm getting it wrong could you please give me details about it, if possible.
@palisadoes

**Comment by AQIB-NAWAB** [comment]
Hy @palisadoes , PR checks fail due to making changes to authorized files and directory 

**Attaching Picture** 
![image](https://github.com/user-attachments/assets/6edf4e4a-5847-4547-9a62-79802b4c8ab1)

**Comment by Cioppolo14** [comment]
@IITI-tushar  Does this needed to be closed?

**Comment by IITI-tushar** [comment]
Yes, I think so as codeql action is working fine with other PR's.
Can I unassign this issue from me?

**Comment by palisadoes** [comment]
It's still failing
