### ISSUE TITLE
Improve INSTALLATION.md. Some Sections are Vague

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#274]
**Is your feature request related to a problem? Please describe.**

This is user documentation. It is the first experience people will have with the software and it will need to be perfect to ensure they are not discouraged to use `talawa-api`.

Detailed comments on the [shortcomings can be found here](https://github.com/PalisadoesFoundation/talawa-api/commit/561c00419350ab44bbf7fa4da87ebde107656abe).

1. People are told to run `docker` commands assuming that they have docker installed. The commands on how to install docker, or links to how it's done need to be added.
2. People are told to run `npm` commands assuming that they have docker installed. The commands on how to install docker, or links to how it's done need to be added.
3. In some steps the shell commands are given. In others the shell commands to do the action are not. All shell commands need to be provided.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
See above

**Additional context**
N/A

**Comment by claudineallen** [comment]
Point 2 under detailed comments seems incorrect.
