### ISSUE TITLE
Updating Docker-compose.dev.yaml file to be accessible

### ISSUE THREAD

**Issue by VanshikaSabharwal** [PalisadoesFoundation/talawa-api#2746]
**Is your feature request related to a problem? Please describe.**
The containers run successfully when using `docker compose -f docker-compose.dev.yaml up -d ` but they are not accessible to respectiive ports. Despite the containers being up and running, the service is not reachable on the expected port from the host machine.

**Describe the solution you'd like**
Ensure that the containers are properly exposed to localhost:4000. The goal is to fix the port mapping or the network configuration to make the service accessible on the expected port without any issues.

**Describe alternatives you've considered**
I have tried checking the docker-compose.yml file for proper port mapping, and also verified that the firewall isn't blocking the port. However, the problem persists.

**Approach to be followed (optional)**
I would suggest checking the Docker container's network configuration, verifying the exposed ports, and ensuring the application inside the container is correctly configured to listen on all network interfaces. Additionally, confirming that there is no firewall blocking the required ports would be helpful.

**Additional context**
none

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by abbi4code** [comment]
can i work on this issue ?

**Comment by VanshikaSabharwal** [comment]
PR  is merged so this issue can be closed. @palisadoes
