### ISSUE TITLE
Bug Report Setup Script does not add MongoDB URL Input Correctly to .env

### ISSUE THREAD

**Issue by Nirvanjha2004** [PalisadoesFoundation/talawa-api#2758]
**Describe the bug**
The .env setup script does not add the mongodb url correctly to the .env file which can cause a problem while seeding the data in the database

**To Reproduce**

1. Run npm run setup to generate the .env file.
2. Provide a MongoDB URL when prompted.

**Expected behavior**
It should save the mongoDB url in the .env like : 
mongodb://localhost:27017/talawa-api

**Actual behavior**
It saves it like this :- 
( with extra '/ ' ) 
mongodb://localhost:27017//talawa-api

**Screenshots**
![image](https://github.com/user-attachments/assets/b5c9306f-754a-415e-84c2-23a4494245b0)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nirvanjha2004** [comment]
@palisadoes shall i work on this issue ??

**Comment by Cioppolo14** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

I am going to close this, but we can reopen if it currently causing a problem.
