### ISSUE TITLE
Only members of organisations should be allowed to create events for them

### ISSUE THREAD

**Issue by akshatgarg12** [PalisadoesFoundation/talawa-api#276]
**Describe the bug**
Any user can create events for any organisation

**To Reproduce**
1. create a new organisation
2. login with a diff account
3. use create-event mutation without joining the org 

**Expected behavior**
### User should only be able to create events in the organisation if they are a member of it.
**Actual behavior**
Anyone can create events.

**Additional details**
The logic in the [/resolvers/event_mutations/createEvent.js](https://github.com/PalisadoesFoundation/talawa-api/blob/master/resolvers/event_mutations/createEvent.js) is to be changed to deal with this.

**Comment by uzair-ali10** [comment]
Hey, I would love to work on this issue!!

My Approach:
* I would create a boolean function inside [createEvent.js](https://github.com/PalisadoesFoundation/talawa-api/blob/master/resolvers/event_mutations/createEvent.js) which looks up in [models/User.js](https://github.com/PalisadoesFoundation/talawa-api/blob/master/models/User.js)  if user is a part of or has created the organization. If yes the function returns `true` or else `false`
*  if the above function returns `true` only then the rest of the code inside [createEvent.js](https://github.com/PalisadoesFoundation/talawa-api/blob/master/resolvers/event_mutations/createEvent.js) would execute or else an auth error would throw-up

**Comment by palisadoes** [comment]
@sumitra19jha Is this still an issue with the API?

**Comment by sumitra19jha** [comment]
Yes, this issue still persist. It hasn't been updated

**Comment by palisadoes** [comment]
@uzair-ali10 please proceed

**Comment by uzair-ali10** [comment]
@palisadoes
Yea Sure, On it!

**Comment by uzair-ali10** [comment]
@sumitra19jha 
Can you please take a look at my approach which is mentioned above

**Comment by uzair-ali10** [comment]
@palisadoes 
Please Close this issue it is resolved via #337
