### ISSUE TITLE
Bug Report: Flickering screen when port `localhost:4000/graphql` is not found

### ISSUE THREAD

**Issue by VanshikaSabharwal** [PalisadoesFoundation/talawa-api#2771]
**Describe the bug**
When starting the talawa-admin application, the screen begins to flicker if the GraphQL API endpoint (localhost:4000/graphql) is not reachable.

**To Reproduce**

1. Start talawa-api using docker
2. Start talawa-admin 
3. The screen will start flickering if `localhost:4000/graphql` is not found
4. Logs shows the error.
` Error logs: - Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:4000/graphql/. (Reason: CORS request did not succeed). Status code: (null)`

**Expected behavior**
 - The screen should not flicker when the API endpoint is unreachable.
 - Instead, a clear error message should be displayed to the user indicating that the GraphQL endpoint is down or inaccessible.

**Actual behavior**
-The screen flickers continuously when the API endpoint (localhost:4000/graphql) is not found.
-Logs indicate a CORS request failure with no clear status code.

**Screenshots**

https://github.com/user-attachments/assets/85df9b0f-4f88-43b2-8516-ce4af75c6174

**Additional details**
  -  The issue occurs when the talawa-api backend is not up or misconfigured.
  - This results in talawa-admin failing to fetch the GraphQL endpoint, leading to flickering.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by VanshikaSabharwal** [comment]
@palisadoes  can i work on this issue.

**Comment by Coolsheru2526** [comment]
@palisadoes can i work on this issue

**Comment by dhanagopu** [comment]
@VanshikaSabharwal  Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects.  You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by VanshikaSabharwal** [comment]
Yeah sure @dhanagopu  i am aware of the policy but this issue was urgent that is why i asked it to assign me

**Comment by akshayw1** [comment]
@dhanagopu Can In work on the issue

**Comment by Cioppolo14** [comment]
@akshayw1 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by Coolsheru2526** [comment]
@Cioppolo14 I am facing issue with the docker installation to replicate the issue and start working on it
![Screenshot (606)](https://github.com/user-attachments/assets/f4e25331-33ba-49af-ac8e-9f560f65859d)
![Screenshot (607)](https://github.com/user-attachments/assets/fbde2e83-21d4-4841-bcee-1af1487faef0)
![Screenshot (608)](https://github.com/user-attachments/assets/da4a7a35-28bc-47f0-a33c-c1ccba380d33)
![Screenshot (615)](https://github.com/user-attachments/assets/a3a92583-7a68-43df-8b9c-7943620e8f57)

**Comment by Aad1tya27** [comment]
Shouldn't this issue be in Talawa-Admin repo? It might just fix by clearing local storage before navigating to login screen.

**Comment by gautam-divyanshu** [comment]
@Coolsheru2526 Try to clear the local storage or use incognito mode.It will work fine.
Let me know so that I can close this issue.

**Comment by Coolsheru2526** [comment]
@Coolsheru2526 i wasn't able to clone the problem hence unsiggned myself

**Comment by Aad1tya27** [comment]
Can I work on this?

**Comment by Aad1tya27** [comment]
This issue can be closed now, fixed in talawa admin repo.
