### ISSUE TITLE
 Authorized checks for  unnecessary Files  which is causing to failing every PR

### ISSUE THREAD

**Issue by AQIB-NAWAB** [PalisadoesFoundation/talawa-api#2772]
**Describe the bug**
 There is a restriction for users to not allow them to change specific files like setup.ts. If user made changes to those files it will cause the workflow to fail that's why every PR  is getting failed  
**To Reproduce**
Open a pull request 

1. create a issue
2. link a PR to it
3. github workflow will expose the errors

**Screenshots**
![image](https://github.com/user-attachments/assets/8785856d-59e6-411e-9cbe-c0eeb8a25605)

**Additional details**

**Comment by AQIB-NAWAB** [comment]
Please assign this issue to me

**Comment by bandhan-majumder** [comment]
Is this a valid issue? Should not it fail the check if someone unintentionally changes some important files? Although PR can still get merged if the issues needs to change sensitive files in order to resolve.
