### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Shreyas2309** [PalisadoesFoundation/talawa-api#2796]
**Describe the bug**

When running the script to list sample data files, it fails with the following error:
Error listing sample data: Error: ENOENT: no such file or directory, scandir 'C:\C:\Shreyas\Project\talawa-api\sample_data'

The issue appears to stem from an incorrectly resolved file path, where an extra C:\ is added to the start of the path.

**To Reproduce**

1. Clone the repository.
2. Run the script using the appropriate command: npm run import:sample-data
3. Observe the error message in the console.

**Expected behavior**
The script should successfully locate and list the .json files in the sample_data directory and display their document counts.

**Actual behavior**

The script fails to locate the directory due to an incorrectly resolved path:
C:\C:\Shreyas\Project\talawa-api\sample_data

**Screenshots**
![image](https://github.com/user-attachments/assets/a60f78b5-a698-4a08-b4bd-1f4712a4c29a)

**Additional details**

1. The issue is likely caused by the resolution of import.meta.url to a filesystem path. This behavior is inconsistent across operating systems, particularly on Windows.

2. The dirname calculation may need an update to handle the leading / or file:/// prefix correctly.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
1. Do you want to work on this?
2. The solution must work for MacOS and Linux.
3. Tests must be written so that the issue isn't repeated

**Comment by Shreyas2309** [comment]
Yes, I’d like to work on this issue!

Could you please assign it to me? I’ll ensure the solution works across macOS, Linux, and Windows. Additionally, I’ll write tests to prevent this issue from recurring.

Looking forward to contributing!

**Comment by abhassen44** [comment]
same error i came across but i think its not error if run this 
command inside wsl(linex) 
or 
linex (api-container) inside doker it will work

![Screenshot 2024-12-27 211443](https://github.com/user-attachments/assets/c05d08c7-a0a1-475d-aac7-ce5e9eedb7cb)

its showing deplicate because i already import it

**Comment by prayanshchh** [comment]
> Yes, I’d like to work on this issue!
> 
> Could you please assign it to me? I’ll ensure the solution works across macOS, Linux, and Windows. Additionally, I’ll write tests to prevent this issue from recurring.
> 
> Looking forward to contributing!

I don't get this error, everything works fine for me, are u working in `develop-postgres` branch..there is no sample_data folder in that branch

**Comment by Shreyas2309** [comment]
This error occurs particularly on windows.

**Comment by palisadoes** [comment]
Thanks. You're solution mustn't break it's functionality with other operating systems
