### ISSUE TITLE
Bug Report: API isn't accessible at localhost:4000/graphql when run using docker compose 

### ISSUE THREAD

**Issue by Aad1tya27** [PalisadoesFoundation/talawa-api#2799]
**Describe the bug**
The API isn't available on ```http://localhost:4000/graphql``` when run using docker compose.

**To Reproduce**

1. Run ```npm run setup``` and select development mode.
2. Select installation using docker, and then select option to start the containers.
3. Go to ```http://localhost:<api-port>/graphql```

**Expected behavior**
Server should be accessible at the Custom Port or default port if nothing entered.

**Actual behavior**
Server not accessible at the given url.

**Screenshots**
![image](https://github.com/user-attachments/assets/89d09e73-3c49-4b5c-814c-bf572aef0eca)
![image](https://github.com/user-attachments/assets/721833fd-95d4-4a63-9524-dbd9aef4221e)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Aad1tya27** [comment]
Can I work on this issue?

**Comment by palisadoes** [comment]
We are going to remove the dev environment from the API. It would be better to work on this issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/2800
