### ISSUE TITLE
Add and test GitHub action to lint all PRs before submission

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#284]
We need to lint all code as part of the pull request process. 

1. The commands for the actions file can be found at the beginning of the documentation of this [outdated GitHub action](https://github.com/marketplace/actions/run-eslint)
1. We will need the action to be activated only on a pull request. [We have an example of how to do that in the Talawa repo](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/.github/workflows/linter.yml)
1. Make the action be defined in a file named `pull-requests.yml`

Test and make sure it doesn't break the code. Try running the linter on the code base as proof.

Parent Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/287

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by muskan399** [comment]
Assign this issue to me.
I'm a GitHub Extern candidate 28-04_Mus695_tfa_262.

**Comment by muskan399** [comment]
Please close this issue, as it is already resolved via PR #307.
