### ISSUE TITLE
GitHub Action To Limit Code File Sizes

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#285]
**Describe the bug**

1. In order to improve the readability of the code we need to enforce a file size limit on code submitted to pull requests. This has been done effectively with Talawa using the [countline.py script](https://github.com/PalisadoesFoundation/talawa/tree/master/.github/workflows)
2. We need a GitHub action specifically for Node.js code that will fail when the code file sizes are too large. 400 lines to start.

**To Reproduce**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**Screenshots**

N/A

**Additional details**

Parent Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/287

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by muskan399** [comment]
Can we use the same countline.py script?

**Comment by palisadoes** [comment]
Yes
