### ISSUE TITLE
GitHub Action: Code Formatter

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#286]
**Describe the bug**

1. To reduce the risk of conflicting files, we need a standardized way of formatting the Node.js code before a pull request.
2. [There are a number of solutions for this](https://www.google.com/search?q=GitHub+action+formatter+node.js&oq=GitHub+action+formatter+node.js&aqs=chrome..69i57j69i64.9200j1j7&client=ubuntu&sourceid=chrome&ie=UTF-8)

**To Reproduce**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**Screenshots**

N/A

**Additional details**

Parent Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/287

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by muskan399** [comment]
Assign this issue to me.
I'm a GitHub Extern candidate 28-04_Mus695_tfa_262.
