### ISSUE TITLE
Parent Issue: Various GitHub Actions Issues

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#287]
**Describe the bug**

1. Add Test Coverage Check for Pull Requests as a GitHub Action: https://github.com/PalisadoesFoundation/talawa-api/issues/258
2. Standardize GitHub Actions File Layout: https://github.com/PalisadoesFoundation/talawa-api/issues/255
3. Add and test GitHub action to lint all PRs before submission: https://github.com/PalisadoesFoundation/talawa-api/issues/284
4. GitHub Action To Limit Code File Sizes: #285
4. GitHub Action: Node.js Code Formatter #286
5. Run Automated Tests with Each Pull Request #289

**To Reproduce**

N/A 

**Expected behavior**

N/A

**Actual behavior**

N/A

**Screenshots**

N/A

**Additional details**

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by Sagar2366** [comment]
@muskan399 is working on all GitHub Actions related issues.
