### ISSUE TITLE
Urgent: Update `package-lock.json` to `ws` version `7.4.6`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#288]
**Describe the bug**

1. [GitHub Advisory to Upgrade](https://github.com/advisories/GHSA-6fc8-4gx4-v693)

**To Reproduce**

See below

**Expected behavior**

See below

**Actual behavior**

See below

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/120088381-b17f1f80-c0a4-11eb-9b39-0867d0c8b5cc.png)

**Additional details**

**Comment by impiyush83** [comment]
@palisadoes  Please assign this to me

**Comment by palisadoes** [comment]
@impiyush83 This is still not fixed. You did not address the  `apollo-server-express@2.14.2` dependency in the issue. 

Please also read up on how to automatically close issues in GitHub pull requests.

**Comment by palisadoes** [comment]
@impiyush83 Do a pull request against the `develop` branch. 

Also. Take a look at how to auto close issues on GitHub. It'll help greatly.
