### ISSUE TITLE
Run Automated Tests with Each Pull Request

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#289]
**Is your feature request related to a problem? Please describe.**
To ensure that tests are run before code is merged we need a tool to automatically run the tests to improve the reliability of Talawa-Admin as all feature/pull requests need to be adequately tested before they are merged.

**Describe the solution you'd like**
The tool must be :
    - Free for non-profit organizations (ideally)
    - Automated against the master and develop branches

**Describe alternatives you've considered**

1. [Talawa-Admin currently uses CodeQL](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/.github/workflows/codeql-analysis.yml) 
2. A similar methodology must be used

Parent Issue: Various GitHub Actions Issues #287

**Comment by muskan399** [comment]
Assign this issue to me.
I'm a GitHub Extern candidate 28-04_Mus695_tfa_262.

**Comment by uzair-ali10** [comment]
Is this issue resolved?
