### ISSUE TITLE
Master server is down

### ISSUE THREAD

**Issue by impiyush83** [PalisadoesFoundation/talawa-api#295]
**Describe the bug**
Due to duplicate graphql type PageInfo pushed in master the apollo server is not up.

**Severity**
High

**To Reproduce**

1.  npm install 
2. npm run start

**Expected behavior**
The server should be able to serve requests.

**Actual behavior**
The server restarts due to the failure mentioned in the image above.

**Screenshots**
@sumitra19jha 

<img width="852" alt="Screenshot 2021-06-01 at 7 17 12 AM" src="https://user-images.githubusercontent.com/20107021/120255492-b3660000-c2a9-11eb-9222-f7e29c429fa3.png">

**Additional details**

**Comment by sumitra19jha** [comment]
@palisadoes Please assign this to me

**Comment by sumitra19jha** [comment]
Please Close the issue
