### ISSUE TITLE
[Feature request] Separating authentication logic from resolvers and handling them at schema level.

### ISSUE THREAD

**Issue by aniketbiswas21** [PalisadoesFoundation/talawa-api#297]
**Is your feature request related to a problem? Please describe.**
Currently, the authentication is being handled by a helper function at the resolver level. This makes for reduced flexibility in terms of how we can block access.

**Describe the solution you'd like**
We can make use of a custom directive that handles authentication at the schema level. This provides us with more flexibility in terms of restricting access. Be it restricting a complete query or just a field. In addition, it separates out the authentication logic from the business logic.

**Describe alternatives you've considered**
None

**Approach to be followed (optional)**
Creation of a custom authentication directive and handling authorization at the schema level.

**Additional context**
I would like to work on this under the guidance of @sumitra19jha

**Comment by palisadoes** [comment]
@aniketbiswas21 

1. Please read our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/CONTRIBUTING.md) document completely.
     1. You need to open an issue and use the issue's comments to request that the issue be assigned to you first.
     1.  Open a pull request when the work is finished.
  
We appreciate the interest in the project. This a worthwhile feature to add.  I'm going to close this PR.

**Comment by palisadoes** [comment]
@aniketbiswas21 It looks like our GitHub actions are mislabeling issues. We'll try to fix it. Sorry for the confusion. Please proceed.
