### ISSUE TITLE
Creating Data Model to handle images/files/link

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#312]
**Is your feature request related to a problem? Please describe.**
New model to handle image or any file

**Describe the solution you'd like**
All files needed to be handled carefully making sure they are stored properly. 

**Approach to be followed (optional)**
File model will make sure that files data are maintained properly

**Comment by palisadoes** [comment]
@sumitra19jha Please get these approved before submitting the PR. Work with @DMills27 or another mentor if necessary

**Comment by sumitra19jha** [comment]
ok
