### ISSUE TITLE
Updating Users, Organizations & Events Query

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#315]
**Is your feature request related to a problem? Please describe.**
```
Following Query Modification is needed:
1. user,
2. users,
3. usersConnection,
4. organizations,
5. organizationsConnection,
6. organizationsMemberConnection,
7. event,
8. events,
9. registrantsByEvent,
10. eventsByOrganization,
11. registeredEventsByUser,
```

**Describe the solution you'd like**
The Query needs to follow the rules mentioned in [doc](https://docs.google.com/document/d/1skau0JdNXXKIH5MMP09USzq1RZwWV1EANJ-xXIDQg7A/edit?usp=sharing)

**Additional context**
Needs to be done before 24 June

Parent issue: 
- https://github.com/PalisadoesFoundation/talawa-api/issues/314

**Comment by palisadoes** [comment]
@sumitra19jha Can this be closed now?
