### ISSUE TITLE
Upgrade glob-parent to version 5.1.2 or later

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#317]
**Describe the bug**
1. Upgrade glob-parent to version 5.1.2 or later. 
1. [The current version is vulnerable to a regular expression denial of service attack.](https://github.com/advisories/GHSA-ww39-953v-wcq6)

**To Reproduce**

* See advisory above

**Expected behavior**
* See advisory above

**Actual behavior**

* See advisory above

**Screenshots**

![image](https://user-images.githubusercontent.com/16875803/122705144-fc0a3c80-d209-11eb-95f2-bde12f56a9cf.png)

**Additional details**
None

**Comment by saymedgm** [comment]
@palisadoes please assign me this issue

**Comment by saymedgm** [comment]
@palisadoes please review my pull request

**Comment by saymedgm** [comment]
@palisadoes please review my pull request
