### ISSUE TITLE
Volunteer and Attendee Check-ins

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa-api#319]
An organization may rely on volunteers for manage events. It would be good to have a simple system for users to be able to let the event coordinators know that they are on site and available.

The system could also be used to have attendees confirm that they are actually at the event. This would help with capacity planning.

**Comment by palisadoes** [comment]
@tasneemkoushar @anwersayeed you can update this issue with information. As you can see it is over 2 years old
