### ISSUE TITLE
Github Workflow for Linting and Checking the number of lines per file

### ISSUE THREAD

**Issue by DangaRanga** [PalisadoesFoundation/talawa-api#322]
**Is your feature request related to a problem? Please describe.**
The codebase for Talawa-API needs to be linted, and a limit for maximum the number of lines per file needs to be set

**Describe the solution you'd like**
A GitHub workflow needs to be implemented for automatically linting the codebase. This could be achieved using ESLint.
Additionally, the maximum number of lines per file should also be checked using a GitHub workflow.

An example of this can be found in Talawa-Admin

**Describe alternatives you've considered**

**Comment by uzair-ali10** [comment]
I belive this issue has been resolved and thus should be closed
@palisadoes 
Please take a look!!
