### ISSUE TITLE
Feature request for Handling Multiple Plugins

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#327]
**Is your feature request related to a problem? Please describe.**
The feature is related to the idea of giving users the capability to add to use multiple plugins

**Describe the solution you'd like**
To update the API's and create the necessary schema modification

**Describe alternatives you've considered**
Use plugin as a part of the environment variable

**Approach to be followed (optional)**
Performs update by adding the required data model, create query and mutation related to it.

**Additional context**
This is a request made by Reetik

**Comment by CyberWake** [comment]
Requirement a plugin table in database which stores configuration data of each organisation for all the plugins used in talawa-api.
Schema for a single plugin table object would we like:
```
{  id(org id)
   razorpayPlugin(RazorpaySchemma)
   plugin1Name(Schema for plugin 1)
   plugin2Name(Schema for plugin 2)
  ...
  ...
   all other plugins
}
```
RazorPay Schema:
```
{
   razorPayKey(id field from razorpay)
}
```

Mutation access permission:
super admin can set an environment variable to give rights to org admins to get donations keys set up.
If org admins don't have this right then plugin table should store the data for universal plugin configuration with any unique id.

Query Access:
Any user.
