### ISSUE TITLE
Feature request for user profile image update 

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#328]
**Is your feature request related to a problem? Please describe.**
As of now, the user can't update the user’s profile. With the edit profile option user should be able to:
1. Change the profile photo which includes adding and removing profile pictures similar to WhatsApp.
2. Change the First Name.
3. Change the Last Name.

**Describe the solution you'd like**
UpdateProfile Mutation Changes

**Describe alternatives you've considered**

**Approach to be followed (optional)**
The name will be updated by the mutation itself but for images, I need the clarification on cloud service we will be using 

**Additional context**
The request is made by @utkarshshendge

**Comment by sumitra19jha** [comment]
@utkarshshendge If I miss anything please mention it here

**Comment by utkarshshendge** [comment]
> @utkarshshendge If I miss anything please mention it here

LGTM. Thanks, @sumitra19jha !!

**Comment by sumitra19jha** [comment]
@palisadoes Please assign me this issue

**Comment by Gautam-Arora24** [comment]
Hi @sumitra19jha! Can I start working on this issue?
