### ISSUE TITLE
Feature request for handling event registrants and admins

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#330]
**Is your feature request related to a problem? Please describe.**
The event schema is currently focused on with respect to attendees. This needs to be changed in terms of Admins and Registrants.

**Describe the solution you'd like**
Schema, Mutation and Query Modifications to make those changes visible

**Additional context**
This is a request from @utkarshshendge Following are his inputs:

1. In the EventInput we can see an input for the attendees can be given. This is not required as attendees are Event Admins + Event Registrants. Instead, we need to include a list of registrants and a list of events admins for that event. Please see the Create Event page in the Figma document.

2. Currently we are able to register users for an event but as observed the isRegistered boolean value comes out to be null even after registration. When the user registers for an event he/she should be added to the list of registrants as well. Once a user registers for an event they should also be able to unregister from that event. Currently, there is no mutation to unregister.

3. Once unregistered the user’s details from the event’s registrants list should be removed. Additionally, the creator of the event should be able to remove a specific user from the registrant's list while editing an event.

4. As of now we are only able to get the userID of the event creator, any other details of the event creator are null, but as per the new UI, we need to display the full name of the user in the event information page. This may require changes in the EventInput to accept details of the creator.
```

**Comment by utkarshshendge** [comment]
@sumitra19jha as of now we are not getting events specific to an Org. Could you please add this as well?

**Comment by utkarshshendge** [comment]
@AdityaBirangal  since you are also working on the events, do these requirements align with your goals? If you have any changes please mention them.

**Comment by AdityaBirangal** [comment]
Thanks for mention Utkarsh.
I need one Boolean (is_check_in) value for every registrants. 
which can be modified by admins/creator (not everyone)

all attendees unique id are required (of that particular event)
Please refer https://github.com/PalisadoesFoundation/talawa-admin/issues/91
