### ISSUE TITLE
Replace CodeQL in GitHub Actions: Deprecation

### ISSUE THREAD

**Issue by DangaRanga** [PalisadoesFoundation/talawa-api#331]
**Is your feature request related to a problem? Please describe.**
After experiencing quite some difficulty to get CodeQL consistently running for all, we have come to the decision to remove the workflows that use CodeQL.

**Describe the solution you'd like**
In light of this, we will have to find another static code analysis tool to scan the code base for anti-patterns and potential vulnerabilities.

**Comment by palisadoes** [comment]
@uzair-ali10 This may be interesting for you

**Comment by uzair-ali10** [comment]
@palisadoes 
Thanks for bringing this to my notice, I'll try to find an alternative for CodeQL which scans the codebase with potential vulnerabilities.
By the way, Do you have any alternative in mind?

**Comment by palisadoes** [comment]
No, but there should be recommended alternatives mentioned as part of the
original deprecation notice on GitHub.

**Comment by uzair-ali10** [comment]
@palisadoes 
Could you please direct someone to post a screenshot of the deprecation warning

**Comment by palisadoes** [comment]
Please take a look at this:
https://github.com/github/codeql-action/security/advisories/GHSA-g36v-2xff-pv5m

It outlines what needs to be done to fix CodeQL. At first they said it was
deprecated, now there is a fix.
