### ISSUE TITLE
Bug report for not being able to access the data due to limitation of depth

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa-api#342]
**Describe the bug**
Some of the queries/mutations need to have 3 level access to avoid unnecessary simultaneous calls from the frontend

**To Reproduce**

1. accessing the joined organizations, membership request from login mutation is not possible.
2. same for the signup mutation
3. joinPublicOrganisation mutation doesn't give data for the creators of org and its admins.

**Expected behavior**
There should be 3 level of access to the mutations and queries this will be more than sufficient for any mutation and query.

**Actual behavior**
Throws error on requesting the data from the same mutation/query. Work around is to make more simultaneous calls from the result of previous calls.

**Screenshots**
[here](https://thepalisadoes-dyb6419.slack.com/archives/CSWH4PN0M/p1628574107015700?thread_ts=1628573097.014200&cid=CSWH4PN0M)

**Comment by sumitra19jha** [comment]
Please give the list of all the api where you need that access. 3 Level is not a behaviour we desired in the APIs

**Comment by CyberWake** [comment]
https://thepalisadoes-dyb6419.slack.com/archives/C022ZS19NDC/p1629018963030400 slack discussion thread for the api's that need this 3 level access
