### ISSUE TITLE
removeMember Mutation Malfunctioning

### ISSUE THREAD

**Issue by uzaxirr** [PalisadoesFoundation/talawa-api#347]
**Describe the bug**
`removeMember` mutation returns `User is not a member` even if the user id exists in DB and the Mutation is executed by Admin of the Org

**To Reproduce**

1. Login as an Admin for any Org
2. Try to remove a member who isn't an admin

**Expected behavior**
The member should be removed

**Actual behavior**
Instead of removing a member, The mutation throws the error `User is not a member`

**Screenshots**
Org's Document in DB
![Screenshot from 2021-08-16 10-32-05](https://user-images.githubusercontent.com/72073401/129513857-03904aa6-d576-4eeb-8536-bcb7263e2e54.png)

Logged in as an Admin
![Screenshot from 2021-08-16 10-31-47](https://user-images.githubusercontent.com/72073401/129513994-5f6a06cb-0df5-4c03-bc28-8533e6f76b81.png)

Mutation throws error 
![Screenshot from 2021-08-16 10-31-27](https://user-images.githubusercontent.com/72073401/129514081-6ea77a0a-e1f5-4baf-9712-f2c1f1d0c3bc.png)

**Additional details**
As we can see that user with ID `611210e9c3353218d02426f7`  exists in the `members`  array of the org so it should be removed successfully but instead the mutation throws an error

**Comment by SiddheshKukade** [comment]
no further activities are seen
