### ISSUE TITLE
[Parent Issue] Mutation Documentation

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#360]
**Is your feature request related to a problem? Please describe.**
Graph API's Mutation documentation needs to be added for a better understanding

**Describe the solution you'd like**
While writing the documentation make sure of the following points:
1. Aim of the mutation
2. Describe input fields
3. Describe return types
4. If a mutation is causing changes at different data fields in the database which is not part of the return type, then state and describe those too. For this, you need to go through the API Code.

**Additional context**
As there are large number of mutations, so before documentation please specify which mutation you are working on so that others can work accordingly.

**Comment by Rottenblasters** [comment]
@sumitra19jha I would like to work on this. I am new to the organization so can you guide me where to write the documentation?

**Comment by palisadoes** [comment]
@sumitra19jha Where are the child issues related to this issue?

**Comment by PSY27** [comment]
Hello can i work on this

**Comment by akshatgarg12** [comment]
I would like to work on this, specifically `organisation mutations`, should i create a child issue for this?
