### ISSUE TITLE
[Parent-Issue] Creating Test Cases for Login/Signup 

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#361]
**Is your feature request related to a problem? Please describe.**
Our backend logic related to users needs to have test cases.

Following are the mutations for which test cases will be created:
1. signUp #362 
2. login #363
3. refreshToken #364 
4. revokeRefreshTokenForUser #364 
5. updateLanguage #365

Following are the queries for which test cases will be created:
1. me #366 
2. user #366 
3. users #367 
4. usersConnection #368

**Describe the solution you'd like**
Test Code should be written to cover the entire business logic including all CRUD operations happening in the database 

**Additional context**
Please note that for testing purposes use Test Database

**Comment by khanjasir90** [comment]
@sumitra19jha can we provide more information about the same! would like to work on the same

**Comment by palisadoes** [comment]
@khanjasir90 Which child issue would you like to work on? There are many.

**Comment by khanjasir90** [comment]
@palisadoes would like to work of test cases for login

**Comment by palisadoes** [comment]
Please comment on that issue so that it can be assigned to you.

**Comment by khanjasir90** [comment]
umm...then would like to work on #366
