### ISSUE TITLE
[Child Issue] Test Cases for Signup Mutation

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#362]
**Is your feature request related to a problem? Please describe.**
Test Case is required for Signup Mutation

**Describe the solution you'd like**
As the new user login into the system, we take user input and returns the AuthData (including token). When creating the test issue please cover all the business logic involved in the process. Go through the Signup Mutation for understanding the logic.

**Additional context**
Parent Issue: 
- #361

**Comment by sandeep-v1404** [comment]
Can I work on this issue?
