### ISSUE TITLE
[Child Issue] Test Cases for login Mutation

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#363]
Is your feature request related to a problem? Please describe.
Test Case is required for login Mutation

Describe the solution you'd like
As the existing user login into the system, we take user input, verify it and returns the AuthData (including token). When writing the test code please cover all the business logic involved in the process. Go through the login Mutation for understanding the logic.

Additional context
Parent Issue: 
- #361

**Comment by sandeep-v1404** [comment]
@palisadoes sir, this issue has been resolved.

**Comment by sandeep-v1404** [comment]
@palisadoes This issue is resolved and it can be closed.
