### ISSUE TITLE
[Child Issue] Test Cases for refreshToken and revokeRefreshTokenForUser Mutation

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#364]
Is your feature request related to a problem? Please describe.
Test Case is required for refreshToken and revokeRefreshTokenForUser Mutation

Describe the solution you'd like
As the tokens expire into the system, we automatically refresh the expired token and returns the fresh token. When writing the test code please cover all the business logic involved in the process. Go through the refreshToken and revokeRefreshTokenForUser Mutation for understanding the logic.

Additional context
Parent Issue: 
- #361

**Comment by sandeep-v1404** [comment]
@palisadoes Can I work on this issue?
