### ISSUE TITLE
[Child Issue] Test Cases for updateLanguage Mutation

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#365]
Is your feature request related to a problem? Please describe.
Test Case is required for updateLanguage Mutation

Describe the solution you'd like
As a user changes his language preference into the system, we take the language input selected by the user, stores user language preference in the database and returns the user data. When writing the test code please cover all the business logic involved in the process. Go through the login Mutation for understanding the logic.

**Additional context**
Parent Issue: 
- #361

**Comment by Prathamesh010** [comment]
I would like to work on this.
