### ISSUE TITLE
[Child Issue] Test Cases for user related query

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#366]
Is your feature request related to a problem? Please describe.
Test Case is required for the following queries:
1. me
2. user

Describe the solution you'd like
If any client (app or web) ask for any single user node, we check the authentication of the user then accordingly return the node data. While returning the data we make sure some of the sub-data points (child nodes) access is restricted. While writing the test code please take all the scenarios in which any client can call those queries and can ask for output. Go through the me and user queries for understanding the business logic.

**Additional context**
Parent Issue: 
- #361

**Comment by khanjasir90** [comment]
@palisadoes would like to work one this!

**Comment by khanjasir90** [comment]
@palisadoes could u also provide me with some resources to refer to get this done!

**Comment by palisadoes** [comment]
Please take a look at the `tests/ `directory for examples for other queries.

**Comment by sandeep-v1404** [comment]
@khanjasir90 Are you working on it?
