### ISSUE TITLE
`pac-resolver` vulnerability in package-lock.json

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#373]
**Describe the bug**

This affects the package pac-resolver before 5.0.0. This can occur when used with untrusted input, due to unsafe PAC file handling. NOTE: The fix for this vulnerability is applied in the node-degenerator library, a dependency written by the same maintainer.

**Parent Issue**
- https://github.com/PalisadoesFoundation/talawa-api/issues/369

**References**
- https://github.com/advisories/GHSA-9j49-mfvp-vmhm

**Remediation**
The earliest fixed version is 5.0.0.

**Screenshots**

![image](https://user-images.githubusercontent.com/16875803/143076610-1120b371-59fc-459d-8412-ead5f0651bf6.png)

**Comment by asmitsirohi** [comment]
Hello @palisadoes , I would like to work on this, could you please assign it to me.
