### ISSUE TITLE
Creating Test Cases for organizations

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#375]
**Is your feature request related to a problem? Please describe.**
Our backend logic related to organizations needs to have test cases.

Following are the mutations for which test cases will be created:
1. createOrganization #376 
2. updateOrganization #377 
3. removeOrganization #378 

Following are the queries for which test cases will be created:
1. organizations #379 
2. organizationsConnection #380  
3. organizationsMemberConnection #381 

**Describe the solution you'd like**
Test Code should be written to cover the entire business logic including all CRUD operations happening in the database 

**Additional context**
Please note that for testing purposes use Test Database

**Comment by akshatgarg12** [comment]
Hey @sumitra19jha , I found test cases are already written for all CRUD operations on organisations in [tests/organization.spec.js](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/tests/organization.spec.js) ,
let me know , if any changes are required in these tests.

**Comment by sumitra19jha** [comment]
We are working on revamping that. Most of codes have changed and test code are not written taken into aspect of different scenarios in which api calls can be made.

**Comment by akshatgarg12** [comment]
> We are working on revamping that. Most of codes have changed and test code are not written taken into aspect of different scenarios in which api calls can be made.

By different scenarios , do you mean sending different arguments in the gql request like for sorting, filtering response etc.?
