### ISSUE TITLE
[Child Issue] createOrganization mutation testing

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#376]
Is your feature request related to a problem? Please describe.
Test Case is required for createOrganization Mutation

Describe the solution you'd like
As the existing admin login into the system, we take admin input, verify it and create organization. When writing the test code please cover all the business logic involved in the process. Go through the createOrganization Mutation for understanding the logic.

**Additional context**
Parent Issue: 
- #375

**Comment by akshatgarg12** [comment]
I would like to work on this @palisadoes @sumitra19jha

**Comment by palisadoes** [comment]
The previous work on this issue failed. We need another person to give it a try.
