### ISSUE TITLE
[Child Issue] Test Cases for updateOrganization Mutation

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#377]
Is your feature request related to a problem? Please describe.
Test Case is required for updateOrganization Mutation

Describe the solution you'd like
As the organization creator or admin updates organization-related data, we take client input, verify it and update organization. When writing the test code please cover all the business logic involved in the process. Go through the updateOrganization Mutation for understanding the logic.

**Additional context**
Parent Issue: 
- #375

**Comment by sandeep-v1404** [comment]
Can I work on this?
