### ISSUE TITLE
[Child Issue] removeOrganization mutation testing

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#378]
Is your feature request related to a problem? Please describe.
Test Case is required for removeOrganization Mutation

Describe the solution you'd like
When writing the test code please cover all the business logic involved in the process. Go through the removeOrganization Mutation for understanding the logic.

**Additional context**
Parent Issue: 
- #375

**Comment by akshatgarg12** [comment]
may i work on this?
