### ISSUE TITLE
[Child Issue] organizationsConnection query testing

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#380]
Is your feature request related to a problem? Please describe.
Test Case is required for organizationsConnection query

Describe the solution you'd like
When writing the test code please cover all the business logic involved in the process. Go through the organizationsConnection query for understanding the logic.

**Additional context**
Parent Issue: 
- #375

**Comment by sandeep-v1404** [comment]
I wanna work on this issue.

**Comment by palisadoes** [comment]
@sandeep-v1404  You are already working on 3 issues. Please complete those before working on any more. 
- https://github.com/PalisadoesFoundation/talawa-api/issues/assigned/sandeep-v1404
