### ISSUE TITLE
[Child Issue] organizationsMemberConnection query testing

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#381]
Is your feature request related to a problem? Please describe.
Test Case is required for organizationsMemberConnection query

Describe the solution you'd like
When writing the test code please cover all the business logic involved in the process. Go through the organizationsMemberConnection query for understanding the logic.

**Additional context**
Parent Issue: 
- #375

**Comment by sandeep-v1404** [comment]
@sumitra19jha I want to work on this issue.
