### ISSUE TITLE
CodeCov Github Action

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#386]
**Is your feature request related to a problem? Please describe.**
Workflow related to code coverage needs to be added

**Describe the solution you'd like**
Please refer to the documentation [here](https://github.com/marketplace/actions/codecov) which gives step by step procedure for adding the coverage

**Additional context**
Don't create a separate workflow, write the code in the existing workflow itself

**Comment by veerreshr** [comment]
Hello @sumitra19jha , I would like to work on this, could you please assign it to me
