### ISSUE TITLE
Creating Role Based Access

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#388]
**Is your feature request related to a problem? Please describe.**
Different roles need to be created based on user type. A user can be a normal user in-app, admin or super admin. As a client makes a request to the API, based on the client role access should be provided to the client. For example: Blocking the users, deleting requests, payment etc

**Describe the solution you'd like**
An enum for the classification of users into different types and on the creation of user classification of user based on that. A lot of API's might need a change after the creation of roles (especially mutations and subscriptions). So updates in them need to be performed accordingly.

**Additional context**
Please go through our database schema to understand where those changes are needed.

**Comment by AmeyaJain-25** [comment]
Hey, can I know how to work on this. I have some regarding this stuff but don't know how and where to start contributing.

**Comment by sumitra19jha** [comment]
> Hey, so primarily we need to add an enum to the user model [here](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/models/User.js) and then sign the JWT with an added field as below:
> ```js
>     {
>       tokenVersion: user.tokenVersion,
>       userId,
>       usertype: user._doc.type
>       firstName: user._doc.firstName,
>       lastName: user._doc.lastName,
>       email: user._doc.email,
>     },
> ```
>   [here](https://github.com/PalisadoesFoundation/talawa-api/blob/b3283ca965d98fd8cd1887fdd7a3eeea47b4ed4e/helper_functions/auth.js) and accordingly in the subsequent decoding too. And then we can create a middleware that takes in the user object and the expected userType and can return a bool if it finds one or not!
> 
> Is this what we're basically planning?

We don't need to add any parameters in JWT. User id is more than enough itself, all we need to do is too add a new parameter to user model where user will be quantified as admin, superadmin or normal user. In resolver we will read the access level from that user model parameter.

**Comment by sumitra19jha** [comment]
@ShubhamPalriwala Do you like to work on this issue?

**Comment by sumitra19jha** [comment]
> Hey, can I know how to work on this. I have some regarding this stuff but don't know how and where to start contributing.

Hi @AmeyaJain-25, Can you please let me know some other issue you want to work on, I will assign that to you

**Comment by sandeep-v1404** [comment]
> We don't need to add any parameters in JWT. User id is more than enough itself, all we need to do is too add a new parameter to user model where user will be quantified as admin, superadmin or normal user. In resolver we will read the access level from that user model parameter.


I think that there is already a parameter named `userType`. Please have a look [here.] (https://github.com/PalisadoesFoundation/talawa-api/blob/develop/models/User.js#L48) @sumitra19jha

**Comment by sandeep-v1404** [comment]
> > Hey, so primarily we need to add an enum to the user model [here](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/models/User.js) and then sign the JWT with an added field as below:
> > ```js
> >     {
> >       tokenVersion: user.tokenVersion,
> >       userId,
> >       usertype: user._doc.type
> >       firstName: user._doc.firstName,
> >       lastName: user._doc.lastName,
> >       email: user._doc.email,
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [here](https://github.com/PalisadoesFoundation/talawa-api/blob/b3283ca965d98fd8cd1887fdd7a3eeea47b4ed4e/helper_functions/auth.js) and accordingly in the subsequent decoding too. And then we can create a middleware that takes in the user object and the expected userType and can return a bool if it finds one or not!
> > Is this what we're basically planning?
> 
> We don't need to add any parameters in JWT. User id is more than enough itself, all we need to do is too add a new parameter to user model where user will be quantified as admin, superadmin or normal user. In resolver we will read the access level from that user model parameter.

I think that there is already a parameter named `userType`. Please have a look [here.](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/models/User.js#L48)  @sumitra19jha

**Comment by sumitra19jha** [comment]
@sandeep-v1404 The issue is that the usertype is not in sync with API. For example: a normal user should not have the same node power limit with a query which super admin will have (Currently we have restricted node access level for every user type). One of the good feature of **graphql** is that it provide diving inside the nodes, which should be restricted in some usertype while not in others. Same case with mutations, delete operation shall not be provided to every user. Database schema level changes are important here.

**Comment by sandeep-v1404** [comment]
> @sandeep-v1404 The issue is that the usertype is not in sync with API. For example: a normal user should not have the same node power limit with a query which super admin will have (Currently we have restricted node access level for every user type). One of the good feature of **graphql** is that it provide diving inside the nodes, which should be restricted in some usertype while not in others. Same case with mutations, delete operation shall not be provided to every user. Database schema level changes are important here.

So, what should one consider for DB Level Schema Changes? Do you mean API level changes, so that normal users can't access allUsers Queries or something like that.

**Comment by palisadoes** [comment]
@ShubhamPalriwala are you still working on this?

**Comment by SiddheshKukade** [comment]
Closing this as no further PRs are seen.
