### ISSUE TITLE
Revamping the overall architecture of Talawa-API

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#389]
**Is your feature request related to a problem? Please describe.**
Talawa Backend needs to be flexible to enable the client requirements of external cloud service providers and preserve the context of an open-source organisation as well. For this:
1. API should run and support storage, authentication etc in the absence of the cloud.
2. API should be flexible enough to support the presence of the cloud as well.

**Describe the solution you'd like**
If a user needs the support of storage using AWS, GCP etc for storing images and videos our API should provide that. For this, all APIs related to this needs to be created and existing ones should be modified.

**Notes**
Once a user selects the type of storage they want to prefer like the cloud or local then the backend will support that throughout its lifetime and the database will react accordingly. Assume that if a user selects local storage then in future they can't migrate to cloud or cloud then they can't migrate to local.

**Changes on database schema**
While creating the solution the entire database schema will change accordingly to support either cloud or local storage. In the case of the cloud, you might need to change the schema to support storing Id's, keys etc given by the cloud.

**Additional context**
All forms of communication with any third party services will happen using our API's rather than client and third-party directly.

Child Issue:
1. #427 
2. #428

**Comment by sandeep-v1404** [comment]
Does

> **Is your feature request related to a problem? Please describe.** Talawa Backend needs to be flexible to enable the client requirements of external cloud service providers and preserve the context of an open-source organisation as well. For this:
> 
> 1. API should run and support storage, authentication etc in the absence of the cloud.
> 2. API should be flexible enough to support the presence of the cloud as well.
> 
> **Describe the solution you'd like** If a user needs the support of storage using AWS, GCP etc for storing images and videos our API should provide that. For this, all APIs related to this needs to be created and existing ones should be modified.
> 
> **Notes** Once a user selects the type of storage they want to prefer like the cloud or local then the backend will support that throughout its life time and the database will react accordingly. Assume that if a user selects local storage then in future they can't migrate to cloud or cloud then they can't migrate to local.
> 
> **Changes on database schema** While creating the solution the entire database schema will change accordingly to support either cloud or local storage. In the case of the cloud, you might need to change the schema to support storing Id's, keys etc given by the cloud.
> 
> **Additional context** All forms of communication with any third party services will happen using our API's rather than client and third-party directly.

What does local storage exactly refer to? Does it refer to Talawa App in mobile?

**Comment by sumitra19jha** [comment]
@sandeep-v1404 Sure. There can be two types of setup for talawa-backend:
1. Entire Storage is the combination of MONGO plus local drive which can be a user laptop (for images, videos etc)
2. Mongo + External Service provider (let say AWS Cognito for extra secure authentication, S3 for images or videos etc)

Now here are three issues that come to mind when you frame solutions:
1. How will you make changes on the database schema level: It will be different if you are not using the cloud or using it. For example: If you are using S3 then in your database you will make changes to make sure you store id, URL, size(or other parameters) and some keys for secure access. Also, you have to make sure that only our backend can use that service so securities have to be set so that if any user gets the image URL then they shall not be able to see it until and unless the request is coming from our server and the user has access to see the image.
2. How should API's be constructed: For example: If the cloud is used separate steps might have to be performed by API's which will be different in the case of storing on the local system.
3. Do which cloud we use will affect the schema of the database or should we make one consistent one

I think this issue will include various child issues

**Comment by palisadoes** [comment]
@sumitra19jha @sandeep-v1404 Please create the child issues that refer to this one as the parent. It will be very helpful for others to work on them too.
