### ISSUE TITLE
[Bug report] : Dev Dependency Missing 

### ISSUE THREAD

**Issue by sandeep-v1404** [PalisadoesFoundation/talawa-api#399]
**Describe the bug**
Dev Dependency `nodemon` is not present in package.json which leads to errors while starting the test server.  

**To Reproduce**

1. Go to the root folder of talawa-api
2. run  `npm install`
3. run `npm run test-server`

**Expected behavior**

The test server should start after running `npm run test-server` without any errors.

**Actual behavior**

It throws errors that don't lead to successfully running the test server.

**Screenshots**
![image](https://user-images.githubusercontent.com/57038543/146575747-4b146eeb-0c77-4833-8f3c-84f4754b9510.png)

**Additional details**

A beginner might get stuck on this issue.
So, I would like to fix it.

**Comment by palisadoes** [comment]
@sandeep-v1404 Do you want to work on this?

**Comment by sandeep-v1404** [comment]
Yes @palisadoes
