### ISSUE TITLE
[Bug report]: Minor bug in OrganizationConnection and UserConnection Filter

### ISSUE THREAD

**Issue by sandeep-v1404** [PalisadoesFoundation/talawa-api#403]
**Describe the bug**
Filter in `OrganizationConnection` and `usersConnection` Query is not working as expected.

**To Reproduce**

1. npm install
2. npm start
3. SignUp and Create an Organization.
4. Query with organizationsConnection with where > id parameter. 

**Expected behavior**
The organization with a specified Id should be the output.

**Actual behavior**
It returns an empty Array. 

**Screenshots**

![image](https://user-images.githubusercontent.com/57038543/146656329-2c75cf29-a462-4e9e-a6e9-c2d3ce399f88.png)

**Additional details**

I would like to fix this issue.

**Comment by sumitra19jha** [comment]
@sandeep-v1404 The organisation whose id you put in the query is public variable set to FALSE?

**Comment by sandeep-v1404** [comment]
> @sandeep-v1404 The organisation whose id you put in the query is public variable set to FALSE?

No

**Comment by sandeep-v1404** [comment]
And while playing with organizationsConnection, I encountered some other bugs too.

- `id_contains` parameter under where
![image](https://user-images.githubusercontent.com/57038543/146669826-6354f27a-98df-4f6d-bbee-fbcdd0275e01.png)

- `id_starts_with` parameter under where
![image](https://user-images.githubusercontent.com/57038543/146669867-3134f587-0e50-409d-aa77-4475bffbbc78.png)
