### ISSUE TITLE
Add Test Coverage Check for Pull Requests as a GitHub Action

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#419]
**Is your feature request related to a problem? Please describe.**

1. The code base is insufficiently testable.
1. We need all code to be tested as part of each pull request.

**Describe the solution you'd like**

1. We need a way to add a GitHub action that automatically checks the codebase for the percentage coverage by tests.
1. The check should error out when the percentage is below a predefined level
1. The aim is that we’ll set increasingly higher percentage coverage until the codebase is 100% covered
1. We also want to ensure and verify that all tests in the repo are automatically run as part of each pull request as a GitHub action.
1. We also need to be able to report on the current code coverage percentage for the repo using the `codecov` tool. We use this with Talawa where a badge in the README.md file displays the code coverage value. [![codecov](https://codecov.io/gh/PalisadoesFoundation/talawa/branch/develop/graph/badge.svg?token=3PJXIKRS1S)](https://codecov.io/gh/PalisadoesFoundation/talawa)
 1. Ideally the modified workflow would create a `lcov.info` file that could be analyzed with a GitHub action like `VeryGoodOpenSource` which we have successfully used with `Talawa`.

**Describe alternatives you've considered**

1. None

**Approach to be followed (optional)**

1. **Pushes:** 
    1. The update / creation of a `push.yml` GitHub Action file that updates the `codecov` dashboard with each push. An example of how this could work is in the [`push.yml` file we use in the Talawa repo](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/push.yaml).
1. **Pull Requests:** 
    1. The update of the `pull-request.yml` GitHub Action file that will generate code coverage data in an `lcov.info` file. [An example of how this could work is provided by the codecov team](https://about.codecov.io/blog/javascript-code-coverage-using-github-actions-and-codecov/).
    1. The integration of the [VeryGoodOpenSource](https://github.com/VeryGoodOpenSource/very_good_coverage) GitHub action to analyze the `lcov.info` file created by the previous step. The minimum coverage level of the GitHub action must be set to the current code coverage level.

**Additional context**

A similar issue was created for Talawa-API:
- https://github.com/PalisadoesFoundation/talawa-admin/issues/205

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by palisadoes** [comment]
@sumitra19jha  I added this because though we run tests on the repo with each pull request, we are not checking the code coverage level with an aim to improving it. This should help. We recently implemented something similar for Talawa. Let me know your comments. It looks like an easy fix.

**Comment by sandeep-v1404** [comment]
Can I work on this issue?
