### ISSUE TITLE
[Child Issue] Image Storage in AWS

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-api#427]
**Is your feature request related to a problem? Please describe.**
User images and videos should be saved in AWS S3

**Describe the solution you'd like**
1. Construct API
2. API Should send requests and dump data to AWS S3
3. Create a data model which store image information related to location, size etc

**Additional context**
Please go through S3 Documentation on how to dump images and videos S3
Parent Issue: #389

**Comment by palisadoes** [comment]
The installation script should also prompt for AWS authentication details

**Comment by kailash360** [comment]
@sumitra19jha 
Can I work on this?

**Comment by sumitra19jha** [comment]
@palisadoes Should I work on this issue?
I am enthusiastic about this problem statement

**Comment by palisadoes** [comment]
@sandeep-v1404 is working on something similar for the GitHub Externship program. Please verify if this is the case. We may have to sign this issue to him

**Comment by sumitra19jha** [comment]
@palisadoes Please assign this issue to Sandeep. He will be working on this

**Comment by palisadoes** [comment]
Si him to comment on it so we can do that

**Comment by sandeep-v1404** [comment]
@palisadoes I'm working on this issue.
