### ISSUE TITLE
Update documentation on how to setup API with MongoDB URLs

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#430]
**Is your feature request related to a problem? Please describe.**
1. The documentation isn't clear enough on how to setup MongoDB and the MongoDB URLs for each of these scenarios:
    1. Using Docker
    1. Using a hosted MongoDB service
    1. Using MongoDB on your local machine
1. Caveats:
    1. In the case of the hosted MongoDB service, the steps need to be provided configuration for one or more commonly used service providers.
    1. Disadvantages of using Docker, such as its resource demands, needs to be included.
    1. A link to setting up MongoDB on  a local machine needs to be included.

The current documentation causes confusion. The process needs to be better defined.

**Describe the solution you'd like**

- Update the [INSTALLATION.md](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md) file with the improved documentation
- Update the [`.env.sample`](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.env.sample) file with the improved documentation.

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
N/A

**Additional context**
N/A

**Comment by sandeep-v1404** [comment]
@palisadoes Can I work on this issue?

**Comment by palisadoes** [comment]
Sandeep.

- I tried installing Talawa-API on a new local system and updated [INSTALLATION.md](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md)
- Let me know if this updated procedure is correct.

I want to get all the important repo documentation pages up to date before before the end of the month.

**Comment by sandeep-v1404** [comment]
@palisadoes I have gone through the updated INSTALLATION.md

- It's clean.
- I want to add small changes, to make it clear. Shall I do it ASAP?

**Comment by palisadoes** [comment]
Yes, go ahead.
