### ISSUE TITLE
[Bug Report]: Create Event Mutation not working as Expected

### ISSUE THREAD

**Issue by sandeep-v1404** [PalisadoesFoundation/talawa-api#435]
**Describe the bug**
- `createEvent` mutation when triggered throws errors, but still creates event. 

**To Reproduce**

1. `npm start`
2. create user
3. create org
4. create event

**Expected behavior**
- User who created or joined an organization can create event without errors. 
- Appropriate Error messages should appear.

**Actual behavior**
- Creator of an organization while creates an event, the mutation throws errors, but still creates event. 
- User, who is not a part of an organization while creates an event, the mutation throws errors, but still creates event. 
- Similar issue with user who joined organization
- Appropriate Error messages are not being shown.

**Screenshots**

1. `createEvent` mutation

![image](https://user-images.githubusercontent.com/57038543/150657028-3db6bedb-6fb9-4f19-a2da-b4f66c642381.png)

2.`events` query

![image](https://user-images.githubusercontent.com/57038543/150657041-c0b2e781-4fcb-46c6-87ab-8b11a8ed516e.png)

**Additional details**

- I would like to work on this issue.

**Comment by palisadoes** [comment]
Please include appropriate tests as part of the PR.
