### ISSUE TITLE
Fix Current API Tests (January 2022)

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#449]
The `Talawa-API` code base needs to be 100% reliable. This means we need to have We 100% unittest code coverage. 

Our integrated test suites need to function correctly. This suite is currently failing and needs to be fixed.

This is a parent issue for fixing existing tests.

- We'll only assign the child issues. 
- Please comment on one of the child issues for assignment.
- Only one child issue will be assigned to a person at any one time.

The following files need to be fixed as they are failing.

- `tests/user_subqueries.spec.js`
- `tests/user_update.spec.js`
- `tests/user.spec.js`
- `tests/organizations_connection.spec.js`
- `tests/block_user_functionality_tests.spec.js`
- `tests/event.spec.js`
- `tests/private_organization_membership.spec.js`
- `tests/user_organization.spec.js`

Child issues:
- https://github.com/PalisadoesFoundation/talawa-api/issues/450
- https://github.com/PalisadoesFoundation/talawa-api/issues/451
- https://github.com/PalisadoesFoundation/talawa-api/issues/452
- https://github.com/PalisadoesFoundation/talawa-api/issues/453
- https://github.com/PalisadoesFoundation/talawa-api/issues/454
- https://github.com/PalisadoesFoundation/talawa-api/issues/455
- https://github.com/PalisadoesFoundation/talawa-api/issues/456
- https://github.com/PalisadoesFoundation/talawa-api/issues/457
- https://github.com/PalisadoesFoundation/talawa-api/issues/458

**Comment by sandeep-v1404** [comment]
@palisadoes All these issues have a PR, it needs to be reviewed and merged.

**Comment by palisadoes** [comment]
Which PR specifically?

**Comment by palisadoes** [comment]
OK, add a `Fixes:` statement to each related PR so we can autoclose the issues.
