### ISSUE TITLE
Update GitHub Action for Pull Requests to fail when tests fail

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#458]
The `Talawa-API` code base needs to be 100% reliable. This means we need to have We 100% unittest code coverage. 

Our integrated test suites need to function correctly. This suite is currently failing and needs to be fixed.

**Current Behaviour**

- Our [GitHub Action file](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml) currently allows tests to fail without stopping the PR analysis in a failed state to alert PR reviewers. The 

** Expected Behaviour**
- _**When all the other tests of the parent issue are fixed**_, PRs must fail when tests fail.
- The [GitHub Action file](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml) will need to be updated accordingly.

### Note
_**When all the other tests of the parent issue are fixed**_ then this issue can be assigned.

Parent issue:
- https://github.com/PalisadoesFoundation/talawa-api/issues/449

**Comment by nishant3721** [comment]
@palisadoes can I work on it?

**Comment by palisadoes** [comment]
This will have to be worked on by me.
