### ISSUE TITLE
Write a script to check if all pull requests meet the requirements for JSDoc

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa-api#474]
In order to ensure that documentation is seamlessly being created with each addition/modification of a file, write a script to check that the file follows the specifications described in the Getting Started section [here](https://jsdoc.app/). This task essentially involves the creating of a parser (preferred from a maintainability point of view) or use of a regular expression that will check to see if the patterns for generating documentation are adhered to. The script should be written in Python and is written with the goal of it being used with a Github action being triggered upon a pull request.

Parent Issue
- https://github.com/PalisadoesFoundation/talawa-docs/issues/188

**Comment by akshatgarg12** [comment]
So essentially the script should check whether the files in PR, have comments (in this style /** */) before the functions which are required for JSDoc to generate docs, and if it contains them move the file to pipeline to create docs.

**Comment by DMills27** [comment]
@akshatgarg12 Yes, that is correct.

**Comment by palisadoes** [comment]
@akshatgarg12 do you want to work on this?

**Comment by akshatgarg12** [comment]
> @akshatgarg12 do you want to work on this?

Yes , i m actually looking for a proper solution to do this using github actions
