### ISSUE TITLE
Exposure of Sensitive Information to an Unauthorized Actor in nanoid package

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#477]
**Describe the bug**

The package `nanoid` before 3.1.31 are vulnerable to Information Exposure via the valueOf() function which allows to reproduce the last id generated.

The earliest fixed version is `3.1.31`

Upgrade `nanoid` to `3.1.31`

**Comment by DivyanshuParwal** [comment]
Can I work on this issue?
