### ISSUE TITLE
Tmp files readable by other users in sync-exec 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#479]
Affected versions of `sync-exec` use files located in `/tmp/` to buffer command results before returning values. As `/tmp/` is almost always set with world readable permissions, this may allow low privilege users on the system to read the results of commands run via `sync-exec` under a higher privilege user.

### Recommendation

There is currently no direct patch for `sync-exec`, as the `child_process.execSync` function provided in Node.js `v0.12.0` and later provides the same functionality natively.

The best mitigation currently is to update to Node.js `v0.12.0` or later, and migrate all uses of `sync-exec` to `child_process.execSync()`.

### Expected Fix in the PR
Migrate all uses of `sync-exec` to `child_process.execSync()`.

**Comment by ayushbhaimehta** [comment]
I would like to work on this

**Comment by lklivingstone** [comment]
@palisadoes Hi, I want to start my open-source contribution with this issue. Can I take up this issue?

**Comment by noman2002** [comment]
Unassigned due to inactivity.

**Comment by faraz16iqbal** [comment]
@noman2002 can I work on this issue?

**Comment by anshgoyalevil** [comment]
@palisadoes 

I guess this issue is resolved, since there is no occurrence of ```sync-exec``` in codebase. It is only installed as a dependency inside the ```package.json``` file.
