### ISSUE TITLE
Fix GitHub Actions: Remove Visible  Secrets

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#485]
**Describe the bug**
Our [push.yml](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/push.yml) and [pull-request.yml](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml) files use hard coded values for these environment variables for our tests to pass successfully.

- `ACCESS_TOKEN_SECRET`
- `REFRESH_TOKEN_SECRET`

As these are security related environment variables and should be invisible to users and persons with access to our GitHub repositories. They MUST be either dynamically generated or created as repository secrets.

We have tried creating `ACCESS_TOKEN_SECRET` and `REFRESH_TOKEN_SECRET` repository secrets where we used the nomenclature below to access them in the GitHub Actions workflow. 

- ${{secrets.ACCESS_TOKEN_SECRET}} 
- ${{secrets.REFRESH_TOKEN_SECRET}} 

Unfortunately, the `talawa-api` application cannot access them when we try this approach and all our tests fail.

We need to find a way to fix this and maintain the security of our testing regime.

**Comment by Waer1** [comment]
hey there, I hope that finds you well, I think you miss the Naming conventions for GitHub action you can look at the documentation here https://docs.github.com/en/actions/learn-github-actions/variables, even I'd like to contribute to solving this issue if that is possible, I will just apply GitHub action name convention and I hope that will work

**Comment by palisadoes** [comment]
Please explain how adjusting the naming convention solve the issue.

**Comment by anshgoyalevil** [comment]
@palisadoes 

If this issue isn't resolved yet, I can help resolve it. 

I have already figured out the way for doing so.

Check this file in my forked repo: https://github.com/anshgoyalevil/talawa-api/blob/workflow/.github/workflows/pull-request.yml

And this completed workflow: https://github.com/anshgoyalevil/talawa-api/actions/runs/4374743358/jobs/7654549491
