### ISSUE TITLE
Create group chat on event creation

### ISSUE THREAD

**Issue by ranilwallace** [PalisadoesFoundation/talawa-api#51]

**Comment by pranavich18** [comment]
@ranilwallace I would like to work upon this. Can you describe this issue a little bit more

**Comment by arjungarg07** [comment]
Hey @ranilwallace I would like to work on this as my first issue. Can you please elaborate the issue. Thanks.

**Comment by Priyaraj17** [comment]
Hey @ranilwallace , I would like to work on this issue. If its still open.
