### ISSUE TITLE
Resolvers: Create tests for updateOrganization.js

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#552]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/organization_mutations/updateOrganization.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/organization_mutations/updateOrganization.spec.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/organization_mutations/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by saga2405** [comment]
can you assign this to me

**Comment by palisadoes** [comment]
You already have 3 issues assigned. Please focus on closing those.

**Comment by saga2405** [comment]
Two issues are already approved and merged and I've made a PR for the 3rd issue too. So now I can work on a new issue

**Comment by palisadoes** [comment]
Why aren't the issues closed?

**Comment by saga2405** [comment]
can i close it by myself as the PRs are merged?

**Comment by palisadoes** [comment]
There is an autoclosing feature in GitHub. It's outlined in the CONTRIBUTING.md file.

**Comment by palisadoes** [comment]
The time of our contributors and reviewers is valuable. I'm sure you understand. The procedures are put in place to help everyone, you included. Please follow the process in future. I'll assign the issue

**Comment by saga2405** [comment]
yes, I understand. sorry for missing these details, I'll keep this in mind from now on.
