### ISSUE TITLE
Resolvers: Create tests for updateUserProfile.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#559]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/lib/resolvers/Mutation/updateUserProfile.ts`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/Mutation/updateUserProfile.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/user_mutations/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by Freedisch** [comment]
@palisadoes I want to know if this issue is still available, because It seems that most of the test cases have already been written but they are still open as an issue.

**Comment by palisadoes** [comment]
We have done many of the tests. Please let me know if any you find that should be closed.

Otherwise feel free to go ahead and work on any that are still valid.

**Comment by Freedisch** [comment]
@palisadoes I checked, and there is already a test file for this issue.
I tried to run a test coverage, but i just keep getting these result 
![image](https://user-images.githubusercontent.com/82499435/204134742-d5419ba6-3ba1-406a-8466-9d1501929d51.png)

![image](https://user-images.githubusercontent.com/82499435/204134821-abc2dc79-f303-4ce1-8f2c-16c48a610541.png)

**Comment by SiddheshKukade** [comment]
@Freedisch the `updateUserProfile.js` is having around 30% Code Coverage but expected coverage is 100%
![image](https://user-images.githubusercontent.com/65951872/205435273-98648d27-03ad-4657-a3f9-e8de93597c11.png)

**Comment by Freedisch** [comment]
@SiddheshKukade, please, how did you run the test coverage, I'm running it on my machine, and I'm not getting any result
I run `npm run test`  and I'm getting no result. Did I miss a step?

**Comment by SiddheshKukade** [comment]
@Freedisch it's simple use `yarn test --coverage`

**Comment by Freedisch** [comment]
@SiddheshKukade  I keep getting the same error whether with `npm run test` or `yarn test --coverage`
` · __tests__/resolvers/Query/postsByOrganizationConnection.spec.ts (1)
 · __tests__/resolvers/Query/organizationsMemberConnection.spec.ts (1)
 · __tests__/resolvers/Query/postsByOrganization.spec.ts (18)
 · __tests__/resolvers/Query/posts.spec.ts (18)`

**Comment by Freedisch** [comment]
It's okay I just fixed it, the bug was from my MongoDB setup. I'm working on the issue

**Comment by palisadoes** [comment]
@Freedisch are you still working on this?

**Comment by kb-0311** [comment]
If @Freedisch is unavailable pls assign it to me.

**Comment by palisadoes** [comment]
100% code coverage has been reached
