### ISSUE TITLE
Resolvers: Create tests for createDirectChat.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#572]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/lib/resolvers/Mutation/createDirectChat.ts`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/Mutation/createDirectChat.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/direct_chat_mutations/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by xoldyckk** [comment]
I'd like to work on this issue.

**Comment by arunavabasu-03** [comment]
i would like to do this one ??

**Comment by arunavabasu-03** [comment]
Actually I think all the necessary test cases are added already !! 😅

**Comment by palisadoes** [comment]
Because of the partial migration to typescript we'll need to get the typescript equivalent's [code coverage to 100%](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/blob/c9ca02cc08bfde87d0a5c49df65626b1f354dae1/src/lib/resolvers/Mutation/createDirectChat.ts) 

Can you work on that?

**Comment by arunavabasu-03** [comment]
Ok

**Comment by palisadoes** [comment]
@arunavabasu-03 Are you still working on this?
