### ISSUE TITLE
Resolvers: Create tests for groups.js

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#585]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/group_query/groups.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/group_query/groups.spec.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/group_query/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by arnab15** [comment]
@palisadoes  please assign this issue to me

**Comment by palisadoes** [comment]
You already have two other issues assigned. If they are in a PR, ask for a review in the comments. We need to make everyone have a chance to participate.

**Comment by ebrahim354** [comment]
I want to work on this please

**Comment by joharikushagra** [comment]
@palisadoes can I work on this issue?

**Comment by palisadoes** [comment]
@arnab15 do you still want to work on this issue?

**Comment by arnab15** [comment]
@palisadoes yes I can assign it to me

**Comment by arnab15** [comment]
due to my ongoing semester exam from 2nd May to 21 May, I am not able to contribute to this issue ,after 21May I'll start contributing again.

**Comment by rakshitgondwal** [comment]
Hey @palisadoes !!
Can I try contributing to this issue?

**Comment by SiddheshKukade** [comment]
@palisadoes I would like to take this sir
