### ISSUE TITLE
Uncontrolled Resource Consumption in markdown-it

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#616]
**Describe the bug**
Special patterns with length > 50K chars can slow down parser significantly.

- This vulnerability may be due to a package or a dependency of this packages that we are not using. This needs to be considered

**To Reproduce**
See screenshot

**Expected behavior**
Normal parsing velocity

**How to fix**
Upgrade to v12.3.2+

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/158198686-623f93bb-218f-4bed-907d-b3ef50c3b9a4.png)

**Additional details**

**Comment by arnab15** [comment]
@palisadoes after auditing packages I found that "markdown-js": "^0.0.3" is going to fix this issue should I update "markdown-js" to ^0.0.3?and it seems this version is not dependent on markdown-it.

**Comment by palisadoes** [comment]
Should we therefore remove `markdown-it` from `package.json`? If it is unnecessary, then it should be reomoved.

**Comment by arnab15** [comment]
@palisadoes I found that currently, markdown-js is deprecated as it's no longer in maintenance.in markdown-js v 0.04, they have a peer dependency on markdown-it but in v0.0.3 there is no dependency on markdown-id.
As markdown-js official docs say to use markdown-it so another workaround  for us will be we have to ditch markdown-js and use markdown-it,
currently, we are not using markdown-it as the main dependency it's a part peer dependency in markdown-js@0.0.4

**Comment by arnab15** [comment]
@palisadoes I think we have to downgrade to markdown-js@0.0.3 for @0.04 it is going to solve that warning

**Comment by palisadoes** [comment]
Have you investigated whether we need to use the package at all?

**Comment by kunal-iitj** [comment]
can I use this lib https://www.npmjs.com/package/markdown-it to solve the issue. It does the same job

**Comment by palisadoes** [comment]
This is no longer an issue. Closing
