### ISSUE TITLE
Link to Issue Template in Issue Report Guidelines returns a 404 error

### ISSUE THREAD

**Issue by AbhishekM2001** [PalisadoesFoundation/talawa-api#622]
**Describe the bug**
Link to Issue Template in Issue Report Guidelines is broken and returns a 404 error.

**Expected behavior**
The link should direct to a proper Issue Template file.

**Actual behavior**
The link instead returns a 404 error.

**Additional details**
As per the discussion on this issue on organization's slack channel, I'd like to be assigned to solve this issue.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by AbhishekM2001** [comment]
I'll work on it after working on a test creation issue. If the testing issue takes lot of time,I'll work on this alongside that(as this is easier).

**Comment by SiddheshKukade** [comment]
@AbhishekM2001 I think the link is working fine now.
[screen-capture.webm](https://user-images.githubusercontent.com/65951872/190690758-35c51ce9-a0de-4fc3-9092-20c8349688e0.webm)
