### ISSUE TITLE
Error: commentsByPost.js never throws an error when no comment is found

### ISSUE THREAD

**Issue by Kunal4now** [PalisadoesFoundation/talawa-api#658]
**Describe the bug**
In `lib/resolvers/post_query/commentsByPost.js`

`if (!commentFound) {
    throw new NotFoundError(
      requestContext.translate('comment.notFound'),
      'comment.notFound',
      'comment'
 );`
 
 This block of code never executes because the query returns an empty object instead of a null value.
 
 `(!commentFound)` is always false even if there was no comment found

**Expected behavior**
`!commentFound` should be true when there is no comment found

**Actual behavior**
`commentFound` contains an empty object and instead of throwing an error it skips the if block

**Comment by palisadoes** [comment]
The PR for this issue was reverted. The code modification caused other tests to fail. If you make a modification, please run the entire test suite.

    https://github.com/PalisadoesFoundation/talawa-api/runs/5806689541?check_suite_focus=true
