### ISSUE TITLE
Implementing new API testing features

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa-api#660]
A method suggested by @xoldyckk described in https://github.com/PalisadoesFoundation/talawa-api/issues/554#issuecomment-1086209815 seems to be the most promising for our testing and verification purposes. Create a toy model to see how well it suits our purposes. The toy model should be sufficiently extensive to cover the scope of our testing  while not being overly complicated. The tasks at hand are

- Implement the testing method outlined in the linked comment above. 
- Run tests using the method outlined in the comments and see how well they overcome the issues we previously faced (i8n internationalisation issue, incorrect code coverage results, etc)

**Comment by SiddheshKukade** [comment]
Hello @xoldyckk, Is this still being worked on? Let me know so that I can update the staus of this issue.

**Comment by cAmartya** [comment]
Hi, @SiddheshKukade , itf this issue is still open and no one else is working on it. Can this issue be assigned to me?
