### ISSUE TITLE
Update INSTALLATION.md

### ISSUE THREAD

**Issue by rohit-raje-786** [PalisadoesFoundation/talawa-api#677]
**Describe the bug**
The Installation.md File needs to be updated. Installing through the docker procedure needs to change the MongoDB URI and need to make changes in the docker.compose.yml file to map the port to the system port, so as to connect it to the MongoDB 

**Expected behavior**
Changes In the MongoDB URI and docker.compose.yml file

**Comment by palisadoes** [comment]
What are the changes you are proposing? What needs to change in the URLs and why?

**Comment by rohit-raje-786** [comment]
When I tried to run the test, I was facing the issue of MongoDB :
**Screenshot**
<img width="674" alt="Screenshot 2022-04-13 at 2 55 10 PM" src="https://user-images.githubusercontent.com/61861303/163242584-308ee5c0-a885-46af-9979-8942e3715315.png">

After making changes in the docker.compose.yml file and change in the MONGO_DB_URL the issue was resolved.

For proper installation, through docker, the docker.compose.yml file should contain the following:
version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always

And the MongoDB URI should be:mongodb://localhost:27017/talawa-api?retryWrites=true&w=majority

Updating the INSTALLATION.MD file for docker will help the newcomers to install the setup properly through docker.

**Comment by palisadoes** [comment]
OK

**Comment by palisadoes** [comment]
OK. Have you confirmed this with others on the slack channels? The concern is that we fix it for testing and it doesn't work in production.

**Comment by SiddheshKukade** [comment]
Hello @rohit-raje-786, It's been over 6 months and no PRs are associated with this.
