### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by anwersayeed** [PalisadoesFoundation/talawa-api#681]
In the `Contributing.md ` there is a section of `Internship` which include 
* GSOC 
* GitHub Externship
![Screenshot from 2022-04-17 13-20-42](https://user-images.githubusercontent.com/57287988/163705896-e1379738-fe8f-4edd-8e8a-5347aba8c151.png)

But in year 2022, `Talawa` also got selected for `Google Season of Docs`, So this should also be mentioned there.

**Comment by palisadoes** [comment]
Closing. There is no issue mentioned in the PR. Please follow the procedure in CONTRIBUTING.md

**Comment by anwersayeed** [comment]
@palisadoes I mentioned this issue over the slack channel also. Now can you please open this issue so that I will make a fresh PR?
OR should I open the same issue again and ask for assignment?
