### ISSUE TITLE
Maximum depth issue

### ISSUE THREAD

**Issue by nishnatadebnath** [PalisadoesFoundation/talawa-api#704]
**Describe the bug**
Since in the frontend talawa uses fetch with more than 3 depth of fetching ,the app is bugged right now and non usable as it showing error.
**To Reproduce**

1.Login into app will show the issue
2.Signup also has same problem

**Expected behavior**
Proper login and sign-up to fetch all the details .
**Actual behavior**
Server is nor running or wrong url problem is showing up
**Screenshots
![Screenshot from 2022-05-07 03-43-58](https://user-images.githubusercontent.com/53905682/167228462-0f100ce2-2155-4368-940a-869e3fd6d428.png)

**Additional details**
I think we should increase the maximum depth.Please give it a view @sandeep-v1404 @palisadoes .Login and fetching user details is  not happeing . Please review it once although I tried on multiple devices and with older git hub detached head commits.

**Comment by palisadoes** [comment]
@sandeep-v1404 Can you look into this? It's a show stopper bug

**Comment by nishnatadebnath** [comment]
I can easily fix the bug but need a thumbs up that this is a approved and verified issue and not something which is happening due to changes made recently in other dependent part of the program!

**Comment by palisadoes** [comment]
Approved and assigned

**Comment by palisadoes** [comment]
Closing as this is fixed by #705
