### ISSUE TITLE
Login and signup issue at frontend talawa app.

### ISSUE THREAD

**Issue by nishnatadebnath** [PalisadoesFoundation/talawa-api#706]
**Describe the bug**
The login and signup is currently having a problem due to null being returned in query and mutation. This is follow up of the issue  #704  where we solve the null issue.
**To Reproduce**

1.Login in Talawa
or
2.SignUp in Talawa

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**
All the detailed behaiviour can be seen in #704

**Comment by guptapriyanshu7** [comment]
I'm getting 404 "Not Found" exceptions while signing up and the app stops at fetching organizations on the select screen.
There is no such problem in the locally hosted server which is also from the latest develop branch. 

![image](https://user-images.githubusercontent.com/60141300/169783477-53cd91af-8e00-485e-98f4-342d5cac72e1.png)

<img src="https://user-images.githubusercontent.com/60141300/169784545-316c6776-21de-4b99-9ad2-ae6dc7f8f1c6.jpg"  width="300" height="600"  />

**Comment by guptapriyanshu7** [comment]
During logging, the app is throwing the null error for Organization name.
I have checked the login resolver file and found that during fetching the User from database "joinedOrganization" field is not populated and hence it remains null. @nishnatadebnath please look into it.

**Comment by kb-0311** [comment]
> During logging, the app is throwing the null error for Organization name. I have checked the login resolver file and found that during fetching the User from database "joinedOrganization" field is not populated and hence it remains null. @nishnatadebnath please look into it.

But then would that not return only the the joinedOrganization array of the ids as null in the user which we fetched from the User model by email ?

**Comment by guptapriyanshu7** [comment]
@kb-0311, joinedOrganization is a reference to 'Organization' model, using the populate method which mongoose provides all the fields be 'populated'.

**Comment by kb-0311** [comment]
@guptapriyanshu7 Thanks for your reply!
Yeah I got that the joinedOrganization is a reference to the Organization models but it will essentially store the Reference to a given organization object id. If The user has joined multiple orgs then the references to the Object will be stored as an array of objects containing the id of the orgs in the Organization Model..

What I was saying that if that was the issue then the user would have been fetched and return but the joinedOrganization object within the fetched user would be null and not the entire user.

**Comment by guptapriyanshu7** [comment]
The user doc which is returned is not null in itself, it's just that the joinedOrganizations fields have no data (other than ids) hence, an error is returned that the Organization.name is null which is expected to be non-nullable.

**Comment by guptapriyanshu7** [comment]
I have resolved the login issue, just have to open the PR.
You could look into registration, though I believe there is something else going wrong with it because I am able to signup with my local server.

**Comment by kb-0311** [comment]
ok great!
I don't think during registration we are passing the `joinedOrganizations` as an argument to create the new user.
We are only taking the `organizationBelongsTo` as an argument.

**Comment by palisadoes** [comment]
This is good progress. Thanks for your efforts.

**Comment by guptapriyanshu7** [comment]
> I'm getting 404 "Not Found" exceptions while signing up and the app stops at fetching organizations on the select screen. There is no such problem in the locally hosted server which is also from the latest develop branch.
> 
> ![image](https://user-images.githubusercontent.com/60141300/169783477-53cd91af-8e00-485e-98f4-342d5cac72e1.png)
> 
> <img alt="" width="300" height="600" src="https://user-images.githubusercontent.com/60141300/169784545-316c6776-21de-4b99-9ad2-ae6dc7f8f1c6.jpg">

@kb-0311, yeah it could be that but in my case I am unable to fetch all the organizations during the first step of signup as shown in the screenshot. Are you facing similar issue?

**Comment by kb-0311** [comment]
I am sorry but I did not find where the `link.dart` file is could you pls link the file from the source code int the talawa mobile repo? Thanks.

The debugger shows an exception on a post request first which I think is the user details? Where are we making a get request to fetch all organizations again?

**Comment by guptapriyanshu7** [comment]
I was using wrong Heroku API URL that's why organizations were not fetching. Now it's working.

**Comment by kb-0311** [comment]
Great! So does that now mean this issue will be resolved and can be closed after your PR is merged?

**Comment by nishnatadebnath** [comment]
I have a few days free in between the exam , so I will sum up the whole situation -
1)Signup issue-Why it is working in the latest developer branch and not in the

**Comment by nishnatadebnath** [comment]
The signup issue is not updated in the main server because there is a problem with GitHub Heroku integration that's why #705  is not reflected in the server deployed. Merging this PR will solve the total issue. @palisadoes 

We also have to manually update the Heroku  server  .

**Comment by palisadoes** [comment]
I pushed the code manually earlier this week after making the announcement on slack. 

I've done so again, however the branch has changed from `master` to `main` in their portal. When the automation is restored we'll need to take this into consideration

Please let me know if it works for you now.

**Comment by palisadoes** [comment]
The automated Heroku deployment has been restored using the `develop` branch.
