### ISSUE TITLE
Bug Report :  npm run setup compiles with error 

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#712]
**Describe the bug**
The Express Installtion Functionality provided by the command `npm run setup ` executes with an error 
Output :
![image](https://user-images.githubusercontent.com/65951872/172212087-ef115e31-11e6-454c-a123-8913ee672082.png)

**To Reproduce**

1. Clone the project in your machine and run 'cd talawa-api'
2. run `npm install`
3. run `npm run setup `
 command provides an error

**Expected behavior**
Should provide the steps required for the installation feature
**Actual behavior**
Commands finishes execution with an error 

**Screenshots**
![image](https://user-images.githubusercontent.com/65951872/172212635-55a470f9-ca37-4de8-a4b3-9d414f00fe65.png)

**Comment by palisadoes** [comment]
That `about.md` file was used as part of the installation script. It seems to have been removed.

Do you want to work on this bug?

**Comment by SiddheshKukade** [comment]
Yes sir you can assign to me 👍🏻
