### ISSUE TITLE
[Feature Request] New Features for Talawa-admin

### ISSUE THREAD

**Issue by asmitsirohi** [PalisadoesFoundation/talawa-api#717]
**Is your feature request related to a problem? Please describe.**

Currently, in Talawa-admin, the feature for forgetting passwords is not present, and while logging in or signup there is no captcha to detect the bot activity. Also, there is no feature that exists in talawa-admin to allow only authorized admins and the current super admin is not able to create new super admins. For more info PalisadoesFoundation/talawa-admin#342

**Describe the solution you'd like**

* Mailer will be configured to send OTP mails to the user.
* Google Recaptcha backend endpoint will be configured.
* Resolvers for forgotten passwords, verify google Recaptcha, and OTP will be implemented.
* A mutation will be added in order to toggle the roles of users.
* A new field will be added in the user model name ‘adminApproved’ to verify whether the user is an authorized admin or not.
* A mutation will be added in order to accept or reject the request of an admin.
* A new field will be added in the organization model name ‘tags’ to store the tags of an organization.
* A new field will be added in the user model name ‘createdAt’ to track the time when a user is created. This data will be useful while displaying users in the talawa-admin.

**Comment by nishant3721** [comment]
@asmitsirohi can I work on it?

**Comment by nishant3721** [comment]
@asmitsirohi ??

**Comment by nishant3721** [comment]
Ok
