### ISSUE TITLE
Update: INSTALLATION.md

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-api#773]
**Describe the bug**
https://github.com/PalisadoesFoundation/talawa-api/blob/01b2c8e3f0fa487928441dcfb4255dddd4d9b442/INSTALLATION.md?plain=1#L18-L20
This is a wrong method of copying the contents of .env.sample to env and instead, the command should be `cp .env.sample .env` as rectified below in the same installation guide.

**To Reproduce**

1. Running `cp .env .env.sample` makes the `.env.sample` file empty
2. Sample env contents are flushed

**Expected behavior**
Content of `.env.sample` compiled to newliy created `.env` file .

**Actual behavior**
Contents of empty `.env` file copied on `.env.sample` (clearing out the file).

**Possible Fix**
change the command in that line to `cp .env.sample .env`

**Comment by palisadoes** [comment]
@kb-0311 Please follow the procedure of creating the issue, and waiting for it to be approved. We do it this way to prevent a chaotic process. We had that situation in the past and we really don't want to repeat it. Thanks for your contribution, but please follow the guidelines in our CONTRIBUTING.md file

**Comment by kb-0311** [comment]
Thanks for the merge @palisadoes . Yes, Sorry, I will first discuss the issue on the slack channel before opening an issue. Thanks for the CONTRIBUTING guide.
