### ISSUE TITLE
Resolvers: Create Tests for resolvers/DirectChat/index.ts

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#810]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/lib/resolvers/DirectChat/index.ts`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `src/lib/resolvers/DirectChat/index.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/blob/6ab23bc8df31919f0bc551544a4d29dd408207fc/src/lib/resolvers/DirectChat/index.ts). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by cAmartya** [comment]
Hey @SiddheshKukade , I want to work on this issue. Can you assign it to me?

**Comment by cAmartya** [comment]
Hey @SiddheshKukade , I think the folder structure might have been updated, I don't think the file directChat.js according to the path `lib/resolvers/direct_chat_query/directChat.js` exists. The folder `direct_chat_query` is not present

**Comment by beingnoble03** [comment]
@SiddheshKukade can I work this issue?

**Comment by beingnoble03** [comment]
Do we need to work here for `src/lib/resolvers/DirectChat/index.ts`? Can you please confirm once?

**Comment by SiddheshKukade** [comment]
> Do we need to work here for `src/lib/resolvers/DirectChat/index.ts`? Can you please confirm once?

Yes

**Comment by beingnoble03** [comment]
> > Do we need to work here for `src/lib/resolvers/DirectChat/index.ts`? Can you please confirm once?
> 
> Yes

Can you please assign me?
