### ISSUE TITLE
Resolvers: Tests for createMessageChat.ts

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#814]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `/lib/resolvers/Mutation/createMessageChat.ts`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/Mutation/createMessageChat.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/blob/develop/src/lib/resolvers/Mutation/createMessageChat.ts). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by beingnoble03** [comment]
@SiddheshKukade did you mean the path `src/lib/resolvers/Mutation/createMessageChat.ts`? If yes, the current test coverage of this file is 96%. I want to work on this file, can you please assign me?

**Comment by SiddheshKukade** [comment]
@beingnoble03 go ahead

**Comment by SiddheshKukade** [comment]
@palisadoes sir, please take a look.

**Comment by palisadoes** [comment]
@beingnoble03 You are already working on two other issues. Please complete those first.

**Comment by beingnoble03** [comment]
@palisadoes I am not working on any issue right now. All the issues, that I was assigned, are closed as the files that were linked by these issues had a code coverage of 100% already. So, can I work on this?

**Comment by beingnoble03** [comment]
Travelling this week. Will open a PR next week.
