### ISSUE TITLE
Resolver: Create Tests for postsByOrganization.js

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#815]
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/Query/postsByOrganization.ts`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/post_query/postsByOrganization.sepc.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/organization_query/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

**Comment by beingnoble03** [comment]
@SiddheshKukade can i work on this issue?

**Comment by beingnoble03** [comment]
@palisadoes @SiddheshKukade this file's test coverage is 100% already. 
![image](https://user-images.githubusercontent.com/62551163/206404026-be9519a6-f064-462c-9e67-0bef3feceb5b.png)
Check for `postsByOrganization.ts`

So, can we close this issue?

**Comment by SiddheshKukade** [comment]
@beingnoble03 I've updated the path now

**Comment by beingnoble03** [comment]
@SiddheshKukade the current test coverage of the file is already 100%. I think we can close this issue.
![image](https://user-images.githubusercontent.com/62551163/206533793-c96c5b05-9f8a-4120-80c0-de014e522f37.png)
look for `postsByOrganization.ts`

**Comment by beingnoble03** [comment]
@SiddheshKukade Also, most of the recent issues about test coverage also have the issue with the path and many of the `.ts` files, linked with these issues, are already 100% covered.
