### ISSUE TITLE
Feature Request : Adding `.nix` file to enable reproducible developer environments using `nix-shell`

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-api#818]
**Is your feature request related to a problem? Please describe.**
Nix is a tool that takes a unique approach to package management and system configuration. Using nix-shell in our project can help the new contributors to quickly setup the required programs in order to run the API.
**Describe the solution you'd like**
A .`nix` file can be added 

**Approach to be followed (optional)**
1. create a file named `default.nix`
2. It will contain following
```sh
{ pkgs ? import <nixpkgs>{} 
}:
  pkgs.mkShell { 
    name="dev-environment";
    buildInputs = [
       pkgs.nodejs
       ];
     shellHook = '' 
     echo "Talawa API Configurations loading..."
     echo "Make sure to fill in the environment variable for successful exeution."
     echo "Running Talawa API Developement Environment"
     npm run dev 
  '';
}
```
The above fill will install nodejs@LTS to separate shell keeping the user environment & development environment isolated.

**Comment by SiddheshKukade** [comment]
I've tried this file with `nix-shell` command & it works fine. 
![image](https://user-images.githubusercontent.com/65951872/208296924-3e88faa3-07e6-48b4-bbbe-a058c6e79833.png)

@DMills27 sir & @palisadoes sir, I would like to have your feedback.

**Comment by palisadoes** [comment]
@DMills27 please comment on this. It looks like a good first step

**Comment by DMills27** [comment]
The nix config as it is now is not reproducible nor hermitic. The LTS version of Node.js can change in the future and break our app quite easily. You need to use Nix flakes to achieve the goal we seek. Here is an overview of what would be need to be done as well as the issues with the approach you are currently using: https://www.tweag.io/blog/2020-05-25-flakes/

**Comment by SiddheshKukade** [comment]
@DMills27 Sir, thanks I'll take a look and will try to improve 👍🏻

**Comment by palisadoes** [comment]
@SiddheshKukade how's progress on this?

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade how's progress on this?

@palisadoes  sir actually me and @anwersayeed  are focusing on setting this up for the talawa-admin first as it will be a bit easier to get us started .

**Comment by rv602** [comment]
@palisadoes I would like to work on this

**Comment by palisadoes** [comment]
@DMills27 Dominic Mills is working on this behind the scenes. Some work has been done already. Please contact him on slack to coordinate this activity.

**Comment by DMills27** [comment]
For anyone who decides to work on this, I suggest reading this blog post that details how one would create a derivation for building the API ( https://lambdablob.com/posts/program-declarative-nix-package-derivations/) and then playing with simple examples to get a feel for it. 

Additionally, here is a blog post about how to search for various Nix packages: https://lambdablob.com/posts/nix-search-for-apps-in-packages/

**Comment by rv602** [comment]
@DMills27, I'll go through the given links and get back to you. Thank you.

**Comment by rv602** [comment]
Hello @DMills27, as recommended by @palisadoes, I reached out to you on Slack to inquire about the next steps to take regarding this matter. Could you kindly take a look at my message? Thank you.

**Comment by rv602** [comment]
@DMills27 I looked into Nix. I installed it and faced some issues on my device but it is working now.
As advised by you to get comfortable with Nix, I went through its docs and read some blogs on it.
I'll update you once I make some more progress.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.
