### ISSUE TITLE
BUG: file-type vulnerable to Infinite Loop

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#830]
**Describe the bug**

An issue was discovered in the file-type package from 13.0.0 until 16.5.4 and 17.x before 17.1.3 for Node.js. A malformed MKV file could cause the file type detector to get caught in an infinite loop. This would make the application become unresponsive and could be used to cause a DoS attack when used on a web server.

Update [package-lock.json](https://github.com/PalisadoesFoundation/talawa-api/blob/-/package-lock.json)

![image](https://user-images.githubusercontent.com/16875803/210032121-6c6b56bc-893b-480e-84ee-f85435aef633.png)

**To Reproduce**
See above

**Expected behavior**
No vulnerabiltiy present

**Actual behavior**
See above

**Screenshots**
See above

**Additional details**

**Comment by prathamesh-mutkure** [comment]
I think I can work on this issue, assigning it to myself
