### ISSUE TITLE
Crash in HeaderParser in dicer

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#831]
**Describe the bug**
This vulnerability is for dicer a package that may not be used any more. Investigate whether this package is still used and remove it from package-lock.json  if not

![image](https://user-images.githubusercontent.com/16875803/210032546-94ade9d9-52bc-4f9a-a4cb-30d6627a8b29.png)

**To Reproduce**
See above

**Expected behavior**
No vulnerabiltiy present

**Actual behavior**
See above

**Screenshots**
See above

**Additional details**

**Comment by beingnoble03** [comment]
@palisadoes I looked dicer in the codebase, found that we currently don't use it. I think it is safe to remove from package.json.

**Comment by beingnoble03** [comment]
Sorry, found out that `dicer` is a dependency for other packages.
@palisadoes should we close this issue?
