### ISSUE TITLE
Tmp files readable by other users in sync-exec

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#833]
**Describe the bug**

Affected versions of sync-exec use files located in /tmp/ to buffer command results before returning values. As /tmp/ is almost always set with world readable permissions, this may allow low privilege users on the system to read the results of commands run via sync-exec under a higher privilege user.

There is no current fix, however we need to check whether we are using sync-exec and can remove references to it from the code base.

Consider upgrading to Node.js v0.12.0 or later, and migrate all uses of sync-exec to child_process.execSync()

![image](https://user-images.githubusercontent.com/16875803/210033000-c6b60377-5be7-4e60-a0ee-f42e0992a399.png)

**To Reproduce**
See above

**Expected behavior**
No vulnerabiltiy present

**Actual behavior**
See above

**Screenshots**
See above

**Additional details**

**Comment by VaibhavJak** [comment]
@palisadoes would like to solve this issue. Please assign it to me. Will follow the necessary guidelines

**Comment by VaibhavJak** [comment]
@palisadoes would like to solve this issue , please assign this to me. Will follow the contributors' guidelines

**Comment by noman2002** [comment]
Unassigned due to inactivity.

**Comment by faraz16iqbal** [comment]
@noman2002 Can I work on this?

**Comment by palisadoes** [comment]
> @noman2002 Can I work on this?


@faraz16iqbal Stop immediately. I have warned you multiple times to follow the guidelines in the CONTRIBUTING.md file. Everyone needs to get a chance. Your actions are not in keeping with the collaborative culture of our community.

You have repeatedly asked to be assigned issues that are already assigned an in many cases, issues that were assigned in the past 24 hours.

Please run the apps and try to discover serious bugs or serious flaws in the features. That will be a good start. 

We also have lots of testing issues that will provide a good start. This is stated in the pinned issues in the #general slack channel.

**Comment by anshgoyalevil** [comment]
@palisadoes 

This issue can be closed since it is related to https://github.com/PalisadoesFoundation/talawa-api/issues/479
