### ISSUE TITLE
Not able to display markdown while running setup command

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-api#845]
**Describe the bug**
While running setup command, the terminal is falling with error,

console.log(marked(text));
              ^

TypeError: marked is not a function

**To Reproduce**

1. Run the command 'npm run setup'
2. Check the terminal, there will be a marked error

**Expected behavior**
It should execute the **automated installation** process of Talawa API. Each file contains a function to complete a particular step. All the functions are asynchronous and display whether the operation has been completed successfully or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/211142030-e5215a9f-5f60-4717-93fa-95b6b2696bf2.png)

**Actual behavior**
See above

**Additional details**

**Comment by nishant3721** [comment]
@palisadoes I would like to work on this

**Comment by palisadoes** [comment]
It looks like this was missed in your previous PR.  https://github.com/PalisadoesFoundation/talawa-api/issues/834
