### ISSUE TITLE
Fix Deprecated Packages

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#866]
**Describe the bug**

Running the `npm ci`  command generates many reports of deprecated packages used by the repo. We need to update the packages for long term maintainability while adjusting the tests and code accordingly. 

The best approach may be to make this a parent issue and refer child issues for each deprecated package for people to fix. 

**To Reproduce**

1. You can see the nature of the issue by following this link for a recent `GitHub Action` under `install dependencies`: https://github.com/PalisadoesFoundation/talawa-api/actions/runs/3941696944/jobs/6746875712 

**Expected behavior**
No errors when running the command.

**Actual behavior**
See screenshot below

**Screenshots**

![image](https://user-images.githubusercontent.com/16875803/212999525-c784d90d-5b04-4f94-9e71-c20b4b6bee0d.png)

**Additional details**
Create child issues referring to this one as needed.

**Comment by beingnoble03** [comment]
@palisadoes Can I create a child issue for removing `@types/mongoose-paginate-v2`?

**Comment by beingnoble03** [comment]
And do we need to create child issue for every deprecated dependency?

**Comment by palisadoes** [comment]
We can do it all at once.

**Comment by beingnoble03** [comment]
@palisadoes fine. Can you please assign me this issue?

**Comment by beingnoble03** [comment]
Travelling this week. Will open a PR next week.

**Comment by beingnoble03** [comment]
<img width="735" alt="Screenshot 2023-01-27 at 6 23 50 PM" src="https://user-images.githubusercontent.com/62551163/215091842-b405d7fa-fbbd-463b-9ca3-d16793307ddf.png">

Error log

**Comment by noman2002** [comment]
@DMills27 @TheHazeEffect Please have a look at it.

**Comment by palisadoes** [comment]
Closing. We are going to make this a part of the GSoC ideas.
