### ISSUE TITLE
[Feature Request] : making a python script to automate the setup of talawa-api

### ISSUE THREAD

**Issue by rv602** [PalisadoesFoundation/talawa-api#885]
### Is your feature request related to a problem?
For anyone who wishes to contribute to talawa, setting up a local instance of the talawa-api is one of the most crucial steps. I personally feel this is a step where many people either get stuck for a long time or loose the interest to debug it further.

### Proposed solution
I propose to make a shell script (.sh file) that will automate most of the setup for talawa-api. Although every single part may not be suitable for automation, but most of the part like setting up access tokens, refresh tokens, generating a local MongoDB url can be done error-free within seconds, without any hassle.

### Alternatives considered
As of now, I think that making a shell script should solve the problem. But if for some reason it seems to not be feasible in the future, I think an alternative would be a python script to automate the process.

### Approach
My approach would be making a shell script. To run this, all the user has to do is run the following command : - ```./installer.sh```
This will generate a new .env file, fill it with autogenerated access and token secrets, and a MongoDB url for the ones who prefer to use a local instance. For steps that can’t be automated, such as generating a Google recaptcha secret key etc, instructions can be shown on how to proceed.
For steps where configurations may be based on user preference, such as using a cloud/local instance of MongoDB or the preferred PORT for the api to be run on, multiple options can be provided in the cli itself.

**Comment by xoldyckk** [comment]
It is needless. The contributer will have to go through the installation instructions at least once and they will have to manually set up most of the environment variables anyway. The instructions are already written to be very beginner friendly.

There used to be a setup script for talawa-api written in javascript previously. It was removed because of the same reasons.

**Comment by rv602** [comment]
I did check the old javascript setup file. All it did was install dependencies and make a .env file.

What I am proposing is much beyond that, wherein I am actually automating most of the part.

Even if the docs are beginner friendly, the script I am proposing would save a lot of time and do most of the process faster and much more error free.

**Comment by xoldyckk** [comment]
@rv602 Realistically the only things u can automate are generating .env file, copy stuff from .env.sample to it and set up access/refresh token secrets, copy other environment variables with dummy values. If you want to do just this go ahead. And also make sure to include this in the documentation right after setting up access/refresh token part.

**Comment by palisadoes** [comment]
We are not approving new features, however this would be a significant improvement and deserves an exception. Please proceed.

**Comment by rv602** [comment]
alright, i'll try implementing it in Python.

**Comment by palisadoes** [comment]
@DMills27 @anwersayeed @SiddheshKukade wouldn't this be better to make this a part of our Nix & Hazel project? It's for improving the installation process.

**Comment by SiddheshKukade** [comment]
> @DMills27 @anwersayeed @SiddheshKukade wouldn't this be better to make this a part of our Nix & Hazel project? It's for improving the installation process.

Yes It will be. Actually Nix and Bazel are trying to solve the environmental installation issues. We can include this as well after that it done 👍🏻

**Comment by palisadoes** [comment]
@SiddheshKukade 
1. We'll still continue with this because users will need something until then.
1. This will also provide you with a guide on what to do.

**Comment by rv602** [comment]
@palisadoes I looked into the `python env package` mentioned in the PR. The problem with that is when you run the script, the values of the `env variables` assigned by it stay valid only for the current session, so once the python script stops running those values would be invalid, defying the whole point of convenience.

I was thinking how we have a `.env.sample` file, I can similarly make a `.env.script` file, that will contain the `sections[]` for the configparser, and a comment at the top of the `.env.script` saying that do not edit this file as it will be used by the script to automate installation. This way all the behaviour of the script would be isolated.

I am suggesting this method as apart from the problem of modifying the `.env.sample` , the `configparser`seems like a very good solution hence I think we can retain it.

Just wanted your feedback on this, as all other changes are done, so that this issue can be resolved.

**Comment by rv602** [comment]
@palisadoes should I make a new PR with the above mentioned changes?

**Comment by palisadoes** [comment]
Sorry for the delay. This pull request solves the biggest concern. So the mongo related aspects can be removed.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1120

The remaining features should be handled by the script and should not alter the contents of an existing `.env` file unless the script's user decides to override them.

The PR introduces a new parameter, so you'll need to take that into consideration. When done, please submit the PR.

**Comment by rv602** [comment]
@palisadoes, I have made the required changes to the code and included error handling for all possible scenarios.

In my opinion, keeping the `SUPERADMIN` section in the script would give the user a sense of completeness, knowing that the API is fully configured and ready to run. However, I can add a `Yes/No` option for creating the `SUPERADMIN` section, allowing the user to skip this step if desired.

Awaiting your feedback on this suggestion before creating the pull request.

**Comment by rv602** [comment]
@palisadoes I have made the PR
