### ISSUE TITLE
Test: src/lib/resolvers/Subscription/messageSentToDirectChat.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#890]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Subscription/messageSentToDirectChat.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name ` __tests__/resolvers/Subscription/messageSentToDirectChat.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by kb-0311** [comment]
@noman2002 pls assign this to me

**Comment by palisadoes** [comment]
You already have 3 assigned issues. Please wait until your PRs are merged.

**Comment by kb-0311** [comment]
Oh yeah , because I will be changing deleteImage too in #952 , the PR for #888 will need to wait too.

You are right, I won't be taking new issues until PR for #952 is done and then solve the other two PR I am assigned.

**Comment by kb-0311** [comment]
pls assign this to me, I have made a PR for two assigned issues with one of them merged.

**Comment by palisadoes** [comment]
You already have 3 issues assigned to you. Please allow others to get a chance

**Comment by kb-0311** [comment]
Oh yeah, the comment was before I was assigned my 3rd issue.

**Comment by kb-0311** [comment]
Can I be assigned to this issue now ?

**Comment by Frey0-0** [comment]
@palisadoes can you please assign this issue to me?

**Comment by noman2002** [comment]
@Frey0-0 Any update ?

**Comment by palisadoes** [comment]
Unassigning so that others can get a chance.

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this issue?
