### ISSUE TITLE
Test: src/lib/resolvers/Subscription/index.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#891]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Subscription/index.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/Subscription/index.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by kunal-gg** [comment]
can I work on this issue

**Comment by noman2002** [comment]
Sure, assigned it to you.

**Comment by nishant3721** [comment]
@noman2002 I have already the test for it? can you assign it to me?

**Comment by anshgoyalevil** [comment]
@noman2002 I have written the tests for this file. Can I be assigned to this issue. The test is covering 100% of src/lib/resolvers/Subscription/index.ts file.

**Comment by noman2002** [comment]
@nishant3721 @anshgoyalevil  Please follow the procedure. It can't be assigned to you guys because someone is already working on this issue. Please take other issues. 
@anshgoyalevil You already have 3 issues assigned to you please get the PR merged for all of them before asking for more issues. Thank you.

**Comment by anshgoyalevil** [comment]
> @nishant3721 @anshgoyalevil Please follow the procedure. It can't be assigned to you guys because someone is already working on this issue. Please take other issues. @anshgoyalevil You already have 3 issues assigned to you please get the PR merged for all of them before asking for more issues. Thank you.

Sure Sir. Thanks

**Comment by aviraldevv** [comment]
@kunal-gg are you still working on this issue?

**Comment by kunal-gg** [comment]
> @kunal-gg are you still working on this issue?

Yes. I have done some work. I had few exams this week that is why got a little busy. Will probably make a PR by tomorrow or day after max.

**Comment by aviraldevv** [comment]
It's totally fine @kunal-gg take your time.

**Comment by palisadoes** [comment]
Closing as this is not best practice.
