### ISSUE TITLE
Test: src/lib/resolvers/Query/postsByOrganizationConnection.ts 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#893]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Query/postsByOrganizationConnection.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/Query/postsByOrganizationConnection.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by gurpreet-legend** [comment]
@noman2002 @tonythegr8 @nesiann, I would like to work on this

**Comment by noman2002** [comment]
@gurpreet-legend 2 issues are already assigned to you. Please work on them and get the PR merged.

**Comment by arunavabasu-03** [comment]
can you assign it to me ??

**Comment by noman2002** [comment]
Sure.

**Comment by kb-0311** [comment]
@arunavabasu-03 are you still working on this issue? If not can I take up this issue instead?

**Comment by noman2002** [comment]
Unassigned due to inactivity

**Comment by noman2002** [comment]
@kb-0311 You already have 3 across the repos. get them merged first.

**Comment by anshgoyalevil** [comment]
Can I get assigned to this issue please.

**Comment by anshgoyalevil** [comment]
@palisadoes I just checked this file, and it already have a test written for it, with 100% code coverage. This issue may be closed.

**Comment by palisadoes** [comment]
It's at 24% search for `postsByOrganizationConnection.ts` in the link above

**Comment by anshgoyalevil** [comment]
> It's at 24% search for `postsByOrganizationConnection.ts` in the link above

But, I checked it locally, and it is 100% 

![image](https://user-images.githubusercontent.com/94157520/218532690-df70d24e-798b-42e1-934c-a8c047d981dd.png)

**Comment by anshgoyalevil** [comment]
I guess, it is an issue with CodeCov.

**Comment by anshgoyalevil** [comment]
> > It's at 24% search for `postsByOrganizationConnection.ts` in the link above
> 
> But, I checked it locally, and it is 100%
> 
> ![image](https://user-images.githubusercontent.com/94157520/218532690-df70d24e-798b-42e1-934c-a8c047d981dd.png)

@palisadoes
