### ISSUE TITLE
Test: src/lib/resolvers/Mutation/otp.ts 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#903]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Mutation/otp.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name ` __tests__/resolvers/Mutation/otp.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by anshgoyalevil** [comment]
@palisadoes I was working on this issue. I have added 2 additional tests to the existing otp.spec.ts file.

![image](https://user-images.githubusercontent.com/94157520/214293475-d170eaa5-b519-4bbb-a664-4ecd9ea29820.png)

The tests are covering the following cases:
- throws Error if no user exists with email === args.data.email
- otp token expires after 15 minutes
- otp token is signed with the ACCESS_TOKEN_SECRET

Additionally, there is a typo in the otp.ts file.

Can I create a pull request adding the changes to otp.spec.ts file?

The Coverage according to Code coverage generated by istanbul is 100%

**Comment by palisadoes** [comment]
You need to be assigned the issue first before submitting the PR. Do you want to be assigned?

**Comment by anshgoyalevil** [comment]
@palisadoes Yes, Please assign this issue to me.

**Comment by noman2002** [comment]
@anshgoyalevil Are you still working on this issue ??

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil Are you still working on this issue ??

Yes sir, I was working on it, and also created a pull request 3-4 dats back. There is an issue with the GitHub Workflow of this repository, which is that the Mail Configuration variables are missing, and thus, would need the help of someone to add them inside the Workflow file.

**Comment by noman2002** [comment]
Reach out on  slack.

**Comment by ayushbhaimehta** [comment]
Hi @noman2002  if no one is working on this then I would be happy to contribute.

**Comment by ayushbhaimehta** [comment]
I am thinking of adding a test for otp expiration. I think it would be easiest if we add a date argument and then check whether it is  within 15min from the generated one. Do let me know if I should work on this or think of something else.

**Comment by palisadoes** [comment]
@noman2002 Any thoughts?

**Comment by anshgoyalevil** [comment]
> I am thinking of adding a test for otp expiration. I think it would be easiest if we add a date argument and then check whether it is within 15min from the generated one. Do let me know if I should work on this or think of something else.

You can still tackle the test for checking if the otp expires within 15 minutes or not, without changing it to a date object. The code would look something like (Actual test code would be different)
```
const decoded = jwt.decode(otpToken) as any;
    const currentTimestamp = Date.now() / 1000;
    const tokenExpirationTimestamp = decoded.exp;
    const differenceInSeconds = tokenExpirationTimestamp - currentTimestamp;

    // 15 minutes in seconds
    const expectedExpirationInSeconds = 15 * 60;

    expect(differenceInSeconds).toBeLessThanOrEqual(expectedExpirationInSeconds);
```

I was working on this issue previously, and I wrote the whole test file for it, with 100% coverage. The only part where my test failed during the PR workflow is, I was not mocking the ```mailer``` function, and the PR workflow was not having the mail variables.

Try finding a way to mock the ```mailer``` function, since, PR workflow doesn't have mail variables, and your PR will fail during the Automated testing in PR workflow, if not done so.

**Comment by ayushbhaimehta** [comment]
Well I am relatively new to CI/CD. I would need some help on that part.

**Comment by anshgoyalevil** [comment]
> Well I am relatively new to CI/CD. I would need some help on that part.

Mocking the ```mailer``` function wouldn't include the CI/CD part. It would need some in-depth knowledge of testing frameworks like ```jest``` and ```vitest```

**Comment by ayushbhaimehta** [comment]
I am having difficulty in mocking it. Can someone help me through the process

**Comment by palisadoes** [comment]
@ayushbhaimehta Please ask in the #talawa-api slack channel.

**Comment by arunavabasu-03** [comment]
Can I work on this ?

**Comment by arunavabasu-03** [comment]
Can I work on this @palisadoes ? Actually my exams are going !!
