### ISSUE TITLE
Test: src/lib/libraries/requestTracing.ts 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#913]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/libraries/requestTracing.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name ` __tests__/libraries/requestTracing.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by gurpreet-legend** [comment]
@noman2002 , can I work on this too, would let me understand the codebase better?

**Comment by noman2002** [comment]
@gurpreet-legend Assigned you 2 issues please get the PR merged for both the issues before asking for more. Thank you.

**Comment by noman2002** [comment]
@gurpreet-legend  are you still working on this ?

**Comment by gurpreet-legend** [comment]
@noman2002, yes I'll soon raise a PR

**Comment by kb-0311** [comment]
@gurpreet-legend are you still working on this issue? If not can I get this issue instead?

@noman2002 it's been 3 weeks since no PR for this issue should we wait a bit more in this case? Because I want to be assigned here as well.

**Comment by noman2002** [comment]
@gurpreet-legend Any update ?

**Comment by kb-0311** [comment]
@noman2002 My other two PRs have been merged now btw. 

Let's just wait a bit for @gurpreet-legend's reply before you assign me though.

**Comment by arunavabasu-03** [comment]
Can I work on this ?

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this? I have completed writing test cases for `requestContext.ts` and since both the file functions include `cls-hooked`, I might provide some help on this

**Comment by noman2002** [comment]
@KrutikaBhatt You already have 2 issues assigned to you. If you want this to assigned. Either unassign any one or get the PR merged for atleast one.

**Comment by KrutikaBhatt** [comment]
Yes sure @noman2002, I have just added a PR for issue #914. I will wait up for assignment until it gets merged. Thanks!
