### ISSUE TITLE
Test: src/lib/libraries/errors/internalServerError.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#917]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/libraries/errors/internalServerError.ts `
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/libraries/errors/internalServerError.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by Manoramsharma** [comment]
Hi @noman2002 , I would like to work on this issue. please assign it to me.
