### ISSUE TITLE
Test: src/lib/directives/index.ts 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#919]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/directives/index.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name ` __tests__/directives/index.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by Rishab49** [comment]
I want to work on this

**Comment by anshgoyalevil** [comment]
I would like to work on this issue, as I have completed the test file for it, will 100% code coverage. Could you please assign it to me.

**Comment by noman2002** [comment]
@anshgoyalevil It is assigned to @Rishab49 yesterday.  You can work on some other issue.

**Comment by anshgoyalevil** [comment]
@Rishab49 are you still working upon this issue?

**Comment by aviraldevv** [comment]
@Rishab49 if you need any help for this you can refer to my PR this issue is same with minor tweak. I am attaching my PR link for reference https://github.com/PalisadoesFoundation/talawa-api/pull/945 . Best Wishes!!!

**Comment by anshgoyalevil** [comment]
@Rishab49 Are you still working on it.

**Comment by Rishab49** [comment]
No I'm not

**Comment by anshgoyalevil** [comment]
@palisadoes Could you please assign this issue to me.

**Comment by aviraldevv** [comment]
@anshgoyalevil could you please let me work on this issue I have done similar work earlier, currently the issue I was working on might get closed.

**Comment by aviraldevv** [comment]
Nevermind you have been assigned you can work.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil could you please let me work on this issue I have done similar work earlier, currently the issue I was working on might get closed.

Totally understand your point buddy, but, I have also worked upon the similar issue, and that one is closed as well. Hope you get any other issue to work upon. Thanks.

**Comment by aviraldevv** [comment]
Definitely buddy :)
