### ISSUE TITLE
Use constants instead of environment variables across the app

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-api#950]
**Is your feature request related to a problem? Please describe.**

We need to improve the code quality in the `Talawa-API` repo as we have done in `Talawa-Admin` here: https://github.com/PalisadoesFoundation/talawa-admin/pull/420

- There are many instances of  `process.env.VARIABLE_NAME` in the code.
- This is a bad coding practice since it is difficult to maintain and refactor the code

**Describe the solution you'd like**

- A better approach will be to store the value extracted from the environment variable in constant files
- And the constant will be used across the app 

**Describe alternatives you've considered**

This seems to be the best approach

**Additional context**

- This will make it easy to update names of environment variables like done in this [commit](https://github.com/PalisadoesFoundation/talawa-admin/commit/f659baf02e55b302d41bd929523610bd37ca951b)

**Comment by anshgoyalevil** [comment]
@palisadoes I can work upon this issue, if I am allowed to do that.

**Comment by manav23lohani** [comment]
@palisadoes please assign this issue to me, I can work on this.
