### ISSUE TITLE
Feature Request: Separation of testing database

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#964]
**Is your feature request related to a problem? Please describe.**
Currently the same database is being used for managing the user data as well the test data. This is not desirable, as every time the tests are run, the database gets bloated with objects which are not going to be used by the user anytime soon. 

**Describe the solution you'd like**
To make the database and production system system ready, I would like to propose a two step solution. 
1. Add another environment variable to store a database connection to a `MONGO_TEST` database which should be used for testing.
 
Some relevant points:-
- If the user does not have the testing database set, we can default to the main database for testing.
- In all of the files, only the `.connect()` method would need to be changed with a `.connectTest()` method, which will open the connection to the test database instead of the main database.

2. Deletion of the objects created during testing in the `afterAll` clause of each of the tests must also be done. This must be done to ensure that even the testing database does not become bloated with stale data. This would allow us to up the integrity of our API testing, as we should ensure that the state of our database before and after running the test should be EXACTLY the same. If any test would fail, the data would be directly present in the testing database, and would help the developers to debug the API.

The second step is somewhat of a long project, which can be done on a per test file basis, as was done with code coverage. The implementation of the same would help debugging for developers in the future as new features are added, and make for better and scalable experience.

**Approach to be followed (optional)**
Described above

**Comment by anshgoyalevil** [comment]
@EshaanAgg I think, this is really a good decision to separate the test database from the development database.

For the 2nd point, we can cover that as well, while separating the common objects from the test files. This would include some risks and could break the test code. What I would prefer is to clear the whole test database in the afterAll function for all standalone tests. This would be much more easy than removing the specific objects added while running the tests.

**Comment by EshaanAgg** [comment]
@anshgoyalevil Purging the whole database is an expensive transaction, and seems like a low-hanging fruit to me personally. Since we have already started migrating towards centralised helper functions for testing in awe of #961, we can begin to add helper function to delete objects too and just call them in the `afterAll()` clause. 
The tests would not break as their status would be independent of the database state. 

@palisadoes 
1. We can add a `TEST_MONGO_DB` in the `.env` with the default value `NULL`. 
2. Update installation instructions to optionally setup 2 database, each of which would be a constant.
3. Replace all the `.connect` and `.disconnect` functions in the test directory with `.connectTest()` and `.disconnectTest()`
4. In these functions, we just check at runtime if the `TEST_MONGO_DB` is set or not. If it is set, we connect to it, otherwise we default to the regular database, while logging a message recommending user to setup separate testing database. 

Once this functionality is stable, we can open a new parent issue of having better `afterAll()` functions for each test file, and migrate towards them.

**Comment by palisadoes** [comment]
You will also need to ensure that the test DB  cannot be accessed by connect() and disconnect(). 

I greatly prefer a complete separation of database access.

**Comment by anshgoyalevil** [comment]
> The MongoDB url should be a const. So it would be easier to see whether there is a test database url configured and then use that as the const.
> 
> We could also ensure that test databases must have some feature such as a name or flag on which tests will only operate.
> 
> Is this a feasible approach? How would you implement it?

The more feasible approach would be to apply a logic such that, a user can set the boolean variable inside the .env file which would further be used to change the value of the MongoDB development URI with the MongoDB test URI.

It would work in the following way:
- add a new .env variable ```isTest=true or false``` and ```testDB=mongoURL```
- add an if statement inside the constants file to check for the value of isTest, if available, and change export the desired MongoDB url based on it.
- This would help in a quick switching between test db and development db.

I wouldn't prefer changing the whole test codes.

The solution I suggested can be implemented quickly, and without changing any of the test file. This will also help in maintaining the code, and further the GitHub actions would also need not to be changed.

**Comment by palisadoes** [comment]
You will also need to ensure that the test DB  cannot be accessed by connect() and disconnect(). 

I greatly prefer a complete separation of database access.

**Comment by palisadoes** [comment]
Changing the GitHub action should be a trivial thing to do.

We should err on the side of caution.

The Linux `sed -i` command can be used to quickly change the connect and disconnect references.

**Comment by palisadoes** [comment]
The test database must have some intrinsic quality to ensure that it is treated as test. A configuration flag is not enough.

**Comment by EshaanAgg** [comment]
Getting your concerns @palisadoes. I would read more about test databases, and then try to come up with a strategy that could achieve all the said points.

**Comment by anshgoyalevil** [comment]
> The test database must have some intrinsic quality to ensure that it is treated as test. A configuration flag is not enough.

In that case, we would have to find a more robust solution, and the complete test code along with some corebase will need to be changed

**Comment by EshaanAgg** [comment]
I think so we can ensure that the access to the testing database is only limited to `Vitest` with the following approach:

1. Changing the `test` script to ` "test": "NODE_ENV=testing vitest run --no-threads --coverage"` 
(This would ensure that whenever the tests are run, the `NODE_ENV` variable is set to `test` and reverted back to the default `development` after  the command is complete.)
2. Change the `.connect()` and `.disconnect()` methods to connect to the required database on the basis of the `NODE_ENV` variable.

Another suggestion:
Instead of asking the user to provide another database for testing, we can consider using the `ORGINAL_CONN_STR + "_TEST"` as the new connection string, as this would create a new MongoDB database automatically with the name `ORIGINAL_NAME + T_EST` for the user, and would be provisioned only if and when the developer runs the tests. 
We can add documentation about this behaviour in the docs as well as the INSTALATION.md.

**Comment by palisadoes** [comment]
@EshaanAgg We need to be doubly sure mistakes are not made:

1. The environmental variable that we have discussed needs to be used
2. Tests must only run on a database that is unquestionably for testing, such as the DB's name containing the string `TEST`  (preferred) or some other method. The `connect()` and `disconnect()` must ensure this.

I'll assign this to you as an urgent exception. You are way over the issue limit now. Please make sure to close some before asking for any more. Everyone needs a chance.

Make sure to include any required changes in the GitHub action and INSTALLATION.md files.

**Comment by EshaanAgg** [comment]
Thanks @palisadoes. I will get working on it, and will post about my progress asap.
