### ISSUE TITLE
Refactor: tests/resolvers/GroupChat

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#968]
This is a child issue to the issue listed here: #965 

- Code need to be refactored for folder ```tests/resolvers/GroupChat```
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issue on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/965)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visiting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by anshgoyalevil** [comment]
Assign this issue to me.

**Comment by noman2002** [comment]
@anshgoyalevil 2 issues assigned to you. Please get the PRs merged before asking for more. We want give everyone a chance.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil 2 issues assigned to you. Please get the PRs merged before asking for more. We want give everyone a chance.

Yes, I unassigned a previous issue.

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this issue?

**Comment by anshgoyalevil** [comment]
> > @anshgoyalevil 2 issues assigned to you. Please get the PRs merged before asking for more. We want give everyone a chance.
> 
> Yes, I unassigned a previous issue.

Now, I can be assigned this issue. Please assign this issue to me.

**Comment by noman2002** [comment]
@KrutikaBhatt Please have a look at various similar open issues. I have to assign this to @anshgoyalevil coz he commented first.
