### ISSUE TITLE
Refactor: tests/resolvers/Mutation

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-api#971]
This is a child issue to the issue listed here: #965 

- Code need to be refactored for folder ```tests/resolvers/Mutation```
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issue on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/965)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by anshgoyalevil** [comment]
@EshaanAgg You may work upon this

**Comment by EshaanAgg** [comment]
Please assign this issue to me.

**Comment by noman2002** [comment]
@EshaanAgg 2 issues assigned to you. Please get the PRs merged before asking for more. We want to give everyone a chance

**Comment by EshaanAgg** [comment]
I have completed my work on the already assigned issues. Can I start working on this directory?

PS. As this directory has many tests, I would like to start working on the first 10 test files (i.e. `acceptAdmin.spec.ts` to `blockPluginCreationBySuperadmin.spec.ts`). In this way others too can contribute by getting themselves some files assigned in this directory.

**Comment by anshgoyalevil** [comment]
@sandeep-v1404 Would you like my help for the rest of the files in this folder?

**Comment by EshaanAgg** [comment]
> Would you like my help for rest of the files in this folder.?

Sure. You can get cracking on the next set of files if the maintainers allow.

**Comment by palisadoes** [comment]
@anshgoyalevil please open a separate issue for the remaining files in the folder

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil please open a separate issue for the remaining files in the folder

Sure Sir.

**Comment by noman2002** [comment]
Completed
