### ISSUE TITLE
Test: tests/resolvers/Query

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-api#991]
**Describe the bug**
Most of the test for the Query doesn't have 100% test coverage, it doesn't cover the error handling when IN_PRODUCTION=true

**Expected behavior**
For IN_PRODUCTION=true, it should have 100% test coverage

**Actual behavior**
some of the tests do not have 100% test coverage for IN_PRODUCTION=true

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/216520627-c4cbec30-6306-410a-8806-94979873ab13.png)

**Additional details**

**Comment by nishant3721** [comment]
@palisadoes Please assign this to me.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by nishant3721** [comment]
@palisadoes I was unavailable this weekend due to some emergency, will make pr by today
