### ISSUE TITLE
Test: src/utilites/creatorCheck.ts

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-api#992]
**Describe the bug**
The test coverage for this file is currently 96.29%.

**Expected behavior**
The test coverage should be 100%.

**Actual behavior**
coverage is not 100%.

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/216526970-41e3c616-32a0-4ad9-9f93-221dc8221286.png)

**Comment by nishant3721** [comment]
@palisadoes I would also like to work on it.

**Comment by palisadoes** [comment]
This is related to https://github.com/PalisadoesFoundation/talawa-api/issues/993 which will solve the issue with a mock across the board. 

Closing. Let me know if this is in error.
