### ISSUE TITLE
Remove the conditional check `process.env !== "PRODUCTION"` for `requestContext.translate()` in code files.

### ISSUE THREAD

**Issue by xoldyckk** [PalisadoesFoundation/talawa-api#993]
**Is your feature request related to a problem? Please describe.**
The whole idea of checking `process.env !== "PRODUCTION"` in places where `requestContext.translate()` function was being used was to make it not error out when testing the code that utilised that function. This was because `requestContext.translate()` would only properly work under the context of a running api server.

But as the recent test changes have shown, `requestContext.translate()` can be mocked while testing a particular module/file and therefore the check `process.env !== "PRODUCTION"` no longer needs to exist.

**Describe the solution you'd like**
All the places in code where the check  `process.env !== "PRODUCTION"` is made should be removed and `requestContext.translate()` should be mocked when testing the code utilising that function. 

This also means all the test code that doesn't mock `requestContext.translate()` should be removed/replaced with the one that does mock it. Two identical suites of tests running for the same logic should not exist when there's no need.

**Describe alternatives you've considered**

-

**Approach to be followed (optional)**
1. Removed all instances of the check  `process.env !== "PRODUCTION"` and conditional usage of  `requestContext.translate()` function depending on that check from code files.
2. Migrate/refactor tests to test code files using the mocked version of `requestContext.translate()`. All test code depending on the check `process.env !== "PRODUCTION"` should be removed.

**Additional context**
I can't think of any reason for which this would affect talawa-api negatively. Leave your opinions/thoughts on this.

**Comment by EshaanAgg** [comment]
I agree with the provided solution. This would make tests simpler, and move away from redundant tests.

**Comment by aviraldevv** [comment]
@xoldyckk I researched on this and now requestContext,translate() can be properly mocked while testing. Therefore it is redundant checking `process.env !== "PRODUCTION"`. I feel we should do the necessary changes. I can work on this if I get issued.

**Comment by xoldyckk** [comment]
@anshgoyalevil I see you've done a major overhaul in removing redundant test data. Share your opinion.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil I see you've done a major overhaul in removing redundant test data. Share your opinion.

- As we can control the ```requestContext``` function by mocking it, we can remove the conditional check for ```IN_PRODUCTION !== true```.

- I have a little doubt over here. If we remove the ```IN_PRODUCTION``` variable, the requestContext() function we always be outside of the automated test suite, since we are only mocking it inside the automated tests.
- If we run a development API server for testing the API manually, the actual requestContext() function will be called, no matter if the NODE_ENV===PRODUCTION.
- If you think, there's is no problem in calling the actual requestContext() function while testing the API manually, we can proceed further.
- Else, we can go for adding the mock requestContext() function which returns ```IN_PRODUCTION=true```, as it was done in some of the recent tests.

**Comment by xoldyckk** [comment]
@anshgoyalevil I think you didn't understand what I meant. Removing the check for one of the resolvers and try testing the file. You'll be hit up with an error like `i18n is not initialized`. Try it.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil Try this. Remove the condition `IN_PRODUCTION !== true` for one of the resolvers, replacing it with just the `requestContext` part and try testing the that resolver. You'll be hit up with an error like `i18n is not initialized`.
> 
> The problem isn't the environment. Problem is that we're testing functions here. Not the api itself. Whenever requestContext is called outside the context of a running talawa-api server(like we're doing here by testing just the resolver function), it'll error out.

Okay wait, let me test it out. Will get back to you shortly.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil Try this. Remove the condition `IN_PRODUCTION !== true` for one of the resolvers, replacing it with just the `requestContext` part and try testing the that resolver. You'll be hit up with an error like `i18n is not initialized`.
> 
> The problem isn't the environment. Problem is that we're testing functions here. Not the api itself. Whenever requestContext is called outside the context of a running talawa-api server(like we're doing here by testing just the resolver function), it'll error out.

Okay. Got it what you were saying.

I just tested it out.

We can safely remove the tests which are dependent of the ```IN_PRODUCTION``` condition, and thus, can remove the condition from all places where requestContext() is used. There will be no effect on the Core API.

We can also perform a quick manual test by removing some of these instances in the code, and comparing the API response for that particular function with the response after removing that condition, just to be double sure.

**Comment by xoldyckk** [comment]
> > @anshgoyalevil Try this. Remove the condition `IN_PRODUCTION !== true` for one of the resolvers, replacing it with just the `requestContext` part and try testing the that resolver. You'll be hit up with an error like `i18n is not initialized`.
> > The problem isn't the environment. Problem is that we're testing functions here. Not the api itself. Whenever requestContext is called outside the context of a running talawa-api server(like we're doing here by testing just the resolver function), it'll error out.
> 
> Okay. Got it what you were saying.
> 
> I just tested it out.
> 
> We can safely remove the tests which are dependent of the `IN_PRODUCTION` condition, and thus, can remove the condition from all places where requestContext() is used. There will be no effect on the Core API.
> 
> We can also perform a quick manual test by removing some of these instances in the code, and comparing the API response for that particular function with the response after removing that condition, just to be double sure.

There's no problem in removing it. In the first place it was put all over the codebase just because of this issue because mocking it in jest wasn't working and resolvers needed to be tested. 

@anshgoyalevil @EshaanAgg @aviraldevv So, what do you guys think when should we do the refactor?

**Comment by anshgoyalevil** [comment]
> > > @anshgoyalevil Try this. Remove the condition `IN_PRODUCTION !== true` for one of the resolvers, replacing it with just the `requestContext` part and try testing the that resolver. You'll be hit up with an error like `i18n is not initialized`.
> > > The problem isn't the environment. Problem is that we're testing functions here. Not the api itself. Whenever requestContext is called outside the context of a running talawa-api server(like we're doing here by testing just the resolver function), it'll error out.
> > 
> > 
> > Okay. Got it what you were saying.
> > I just tested it out.
> > We can safely remove the tests which are dependent of the `IN_PRODUCTION` condition, and thus, can remove the condition from all places where requestContext() is used. There will be no effect on the Core API.
> > We can also perform a quick manual test by removing some of these instances in the code, and comparing the API response for that particular function with the response after removing that condition, just to be double sure.
> 
> There's no problem in removing it. In the first place it was put all over the codebase just because of this issue because mocking it in jest wasn't working and resolvers needed to be tested.
> 
> @anshgoyalevil @EshaanAgg @aviraldevv So, what do you guys think when should we do the refactor?

We can start working on it right away. I think, we can create a helper file to separate this mock, and use that in the whole test suite, wherever necessary.

**Comment by xoldyckk** [comment]
@anshgoyalevil You still haven't refactored much of the tests for mutation and queries right? You've only done for relation resolvers I presume?

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil You still haven't refactored much of the tests for mutation and queries right? You've only done for relation resolvers I presume?

Yes, I am assigned to refactor the mutation folder. The queries folder is assigned to some other contributor.

I was busy the whole day today, so wasn't working on it today. Will surely create a PR by tomorrow for those issues assigned to me.

**Comment by aviraldevv** [comment]
> > > > @anshgoyalevil Try this. Remove the condition `IN_PRODUCTION !== true` for one of the resolvers, replacing it with just the `requestContext` part and try testing the that resolver. You'll be hit up with an error like `i18n is not initialized`.
> > > > The problem isn't the environment. Problem is that we're testing functions here. Not the api itself. Whenever requestContext is called outside the context of a running talawa-api server(like we're doing here by testing just the resolver function), it'll error out.
> > > 
> > > 
> > > Okay. Got it what you were saying.
> > > I just tested it out.
> > > We can safely remove the tests which are dependent of the `IN_PRODUCTION` condition, and thus, can remove the condition from all places where requestContext() is used. There will be no effect on the Core API.
> > > We can also perform a quick manual test by removing some of these instances in the code, and comparing the API response for that particular function with the response after removing that condition, just to be double sure.
> > 
> > 
> > There's no problem in removing it. In the first place it was put all over the codebase just because of this issue because mocking it in jest wasn't working and resolvers needed to be tested.
> > @anshgoyalevil @EshaanAgg @aviraldevv So, what do you guys think when should we do the refactor?
> 
> We can start working on it right away.
> 
> There are over 23 affected files. I think, it wouldn't take that much time in refactoring the whole codebase.

I agree with you @anshgoyalevil . I am totally available to work this weekend.

**Comment by EshaanAgg** [comment]
I can get started on this issue as well. One of us can put a sample PR, which can be reviewed by others, and then we can divide the files and refactor the files over this weekend itself.

**Comment by xoldyckk** [comment]
@anshgoyalevil If you haven't refactored those test files to include tests for both `IN_PRODUCTION === true` and `IN_PRODUCTION === false` then it'll save you a lot of time. Remove the check first then refactor the tests for reusing those helper functions.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil If you haven't refactored those test files to include tests for both `IN_PRODUCTION === true` and `IN_PRODUCTION === false` then it'll save you a lot of time. Remove the conditional check first then refactor the tests to mock requestContext and also reuse those helper functions.

I haven't refactored ```Mutation``` test files. I will coverup this issue as well.

**Comment by xoldyckk** [comment]
@anshgoyalevil @EshaanAgg @aviraldevv discuss it between yourselves and divide the work.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil @EshaanAgg @aviraldevv discuss it between yourselves and divide the work.

Could you please review this 
https://github.com/PalisadoesFoundation/talawa-api/commit/6095d86a4728426525ef8d22f90e3f0f3a2816ef (Test Coverage before and after is same, i.e., 100%)
and tell whether this was the required change according to this issue. We would then proceed further refactoring other similar files as well.

**Comment by xoldyckk** [comment]
> > @anshgoyalevil @EshaanAgg @aviraldevv discuss it between yourselves and divide the work.
> 
> Could you please review this [6095d86](https://github.com/PalisadoesFoundation/talawa-api/commit/6095d86a4728426525ef8d22f90e3f0f3a2816ef) (Test Coverage before and after is same, i.e., 100%) and tell whether this was the required change according to this issue. We would then proceed further refactoring other similar files as well.

Yeah exactly that.

**Comment by noman2002** [comment]
As this is parent issue so I assigned it to Mr. Peter and child issues will be assigned to individuals. 
@anshgoyalevil @EshaanAgg @aviraldevv comment on child issues to get it assigned.
