### ISSUE TITLE
Feature Request: Better INSTALLATION instructions for setting up GitHub repository

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-api#995]
**Is your feature request related to a problem? Please describe.**
In the current guide on setting up the project locally, we are just asking the user to fork the repo and clone it to contribute. This works, but a better solution would ask the user to setup different `upstream` and `origin`, so that they can push to their fork, but get updates directly from the main `talawa-api` repository.

**Describe the solution you'd like**
Update `INSTALLATION.md` to have cloning instructions like [Oppia](https://github.com/oppia/oppia/wiki/Installing-Oppia-%28Linux%3B-Python-3%29#clone-oppia)

**Approach to be followed (optional)**
Update INSTALLATION.md

**Additional context**
This would help to improve the developer experience, as while working on longer PR's, often the main repository gets some updates, which lead to our local branches to lag behind, and results in merge conflicts in PR's.
The workflow described in the linked file is the "ideal" GitHub setup in my opinion, and would help beginners to keep their repository's up to date without much hassle.

**Comment by xoldyckk** [comment]
@EshaanAgg go ahead
